kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:o6as3CmP9JSW2o71nxrNFf+AEShf,iv:XLbSOw5F39I1sGfNFQ2mqEByBk2dhHa3KbmSmrg+a0k=,tag:cyJT0lrwzQqBEV3JTW9wRA==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:orTX6YMkRpx7pA==,iv:eubzmabY+3zFat0360XcW6t5lpaLWoyIeWv1w58EGmk=,tag:p8Oo4n4lyzxV8TqTPUULJQ==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:psfIK7xoLB0lRYtbdXPF6hdD49Sl,iv:roD5QL6n5YMqQZoyy+u9EjA5PPQgDJSfwAhP47wW04A=,tag:AShL4ZxfUSIqgGyNBbE0+Q==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:TcKgfesosX+70eKskrkp,iv:NEiarD4jlF+WwZJyiBWIZECPOGoyMuQsmFE7cK3pLjs=,tag:lnYOHn9vMSMjhNQ3HPJ9eQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:13Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQE2XjP6DZBRVtmUPMb2XJTzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgROqjfiFIF6Eb71mAgEQgDuv1m4Jv/aTLl6Gbc9beDYc0yQfFaOT601rjmyDDK07gQc06vAxMdfMprb4k8WPwST9t4Ts+rdxIfsSyw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcmJycTlqRUZNSCtDRkJt
            SURsdk05VUREbGE1RHh6enVDeW1oalk2ZlYwClN6WXNkdmF5MVlwclRneUp1Qmhx
            NGtHMzNpR0F5cjMwcWF0dHRtTEZQS2sKLS0tIE1GK0FkOFgvMTgwVlE4YVpzc1pE
            Y0orN25Za2g4eWs4MG1IL0duTzZ6azgKCcS4XPQ0Cb6udxsDOqVKIq/B8gE0dWXT
            jP6kdcxyYv7lIFHJcy9VyUChp4HFk9L2VDUH+siqz7uIJzv4WHrh+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUERZZnJtRXZ4MzdrdXlq
            MEErTW5qNkVURmViT3JyTnQxZElnbGc3RXpBCmorb25wcE51TWhYWms2S3Q1Vldw
            aWkxZ0NMN2d4VkNmazlCYVFsajllbTQKLS0tIGxSTk41Nk9nbGRlWmhEdkpxMmJZ
            cGxjMjI1TnRkd3B5L3QyOTlKV213TGMKUzhPfZhNoIzqRMxLEN9uMlQjXlEDQdzy
            PcxpnJ+0Vg5rkZLezDIU4bKlujkg5J+JYTyuYtlE1mXtFNe/nOeiNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL1k0K21HSllGOFBTeWZT
            aDB3YTJtMG53aENGK1ZFWkVyY3RJcjEwb3g0Ck4yRGc5M1d0aWt5TGplb0h0ZG11
            RitPdFI5SEUrdzBsZDRPbkFuQUJDSjAKLS0tIHdSR2lvUFBNRWpUazhFQlhXS1Vz
            NU5kNE9kb1NVcm44NkFlamJwVW8xQ3cK5IUceuwgepQuwJ1fGCEdCuc8BzsLAQ+y
            r3vzX5mk2loa0KJLEPKhYVRqb0AcLCUZ46uQDXPEr3ISgagUimzmUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:22Z"
    mac: ENC[AES256_GCM,data:BCwYCEMIb0Lo/T2hgSNM9flBDQ1TOpBA6cAOBTKiMAWL6RFyDsV+JgpI2OmlqIB/a7sPzWEEXWv2pE+JJ4Eg9k1Plk4j8DL42Xqm5U+ZpYlPGY/ESDnudm129RiXayWinlgkGQ5hMoCbK0qGZzpfgePKkb/FW9oGgO6i9tK9uvA=,iv:BOWO0I7ZOb55FqTIFJgOv+SGzuPNQ6IiwBN9A+TKKTs=,tag:Yx9AWEheIDYoB/0eY1qmaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
