kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:o6as3CmP9JSW2o71nxrNFf+AEShf,iv:XLbSOw5F39I1sGfNFQ2mqEByBk2dhHa3KbmSmrg+a0k=,tag:cyJT0lrwzQqBEV3JTW9wRA==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:orTX6YMkRpx7pA==,iv:eubzmabY+3zFat0360XcW6t5lpaLWoyIeWv1w58EGmk=,tag:p8Oo4n4lyzxV8TqTPUULJQ==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:psfIK7xoLB0lRYtbdXPF6hdD49Sl,iv:roD5QL6n5YMqQZoyy+u9EjA5PPQgDJSfwAhP47wW04A=,tag:AShL4ZxfUSIqgGyNBbE0+Q==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:TcKgfesosX+70eKskrkp,iv:NEiarD4jlF+WwZJyiBWIZECPOGoyMuQsmFE7cK3pLjs=,tag:lnYOHn9vMSMjhNQ3HPJ9eQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:21Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGLfulYA2jlYUCtX9IHOBOhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkHohs+tpimhgXYq6AgEQgDsD1BmRmRa9iNd8J7PAEN5u7HOq+i9LJmvKrWjxvVyKT2/TNY4UzppiJV1P5spyDCGHTHsHmtj+gvD+bg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKajY1SkhVU3ZrVDBJdjVQ
            Unp3bnpUMGFaNDdLb1NRbFhsT2g3QmlxZWd3CnNHTTd0V0lqMTlpdTZsOEMxMjc1
            c0c4bThDWWYwQURWWUxTU1VBbUpDSTQKLS0tIG9QK0JvSEdUT3dVZGNGVjZOckhU
            RHZIUUtwblBKUDFXRzkxWHlyNW9Oam8Ktpjq0HIUVkFEiwtUVWRV61lEHnrKjVjC
            IJkktufASsn/FeWV/MzA+4Oc0nPz+gXlpmk8wG14/WPVuLYN9AJGpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:22Z"
    mac: ENC[AES256_GCM,data:BCwYCEMIb0Lo/T2hgSNM9flBDQ1TOpBA6cAOBTKiMAWL6RFyDsV+JgpI2OmlqIB/a7sPzWEEXWv2pE+JJ4Eg9k1Plk4j8DL42Xqm5U+ZpYlPGY/ESDnudm129RiXayWinlgkGQ5hMoCbK0qGZzpfgePKkb/FW9oGgO6i9tK9uvA=,iv:BOWO0I7ZOb55FqTIFJgOv+SGzuPNQ6IiwBN9A+TKKTs=,tag:Yx9AWEheIDYoB/0eY1qmaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
