kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:3DPVbOAEgVDZGzMblGbTfgBKxwYS,iv:hOlFJ29o9gmmTh/98/UTHJxR1olTrIVKz6h8XOMB0f4=,tag:4o5EWBzBGoPejL7a93oo2w==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:xX3bQ9oAmBijFQ==,iv:Pl8vertaangS+8Vv8k/mYFvNLVJCenkRSM6e/BzSOhY=,tag:z91nYou1UPsDS8Vrd+CMiA==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:FOrwXd7uJy27xOv3Q5G7fqUksZnl,iv:P3z2Ru237HjrHsj8sRJxVk6LrcI45/apwgkAnKj0+7o=,tag:1AcV4/NqzqTxkGMokS9H7w==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:Rs/G91YY4mGH1MU+QEZA,iv:b4g5x0hMvuSZX7qv6UIJfJEa8m4IkuvtE1WjpN77e6c=,tag:LKyuJM5eizHd6afxvW3u/A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:14Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEdeKXrUJiHH86NvETjxzFrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb2Kho26Cfc3gndw4AgEQgDuW9nWGfvQr9S4nX4l27NWJc3GYrk+KtRZX2Th03SOzyCNYvTKFGDoXy2N44V2kg4x55bjalK8qx3UYNg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa2FobVNlR2V0VlNkMTVV
            cTN2cGJEcXVJc1J2enpDY3JLMWtOdWQ4eVJJCnpOVkx0c3BjZEdxL0lMWGRtNWl3
            NGhJMnRKZElYQnMxbEtiSk9YTlVweFUKLS0tIDlTMmhKS3RaaE5EUzJUZys5cnZj
            SHo5Y0w2cXRRVjFVckZtOXJFRENMQUkKI6vglh9YPbAEWiq5yolDYwXzAlhsblYm
            2OfYUtfMWoQXFvppbUEIUtUA0Qw0R/HwtqOAgN+/fzOivRsfjwahBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:15Z"
    mac: ENC[AES256_GCM,data:kl2596DAYPoXJb6NZ6e+d6rTpvOFYB5lJjQl+BQAeQ9KAj7sTcWq5uWdKz6iSP1Vy+5GU2V3hXzuSv9g+FmGDvSLge4YXuCJg5H1yrb+wqdh06F/rygrTHfiRn0E5i0THwsVXu3QcqcAEMR3genkvQ97VSf28mP1RW1i77P5GRY=,iv:h1egWeDMMFOT3PLQTAyJ/D3/18HT6LA9IRRkO+vQAvU=,tag:X4fwLy+mR2ArRl5YiL2kyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
