kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:o6as3CmP9JSW2o71nxrNFf+AEShf,iv:XLbSOw5F39I1sGfNFQ2mqEByBk2dhHa3KbmSmrg+a0k=,tag:cyJT0lrwzQqBEV3JTW9wRA==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:orTX6YMkRpx7pA==,iv:eubzmabY+3zFat0360XcW6t5lpaLWoyIeWv1w58EGmk=,tag:p8Oo4n4lyzxV8TqTPUULJQ==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:psfIK7xoLB0lRYtbdXPF6hdD49Sl,iv:roD5QL6n5YMqQZoyy+u9EjA5PPQgDJSfwAhP47wW04A=,tag:AShL4ZxfUSIqgGyNBbE0+Q==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:TcKgfesosX+70eKskrkp,iv:NEiarD4jlF+WwZJyiBWIZECPOGoyMuQsmFE7cK3pLjs=,tag:lnYOHn9vMSMjhNQ3HPJ9eQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:37Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEWOepIa3OJghuKozUX+E2xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfNn1MkM/P7pCJjw6AgEQgDuqGmGCe5opturks1Xon5OYRhhoa4X3ysrqnJAtKqgKX92AHTklQtH5XzSzRexSLCzHuEsjwLfMosuqzg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNVJNOXh2YWZRL1pKYldV
            bnZoS1hCT1VLOEx6ZnkwOVNZVzBXeDd3b2c4CmFHN29GVmszNnJEY1J4VVZ5TnBr
            eFVpd1piLzZUWDcxZ3kzZk83NXlwNmsKLS0tIEg3U0ZwNnNubklIbFU4bU93RFhB
            TzJsSllqNVV3RVluK2ExRXlkbW4rejQKWGtUr4xs0m6FP8hioNUm+FLc7wBGjXMA
            eC8Wry6EdzEaYHhfmp9b1Zkl05ydGjsbmUIJ/ZLKJZnnu7vAgVKBew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb01UOGRFUThsSGlZZ3NW
            QnZ2Yjg3anBubng2b2pGQnZnTmN0SXpFQjE0CllvWXc5dVR3dUNrT09HQzVKV2Y3
            QjRTQ3V1WXJoY3FRWUpPMGs1bEdrVjQKLS0tIDZUaE5uUmlBcFc1ZEExeGcxMUN5
            WkNxZ0VESFNOS21jUWp0ZUVFaUtvZDgKitLvhA+j55RBM1q8Z8UJqUrvB6gDbn30
            qRbajS3HR2ThmIfI28nX5/18to9FYmwEM8nnpqSiu7bmFT7D4+yakQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:22Z"
    mac: ENC[AES256_GCM,data:BCwYCEMIb0Lo/T2hgSNM9flBDQ1TOpBA6cAOBTKiMAWL6RFyDsV+JgpI2OmlqIB/a7sPzWEEXWv2pE+JJ4Eg9k1Plk4j8DL42Xqm5U+ZpYlPGY/ESDnudm129RiXayWinlgkGQ5hMoCbK0qGZzpfgePKkb/FW9oGgO6i9tK9uvA=,iv:BOWO0I7ZOb55FqTIFJgOv+SGzuPNQ6IiwBN9A+TKKTs=,tag:Yx9AWEheIDYoB/0eY1qmaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
