kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:N3d7avfmf90zujlUXlNuTYTRnQsq,iv:WXd0J1BU3lU6Pvts+lrahyGmZlpvUQSu+4oQU9c4T2g=,tag:1G/Wc4499Bh0k2JQFVOLiQ==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:Ba8H+4rpdtfmDg==,iv:v5al5yLn5/H5PE9y+GVz6TCXzGKDJmQ5gKAW5NLQkq8=,tag:EkbnzH0Ndx90I5/RVnLnmw==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:gaSYe4aX3QMuHkoMXSlLZIoleSis,iv:Z9xdU08pcwm2LRWErkhGExO4EG5Cg/fiXKMp2KvRpjE=,tag:Tq3Ih2Nk726uCAFq1ho/Gw==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:TtsBlJp/D+eOJLNWPsCQ,iv:uZOGyWQ2KV6FEwy3yBkOwAqHZ04Lj+m8yc3ByVJL+vw=,tag:rd66mwQKGur3ob5BxfQ5gw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:32Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGTF9PpGtu7voUmgQpXGtNmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK37WmwF9bCuiqCAWAgEQgDub4Yf1qsLFoppzC1jlOGPAMH/K49g30SmJGszHS7XwugOoXH8+ADGr1b9WbqRiqzPJoFHzNJGsuOTHGQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ymtmd2NBM0lQd2JUaVZQ
            akFzVjRxMWFHYzlHZ2lULzRJVXczaHFOdWlJCjRoNGJoaDAvOHBBNElEY2ZtVlB4
            UmJBb0c1dTMrRDNhWk5TNHNCOEczM1EKLS0tIDB4WVRWU2Z2aXZXa0MwUkZLT3h5
            czN2bjd4dXFJOE5iamZQY203ajNpaHMKgx28jj9EYPgH2nP+/U4DDJCQZ2lSr5h2
            kcfRli2yckxoyJ0omKtTidZkbpz5dVjWW8OcJnRXuaS5ivK2e5RUoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:34Z"
    mac: ENC[AES256_GCM,data:JkgSX7ctUrKMSq+gj7XmMXwMLLl/Gyy15XP8euXQESAU0jnOE0HbqR3Vyn/JSUgnv/VposN5GhWNcPtwEKwgJlZMtAQt4FNpXGaXMB8cnWiGYeg2WarDfOUnxF1Zgu6UicxwzPPuKr8sl1NMiWXA5iQ8jFzmk+XcDZqMYQYXzNY=,iv:njcRVffTzerNB4VbQKAkwb/APNZSYLCKxpMbYohQhNo=,tag:vMafm/8yPL9AhvZvxpUZPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
