aws_region: ENC[AES256_GCM,data:iR506vSISjG8,iv:QG57zhfTPBnKOSkLX7x8Oou7KuADoGZU/BZopdxOXQs=,tag:Q5Lt7wUaklX6tSQ3nfsqHg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:16:33Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHVAPR8cmQjlKzm0J0QZhy5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvsvNJi5LfDs/6eB2AgEQgDvvePRkXfSpFgZDZzypb05IgZzeQNk2eO4hubAimaXkXhLWGKGieJTyHDkYjH/ZwMSHUJ0USf4x1ERdsQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSUJrcW9BSTFqbzRnWVFT
            VnFZdXFyNk5UNWtHKzVsTVJmOWdhRmtZWW4wCnYrWEx4VVh1YzJKYlByVEFZaE92
            blZhazJOeWZTWjFndEJ6U01CVnRCMWMKLS0tIDhOdDd6N05Ra2ZBbHZKcVBvbzh6
            SlBQRUdVTnJjR2tUdGpkdHZiVFNZVWcKilmm27n9rsNV/dbDQC97OVMei7ikhVEb
            DTv7omHAQji8F5Tr3sjRMZAZHWYLe5Hl0FfiFiMG11ch5Hm9506krQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:16:35Z"
    mac: ENC[AES256_GCM,data:lR3C4DVxZGNdJ7jQ5L/ED4Lry1us8QmCc/XUMNaq/q/Y2DU+8Y7yTXYer9UpGuaLE1mmujX/p4QK3IQB15dTuX0UzaB0AwtZa9soD3MH3RV2riymQZwcbrQtlYmUlWobqMNPvrICJZXZhuLi44mOwoKwhLJ6c/PckTcpkezr+Js=,iv:uKlG0o+zcdVQl9nb7erL5BCIYlAOqbnwDV6VvaBBCp0=,tag:iXHES3ayrfxZ8rardQXSLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
