aws_region: ENC[AES256_GCM,data:mUZwZQpykIq3,iv:ubqEbTCeE9SnygW+jgSrbpU4h+vfCL/9Ulnpv/aE+aI=,tag:T6+GMHcdPVse4Ow4XYgovQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:02:21Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGi2X5MdOf78x+jyhfvtnu+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/ULPtmvQq9L4iz4KAgEQgDtZATOZNdmBg8Rp334oDTzhqj4wCzP4clxFcC68LV9XPsb16J218g5XG8YG53VN9kAiV0xPi3oXTuO9EA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WjhXclIxd3NXUHBrVmFI
            akExZ1pXa2ZQeGUxa0UyZ3ArMWlPUm1LWlVzCnZ4YkpZMXErU3J6TmFoWnhKSEts
            d3BHVkxKMkIxOG84TFVBdlJsNzB0bzQKLS0tIHpOa1Fhb3FkVm9IMDFydjlZMTlF
            UWN0anowOGdsZE54eFFEYmtTSXBjOU0K/ykWS+mOK9DhAvrGcof6FnOSUkyPiB0V
            grJLWHNhzrXIG4KsbSp0i2aQT3Htq+j7+8vJMS0PgS0E9MlQqCS1vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:02:23Z"
    mac: ENC[AES256_GCM,data:dZy4ePM/E51Kg7tRyOt/ji4B/P72h1kYZtN/FSG/SqA0iJg1HzaXP28XMwLN3hmVQcBE+c6/8516wy6rb0/GSEyZrE5knphpJTfr43ASSZRce4QL9bJ3Zyp9ZfpdilmsJovLrT+m+CJPo5vBQNQsSiL5p7RBG5RfZRmqjxnaL4k=,iv:VBbCrYfxRt8pQi733DUTnDu5rO6nQntcnMoYaH81SCA=,tag:HYS3w+nofOZ+XcHhlRBtgA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
