---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: production
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
  values:
    image:
      repository: ghcr.io/matrix-org/synapse
      tag: v1.93.0
    serverName: matrix.${SECRET_DOMAIN}

    workers:
      media_repository:
        enabled: false

    extraConfig:
      # enable_registration: true
      # registrations_require_3pid:
      #   - email
      email:
        smtp_host: email-smtp.us-west-2.amazonaws.com
        smtp_port: 587
        smtp_user: ${SMTP_USER}
        smtp_pass: ${SMTP_PASSWORD}
        require_transport_security: true
        notif_from: "Your Friendly %(app)s homeserver <noreply@${SECRET_DOMAIN}>"


    ingress:
      enabled: true
      className: nginx
      includeUnderscoreSynapse: true
      includeServerName: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
      hosts:
        - &host "synapse.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: false

    externalPostgresql:
      host: ${POSTGRES_SERVER}
      port: 5432
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: matrix

    # redis:
    #   enabled: true
    #   auth:
    #    enabled: true
    #    password: ${SECRET_MATRIX_REDIS_PASSWORD}

    signingkey:
      job:
        enabled: false
      existingSecret: matrix-synapse-signingkey

    persistence:
      enabled: true
      size: 8Gi
      storageClass: ssd-pool
      accessMode: ReadWriteOnce
