kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:VFtLxm6h,iv:v2Lqxh3Wxx5h2wNg9OdO7CDfyiNf9duitK/IYmP+WWs=,tag:pAtjVCCdLEE/acn1g0UwLw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XttxW7tJMBNWMlc0LqUWXLwGh78fdKmA,iv:1Bc0HD4TGwVxv9yAGYBP5WwfdoFCw0Rpt2pciryIunU=,tag:tGcAKDNmkj3CohmH0KluHA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:LNW6EktZJuKceNlI,iv:ZSnlotZbQQd0DfRMdjpwHlSDibl9UoEWA8cNxD6xlcM=,tag:9o6wRGk7nU7nP3TjznXarg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:IE/Tlle6MMRqLnGcWc687TN3hdg=,iv:F1F6JJVVwfq3Bf8azljh7rIRh8YYyhJS+Mv8WzSvL2c=,tag:8AT6gNFGsscMcDU3yhCBmg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:JA4Ljs2Td5NEsAsrpEVxgVrEgKIY5VQjMNcd07oWsPigN8K2cqaHetVe6G0=,iv:ieOgMyAzPmABT/xJmVDxxqTwg12fR5KXwhsck00Wriw=,tag:fAUdI3Jtv4I0ksM5jeDAwA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-02T07:02:30Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGPhaY78Wq12hUbqOW8lm5hAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYRLEmxV4DptVoo2lAgEQgDubIo+OpnXxqF8lk1EZdG0Fp0Gku/1uGw/dG2g3FN7+0WbjlDRRhdNpeB1k43V9c0v/wE3ExBtK71b0cg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0RNaWFDc3I3dnBWV0Rl
            Sm02YzdFc0Ywdjh4TzdtdlBjaTVWK3puOGhjCllIN3RUKzZiOFRYekhwOFNiUGh5
            RTQ0YXVGMHBBcEk0cm5aL1ZkNWc5MHMKLS0tIGtnZmtXdzZEUzhyZXpiRFprdFlu
            Y2hvZUZWamdQTHY2WTVFeEFMUXozWGsK/S10VMjIi6jXn2IBuh7JBNHG72yUgZh2
            v4OTbekRYD+42m34Stqk1hpK/TmarNWE5GgHrIjcgGS+dMaSKFS5UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T07:14:25Z"
    mac: ENC[AES256_GCM,data:hxMguG1vlhP9DuauNWyqs1ymAJFZuRpjxeZ/7PKZEoK57/wbFoq7JYz+tk60Hx3BzFfxPOjfX1dCVEUUOPZbHMAtRjyt+TT9y8ulA3FgNqCk3dFIneh4wcYkbRSAS9YS1gVyhb1V9GwskUifbDKDLRWWOenOGUGwYxHfHoVAuUY=,iv:GXACrZnq/8bTHSasYitBh1Qdh1Gqk3GF8WoJyGnJlh8=,tag:hMT7ZodXPa+N22goMsb3Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
