kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1xSVkfJB,iv:Kg3zz+gcotX2MhtOzrU0P7EqspUYYBU/LW7QsB28qVc=,tag:plL8DKmLOv+zm7iZJz7mHQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FCkNZ1yocENeR9Vrmv4VR9oBa30rYgZr,iv:qaK+GshFoZJhS2dqm1ZWqVhoN5DZQzg4RO8u+JBR2ns=,tag:2xUavWWKGpZYMZZ60D9rpw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:HeuQbH8wewoV3D9U,iv:hVpEnzwMgZnLJa+lVQKw55ZfMK6KymRAQI+u+DPk6X0=,tag:z81VYhANahvhqINa8zE3ng==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:WrNOuvCFE4XQFmNoyXKvFXvCs74=,iv:hrXkin4g1k/AwWShHU3AV5Ast/Al1ZQBgythBkU0NjQ=,tag:knHJfGkNW7DtnYOSzzWmPQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:R7/TyY1kb393wFkjX9eY5wrFeo6w81hgLgssmriUedTzk8SA64r27lX12Hc=,iv:ulLjoQf+mwmHg85nMdUq5J9D5NgAcESriS5dMKDG1VI=,tag:JUnnWRb+ajsfFQpQ4p2cuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:19Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgFicscXoCSB1gf9aYYAPP/TAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMttromrBskukTME7HAgEQgDu0s5TyNr/F5z+4HVCk4ZeErr9Pe9ikmUckOvOgCV1r9YHMD40MfOO3WUmkkeNT+dgPCdbEpQLnV8iGpg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eDc2SUZJYmNyZERLZWpR
            SkpiNEpsSGhnQ25uUGdCWnYxaUFmOEV0eERvCmNYRWtuQ0dHbkd3M3RPeUpFRGgv
            ZnRJd2NJd1haMTd3ZXhRN0JsbjVFTTQKLS0tIGZOQ3YzUXNXSklOUDV5TVpidHFj
            alpmWXNhSEhmbTJqdktESWJ4SXk4QkEKo6AwdIaIXGvKY6vVrZLOaxASOCySpOFq
            Hsm1v77up/mnET3f7/zbb6XpI1wIhr1qXi02oNDbVlX4XiCs89NbAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:21Z"
    mac: ENC[AES256_GCM,data:dx/fVTI02MJPEBssirNxAyzd+Vc8g7AQtTMbZrE1QhOIFKGnKfOTDxHOjiI6DdLcoTAAMS2k5wDIoQxeCOc8ROfA/lblnjm4oTIlvfynUm53tLXlqxhfbd9R7Hs6zx3EgKeW+ZCid6sDestdFv3soNoqQ73RwJQA8w7AhCCfuq8=,iv:XgZJcafq72j/hDJx7w9zqzQdu5eO2ezjrhfRpScnLcc=,tag:WZ6eqglFHSdgXhxeHJhdeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
