kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:+31DwEyI,iv:DLbEOd8Rpdt54LWYWgRKhVOc5S8hlT6NVhTvxfCmBlI=,tag:JZinZ4uQgQdnFmh9ImpusQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i/dDUATinJc8QgauHqdpXIWhPCAPdZ6z,iv:MsEU+/1TxoJMVTyJkEO5LI1LXsqwKMAdobce2Dpz9Co=,tag:t0z2FRwcQFSqvCVgueoqrw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:jAFWKgurCntW5D1c,iv:6R+klp60IJN2pDDuK/yu1EsZzYL0V+wuTyOMQ3DadL0=,tag:WwK5rGVe/MJcFkGfExMtTg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:EFsX3pLbyfAYbWP1JdhYjUkYpGQ=,iv:WDov/NLmV/iZetEAn1vyAWg15Hu/TVR/a8RY2NUiy+0=,tag:Q1BSGRUNHUzc1MRaKIdMzg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:HF2DnWRi1reIILkWK6iu+qSIMhTt3guJwCxPr3TrITqNm10H/d9VAmg0Okc=,iv:tKov9qz8eYhCmeD2juc54ntyVY5Gq0xIRrSJnOwo0n8=,tag:7nTNSgLV/nwsdW954nockg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:38Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQH51IxA8/b9oPvmUTSsCWnhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhdQkepWU3wB2vdL2AgEQgDu/tTSBbLOPT7lPGqtMyKyF1j+3bN/gER4xq17EZ45hxPAkHmrR7lwv3M2yOgy1mn3fxlCLlQn+NMWfkg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV3E2bFdUWDNSRjJxa05w
            VzVJYmZzSHlpU3lJVTlsWWRaQStKckZZUUdVCndIQzh1OEkyOXcxQ2NsYm9SSVZq
            a09zY2VXUmFpVFJkL0xvaFE1QjU5TzAKLS0tIGxYb1FJZmdGZEZLTmxyV2crMHBu
            MDRxblluaXpKNTV0ZVFjWXQ4c01tWk0KGw+3JZ8NgBP48EWtLI8E1LRIEwzOUhqD
            N7mcMgca0gtcenh1HDtOz35J6h5gqt+KB9wjp47gpjfHIVmTggyKAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:39Z"
    mac: ENC[AES256_GCM,data:NIhdNiKri0ZQeEUg/9qIkQHSfHyLYC/U8qe/hbN9cVlm+6zQb2yKcq8ln2VXYYp+EM8QUWQ7jjXMGGG4NivNCrGqFj8pVGnlyzZm2FvTB0AypeznSrAuCw08l9xjmrCWVHM9F8spkdSGaEEJIS9kWFpyo96bJV4gsImmjtRi0Gs=,iv:4P2/TKQ7moRDzdIshEB6wPh0nHTWf6+b4+koS/KEGIg=,tag:H/eP/hnUqUd66fVw8VwGtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
