kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:kOjMy3qa,iv:rBEawcRK0i3Hmsg0VdJtmGHQlVqFc8R62IXIDPjP+Aw=,tag:0Ab78oJq172VyVrxebQIdg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kh2RcoF3lRjr2gZ0bZyUSxvMrknbzjnC,iv:/yqFboaKr/VMHtxjwZ5BGxaXaRtSq5g/s01PfrdLh9o=,tag:0DluL8HZKo/MwFyxU/2vCg==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:OHwohbDQdaEyd10/,iv:+rtZtd6dt5mYH5mJ/PntHcJQ3GUK4ed41ROyBWGLFZc=,tag:krGzIeP/EmqFIZfHS59YIQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:a+K5Wtu+wko7ZO6L8HNWdTSScEc=,iv:kYv34NZGNdHaqLYTro+AH/7TNbX2reiDbdTFDG8WhbY=,tag:I/+oACTkhTSz1W+bjV2RPQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:OeTW495fPOIOvZ3tW5P7bOi2hcCxOmK6EnKDdVjhzdEX/s0L7ZPIM6z5g3s=,iv:Mh3aIBwPMmGduSXXTeQlWCQrEQZOwnZ28QFGVhD+QMY=,tag:hVMxVDgl4YWY193kEP/LMg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:32Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGeGEX7A9xdZg42mFPcnFrhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvYsiyI++b4/UoIxQAgEQgDtp8ATp4yP1i89SzmdvgfGOdeFmBw+Gxb+VitEAkAyEfdJWKdiGhwD+gv1npqykJbGedrp4dQ8OQ03mHg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYXRpV2NwUVJET2FyUGpH
            YWpHc0p1VktFSnJLK0hzY3YrN25GUUZieHpNClZtcmorMi9RanpSOEo3ditUVFdU
            bzQzVll3Qnd5VHgvdmo3bThDYkVVVXMKLS0tIGJ1UDlWNGdUUGd4alE1TzZ4VTVo
            MkNuenBXR2tiVGRrSTFWUzdiVmM4MG8KCl5obb2Hy1gpbLoR0m1DeZnqBPXP1ze7
            lCNIPHnETNY5fEt9faBF9BFq8rq77HlHVZQNH+gmk0DkkvEogh5hzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:33Z"
    mac: ENC[AES256_GCM,data:9MnvYBq29GTXC6Y5wL55MNdbieVaAQJr0IaWwVcLUPbF8iok4AotUgQPL0W+gPeVLuANL9wSTIxyVTFV0QGXfZJsMdP2eIMiUvJInSNodnBnjM6k2Pvjfia8dMXQTDw3Yr+lroRIqlXNl4BbWez02lIv20cprBocu1wQW/S8Mq8=,iv:3cYGdqtxIsFub72WXm+07JrJxmDcTOREk3APC6UgV3o=,tag:P9aUkB6AL9TRmQrUhA4Dig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
