kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:+31DwEyI,iv:DLbEOd8Rpdt54LWYWgRKhVOc5S8hlT6NVhTvxfCmBlI=,tag:JZinZ4uQgQdnFmh9ImpusQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i/dDUATinJc8QgauHqdpXIWhPCAPdZ6z,iv:MsEU+/1TxoJMVTyJkEO5LI1LXsqwKMAdobce2Dpz9Co=,tag:t0z2FRwcQFSqvCVgueoqrw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:jAFWKgurCntW5D1c,iv:6R+klp60IJN2pDDuK/yu1EsZzYL0V+wuTyOMQ3DadL0=,tag:WwK5rGVe/MJcFkGfExMtTg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:EFsX3pLbyfAYbWP1JdhYjUkYpGQ=,iv:WDov/NLmV/iZetEAn1vyAWg15Hu/TVR/a8RY2NUiy+0=,tag:Q1BSGRUNHUzc1MRaKIdMzg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:HF2DnWRi1reIILkWK6iu+qSIMhTt3guJwCxPr3TrITqNm10H/d9VAmg0Okc=,iv:tKov9qz8eYhCmeD2juc54ntyVY5Gq0xIRrSJnOwo0n8=,tag:7nTNSgLV/nwsdW954nockg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:18Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGKzLZIPdbdPiT+d6KnVOtwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYhVKjOlFCY713NaoAgEQgDv8PiNBUI8RAjjCSw1xMnUR4O/yIuhKYv3IqegCmFCSiSARr2VQUC5griV8bQ0kkHG96iHQyBOvK3AlaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSnR1dDVvOFJQRytjYis5
            RDhNS3FNQy84ei9SSjVSNmluSzlMaDk4UWw4ClYxTURGa1JIRmtGYnVxd3huY3F0
            ZzVmRWxTcjhBWFRZT05UTXJZcXZmb1UKLS0tIGhhTW1jUy9XbFdCWVFvcVErWmJH
            clZIV01iL3VSZnc2V1FvL1FKRGZBMWcKdqS07jCj0B5lHnRoLqTtIbq8LedN020R
            ws18z/WOXAqUDa5sMEs1QWulJENGCdXiLnLBdquLvUQxtR712TkE6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NkJkd0dGL3dOQU8wVTBj
            RlBOcjRtSDkxK1RKYzJicmVQWDZVQnlVTm53CmE1Nnd0U01CdlR4WHd6ZGppOEVq
            QklRcHBYL3p6NFZIbnVpRFdUQVlBUVUKLS0tIHpwU0cvUFJJQUU4ckJFZ2hrKytM
            RHpob0dnRjByUGsyRGdsYlZaOUY4QlkKgQ0+q6jgYkxEaLtsIcWnsYlVHv5xVIcQ
            sJ+4ZViDNzaKXSV8rzDIbfVVcFGJXqdmZoa9XFx+2dryU+G7gpOV5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdHRwc3N6UTJIeU5nRnF4
            d1A2LzNIM2RvQTZHcmo4cTFLRnM0bzdSd2wwCkdqZDF4dUJ3UjlkTVc5UXBZTHBq
            Ni9sVFFrR2xyN2ZySERET1h1OGNLZkEKLS0tIEtwcmZFYlowSGY0Vkh4aVp5NEdr
            eVlkTUdzOU5uLytKRWdKR2NTR01ad0UKQjPFutwKLXsqJpbPejGO0QkikVDENxiV
            ZTeQ+Mqm6h0rrbN5WlQg4XQtc5gop2+iVR/M6wwFIximN81watbepw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:39Z"
    mac: ENC[AES256_GCM,data:NIhdNiKri0ZQeEUg/9qIkQHSfHyLYC/U8qe/hbN9cVlm+6zQb2yKcq8ln2VXYYp+EM8QUWQ7jjXMGGG4NivNCrGqFj8pVGnlyzZm2FvTB0AypeznSrAuCw08l9xjmrCWVHM9F8spkdSGaEEJIS9kWFpyo96bJV4gsImmjtRi0Gs=,iv:4P2/TKQ7moRDzdIshEB6wPh0nHTWf6+b4+koS/KEGIg=,tag:H/eP/hnUqUd66fVw8VwGtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
