kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: synapse-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:gbq4KAMO,iv:k5HXJrrhTEb1lZZE/6WUszEpo0d70ViqpLuIn7a3jIE=,tag:ivQGOVL+IVWWZ6cGdairkg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:SPPcZ9Ig1kBZs5yj17PVQMQ3epMyM7pl,iv:b3OrVkLke52WIixxOysuSE6kxVGEHPR//qX+b02CZjE=,tag:DRbri2odG/NjIgeG2lCgDw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:yUp8UV/UzYQ8dMWs,iv:oXnnmy0FXN1GjRTQqmm6Lz2EMY72/q5n1KuIgefFNlY=,tag:zTKYzXJD5o609SKs62QMZw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:o0EJt6OPPH/mL8PKcJQKHbvjSsk=,iv:UjX50nYJNLzf1t1dn4EbzdgrwC/qNJwwX5g6CO/xJqQ=,tag:I4CGalQTx/pcm971O/TSIQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:IwQwN/c2MRWce4+bxT/fVup3opg5tHILOyYbj0qe5FzsMeYHLZ36pPYngxg=,iv:kHzpKXeM1NB7sqbz3T1GghRXvqWPzHopVv+664U/uKY=,tag:pDtt9/XXZYKx89bWe5kORg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:06Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwG/HS+oEGFs/1O4oKecxE6PAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMY2/dsugkFs+sIybSAgEQgDtYkuyMp5Ti6Y+LLuBGbHeh4vWVFZx07WoI+EcLbsRgzCUAohzlp988/LgXp+buLVESJidZOkGNZyNOOQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYkVyMVdNR3R3d2ZIa2I4
            TW1NTksvSEV0V1JOK2RDN0hUVWY2aHFBL3o0ClRlMWV1bnlaTGMzZi9DaDA3dFRO
            VTc0d20yZWc4M3FOU2l4enhqbHIwd0kKLS0tIGhVdG5BamU4eFlucXMwOSs1MHY4
            WnlTQ1JXVzJIWS9uV2xtN01oaWtEdU0KQ6tDH1nBB7KNL1nBYO68QaKbk5AL6Usb
            4Ea/nfonWm2skE85JwLOOi8yewhHiw9lCsXEerZoMz5hPoxdbYl2ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:10:08Z"
    mac: ENC[AES256_GCM,data:JjYqr7jmTy6xOy2QkgFylTVc4C0N4Ott2r+pCO1bQtKV7l3fqxjeVZUwglBk3DbhEVlyEqtOIflS4BHUGMWA6tAnznhf5OykVFbI3sUw+II2P9n/Ed5B4Ryv5cW0rWIJQYRgq1FOwt6j5iycq4kjlFFmE2LJ7xE8xUyvjNzA1W4=,iv:DW2fymPSCuzST0MraSUa5DhBiuzh94BnN94KfDZbgTg=,tag:sCc0s5m9tFBow5r2OwEWHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
