---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-wizarr
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-overseerr
  path: ./kubernetes/apps/production/wizarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
