---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: "${CLUSTER_TIME_ZONE}"
    image:
      repository: docker.io/hkotel/mealie
      tag: v0.5.6
    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/appName: Recipes
          hajimari.io/group: Home
          hajimari.io/icon: mdi:food
        enabled: true
        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /app/data
        storageClass: ssd-pool
        size: 5Gi

    service:
      main:
        ports:
          http:
            port: 80

