---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    envFrom:
      - secretRef:
          name: mealie-secrets
    env:
      - name: TZ
        value: "America/Los_Angeles"
      - name: DB_ENGINE
        value: "postgres"
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: mealie-secrets
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mealie-secrets
            key: POSTGRES_PASSWORD
      - name: POSTGRES_SERVER
        valueFrom:
          secretKeyRef:
            name: mealie-secrets
            key: POSTGRES_SERVER
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        value: "mealie"

    image:
      repository: docker.io/hkotel/mealie
      tag: v2.8.0
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/appName: Recipes
          hajimari.io/group: Home
          hajimari.io/icon: mdi:food
        hosts:
          - host: &host "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        mountPath: /app/data
        storageClass: ssd-pool
        size: 5Gi

    service:
      main:
        ports:
          http:
            port: 80

