kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RgiYj7Mn,iv:OH0nJdmF5Zk68rVWg2e0XPFn0DgFqK3wdKw6wEcqBHs=,tag:7JEtV3CN09CX0H18aI4xdw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i7/4wZpOe5QA8SgHfZEoEifJWj8+/yWb,iv:n6D2W/zxLowmoZSXWduu4Psd8GwDFbjZuhr8HnzfgYQ=,tag:QYxBLiNccc4bDe9dKjfXzQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:SCelKLCjqkz7dG8y,iv:zvcvkdNe8l53d8eQAs2BumRcYiPj001fxtgCTt5q8A4=,tag:ogBXTbVQcBCrOM7w6Y/CHg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:19Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHX0RV/5IMrxRC4joSBRo8TAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6AMcR0PcV+4YdBnFAgEQgDuSorvWdoCcQOYy5mgv0bzj9sgLz08YzqoWM2hnsh2DHz/HJpbYpQOLjDlcUd38qAFmyhsNfbCOpYuVlw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3VnSm9YZXlHZCtmMVVk
            aW85ZVkwQzg4aGxOSXE5L0x5akFPcjlBdmdNCmoySkREd3RMRlR5NlJBTDZmTGtY
            SW4xaStJeTJaUkpZY3NSbjJVbktqWWMKLS0tIFM3ZGpBOWFLaFdNTXdCL0FTRXp6
            T1owSkZtbksvRTBSbXVIeWJxTXJzbHMKujxXabVNJLrWdVh3hDQOv0hnXXn8uVCD
            967ZySD0cZqF/cry3UpApnAdBuP4c9Y+Hu/N+eZapiDDUR2LthpdpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcmN6enhCbUVBNk5BTnY5
            QTQ0dXdMSmVORW5JTTRESzZsaVkyWDJvT2prClBTWjQ5T09UL2IyOHIrc2drNE9J
            NysxUHh5MmtJcWRWTkRVckMyZkdDQVUKLS0tIDQ1REJBdGpFZ09tM3FOWlJHdUJT
            OVVqYk9VZFZVcE9uekE0dzFPbUptOU0KVQUYTJ30Qt8FkPDUbETMQ1J9l7wypPZD
            WQAGoCcEcO1nV91CIvTqDHeU73U7/wgeGU6AZwI6TIQZ0zYT18CYWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYmcySmJnUUM4WXdvS2Vw
            OTJ3ZWF3a01Mdkw4RldVOG9MdDRjbVNnQkFRCk9KMEp5Zzh2RUdYQ3RSQnlLQm9Y
            OGF3Yld0UHNPWVVhaVg1Q1NTZjdXUFUKLS0tIExxdkF5eDBNb0kzVzdNZ1lhWnF3
            K0tqK2tzQkdTUGlIRkZ1bXBDdEpSNWMKI3DtP8GwShgG792F+EqjwkwZsY8dekOP
            pnNf3HVbUKcg6QXjmH9/LDEktlndQkYMuEfP8PqN6OdzK4f8wCtAQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:41Z"
    mac: ENC[AES256_GCM,data:i+U1kBXD/+ZBl2IgXiI2ffE6FFQGske+wu4Ftpv0SDK0w/dS2NtIWZ7GezSHYtejexAOn8Sy28ZqOSHfUOjdsPPIRzcXhMcywNoDKDdAfmbDRazeEYLaRZndRPiGy4OvcIYoBpcAa0UQtOhuO/V0b0zJ3pqWFREKK4NgsLPQpzg=,iv:XzizTOKGzpZ1SVwsEt6g64QZlRdUmmWlSWmYBI+liyA=,tag:MO728rqg3l5aqqS1ffPFyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
