kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ztHxBwrc,iv:FLHYsk8Ppyc7hq9H18LWK0QvjGF47a2kXN//e/knkQY=,tag:FvvXrNIcybp1s8xXkP6N4g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/PXhIaZjE1XYRaTcBkrN4t3cmRtjCpeZ,iv:Gy4CzOEjn5iNKlpPDDL0qWDp3FjD+df6Fo8cFMUA9Vk=,tag:uwFTK4aRl9cIYOZCm5F/xw==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:/wxw+PP+pu3ShdOi,iv:E1OVwJgvKcTjr5FwVDmBrCvU0o1pPazzX07ECHOgvnY=,tag:unw7m+MkhSwD2q8dGgIK2A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:21Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgGsFS1Z/tfHpBIPomwsPhOqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYTwEHgwG8z/RFcyDAgEQgDuUHsKFGJrQFY0qe2wBjLIJbhGtx3d2ptPBuGrRBRAqzYyghxAbwKNisCxZhff8s9FI19UtjariP8GFtA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZDFqVmx3ZWhqaDNVbWZL
            MUxqNW9TN0pocEVZV1Y2VEh3WkhyeXhGTldzCjdEcVRsT1BNL2IyOWMxYkNiNFdS
            OHRnTnFvSWVDTkhGS1Zoa3BqbWtxNjgKLS0tIEd2cjV1b2dvYk5ZZkRJWi9HMUY4
            UG03UEp6RWxMMldkVlhMTlZlWWlxakEKPPMZzC1e8n8ym2ggFaS1IfAREEcH+lW9
            NnRmPOx7j+nHjUqMduJIh8gHrePSoi7tEhzY8PHLDA+yUTL9s6VXGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:22Z"
    mac: ENC[AES256_GCM,data:nCCZ1s4rMVr9JPGHq4g1yIC5nISNX3p8OnxiIAViuYjZUuhHDHoYqTfPQVR0EyjaSi90JUBoD9uzPXUQVZjLr4mowGrGCrkqo29yMSIp4ahJcCftPvWtkhZaEOkqrOt+Ul2rb5kowhWx+9AXO5zRDP329jGkwgeH7jWuE+rNRz8=,iv:hYnxesvbrJ7naYubkOMpUrS6NSfplbg6pt8r9VI71lM=,tag:EcqqhPzci7cnLex7Id0tfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
