kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:YI0fuODs,iv:Hjzy5yfP3G2GTnQkrjMK96ydr7UeMaYtaeMllNk2Mdk=,tag:hqgBNgV7F/N6lfo3UWECxQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:y4AiKD2QOTTkKBkOF1xqzWurG/vdzTZi,iv:sKyOul2RccgOO/KwnifwgEs+SYB6iMnGSKgrfk7ccik=,tag:BDfRptt+gAE5HjUYMAb7VQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:E8tSMhhBnzU62OHt,iv:QuFteUXfcpHtg731Lx+Yu30l74TQdLGU2+Yj+fm5HaI=,tag:ar+FtU46WO7ucBLIxtN7WQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-02T06:10:44Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwFkH3pHr6VX6SrUxgwIuffPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGb286+YZe213YMrEAgEQgDvKt6+Emxr/MPIrBqHQnbHaEUVmks0QRkosiP/pwHpNif2Blr4Pvr/CllSf3Ob9DNMOQt8BUk3Y2kM8RA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R2lVcDNRM0RIZEk3QW5O
            aGdkeDJUQytPemJjektOQmJnOUpMdHkzc2lnCnZ3RUF4dWg1Q0VaQktZOFBqQmZk
            YXRRellvZUVtUnd2S1dlV3IwU2t2WWMKLS0tIFlLeVo3UmhTaStCTjEzYkVpeUJP
            U2ZDaEdqRFcwaXY1L1lvUEZjSlZMWDQKY7RA77My/TaVw6sTtFvFS4/Dlagd48r2
            zNHdTdMmt9f/Q3M+uoYUQ6iXcszf8vao3QG7t1xtnV228R0VSSRnYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T06:10:44Z"
    mac: ENC[AES256_GCM,data:pEZ/e5utm+fxCfXZS8lOK2Iv7uxTda3RmOsz9EJR/6pAAWox6KKREKVS+QFj3OeH0VzcsEM9w7cfI9xCfCmHPzDI43uXagaCXGe65ySYPGk1bWHaKLdM/fMRDrbHAkr/4lfsTrYtGfjzcvEZKHQzT5k4Ho+08wEvTrrhU/eY81c=,iv:pZG3uUSlMKK881JVVzM/gqzNbzYl2TFJ26J/fxXhhow=,tag:eKleop7WgZDc6CWzDf6HJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
