kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:vqZhng6N,iv:ENDgomg/4NsUAyIhNQ4IxXVX7ZbhBUv+K7oV6c2YM2M=,tag:ziUgYZYchSIVINtHZemOwQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:djORSLZCljWOP1IuIBZxBVPyTwpRyExJ,iv:zTKw/bxwZgvZv6MOynBqBLJqaEUvFZcnusPPvz2FUWw=,tag:JPGoa06UdKEcy7qoLiiLSg==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:4MRpTCfFLQLGSsfU,iv:ivQHSBz+eD5cCbJACeWDsUPzMChGsge5XZ3OUmd1Lng=,tag:9ysGOR+vyer6I7+xgHxcdg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:35Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFCzY4DDNrEPJbaLoUpjd8kAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpWTPCzg7YocC6WTBAgEQgDsvjqN9FmofAQM+BvoPm3v+Z0DRj4oonWZdiYkX6npJ99QQQpGe2wLFhwFJlyRQGQoisIhxX+boCLKFgw==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSjgwN3J1RFR3RnNaeFha
            K0hVaDdQY1RZZ0diUXloZ0xJb2lWeVl6bmlrCldLQ0tEcGRWMUEzS1hxbVhHZFRK
            V0d5T3RsdHk5bWcyQk9neFNvMjFleE0KLS0tIFVraGNLeVdUUy92YTZFTlBudjFH
            WUJOblgzUWp3aTY1c0dhdXU0TGFYdkkKhLzboLUEwgOM1rPDmBEzG+96ZtyYvZOy
            8KajYri8P+W5i1hmNf4FGatygi4/fKqG6RXnoLhUSomSlZ0d+/TKEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:36Z"
    mac: ENC[AES256_GCM,data:6tcurRZprLhX/vxo/tNblbGbsqGQyjTuokpLAlgn1orSc3OLUifHEmLWaOUZLk10Qxewm3IkxRSZ5deTH/AYKeDJU8IWNg6FS5kmu5ggCvqlyGuom4Hcxi43MNvTzMEQ2DisIkg9SJjRBaMLd5k7hfu1UoQctT81bADqEa2iOYo=,iv:KzP3KAS8KmAyaaCQ4pxxhQMLAvgfghRZ0TciIoaUlOc=,tag:pF57EJbUDZ6D4j/V81n37A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
