kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RgiYj7Mn,iv:OH0nJdmF5Zk68rVWg2e0XPFn0DgFqK3wdKw6wEcqBHs=,tag:7JEtV3CN09CX0H18aI4xdw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i7/4wZpOe5QA8SgHfZEoEifJWj8+/yWb,iv:n6D2W/zxLowmoZSXWduu4Psd8GwDFbjZuhr8HnzfgYQ=,tag:QYxBLiNccc4bDe9dKjfXzQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:SCelKLCjqkz7dG8y,iv:zvcvkdNe8l53d8eQAs2BumRcYiPj001fxtgCTt5q8A4=,tag:ogBXTbVQcBCrOM7w6Y/CHg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:41Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHHdof+dk3WTbcROjLs+fTHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiEcu/mPKeG5zdKPiAgEQgDsBdogaIoMPx5rXsFDL+7bQIaO1qkiCKDR8/XOef4FZGyXc70DXVM25ea7Iu+xVNbFyMUY9YLAfSfh1gg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBak9OMFpUSFQ0a1k2Z2dS
            dld3WWlHWmtkTjdJMUxjK1BKZExtNlpvWVJvClAzRjREcUQvSjBtMXNvK2J4RThG
            OG42b1huT0V2QU54M3JITUZtWU0rMTgKLS0tIDRPcmQvMEdZa0RGYVloT2krWG9N
            S3RzczZrSlk5NWlNalJMWVhkK0ZOSHcKkb9cXr1a3aVmiT828R1aQffNPA8UygMC
            nZCCguElfgswTCwbG3xYC1XNUotGeEx/rVWytxoEqNtEZyrL3k5GbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:41Z"
    mac: ENC[AES256_GCM,data:i+U1kBXD/+ZBl2IgXiI2ffE6FFQGske+wu4Ftpv0SDK0w/dS2NtIWZ7GezSHYtejexAOn8Sy28ZqOSHfUOjdsPPIRzcXhMcywNoDKDdAfmbDRazeEYLaRZndRPiGy4OvcIYoBpcAa0UQtOhuO/V0b0zJ3pqWFREKK4NgsLPQpzg=,iv:XzizTOKGzpZ1SVwsEt6g64QZlRdUmmWlSWmYBI+liyA=,tag:MO728rqg3l5aqqS1ffPFyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
