kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:YTD3lVPm,iv:t4Yr6V302VSjyIDiIluONQAjzVGWedaUyfsCxe6rcMY=,tag:IAbLttZCrnvuk41MUPTZBQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:p7UkQtk1V2BlKSK05uVPw/v5R6jyqDwB,iv:uszubsOxZ70tyivySDIcf3vxina5x+LXpvBf7qqQHJQ=,tag:Gw7rg+tlz140aCr5eraKlA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:rcJ3CCaBzGpBL1a+,iv:mE4sM/UeUxZ1d9Papvbm2+RemM15BfJtgDiBjHOSfoE=,tag:jmIL1Fui0ngs9QOBr8oTww==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:08Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwF65JVgUCLNHMLVqMijv7QMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5W26x8m8YNPOg966AgEQgDvbh9OhNwagGo0YPB46Dj88KYMgRzxkqtCd5YBIyTN7ggPLDKosIg/ChqH+MPITKhbdvg9z+fuh1LqynQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL25BWHBkL3pPYmNEOEI2
            N1A1ZlM4N2lCeXJMRVI2eGVGS25tV0k1UUdNCmtZSEd0ZHhoaFNwb2JhME42WTdE
            VzU1OEFuRjJjdHJvSk5RZGdxU3ZVMzgKLS0tICt1b0lKRGFGbHBpbkVFSE5KRzk3
            eXBya2ZmRjIwcVBNWFdObjJvT1UxYkkKQsM8uzd31fWV8MOyc0Qk5u1f2PHHV1DO
            8IMEWeUi/M31ms0zaLmVuvt1vsXL0AstysTsvossTWRUGF1dvfpFUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:10:11Z"
    mac: ENC[AES256_GCM,data:uherzGQqSDNvpQAh7KOxLjG6HEK2Xhq44R48mcVnF6HWD4l+x7EYocAey2h+bQJtEv/LRb2zBKEdS4HfLClKH+WN/kOGlGtNKRRX08XtwlomHKj7/s3UyXvJ7t7Vo5lEKll995eYgLUI3j/gloCij5pFe2tPWeHKX7MoorvIXtg=,iv:UJBZY348490rUXYM/u2sY1RlgrWpneJNDhfeJ3w+F7A=,tag:tI7Q9rJ9007Nko2EXfF9jA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
