kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mealie-secrets
    namespace: production
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RgiYj7Mn,iv:OH0nJdmF5Zk68rVWg2e0XPFn0DgFqK3wdKw6wEcqBHs=,tag:7JEtV3CN09CX0H18aI4xdw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:i7/4wZpOe5QA8SgHfZEoEifJWj8+/yWb,iv:n6D2W/zxLowmoZSXWduu4Psd8GwDFbjZuhr8HnzfgYQ=,tag:QYxBLiNccc4bDe9dKjfXzQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:SCelKLCjqkz7dG8y,iv:zvcvkdNe8l53d8eQAs2BumRcYiPj001fxtgCTt5q8A4=,tag:ogBXTbVQcBCrOM7w6Y/CHg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:49Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQH9E0d8sx4RyDJVssWDG549AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgva82y0/ggRQPCCZAgEQgDvr832dIZIee1sngyyuBp3hIOWsEXMXowdrT3T+BN/tmfq8QHi/lForUCGMHQ/ndhcx5rcYPDQQAiF1VA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ29DRkxTeS9vYW0yL3kr
            eXFsNXNkSDJueEE5SjEyV1o1L29La2VoVndFCkdFR09JMVJWYUhvWmlzbGNaQkk4
            R1JkbTFkU2lhL0dFR3orbEd5eUZmZ0EKLS0tIG5ydG5xRU43REhGZ2psM1NYc2w1
            SlZ1TFVUNVQ3MjFxOWdKL0RIUGIzQjQKBVjQYWfAMksDnKonCat+f2Yfq8o9NNzR
            esnaJln5tKej4gZwZlCaQsiui2qlu3BTxxrBwoXzNecXhXSQUR9uyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcHlDaCtrcXVpUEpqYTdi
            cWFXWC9vTTFDaWswWmZxeE04bG5XcDB2cWpBCmIzSHk0bXRITU52SUcyWUdMSThP
            ODRDTWtYSUdHVzlyWDZLNmxNc0xEc1kKLS0tIHRNMkNLSmdYMjl6aUI5TzBhN094
            bkVybGl6ZFJkaCtNRm5Nd2wvVm5yUE0Kvh0lWwyJDrvvAQH89hdBebvx04z9D2S9
            3V+N5lWcHZrDvyseLcJ/vZ+z7/Z6R9auuqHR7QLT0B3las35D6ifTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:41Z"
    mac: ENC[AES256_GCM,data:i+U1kBXD/+ZBl2IgXiI2ffE6FFQGske+wu4Ftpv0SDK0w/dS2NtIWZ7GezSHYtejexAOn8Sy28ZqOSHfUOjdsPPIRzcXhMcywNoDKDdAfmbDRazeEYLaRZndRPiGy4OvcIYoBpcAa0UQtOhuO/V0b0zJ3pqWFREKK4NgsLPQpzg=,iv:XzizTOKGzpZ1SVwsEt6g64QZlRdUmmWlSWmYBI+liyA=,tag:MO728rqg3l5aqqS1ffPFyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
