apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    VALKEY_PASSWORD: ENC[AES256_GCM,data:n2oWd0/GE7/91SZADdRJTMwKETgVaaUtgCBryzVTMVYu9iAcy+PqglxnWGziwVIC,iv:zvHcOXRyqvKDw7v72tOUef72jY5rdReNVkM6AvoVciw=,tag:gk5DgGTYaB9ucpa+prPCLg==,type:str]
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:CwIDlcmnaw4vZRhaBSC3pCbdx/EXR/t7TaJxnQ==,iv:GUv+zxh62o0oF6SKJC5wjX88BINF/4HYzuXfplFWiGM=,tag:3er1zYngnOlGCTeV7HL1Bg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zvQhJ1hwsZU=,iv:wHuOR4Jp3j/0KqtemXedgb5uuP9bNwmFD3597PZ6csE=,tag:7Wbcog4OeYSr4aTGpo8xcA==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:ZmI2j8EYWaKO,iv:yWCkFoQ6drLNfLCDhE5Yp/tD9ZkXfma0f86QaWEWVp4=,tag:RAH+JQmrBzeCThTSfTyaLQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jwIQ6Va8aQXTrlq+bvKx/g==,iv:YpqcTc96KmgadSZfOrlXnsz+7iqSendi3Z7H1Z0Y19o=,tag:3P/WrOy1/xFApIe0X21TTA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wGJ5ZH0Yu+OCxw6j1qWlf3ZEKik7JNUxcznRSHvIIPzNIp9d,iv:3ljd6GbYOW0c9Ob39wxAHBB5LtP+SUvpBRrtNwM8CtA=,tag:7Kapj0NNXCveIbWUyMbA1Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:w+wp,iv:rzK4ndStvsgdTzrWtC8ogkRQdf2EtRaHnM2NDdiZQXM=,tag:MbPqkmv5Q/DSNCDk4xuEsw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Wvk0q9PVOcf8rqeuqALMKqGUm9J1Ljzi2J2hPERA1OoI7DcaK57qPVAUx//esWCt7qK9fzRAoo7RMogSIGahgA==,iv:TIJmih2Nh8qd1VtJrrp0Sl20NQ2wIXcArAgK5T3KCKA=,tag:FM865uDMkZENQyvOz5PMzQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:KaD1zrQQJp2T4dPc1C5JFsH5eZlz19bML7UdO1FioNmhviN/fj0c,iv:Ocjh+KvzR2ZEwyS8wtUJezMEMjutUXMTwYVvhHKcb30=,tag:QEAE7kwh5z41HwyG7/S6ag==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:QOqtfivRGeuNAKP7J8AMLfklOVM=,iv:DSjJV4yOMdstYSP8GFpXNdaayagu8OgA4c5NotwroSA=,tag:U2ftFGzD2Sq9GxynYz7bPg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:9/EUM58B5SQ0vk1bKTOZmVPyjvXuhUoewM2UpMVWUB6+SUpXD76GCrOvcWQ=,iv:7iC3UIEWFLpSeTd2Qt4G04Ik0BsH/vRmN1YvOQoICUw=,tag:i/UDlpN5z/hc67uBJNAbXw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:371R2CoIXejxqwUYylaJ0PZemA==,iv:CnJPar1/wNaiv6htTzwl4BTiV8G9O4J7v2NP9w4ZYrE=,tag:cOoom1oV8Yas3hDemOfpsQ==,type:str]
    #ENC[AES256_GCM,data:qAvZ/UgDQhtF/iAca8jvlXga94lS/q8=,iv:XILDKhdxC18B4yuV5k+yeh9NLOPksGhY06x3Fj992lk=,tag:Eho65pWqQHBBGRHZirCZnA==,type:comment]
    COGNITO_REGION: ENC[AES256_GCM,data:hnvT6RXkZEYf,iv:nVxtti4yt5uhB4u3DBpIB4Qb4qx9STc8ZOKHE97GVgs=,tag:8HchwpJc3TXlJQV7TijPTA==,type:str]
    COGNITO_USER_POOL_ID: ENC[AES256_GCM,data:tkbHcWhvH/roy//lsYwZ9IEcjQ==,iv:kmXkGklGqGd/1rA6n0kktnpTB1rmaNo9t1UXZWMbGnk=,tag:s/P9lMaUSQf7VUiVfeeZcA==,type:str]
    COGNITO_OIDC_ISSUER_URL: ENC[AES256_GCM,data:CYFw5aXvecKRZZWmgs86wp/gHCXt7yQjo4D2Tu9TPWnkMW54O4fXvOlk/DSgXjD0xBftfZuMoJgzLJ1CAnYk,iv:wvOJuIlYSxzJo6WixHRpCTwFSHBrEAirRIReon5FWes=,tag:1k/k4A6DJhFSngq81Xgfxw==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:+mIdKjTU+D1oCE183j5emNkCDwHXwFwXDA==,iv:MeATjHLLHYREsN1BjPKvr5OcLs4nVPlMxjDv88wL2q4=,tag:tTVLRp1mOlyksYhG+CDkQQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:kFWO09cF6JlKJk7elWgjaGUX5dj/ys6h8MOIzXHUC8SaT6RlF7q330goJ9utVTC16IVV,iv:g9XcsRr3BYUzuviVrCVmLXl3t+k7WXuv9nD9eoUFgzI=,tag:TbtPB/2aduAfQyAYEopXBQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:0gosq46C9BhEj/KLM2dGxjQMR307HjpJRHT7Q076eXE=,iv:LK0vfw6rYnTCZoCgUWjOBWZyUiluvG+F3pTZKCasE/0=,tag:BhjKN4WDJWPnF+dH9c7eCA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-06-03T00:35:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFgx4AH87AMWSZlkdBKDItvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMonjtrxLnqkXu2p2/AgEQgDvZH4xg9SDX6l7YP9DSWWeIjMUyZEmK32BFfo5PPpXgYqZQe+8GIeELdZlKlwSFRE5SCld65Lkg685Prw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaGY3cUJiMjZRR2l6MXpt
            eFRJelJpcUlNMURkSjVvd205MkdpVnlvOHdFClEwSEE2STRSY1Q0alBjbUtpUC9O
            ZkxqRmN6TzIzbGsxN0NNTEtucENkQzQKLS0tIEhIV2wzelp0cTFZcHF4N3J6TkhY
            MEdQVklCeWpQOTZQdWl4bUN2T0ZMeHMKDca4QU6VrD1TpxSZ2x3l25M+ohihpF2p
            i3quzs5ip9KRjRcibEBZJpLYqz5WN8rKS1fMI615d1SKX+kh17EfQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdG51Mmx6RlZRQlllQVRj
            WFE4cWZkSDlQVHVpSVhFV0ViSFU0R1luUWhJCkczRFZNeW0yaE8yTGlsd2h5M3Qv
            MytncGRYSTBMTzlvVWZBNEVPcUhiWncKLS0tIHRpZnBNRWNwZ1ZpRm02MHQzblM4
            M0JJTmxSTHRFNHladkFLcnRaMzU5bUUKgPbOxlaw3omvzHEnXShrNzSjkHgE67K2
            NcVlu1jCGD9Tc2KiTkN2vl9gXUFRixiSxJHkxtlKcb7m/DOohgc0Og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyamNaWUJMdE1DK1R0dzFv
            bHhiNHI4R3hLYkxwM1h1azVhU0xaYlpvRHpzCmdyT0J3cVRXRTJGczBINXBhNTBO
            SzVJNVNHRW1uQ1NndjZ6dWgrNFBBNkkKLS0tIGI1T3dwMGY4My9lVXljTHp0RzlS
            NXdMem1oVUdSd2xoTFZ6QWlzQWUzS2cKpUcu9vYdmZYv34QEjux7q1afBxcFDCPO
            8tKoNWOR9uJ/p0Xlvcd01bbLRhcebHeVJ4v17yYae/iL94w6UwBFlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T00:35:25Z"
    mac: ENC[AES256_GCM,data:uVV84Oh2YnJAemP1reVSuu2F9BC5wYBmHPmBwDAGBeImrvtFIxnpYtUyWjkiZpSSGXKiLHblyvmLjlCRE0EGJC4rqyAueKIRlIc8BmilusZhjdpLzBsQJoNRSIOh8mkofKNZHV9FKurq3G2Ay+zH7NBU7Y67jRULlCGSt3sW+Ec=,iv:gs/jZdIydU7iT8nbEG1Xf0XOPl6TGrNkOxeJ+hlWtr4=,tag:1jDNIUjJcWMiTpmweiP+VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
