apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:ct0bGKe9n2XrGhc4uGPF6/G/7tdMO7g38jhhtg==,iv:EbQ5YmE+APpJlhE7IjB9MscGLsvgQJwQ8rifyIA5YDA=,tag:NvITevo8u65DoSV6dkV7yA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:EN+EoISJV4c=,iv:KbOVmA+FJTAkWp82CekhYd/wXD8A2RoXrjYE0D+jnrA=,tag:KG6snpUA/C/VRF0zRcm83w==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:8xbNnjosoCTM,iv:CA+6V96NwPTIHUtuf1Stvmp7TxGJ62j5RJefA/xTTts=,tag:uDh6O6Y8llvmCrCYesRLDg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U5XV2iIKBZTrAC7/4Yn/Cw==,iv:+YlEj6p+kztX940GgTi3Tnr1d0eTa8MZvpREG38j/rw=,tag:mS4bvwfmUNZ1Mv8/T10qug==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:kHUK/ThRNocJq5TTzdRqX5sdpAcYVyDiZA9eGCyz02GbDyp8,iv:tRCe+YxnAVGXcPUMW5IcHouBqI5C/LYF9197SlinGC4=,tag:wMaoVH8M2sQPi2huXqS2Ag==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/X6B,iv:PnC4r2LkaR0km9YId4zwNQlFOfvI0C1DdCkfloMUNm8=,tag:Q2GSVPddmePJ/WsVZMNiZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0QD0ITekF8cjwBJmRMGpETLmqIQlDVU6ffPsXqlVrurzpZnmvNCFiUDYjQW+jD1C/m8gPMKEZY1slLqe4MP22g==,iv:xFQhZy6D/80iVpB4onFXS7zW48Dackif+xdvsmHKKgY=,tag:gTdODlrdkgM3Yms9iIrO7A==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:dGh4JK5Lrv0NnU1HOmnc08TalOq+P7Nx/1dUwI7nelBa1hMYhMWu,iv:prYjj2TghEzB7ATyiAeSItrD7tgOQbSz0ZfWi/EkGFw=,tag:lsPT1V556uYWSbKK7Z3vTQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:Mp1KpjKll2RuEirlgT00lEJmRrQ=,iv:AukJTLVS4S5McCCJFiCalpewmXIVjScuLxiTkrw18WU=,tag:Cufvci/DDAdDh3MePAeRww==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:nHntPT72eRsfvrenou069sNWo1HSIR9hhwmg+dBAxZofah+yA15Gk0uIUe8=,iv:sDIQzMbxsWaMyk1nRAFFgInk5XGihSOIjguFgcH1LDg=,tag:n9fu/a+WpmiQiC5/KGm9zg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:/sajfowJMxgdSn9AhclNWbB3kg==,iv:QFB6MTvREyqBDO0tNKdKw2/+oCJKde1bCyCSpFAILs0=,tag:6Zlr963rfWFDDkGXWo2OIg==,type:str]
    #ENC[AES256_GCM,data:jl3Qajq6fF89CWE4vIZ/xCaM3Q5h36o=,iv:uCEDuyRhBZzdpRYYoPEECDvDrHDIWk3PXH6IvkiZkDA=,tag:lbuXIiSodnsauK9WLFD3jA==,type:comment]
    COGNITO_REGION: ENC[AES256_GCM,data:M+1DPaLzt8M6,iv:2o5bOkFlod1BUL3InbSqWOCOkc55HjR/KKULUNx36f8=,tag:3Ik1ImSP11KgveseKwaWHQ==,type:str]
    COGNITO_USER_POOL_ID: ENC[AES256_GCM,data:N/VW9/pLVgV77SrPk0WsPflTtg==,iv:pylkgmG4bEMhwPjDETxVCiT8Laq4BfSY3UnEh9fsOfI=,tag:aycPWeF98vRIghisDAMWeQ==,type:str]
    COGNITO_OIDC_ISSUER_URL: ENC[AES256_GCM,data:KTFNmSQnabu4PCd547QsjiPcbmU/tAclTteioWdVy/Mi1ChKa8tMiaQy9i4W8PKIjP/NyTh/wLtgDxKRilbU,iv:Cc2S+QK6ya2T5btPMZcYKFSeXg8VY0sPLzrd3RDfNuA=,tag:QRa+0kB8YAR2kcDINs54SA==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:eWzE26fTwybotZSDer5Bpf2Ix3jb5HNFhw==,iv:TvDISMU1OPSCSNIadUXtFLG0voScuCfnBO9XQr5e4t8=,tag:9FUqjh5SCY8QxmLI8MNHWA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:c3dx4IuXA77yhU2plla4mvvoVeGyR3BCvx7WzgwM9iZtLjCOEHp8sqU4V7y7fwR0jfG1,iv:0CUjX/CLK+poCtccoh/dbGaCdgf0mNk2WRAb8+KKA+s=,tag:ri55gapEmDgvtPd7UhIuRg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:aNpszQWcf0faovolEhG0Co5N4dQYd0njuhOig5imrRA=,iv:j+EqCHvaI4lpaBpSrHwOeu1bzNfrwnrkaSKzRy17L8w=,tag:h52zDWcDqjz1wWqffK0/+A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-26T15:29:32Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGDo4hWVRTpAmvZ7FhP+WplAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMC8bwCXVU8vfghWYlAgEQgDvBWWMnHo8m5/JRCMHsadKXeef7XsP++cI+omIY2wdQGqUPZ/pRQdz0cKG7xohNEQ16Y/YXcWvSVUwXOg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN2JEbW5nRTQzZGdvelky
            NHNJc3NibTQ1WW1nVHJlQVEyclh5a3ZLWWdVCm02M3RRSHBjTXVXQ1dLT09rWG1E
            UEw0UGwyUTd3NG9RMEVNdm9CcmxlQkUKLS0tIFo0ZE14QVJHdjJ4emdTUldQSmVJ
            Y0RRSWhhTHVVM0F0Y1RzdW53NDJXUFUKamUN4dB8Ps3a1XWCTn9MuTvh0U8VabIZ
            vLBrNXPcQ0eocy+94BhRN4lax37ikfsDTrljCVQZJtaIhF/uQrlQbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueXdzTzc3VGs1SUVHQUI1
            NXNGb0hGWWVJbHV1eTB3a2E4WnZzUktzcm4wClRFVyttTUNBWHZrckU4eGZUYkRU
            aFk5Q0ZuZ25JbnB0cG94V3lBNW1HRFEKLS0tIFBBVmdIWjFxUko4UDdJTnJHNTRx
            NU50cVBnT04zSkFlMGNWT0FRWWNnWnMKBcXFPWTh/U7TdGYkJ5SMRShLz9JktSlJ
            pOcxYYREsb2H1KJn+UNSC7yPwfaUq8GUQ4SXvRMyyIOPYXyjWmJcrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTUJYemJ3Y2loU25XTVVm
            SlY3U0VqaDhtTDMxdDdoNkc4WWRTcGhtVUZzCkgxY1RWZmZ1bktYZUVFZlllMVNL
            bk5oU0dnK2t4U0JDYjdFVk52N0ZOVzQKLS0tIFBDdEFqTmgvVlNqZjBGSzk0SlFj
            anpGNVNVUnlFd25NM0p1K1hyQ0tVUHMKWcNZhAcocdX+/RDQtjCccPd7z061mF3c
            Z+8nJPQwQOWdaBeFd+8ZaZ54CM4HrzV6Cmy0VNGsezEpF8w+YCjmTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T14:32:08Z"
    mac: ENC[AES256_GCM,data:P0SZisJiqtlADaca5CDxEikFE5rlYI1lkqe90M5BZrtUkRQpCFrexnKZtszyzFzqgTgCEnDeuAC0LdjqNOzGLSt0k7/UFo+EzSPDwh1lqd8YIdCmITHmCyBnNkK/2bQdZjkcEuzGbqfPA3j/xUnD8+R3EUDXEeC6WcXNi/HgEks=,iv:z55UD9NkHULd5YZIWVGc7v8Px5qMvtxf6avSuXaPbI8=,tag:DM+fvbAsROjSEHKPX7P9GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
