apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    VALKEY_PASSWORD: ENC[AES256_GCM,data:5//5UcSPBE8WAMxSjNEVlv/2X3kH1pG2SckNcDAYSzSNtnsWcCJMoiyqzvpPqFkY,iv:hMcO3SPEoW9W4GCaQBC+bYVdcaze1L5A/X9QpN8L/Sc=,tag:I1j4ukc80Eg5TwVVJHVuOQ==,type:str]
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:zgRw6PuWBzocLHY22MqG2cEofRHS4opjFM5B6A==,iv:SYxPK1RsOxYlG3En3sn9XjcG5G79FCYjZ4xGGVhwmds=,tag:t+J1RVPEX50zvt/vkYqALg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:o8UOp0gjCrk=,iv:1aOG3bB0lBuemN9tPec0ppY5JjtIelJUWxHF1dQHAW0=,tag:xQPX48bf8pHXYd4Qqv58xQ==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:GL6kg6Oo0Grf,iv:8F2GGxpUSEy+60oH1WOsWSFYKSjkbsBmQqFP3Cggbis=,tag:9TgnN+2AuwpJXEQNFS5RwQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FAQIBBWvxOBHUPpaafbJeQ==,iv:L8VKWyW2oYF9NjbML8gfLgd7yfMR4YUcoEwnI7IJx0w=,tag:qgsIFZEjtswfDOoWOMpeug==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:v3ZjO76PBggKmOBsPN+d+F7N7ye4sS5Uo9s3LItwlFpE0XH3,iv:f14dDlZ4siWQZZ1+CC5CIgUamVjdG0pNnGnjO4joQgA=,tag:8syA7rl/6/s1p2LptE+X4w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:tUa0,iv:2vZriIXkD0sAxQ3MNxLwKtoAtEtrWLRZNcFanWuZUiE=,tag:DVoik4iWoTFVD2NqGyR5Gw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CBC9IlrToBIoxlLJSceq6d2V2BMLlWzRQOvY1WfHQMerUVdJ/9ImRvzgZLidcn1UfvdYlfvbKHtF4QJgUn08CA==,iv:pF2tvyWtH0tNkpTI+5M4k7EejtFsOdYITEnjHJFYU+o=,tag:ruCNWXXr1OUMKnUQ0tJT1g==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:v8SX3J+Qkr4GxQyDPLdO8z9d0JgEQB0I7NI/+kJBeAmUgFZFDIdM,iv:uwrydLQwnNKUlZdLIF8hr8nQfY3W+rgZpo8CFdHOSdA=,tag:G8+V2wM/fTy2mMLUwCvriA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:+1fyQ63OoDpqTn66GMCe+xt+zNU=,iv:JR5IdBGYMNwAwizZIw3s+p5Ck1YlDaMYO2N+ciuuFFk=,tag:iN1vK1XSSU4JtkX/45+KeQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:dCLM5O/jm/yEoMkzPesQ/aX2xX5MfBjRTIDbBSteH63SM4aNBV9UjvRR9kM=,iv:P2CiHYDUPkHy5a9TXvnx0kMRjzWr8++c9wC2JS8NfEs=,tag:6mMCe7PHNYuh8zGCC6W7Eg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:ymA92cKlVs30JHWJtyyGx7OYCQ==,iv:f5Ns0xZ5SKL+mqXgX7sNXkd17SxS8KHJOyPWWQe8MvM=,tag:isKndjR6bsTUX/WyTVTxNA==,type:str]
    #ENC[AES256_GCM,data:Zx1wLsbdaJVjpFgibjAnT0UupVZWDc4=,iv:jTM6nrN69fd9L7/SzsEs6gg2VAZRRdbul+I9zXWzfms=,tag:updG6676VWX0YTbAww0T/w==,type:comment]
    COGNITO_REGION: ENC[AES256_GCM,data:jygewaenULuE,iv:ogo1cPZ2EkgtC6HKBqxVJlibcrqwxjPGmjRMhHF/19g=,tag:zctLhBH+PVEzPy24FVWS6w==,type:str]
    COGNITO_USER_POOL_ID: ENC[AES256_GCM,data:FEDzh12MT8bTVA8B+M0JzMPyHA==,iv:rHY4NFrjCPvJ8F+ihBdI86nWhxDWU972bko71hVVdNw=,tag:1HofPVdbgUnvMzzKyXzryg==,type:str]
    COGNITO_OIDC_ISSUER_URL: ENC[AES256_GCM,data:k+Yb81c+st8u08+VcEgXidaOeBZYDvXzfTLTszkdNLu/AJ5pySj8VrZ1nWyxzbkFrRUJrseKpdwv+G0AjgAj,iv:n3V5kTQ0PSh2C1LVmL2QObUDjd2O8bHe5YMXB2G++Ak=,tag:+j6aTcdlUIIOMyGzLL9Emg==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:lN/ARcyGOT2IsZpltU+Atlx31lanGgE1Dw==,iv:YvJIcZu94TrcfsRutuIaRYgBJ0mRw3xRtF5L5rkgA+8=,tag:vkN3T3nyG4bkERzfkvp7wQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Jd4G6GQQ6EOxaEpxahuqlQFCZIhLK3vzlxEJfZzvO9OV4PyQT1Fm06uOz46rWwgAe9oG,iv:bdMwQvbPwkjDRXeC7oFcI1/P4LJcd8wTFbOzWGOjJFw=,tag:km95M0ItEe5HvNq+9MIxFg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:hx+0eXilmF2zklHtGpDR+f03gNf39Ij1PrDpXREH7cE=,iv:rEbetbR8X31ZAZZNk2jG2v7c2DwZfBGcogqa6h3+N6Q=,tag:LJnSbRNI3cdVir+CD5Gg0Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-07-03T04:57:32Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQF7pECJlqzaOxx8fG9UoyMZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYz6760vACB5GwIghAgEQgDsYHO2g7UnQRWCfxQkAKbztVXEsUEKDXN/ZNxVSql+bZyDXY4ga86K34BCsa6bZCboQQua8XizYEyLSaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ0ZleVlzUkFRcVJyVjlZ
            czRHNGYvRTU2ZkFEWjhGNUFZYVg0T2tqeGlrCnhhTWpQM3pTNzhNR08zd0dxcElW
            ZjdlY1YzejhiR0tzRWlDZVZYMjBhRmMKLS0tIE51R2ZEZFZpdngzQ1FGb2dERFUv
            SlY4K29VWG5pUVlXREptcTlwc21UanMKu0fkQwGUoGwJQC64uLhI03o4aQz3zZbD
            20tnd1SdoOFJFH3DKjNE9IiY36Essw/vuXf7ilM1hXyVyKPd/kZImQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZEJhbDdLRmNxSVYvam5C
            N1p4bE5jdHpVZjFWQ2QyYk55bmhPLzN3K0dZCmJmMWEyUzlXVk4wVEQ2RmMxRzVk
            L1RwTDByem1abWk1OTIxVXN3MEdDVVEKLS0tIFJNQm4rRUZ6L3lud1FhRlB4bW1u
            WS80dXZJcFBZYTVjeFdxSW9vOGl5VGcKoX4RbQvC+mZIbnggXu88gpuayoLUMOiC
            vR7o/w6E0V61MIFdj1M4FPOUw+LKIJVlujLzYbQN7HtqVGh/IUFJig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMXpSMUJNdUd1cC9kNmkz
            RGRhVlREVEFINVVGYWJkKzZLbVAzNHRlZWpVCnM4MXlDbUtsTGhHbUk2djNhZFgx
            NnBrTCtvNXY1U3grL2tacWdoOCt5ZGsKLS0tIE5uOXFhbjNqdUZ3SVI2MGo5VnJl
            TEswYmRTVE9QbmtRcTcvelhQdEZBWjAKzg9BTwWHHUssRloMh81wMUShQa/G5UFg
            Xspp8qmpUmIQI4wtc1A8Sv8R70Q0rP05Qpt+EELXyfE0qjE4obke7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T04:57:33Z"
    mac: ENC[AES256_GCM,data:p9FeyyeW0y70LJ4CXSg1X4kAvCyol2UziYEroRjmySLIYdb5ej4p041h9XEcZLObobboXM5X/+tnLm9l7R2HMAnhg85uZhBQqOcH3g5HYPEaoqFT82DhUa5dwwjmAY5wr29jjiu3qm7TY4zyTOK3Kynyc1Uh0weYXKHEbf67KTA=,iv:mKbjHhZPgfI9qVORoeJE7IDlPmeZ6KK/QAjUs+v2w6I=,tag:ENsviDEtqoKI0wLOXXuxQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
