---
# Flux entry point for the WSL cluster.
# Loaded by `flux bootstrap github --path=kubernetes/clusters/wsl`.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./cluster-settings.yaml
  - ./cluster-secrets.sops.yaml
  - ./meta.yaml
  - ./apps.yaml
