---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./recyclarr/ks.yaml
  # - ./external-dns/ks.yaml

