---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: matrix-element
    files:
      - config.json=config/config.json
generatorOptions:
  disableNameSuffixHash: true
