apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:fNzzxcmJnR8=,iv:F9WpN1ZMobw4pGdAHMRx5qQZx1ZYwW2nfAb3Toc6ju4=,tag:+WCU3m8tOKGfW5lgh2jtRA==,type:str]
    password: ENC[AES256_GCM,data:gl4tP0Amp/gd/6z2C4IDgGqIJO0=,iv:bVU8oc33IhEl8RexSIXD0UiWZvHqCjfd2oo4gnb7y0M=,tag:1eX/tQqNIfrdEEWdWKnzUg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEwwJGt9+UlY+kig7gl7vfXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNfGjHsdHj1/6zEeLAgEQgDvjqexJMKQYdRVt2C18/eMKSxPk2Hwe7SYCjJLW28fGitTMqyRjNs3o/sfZzPu5Hjpnmo8QmMCWV4yDXQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MkZMdGlZMWN5NWFZWklW
            dllWNkJFamdsakhBZVdabXVUYUwvNVlBYVdzCndZQlRYK05SMFkrYktrRlV6c1Z4
            OXo3Sm5JTlE3MmpaS3lEenNSRFhuNTQKLS0tIFZXVXVJaHQrTlhqQ2ZTK01VUkhT
            SXh2MlMrb242VjBvOU01TXdKRFd5akUKHr4EyNUb27TlVCcQTwu7bPeCPPVdgSTf
            acDjHdFtNSJSM05EyrwM78Zy5xHojbaapiIvkdND0L50rDyYnyJ4xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRStyNGd5cWpESzEzYmtR
            Ym9UZFhIOGhzTHVWLytXOXZNZnNjVGZ1aEFNCnNxYkQxa1dzdDlQdEtoK3ZIUmI4
            MU1BWWJXVXIxR3VGSXRRKy9kR1dtTlEKLS0tIGpxL3J5akhJOWFoSDJvRHpzdDho
            RmJDTEhhRjEyZnl6ZURSSFEzRUNwb28KyhqiQbMzONjlVDh4VzddwNSeTQx7baeo
            mQ9VmQgGIoWMYd9/j2h7FW+hdKXQMOMjp4X+TvnrLml5wOfrxGUCOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS2MzZGZiREtVcUtlTnNP
            RmdpaWFVcTV6cCtlckd3MFJHQ2RPVlBGdFZZClNzVmRqWmk5cWhSVS9vclc0clg4
            aEw4UWFoUm1GVTR0WkphY1ZubGN0MWMKLS0tIFAzWXhreFZyUDZmeXo1ZUM3UlM4
            bjRJWldqRTlNcERkRnhCbW96UVY5aXcKik2CDUfg0K8u5fB5jlLGAe4GLmXjLtdh
            jJmKbZ37Mnpg+7v+D5t1SPdTSOP1eDGpQdKNuoIUCzxc95Urg+rWHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:37Z"
    mac: ENC[AES256_GCM,data:vpBE2Ic4OPvkXpGZnWcFdi7pAP7sjKybht3fr8PRAZDJfZ8LWShvTy486wv9MKM7b8OprJr3jVDhBvayDFzM4jwu1LnhQaoAuExVMpZw5kV57xBHfU0ku44H51om9qtF8atDIoXt1es7TYzdtYdCssU8qb+m4HsCyTkXttaxVHE=,iv:vkR+SFdkyuP355ihxz+hmDuzt5qH5tpxrZLxGwU5ez8=,tag:9MlMc6YU5g0nHIfxIrhGgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
