apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:Av0RlYJWFDk=,iv:MFKMJzdpH3K2Om2TNBSkPi55SK9Imbthp+3iGRbN5qY=,tag:wSnUGplyA4O3i9W+k0v6ww==,type:str]
    password: ENC[AES256_GCM,data:edKudw6OuOWsitqCEmNplfShfEQ=,iv:uahtYF7NoMcFfRqgFWaMc1jCtwtErJF3MMZmoUZ1To0=,tag:Cnj0nXnj60KDKRajmFoaFw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:43Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgF0fcgiC+2wqtdeoWZeKopVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQMnCPH8H4SeTu2UQAgEQgDtLhxF8p0/A4WJF4khGHGNYCAAaO2zKcKWReS6pWhdbRF7fIetXitLkKwS3Owpf13MuV3lNtSDCE/8kWw==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQVJlNytVSVlFeTJVRUcy
            RFJkbGdtS0xTUDcrNlJTcW9QTEcyb0QxbTNZClZuZUVqeFEwLzBxU0lXa0lONkF6
            d0VrRFlqdkZqN21IbTVRUll2bDFnbzAKLS0tIE9rK3N6MFBQREtBUVNFSWt0Sk43
            aU9MTTkzVkRGYlFDVmNXLzR3NVdjZm8KVtBcw4Lixzw2vNYkJ9Fzo8Vy5F29AgYX
            wJMhxmP4jcowhJ4JyzFc/mIKt/ytToZoNotgEYP7/LgiDhVQlqNi0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:35:44Z"
    mac: ENC[AES256_GCM,data:Lddk1X+g9I8kdxRFPH2fuxj0jeIA8oWSHhrBH0yo1DqlFDtCwwW5jmNYtXObjGMwaOupLLvbKUI2+8zHl11GD3WlcJmLKmjzyio1e3fzgsk9mDHQIP6lyB/TnrI2TyF9cF9AukZzvX0pbj89yJxtylNx62MSVf19/xBLp4G1Jnk=,iv:hnPjtfhVcENfBcN4zfa3+fkGGcIit/lGn5+NGKlTJaU=,tag:xqPQRx+VIt6NrfOx/kMAlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
