apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:fNzzxcmJnR8=,iv:F9WpN1ZMobw4pGdAHMRx5qQZx1ZYwW2nfAb3Toc6ju4=,tag:+WCU3m8tOKGfW5lgh2jtRA==,type:str]
    password: ENC[AES256_GCM,data:gl4tP0Amp/gd/6z2C4IDgGqIJO0=,iv:bVU8oc33IhEl8RexSIXD0UiWZvHqCjfd2oo4gnb7y0M=,tag:1eX/tQqNIfrdEEWdWKnzUg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:36Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFFrffuP2Sn3CAn8CsdEy70AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMogAN6sJ1E1L8maWwAgEQgDu+8UpsECC+OIx+u3k8USTkOv5ybiSSYbSNJUUm2tJOl6zmViZwz+qsDxIaMQBvIPGTP7JgTyZGIDWIug==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa0VsRFdoemhRbWhTNTVJ
            cWE0SEhOKzVxTVg0UWk2N0lYNWpMaWFldWp3Cnd0N2x3WjNsMzh2TjdWdkt6TlNC
            cEpDUm5TTjRYWGM5dFlpVkNqVXlpbk0KLS0tIEpzYzNjV1p4d0xydFNDZzFhMDhl
            UVpGUWtIUE9vSzlOa0c1RjJGQ3lWQlEKPrCCmh6V5KS0ANgSb2/pSZ/LaAGr/8X5
            7W0c+5IJtYo/rF7tlVrDLEjc9touKOhGGBatunmZA2LyEQNEOZ22ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:37Z"
    mac: ENC[AES256_GCM,data:vpBE2Ic4OPvkXpGZnWcFdi7pAP7sjKybht3fr8PRAZDJfZ8LWShvTy486wv9MKM7b8OprJr3jVDhBvayDFzM4jwu1LnhQaoAuExVMpZw5kV57xBHfU0ku44H51om9qtF8atDIoXt1es7TYzdtYdCssU8qb+m4HsCyTkXttaxVHE=,iv:vkR+SFdkyuP355ihxz+hmDuzt5qH5tpxrZLxGwU5ez8=,tag:9MlMc6YU5g0nHIfxIrhGgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
