apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:Bxnc64ArsNc=,iv:CtPTcC+Ch3RlQnjchGtzU1APbsLVShyd5KsfExFYBu8=,tag:+qC10xT82838CKR6K2ChfQ==,type:str]
    password: ENC[AES256_GCM,data:pvrPMmFVUUQJC0URo37XoResGx4=,iv:KJe7CSeofige3H8bch6fUQZuxPA/I8LSUirp8q5u48o=,tag:iTXg632hBxvqm7PQppaWtg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:17Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGJIycZomDgu5cnJNo9m7RoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM50pmelwWLy07BXUIAgEQgDtT2lFc3oM9dnbGtCChFkOWh/4/XRu+DLlhqYOoD5JRN7hZqPtHMkHYiyTApZxBm+GNyqnhiyrnUaVjWw==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTk5jUFZBaDFxMDFSQlBO
            TXhua2JzNVF3NTVkZHBYRlFySEVUT1Q2dFI0ClQ5UXBlNG1QY0RpM0N1K0gzcnNU
            MzdJQVNyS21MZks5NkR0bmF4TnREQjAKLS0tIFJwV2gyL2x1bklWeWY2c04rOTJH
            Y2s0ZDRoZjlRemZIdVJaNkthUGhVMEUKNayWR0vafqH0aMiF6Z9lDBNTLLjSMI3D
            F8ztN7J1y9UoTMSpNFeL9tQXcHayHpYym6H7k1rQ1QDoLkdhKYDS6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:19Z"
    mac: ENC[AES256_GCM,data:cAgC1mNrZJQfc4BGh4YuUO+Od6bziYhxcsDl4okmAJ+85HipBpzaeclmzKThWniBGicKlbnB37oecEq9WPhiHsUvy0ZIi7wJZf3lPFRFNJ7GPPhDagCeQIB8TG7MVt+euU//0GZ/MMBPSy07UYBR9DqAlztwB+ytplihWmFBizo=,iv:cdAKNgK5v7jbkBUGnAAgXeKvRyF0QIqDUh/QTo03asg=,tag:w6Y557LQumRWd0mj6Mep5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
