apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:7bQA6nVx7Vk=,iv:IgF9xBHkw5hd+Dn5KaqeLwvqJu+uMl4qj3VKxbkbvxM=,tag:qTsfXA9vVugpDLrqsu5yjQ==,type:str]
    password: ENC[AES256_GCM,data:b6LLm5ew30HFbygZM657DFEWuYI=,iv:nUEcu9wLUgjloI9ghnYLiOae9GfdPkWk5sKJplnLGsM=,tag:VwI/eFlmzUlUjJLASObt5Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:30Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHCGeC+TfV74b0QTZDQ9t5lAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNaLIYMIbR8NukI24AgEQgDvo8zxgb0jxnK30oJfEwsJNVMSvA0NV0wpqE+Rp3Yq9M8AWjfZzOebUgyromXKXubHhOtbQnKDW6AO65g==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT0p2bVgvWjI5OGYyeUwy
            dGY1VFhhMmNmN05salphRS9KRVZqZUxYMEJrCnpZRmpISVU1b2RWbWROMXQ0UGVm
            bnNuTWZEVXRDdzlaWHBicEwxYmxSZUkKLS0tIG1jMjlLYXhoR0ZWSUxCZVJjTmVS
            RzJESmVvRThSZHlpajBFMlVRaTczK1UKTLEyVWvPWDykqLtwRZYGQPPdaV9XdQYy
            zG5qkpIi9a1YmGK2OE87ZDa9MVKWvHFBKpIRYn9dSyvOAaNXFhKMZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:31Z"
    mac: ENC[AES256_GCM,data:NH1UJB/ZRDCqLpPu2XBucsU9I1Rwqtn1dgQSG3HfuxlZmMUvMkWld+hSQx47SZIuWNZgURhjFtl9oien08tPLlFzKa9g6zovfPQFuwQa50VoZ2t9Vow/FzKU29+e/CaBgXREiaZTZvNz5NLUEhFGVK5DbEVDDSn1JKUF1jlKA6U=,iv:YQ+FmBaOWLEB3KpvzQqDbjx+Q5wpiBfsnDXqidM+jzE=,tag:TNXnkotBm0EeAG6FH7VN/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
