apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:/37GTe0d5Jc=,iv:uPZvGIqs6XJ5BKlRpT5Fd0tK7ZC5yxs4NrbqvX1YlgE=,tag:KVU8mtXPBagPdL2PIYeBqg==,type:str]
    password: ENC[AES256_GCM,data:H9Kfdlr3PKIX0OzDcXjnv9FdGws=,iv:vvpJZNFZ/9Sm1BCzMgfmrTeW5MOk09nU3YsERLkE7HA=,tag:37mnkkuxY8vLko0HBtsVoQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-02T00:56:31Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwFMkc845Y1v0Fmyvz1SLUZ9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiqpT4g4yQoCxKCw+AgEQgDtzXh3XFUWWvbIxMbJZPLX7JgtcnHROKhIQvGFdShVEOpzYTVYWJe5BZ8A6BAUEdmTIalAL60uwy/CYAQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S0pES0hlQ2dNbWUrbU85
            MmdyRWpYRWYvYXRtcEdnTThxQXBRSlZwdEhBCitqVWphZUFFTFRiWllUN09nQit0
            Tm5DbTlWeStSam03QXQ0QXJHc3FXRFEKLS0tIHdUSmJ6bi9GYmRLQWVGd2NXSEZQ
            NmZOcFhHVjc0ME1YUU1GQS94bU9vVVEKPjtDfMZigpFFl9YdqW0dT9vpshqU8/q7
            D6O5uA8VM0N/dDgGZSiznlPJVgp+xG1H6FKiUfnO6vbXOitoUf38Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T05:36:41Z"
    mac: ENC[AES256_GCM,data:Ef7PJXZjaAYcTGnB1/ojFNQwJWqqL34adm7Ap8pEG1H1wnveJYpB0nVJM1I+rGqKRnBCYr8BnYlAG+JZb802+fdZYM1UmayvcLW0etN6rkEOZ+bwzs6nnBD6T5SJxY5ffpezpfdZ7Ll7IEQEiUd0BGq5qjvYyQr8QWinfJKQXaY=,iv:zDuxa0YyNEJjcWyFIM77Tb2SD6fo0H+DCjkqkMQiTks=,tag:g2939FLDUGVL4nSKq35pOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
