kind: ENC[AES256_GCM,data:89tLaWHz,iv:UM91BeRnLfQY+eehHsEJwKBlhH+z+lFqK20XYdDPaoc=,tag:swyxPCxlU9xRBMyOPYCxlQ==,type:str]
ansible_user: ENC[AES256_GCM,data:1SkX+tJLYQfKtUmL/GES,iv:K6GLPkKVrq2XhiDIFY6creBjQUiIlb/80mwFsXXzn4U=,tag:wXk0iVYc14Ap3wgnzCPj7w==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:xlZwcRSaZczo5IJmJw==,iv:1cU1zkSfrLq9Iy1Q4wehzBcEUhz8mJAVldXuIWUfc88=,tag:tObu4TmTHED6NLDf4jxqIw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-28T23:17:28Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwE0we1KBRMwvAO9AFh/f/o9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4MAxAnrFM1eRivg/AgEQgDt0qBQ2FQ6VC0z/XIB78lqQiYpe6f6lb1A4Wo0tmDbU4Qc0BWG95pDS8X6No6CR0LYa0p0ZYEoE/zIIfg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UmM5MWtIZVk0YnJCc0VN
            R3lPdCtaMTBBQ214UnpvODV5L0hOdTRTUzN3CmE4TVVWUzN2K2RhYWZlWjkyU2FU
            T3I1cE9Pckg5Z2h0SFZrNFdDU1ZKSHMKLS0tIC92YWhCai9YRTU4UVRnUE5zVitt
            eURpQm1LOHFON0p3MG8yS1V1VmFiNGcKirAsBVNonzevKPeZtsqAXod5I2/6c8JX
            fYODQdpv1ul1rusnVqaHx/BwoyRWI0lWXr/o44F5iBZMD244nsfodg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T23:17:29Z"
    mac: ENC[AES256_GCM,data:i30U01MObZU5D47x0kkzRPIr6XjZcPUfLkIRzTEwS7wsVdTUnLvlGTkpHiZce+BG5Y6zZ/QAm/OtT41UaW6t9MAWI0FxAttINuYZzIYUqDN9kbiUDsR8p9U0OMNAuIP021gQ2KR0D+xHz0umTvwCDiC6AvFOZ35QBFUO5VyR9vU=,iv:Isj9qGtanSVAZ3dCjwmlXRO48Uev+C7RaPklotjzr6s=,tag:5nqGmhqVLF7Ox/Jql3HLEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
