---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-data
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${STORAGE_CLASS_DEFAULT}"
  resources:
    requests:
      storage: 10Gi
