pve_users:
    - name: ENC[AES256_GCM,data:g7sgXWWyAJxGrA==,iv:fl1Okz1YAVOL8j4rpFQn2mf4B7moiwtHOsbvrcb7+b0=,tag:yJM1cdrxiExTwLqeeoRNbg==,type:str]
      email: ENC[AES256_GCM,data:7Cdn7jRUmY4Bro3P7JWPCg==,iv:rbcXe3ss9LUXPU4Ja3is85gZKH6REf3c7nBEYKwM0p8=,tag:oWNE1yhzRjQde0NYTneX7w==,type:str]
      firstname: ENC[AES256_GCM,data:lxVzdUk=,iv:iSc0xRbuFFYYTmZKYQ+y0c2dfauT8LAppxpnUllFXBg=,tag:LTXVWHss8V0qHQ5q6Ql/BA==,type:str]
      lastname: ENC[AES256_GCM,data:vemWczMd,iv:t6xjM0keMMUtzW1n6Y4WWMN4eoaSAxA+ML3fGRieSjc=,tag:GfvZvZ34h5rKew/FZ4RCBA==,type:str]
      groups:
        - ENC[AES256_GCM,data:Dowd,iv:xOoq+gj765Z0xZnxG80adD75Rek50ta5CRtKxA9+oLY=,tag:Duif9eE+bwHL3IJjVAe6DQ==,type:str]
    - name: ENC[AES256_GCM,data:aVUB1ExcnZ5ZLA==,iv:KyY2CcnwmnDoqK6vEKs5QfKdszVmhLQKJb7nPve+yV0=,tag:FLs/spqWG6m9DhurZ90FYQ==,type:str]
      email: ENC[AES256_GCM,data:ln04FNptzxOyDhP8zIJGIQ==,iv:hQfYIQNPtZpY3SmeRbMseEmhrftCD9v/+VFsYiiDpG0=,tag:GBg3WXjZqf7aI613e4AFXg==,type:str]
      firstname: ENC[AES256_GCM,data:u6P9gMzY,iv:l0wErkS1HxBT2irX6dUmK5ZAxBlYyRHKXYQq317r/gM=,tag:Alw7L/iheJZ1tk3ptXKYlA==,type:str]
      lastname: ENC[AES256_GCM,data:ifsXVUca,iv:NnLPsgkHEY1EEcNeQUijFa+Ry1Hn5W46bd9vm+yp0kc=,tag:h/6Jw244ztk/0uPaKBn+Iw==,type:str]
      groups:
        - ENC[AES256_GCM,data:Dowd,iv:xOoq+gj765Z0xZnxG80adD75Rek50ta5CRtKxA9+oLY=,tag:Duif9eE+bwHL3IJjVAe6DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3emwjh430034a09ats7eyl9u30xzl7qam4e9h3s7t9zyncqpdsqy984t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN1FNMEp4ZncxcWE4MVdW
            RFFOeEZPM1lXMkd1ZCs1QXREWHphYUlaalNBCm9jSEt1bGx3eW50bVJNdzk0d1gx
            bXZJOStCUG5zOXZsaDN4OW5BNnFOTFkKLS0tIElzZjd3ZHYyOUhmY2M1N1RnZGto
            M0ZvaExlelVTRDFtUnNJSXZUMjlZSXcKbFQyP2CvFkmGxhh/iUU8Y94O0r3q1ZME
            SvcWPO/e7k18rRpNNBZYpwAGaFsXVmMW0oAn1YVAz1Z83cDcZjWwlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-26T16:29:12Z"
    mac: ENC[AES256_GCM,data:3GNyeVFT9sdJhPcP3hTLdGXPPIh8CfQIxpyIg3h++/uADmVjbio27bvj0Zh3q8TYZu0ojZN3v1XqqHGh+gpod/IVsrM7YCyUMd0Tj8NDvQzfjYSGxkhvc6mrfL13e2WrkyifoXm2hmcXEW1n5Q4CZjM7l8EIOFbZOwQZB7eMldM=,iv:fdY4sRpP/RX52zdknGVNOaDcz3yRwqGNU3KtQm5goGk=,tag:mHkoBtbqb1l3+epUf6aXBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
