pve_groups:
    - name: ENC[AES256_GCM,data:+8RA,iv:Ly/AXWWBUA0Kn+ZLpZR1hVKe/8ZsUQOofJEkqHTpigg=,tag:XlsG3eCs+dHhY35JymvJIw==,type:str]
      comment: ENC[AES256_GCM,data:GMM/z+PpG7PbtCx5/uRR,iv:KMZC0s/RHsnZH7fbSv/0pR+gBu4mfdDcnq8kNjn2Yhc=,tag:ZwJDvxz7PK5iAtgoqecXvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3emwjh430034a09ats7eyl9u30xzl7qam4e9h3s7t9zyncqpdsqy984t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQUMzTHlvRDdSNngvaXhX
            SGUydVlaYnh2MTZXSFRoaGxxVU5VTklvcVdnClFodTFwUkRCbVVHM1dxb0dORHJa
            TkR0RURYU0dsUTYzS0hGcVN3QzRqUlEKLS0tIE9MVW5mbkdQelZMcUJwL29JbGYy
            NUNWQ3dibE9PaW9VdjJNaFlxN1RMbEUKZBUzGsg4wxhTrf0hmwOOu6RQxPxwri5W
            /x+NIbOC0lcTfb3V/QWLv40W968xlr7baDazIgU9dT8lCM/ms23laQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-26T16:35:19Z"
    mac: ENC[AES256_GCM,data:fPdy1IXkWhXPUm3qLpUPA4R/miz/T0Hw2Dr/YVIuyG/jUCmEBQqYs6sX4CTdSMSKZ6uw3NGSlmgFDJ/R+aW9uVpgKxPGnNjPuBvKS6TVQVghqToHaaILiTjHa3XYjPGoe/b+JsNzuooWIep6y+DL+wCGfkhnLx1Z53F6OSZ7MNo=,iv:cvbktBCJNvoUD/Bu1JNBryCEiXYQ/JQ7Cil0gGM2a8Y=,tag:E0Oi8mkwIbb0qA7YJad/NQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
