---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - secrets.sops.yaml
  - helmrelease.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: plausible
  app.kubernetes.io/instance: plausible
configMapGenerator:
  - name: plausible-clickhouse-config
    files:
      - clickhouse/clickhouse-config.xml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
