apiVersion: v1
kind: Secret
metadata:
    name: plausible-secret
    namespace: selfhosted
type: Opaque
stringData:
    #ENC[AES256_GCM,data:WkyNEBbvBHvshDd51hVGCYyIoalryCdPgWz/jFCabcZn4+uQYAT4T7rbhjMu6xE38m12Vi7aEJ7d1TEL0YMXMRB0SpTc7CrySUs=,iv:jiGShNFk825OGMQpY8zuyJgqKIjsdpbvtPDxQLmaobI=,tag:UX4cqUYgkzOSWsZVG6gO8A==,type:comment]
    #ENC[AES256_GCM,data:PeHzTKTnxSjLOmNm/yJcHW7/keyiTEPdAIKqk/zkN3FyIxk/kfbsXTRF3ZSn2evbErKo/0CbHz5mJ1YUAPEipZ6eAn3CBVQ=,iv:ngugp7X4ntD+kenWXUoSGL94eYpzkMLLJsHR0HvTLDw=,tag:UjuJoNDQyN1Cxf8PwpqK5w==,type:comment]
    #ENC[AES256_GCM,data:BFA6WjkBeBYwTjGk0lURfcqcOK6a6e8KZNGFoILLCJIFkW7C0ZdQugVxREf7M5QomtlTV7r6t3HoLuro+a1ETESUjpswC9VS,iv:DeddtQlKkc874hK2WYst01VrZ88nlAuM3OVavSwjKEQ=,tag:DoxSl/kgk53Y95auisKvOg==,type:comment]
    #ENC[AES256_GCM,data:8yq6d8qa/1fX4juFI/+uYxN9+L44bsMfBqZ1pw7XTduKv9o3c727ul/c44Nn+wrwXpLSarBvIw4=,iv:9uuGSnh2Wu0OGB1HO3ydAodoFs0M7P6RFjuYEBdBMh8=,tag:EgzOGvR/7W8M4l+KN1JhJA==,type:comment]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:i/43obs0iTdUaUK/2qfaEkROh9SecikPUlx2s71t7UD4DlDFvoBrTIcOqz35jDiK+siYmP1ApLWJsu7ACvA7oA==,iv:pT60hvHYdpUWm4hn7B0ujeAq+2qkO0FiOJW8Yqx/rR8=,tag:jKOLNK/HcuPjajkrBiDoGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldVVEd3p6dzEzMTBZcEdn
            TldsMGV5YXZqazdlMm4zK29aV0N3WXFNWVNjCkxxb0FLWXU4bEpmdVA4TTNzL1dS
            QVRydmg2S3dHWEFBZGN2Rmk1TFNjN0UKLS0tIEoxbGxZODNzaGZsbXNYWHFLbDhB
            UUNwVTlhZFhmbWE4TnpHSERGTmtiSkUKjMh8ry7V+RuxM80sJwTlHV+zIhOAAPBl
            lrmEnTxWSpo5el69jv9cWx1EpZc8NEecYRqv5zQHcZy7mLdZpdaaVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2clJZS3RpREdrazd4TGth
            RmVIWTZVRHRoMk1zaVZPUCtydDhnb1JXQUZnCnJBeVdnMWhuRWZURmprcE1HWjBt
            UURacEt0VVZBUUx1VXUzZDRmazFrWVkKLS0tIDNMMDhoVTZncnhIYUVUV2ZBdDBa
            cTJsOG5oNFFVZzhvcmxQQUtqNzZ6emMKHHysEMnK2GVjGqUtGePTuePSV1LpQOhw
            hmNXTjT2O8UWEn1pAifgz1Dk55ofIdqmXXDQ3Mv2BFYfF8TWfAYu6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ2hqbk9qVWZDeGFHd0V0
            RjR4czgvMW1BMHlWTXBUcjdTMUdlV1hoSldnCm15dEo2UWxaWW0wRTNHWWZDaE5x
            YVlFZ0gyTW5OVDhPTkpGZ0R5SWRKcHMKLS0tIGJrMHo3M1VlQldiTS9tNitZejds
            cmxPdmxXRDB5YXBvNmFjL2ZYaGJjZWMKhvDFI20EHyZzpJwlT2GAJKGs9ho3i8oe
            wsXB9lV9MKmkRpaqRnTCvsNiWZy0NJBWbsfLvlr7ad1K1jxK2X01Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T00:14:39Z"
    mac: ENC[AES256_GCM,data:+0vSu6Aa/J3+hWHY3AQtHx3OOpOSj6x4jgO7uwC7i5ym5E5Z93GqHFw7tkSvf3wA423xEK5B9yiGDaPFghD7uXreJFjqahrQ/9w1xyPL4DVLQMkwxL5DXEyStn2vNDT1aqgKuGMSynHpos4xFGf91c897S4+qJov4qA8MpIT9+8=,iv:CwoJcMUxzOMiBVlbRp0ei4rvhJQ2OMTUGzyMelMHqtg=,tag:DS5L6b5OIpiuRUDkVs75pA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
