cloudflare_email: ENC[AES256_GCM,data:yJx0AslLvmHICw5xw7aukU+FX1sgoSrkDlCPqw==,iv:I6XcxLUYaL8PmW0Ochq1A4DDAmUWXxsndC4wKOfYEAk=,tag:6EYMGOEekzNFlIB7LmWFsw==,type:str]
cloudflare_api_key: ENC[AES256_GCM,data:oDmeAJOO2BMBcWFxJujNLxl6hS+G9q3eSZEz1xleUsuQje5dSQ==,iv:HLN9c11/ZYS6x3e2rFHJdPjTQ2RpB86qaP0mqhoinlE=,tag:kC6ZvotB72n+tjme/PUDCA==,type:str]
cf_account_id: ENC[AES256_GCM,data:gZSR/kPND0GBIOfn6FXtMwC44h0RUHw7T0pEhL4HgA4=,iv:Qm7I5K2Zzhs/1Yv0DQQ01LHIMWyup0J2ShNSazKyqf4=,tag:Y2X8m4uMrcmId9xT94lnLw==,type:str]
cf_domain_1: ENC[AES256_GCM,data:24dAoHX6wFY=,iv:YDg7VWHJYfaM6CjC7KwHz/w2b3ne4pA6nMCrLfDFjZk=,tag:OH8RY0xBRuri/kS0GXlg6g==,type:str]
cf_domain_1_aws_eip_unms: ENC[AES256_GCM,data:RlkIDSWaVsB9WvHJxbM=,iv:IZcabvTcm6la7tKZ/kL/wMUfbXbYcAYld5KskNCGgC0=,tag:Pq2Jrjl/+0t+jw17dSlGPg==,type:str]
cf_domain_2: ENC[AES256_GCM,data:ii96dYgUemcRZXSWFPd5Ogd+Tgc=,iv:AMkeZTXohCZAEVjQOYHcmYbTbMeFofoP9rSJT+6HiTk=,tag:/ezjG3pgJuop1TSimxXtWA==,type:str]
cf_domain_3: ENC[AES256_GCM,data:ABkyz6k6Mq6LkhQh,iv:fq/CUiIvMn2iYAox8AwpP9Ci76BS+616qBXPBnhnLKM=,tag:++WUdoYHrmxjkfoc2Isx2Q==,type:str]
cf_domain_3_cloudfront: ENC[AES256_GCM,data:xxcqtVkgVgpi22znUe99WnXR3AfLZzqJcoR7xJc=,iv:fWipYek66CVggp68g6XmSkR0s1HteqRbzn8U5yV0o7o=,tag:dRUJUks1habKMQXcEq5o+w==,type:str]
cf_domain_4: ENC[AES256_GCM,data:qYn8dp4Tw+c=,iv:W/TLB//3hbvTjVnwtHMQaXQWiwB80nUWak62ZxYoG2w=,tag:tm8tJHFbJwv0bf7k7D7lMQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:33:07Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEkWLyFXJppBGBKxIzJLmjMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlePckwsvcxMhpcpVAgEQgDs8MQyeXgO9cARmIHjdcWAdH+oVlshe+qH7ntk8HCy7lItodWkdYRZFSw6z557vEk8jNq5EA4vFzZLECA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcitMeUhhNloveWVPd2Rh
            NnM1SytsbkVmS1FpQWlhVWhvT3VLMmZGMUhvCkdVWC9oYkJSYWRVVlp4STRSaXZ6
            WTUwMEdpdnZySW1CS3NsR2I1V0ZIU2sKLS0tIGlWVmxnOGNIaGtuSnpaL09qVzdN
            ckFVRHI3UXRFSlhBTVZFN3RQbUNHQTAKUyoXSjoSILAzWYauMO0C6L9lgrsbISTf
            lkVXs09F256E/Ivj9fNTBAYsd8UIcC7Ud8y/JvgTC2j86kn5l4Wh0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:33:09Z"
    mac: ENC[AES256_GCM,data:agy48FKEHiGBGe2sKSvY6/Yg2rCtmQelOXLJqVa5tu1ItN2UE1Dp+/mLvVRbYsFt8cHOzsbWUSi6M4C9A9T9dunCfycZESKdfPOpvzbWT5L1g9ZJN9eYLuvLaTGCk0AEYZDEsMxUnPvRR0invuYIdlEGNtYk09hU2gEB2MIZcIY=,iv:eyruJ9S+jGz5Jpv2QQljeRk1s9B2wN7TBK6jBM4uYBs=,tag:+AbNJBSx2/9UaEn6WK+/8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
