apiVersion: v1
kind: Secret
metadata:
    name: plausible-exporter-secret
    namespace: monitoring
type: Opaque
stringData:
    PLAUSIBLE_TOKEN: ENC[AES256_GCM,data:jbCGyizINlENVs9pMayGP44cMp6LY1jn+e+5x1br3bMiFQJjs8sKgHTJXjISSVsKMVFAohc+juT0A+ixoaH/LA==,iv:cQM7yZDuIAve5TKLGuZSPOi5QTCpTGiJnCBjGgdPMQw=,tag:tsDp5Fm9jlAGxOCnyyrfdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcXpZOXlyV0JVb2ZpYTNO
            U3JjRGRsRHp1NU8vN25lWjZxWEt3TDRmNDBNCmE4WTQ4S0t4S2RyVHdRV0l6MElm
            RWFFcGJ6VEgxR1pYQ0pKZTl4NVdsMXMKLS0tIEk4WGpXTHozQi9KUnVjdDFRcm1C
            Y1F4bUtHR0UvcXFmZlYrQU5lUWYrSjQKwzIukYdZb+zjvyuTjT8WITZ8zakG1+mE
            FPnafeWTM176pjfpF8ZrRhFJr7vHqTjsrzd8n70haoaSEbPQVmNIjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT0U4RUxOZGVuWFFGNTY4
            dUdidW5lMjFLTU44V2dFbnNGQ3RLQzI5Q1VjClhPdUZ2U2JqOS9saE9JejhiM0hk
            eUh5c01VK0VIVzRNejJjVXA1QkwyRncKLS0tIFBPOUJVTXcrWkIrNlhrTUN1ZXpY
            aE1XMDhORmIyakg3bmM5eVJ5NTNVRUUKeBa+yMg3WIk/vUGOt3KMUhasnBvyf1nF
            BgLjozXZGBTV9+qX7das32RMogzgxN3lBszegigNx//+aDrOFgpT6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcVVobVA1ZlppRmJJaTFG
            VllRYkgxTzVjYmhLanlMUXFaY2FONDNueWp3CkxjdDBUVDJsQ0dzazE3Z0tiTlhF
            WUo3Rm9QSUR4UkJhNHh3eXVrZ3NmeWMKLS0tIGZpejBxdzhZK3RjMGFKUzU3cEpk
            dmlVZUVvZjloRENQdXByR0FVdGQyb1EKZooG2DL9rG6yffKuCbEs6BfHKFj3gax4
            dBQnPEDSXHFuhoq7VJc6E2daqkkdw/NQkdwPi6dzhLK9gGdGV30JTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:00:49Z"
    mac: ENC[AES256_GCM,data:6e3x73ILKFFJf0e3JUzpQ5lUiabUL/Nh5y57HtoVRkCozAyZqSrZCEthLZCPaoRTb7bkK5RnC2e2QcfnHlOoOMw0oc4YR+ADlw6jFRvzMRhL0fQri/SYDl0BUj0ONAlfOCGyUtFMNDR5I0fLH4D77ugxmmh2KBkNX0AV/5j88fM=,iv:Ud87+JxYC5WOe7I5H+NaiyfeEsMwe7y+cqf/I4HDrKs=,tag:RS/4EelUyE7RLFSYR/F/tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
