apiVersion: v1
kind: Secret
metadata:
    name: plausible-exporter-secret
    namespace: monitoring
type: Opaque
stringData:
    PLAUSIBLE_TOKEN: ENC[AES256_GCM,data:jbCGyizINlENVs9pMayGP44cMp6LY1jn+e+5x1br3bMiFQJjs8sKgHTJXjISSVsKMVFAohc+juT0A+ixoaH/LA==,iv:cQM7yZDuIAve5TKLGuZSPOi5QTCpTGiJnCBjGgdPMQw=,tag:tsDp5Fm9jlAGxOCnyyrfdA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-06-02T02:03:39Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHsgjRUe6niRdLgulYYs0WaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMolrfPCz4JIWy6XvDAgEQgDtjyvhQuOfpxka1453f4huPczopMAAmkvw7TKLpMr8Oit/QrF1oUg4/W5ygfJKGYhT49n/GCHz4/yyCZg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSS9TVXNsUUowZVRFUDZn
            SSswTVBHR21HMit0S1ZVTWVIQW8xdlZxMlZnCnp0QTRQQ3A2Z2FFMmExY1Z2Ym8z
            UzJSR2t0YitaUkRlUWxoRFpHVHVQNDgKLS0tIEIyb0N5UUhQc2NpVmlzQkljbEY5
            MjVMdXFiYThFdDJXSU9XVnpXeldWVXMKQGKSXgYocOWoS5HLzSD0ObEIsGkVJ6VL
            e7mt+Wc4P/h6wB8PEMef8cXICPBvcl0ec5PfnCyxQlW6dSU2xwkBqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMDNHLy94K0hsS3hkV3Vn
            bHh3WTRFRVRnYWpGL3Z1aUtuNVNyTGdZSlMwCjcyT2NraXJCVkk1cTdPcTdPbnVi
            eVMzQmNjMkNkMnRvcVhPbEZFUkZlOUUKLS0tIGpac05jc2hKWDVNaEN2WFJrYUNK
            VDk4clBxYXVQMnJUWXZBUlgxWmsyeWMKadiV3P4YoexHjOVsV06lA1UAyysIz9R6
            9CrIvflKecLpRXWT83YxSvvmnmjBugNF/3uQp6jFtAeLxDY3lCxp1A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU0oyalRDODNMZHpuRU8w
            RjJGUncwdzduT1Y3TXE3c2FqMVNDS0h4NzFrCjhMOUtESGZXRmROVXB3alFDbHJj
            aFpuRXQ4MVNzS0pka0dwTzYrWS9QZDAKLS0tIGJSZmtVazRwbklFMjNpQ2N2ZmJB
            ak9JYnVQc2dWWkFETmp4WkMrSXJ2L28KZJ8vCZPFuGJ4ZRsnN3NgybS78TF+3JOL
            Xr3fyGRYYi9tuhJtzo5MH6lbqBzbAikgEjCzb8/8s/mNhdJ/8vaOMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T02:00:49Z"
    mac: ENC[AES256_GCM,data:6e3x73ILKFFJf0e3JUzpQ5lUiabUL/Nh5y57HtoVRkCozAyZqSrZCEthLZCPaoRTb7bkK5RnC2e2QcfnHlOoOMw0oc4YR+ADlw6jFRvzMRhL0fQri/SYDl0BUj0ONAlfOCGyUtFMNDR5I0fLH4D77ugxmmh2KBkNX0AV/5j88fM=,iv:Ud87+JxYC5WOe7I5H+NaiyfeEsMwe7y+cqf/I4HDrKs=,tag:RS/4EelUyE7RLFSYR/F/tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
