apiVersion: v1
kind: Secret
metadata:
    name: plausible-exporter-secret
    namespace: monitoring
type: Opaque
stringData:
    PLAUSIBLE_TOKEN: ENC[AES256_GCM,data:Aw3qg+KqXxmGP2O8ANnoXh3oQH0tomGgyj493OAJIgAPCxnCGHhzOvwmSv9PC2miy/co1d2KcbqhxdwGMfhfeg==,iv:NKhSdyy0qsl/yMQdpp4xbhJEye0eJ3k+boqPH2dJaJo=,tag:oD7+bTiQCrlJefSRQUqkpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNzZHbzNsbHE1MXpGTnlB
            dmdEYm0wN3B5Qi8rK1RHMFV2Ti84bHN0V1h3ClZVUml5MndudktYaEc0aWhkSlc1
            dkwvcTdqYkhBaGo1cnBKTG9VQUdJMDAKLS0tIFk4WEl5L0I4V3J5cWMvc3VRbnlQ
            Z1dzaW5Uc01Nd3cxa29XT3lLZlI2ck0KQ55nMClzpDORwt1PJEk+FVxJVou3y/k9
            AESxztJXfDxc/BUAAC5qo3zx29D/MWFUunuQhWPL5TABrRGA2oBIRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreG00Qld1T3pXVlhnVDVs
            azNPTG5lMFNqLytLazdSQVdnbElaZ0FYZEFzCkkxYk5keUxiTDF3dFVSTE5FYkV0
            VEpJNi9jS1dRQkpCUTBBVDZjMjNFb1EKLS0tIHgxYlVwT2RpRCt2V1RFNkFmMUMz
            TjlxdjNmZ2p4STl6MU1YUzFqQXRVV2MK2VU26p14AJn6GxxtNbB6dAI5gFV+cftS
            gGrS0gC5rjhETO2rKTcvJ6/ZcehagAnKOuHuiHhpaJXYOUyY809xdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T01:57:37Z"
    mac: ENC[AES256_GCM,data:Oigtgo4juPZZlCauaNqRo3DlKAcs/PfyMuDk2xQhxp/6zhQO6PfiPdjU3WECVI72NURKjS9+XG+RpWorUNEAQX/HEoWJlcWx+7txna2dhNffYDV0sEAxcJu/zJPFeHEb1gF+/21OUFIr7NFMUoAnE3CM4Xspz4gl/kFnRkNy+9M=,iv:GwZ2XlNsCQqWKOBhwt4znWJi8Duy6bKuzrnt1XZS9zI=,tag:H6VFptdY94uBgw+nL48axg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
