---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plausible-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plausible-exporter
  endpoints:
    - port: http
      interval: 60s
      path: /metrics
