kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secrets
    namespace: home-automation
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:CKHhxg3TK3wB10Ljo0fsVkq0TJz5KbOaz/Du6wyNvhii/jSWbRWqLDSIDJfp+D5cFrIIqbW3MezF0Ww3f1c6W4ZDHmKHWAs1jeKJ8mzlXFS5WDwrfnJPn80DQguWuEPrYEExsg==,iv:1N11PHYf/OEjbKUXQF3rVStweGuamb0r48Z4tshVHOk=,tag:oaWBv0govlSAjsK22ZkKCw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:12Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHKUlpCnl0w36DWHM9Iuz2LAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6NquzRsMjq5y0NkfAgEQgDu0Jz9qryhN2R1xHs0X465AcqqdHLZONU27C6SlmxHC2hoBmm+ksOUvIg2y/mVE2qzB1L5DZhjPIUMWsg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TWE4eStwZXNTNjkvdXdm
            ekozNDhIc2IrenMyNkFHZk9lRC9Edkh3OHdRCktxd2JHK2dyYTZjdkdRZEJHbFRE
            VmRkUk8ydXpJdzgxWWxDR0NreFYzNVUKLS0tIFJkSlNoVk9zZ1hMU0lsOThvcGxK
            RVovOVA0K2lMSU5ibXhJUktqbjhIc0kKWumb80USLylAKfrTaAXelyl4KR5WmH9w
            i69a1J7k65gpspGE0/xjYbvoCWEU4y0zLfitQvhvwjQRdHz/5k8Jiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:13Z"
    mac: ENC[AES256_GCM,data:PoArpnvsNyqzMOZ4Rd70RzBZmRW/o7okc9qHFfF9IVFZ6Nksjm4NNf46yC1rlUR7FH8AHdCyh+BVOnSGsM7LahXJJPkdblNGKJZpnlvhb8bZ2tn6piRrmFAsvqEWwBzbu2ew9ZhwzjMNzo92lqKU4yyYHQP4UNZcSFMAabjxZFI=,iv:n25qDi5NXFlDBE669ZVhn38LZMl/QNmug3jXqzsmIhA=,tag:Bp2u4ATq+uqSidbRYbKoXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
