kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secrets
    namespace: home-automation
string:
    mosquitto_pwd: |
        mosquitto_username:mosquitto_password
        mosquitto_zigbee2mqtt_username:mosquitto_zigbee2mqtt_password
    dataFrom:
        - extract:
            key: mosquitto
          rewrite:
            - regexp:
                source: (.*)
                target: mosquitto_$1
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-18T18:41:34Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGc0/Oz+k1CqEwQxx3XbsrJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf/afdMvAN4NW0A0cAgEQgDuDD3vyGy68ZTxovML3U/9nIct3Cn4U3ZaJJlASiSExvtTjs7oySC0+xxsJPrRu2s9b3GYUo81DcEza7A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRnJ6c1ZQbWxwYXNGNGxY
            Y1c5cEZuNjBiYUhlZURmYWZBT2MySCtOaGlVCm1BeGEySWY1R2tDUjI0eVJ2a1hL
            OXFSOFZzTWp0NU45ZSs1V0VpR0tDemMKLS0tIDJjVXBIUUlOQlhpYVlwd1RMcUI4
            ODNiWUV3SzRrZkxWcW5HVjUwSWo1aEUKoFsy37GEokX6ERiZ7ImHQUYpz8PGfXfp
            QBpsDlWkt3aC+lu76eh7sSN3fDsVRX5187XzeuvCvtSV7MHL417LgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T20:27:30Z"
    mac: ENC[AES256_GCM,data:ywUUbaJNMivvre6zvSzQCT8LejnyzngHayiYAgxWaSk6Kg8EPYLTQ4ySioOmA3ncKyEu13twQobhLll/3iBe20WsinTLnlqNvlDyYsAeZU8nnMPLBeaW8F115V4DMgeFQ/O4Z9b/pr2WYjEUQ4A00xFg2fo5jAIocnt4shl0eNU=,iv:TNoNkVa21J8f4hSJ4Cojn/Vgd9d4jFUeB7YnAEyu3ew=,tag:Nh6cPt+J0hrstgjiQt0GcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
