kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-secrets
    namespace: home-automation
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:yRVJBGrd1MKeXq24nltJa2tT0BE0ANq5eo/On9GSUOwpSwJOirQqTfbPbR8mDMd5aF7/KxIEKm2fHl+yLV9XU6CJANwXl3+6g8C0mEhLhbgQdbe6WjZ7kZXF+Vc1wKf4itbDKg==,iv:EegJLepmc/PM5FvZEIC/LVeD6iY0ykdpalE+zgecnEY=,tag:QsdhX02oeIpzCzgdqPhQ3g==,type:str]
    dataFrom:
        - extract:
            key: ENC[AES256_GCM,data:7e183Yn4ft6B,iv:zq8W37kXhbWrruI04qc8fz0siz7gY6kzza0UhIUOvwo=,tag:4JImgC3F89e1TVtxlHNEOQ==,type:str]
          rewrite:
            - regexp:
                source: ENC[AES256_GCM,data:Jomn2g==,iv:kCgh5l3HhWFb1dzYKmYXm3ZcKwY5775DpIzL0PsP8bs=,tag:D/3eXKooC7HtWkEoj6rjqQ==,type:str]
                target: ENC[AES256_GCM,data:e72Vkt/XVTFBXJsD,iv:eOmQOT4/mPfRkNiK8cxHxwi8fJ8K2M0TxQ8EKeLQ3mM=,tag:AaEV21jZ3+RnOX6kpmLCpA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-18T18:41:34Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGc0/Oz+k1CqEwQxx3XbsrJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf/afdMvAN4NW0A0cAgEQgDuDD3vyGy68ZTxovML3U/9nIct3Cn4U3ZaJJlASiSExvtTjs7oySC0+xxsJPrRu2s9b3GYUo81DcEza7A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRnJ6c1ZQbWxwYXNGNGxY
            Y1c5cEZuNjBiYUhlZURmYWZBT2MySCtOaGlVCm1BeGEySWY1R2tDUjI0eVJ2a1hL
            OXFSOFZzTWp0NU45ZSs1V0VpR0tDemMKLS0tIDJjVXBIUUlOQlhpYVlwd1RMcUI4
            ODNiWUV3SzRrZkxWcW5HVjUwSWo1aEUKoFsy37GEokX6ERiZ7ImHQUYpz8PGfXfp
            QBpsDlWkt3aC+lu76eh7sSN3fDsVRX5187XzeuvCvtSV7MHL417LgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-18T18:41:35Z"
    mac: ENC[AES256_GCM,data:L0O6q/vWBUsreNSJzJOjT0XyzWOjhqGzjPYiIqOw8ejDLxXSrIMNjxb54Jv7OVB4C/i8y+HvOgUMc4sCx7mq8KEtspUYwoS8gnDECRPdgjM73JHdLCxcgOjCfft9Kvg2SnByy3soIQFg2ZsN+d6sIgw3LQl27wEGmn5mU2ipP+U=,iv:kNc7r/2hq3PMnqqcUHEyftOteJnl5nQfJSN4sw1k7IE=,tag:+nUbTT5Xo0ZgzsYzdUDpsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
