apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:2eZZ58Q=,iv:FioqN5s7uLRR98l2zw4M3MSLEccS1hhPeYBhhI2mPQ0=,tag:emiVGHGTd3IDh3YJSf8z4A==,type:str]
    admin-password: ENC[AES256_GCM,data:bwD0dJie5vFWWw22HR0wfWeozhjGPVMK,iv:5yvXVQGx8/uCVdtTnogEusa/IAt/lXL/NSkgThx8Yyo=,tag:Usmhe2B71wuS/kvie9TdzA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:20Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFL8R12e4/cYuSI54mIFcIUAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHrqh3jnq4kKvLhhnAgEQgDvttEyR+AWT9a50/oiqmlZQJVz1eJlJgPuWDwDCxwlltR0cxzty32as8/K7Pxfh1mmcj2h33Y+xvVJoxQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN3Z3ZCtzNFlkeXFONHpW
            MW9waUlvOGdoMFNDaFYzQ0ZWUVJ2YzRycWdBClBMQlR1eVI2dVgzT3hUTzV4eEs5
            cFhhSmpPdzV1NnM0eDRTZkdlTkdweVUKLS0tIHptT0RxSkppbGRhYW5MWGpFM0wy
            bkcwWmhqSVIvZytyK3QzeTcvZ1pXaXMKkZ/p+nQaV76ZFZ82RQISUlJ408P1E7ay
            qJhkqNrVwnKie1VwuX5GpYRcmVyV7tSuGF1ZCVTVyq4s6VoBPOdNYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:22Z"
    mac: ENC[AES256_GCM,data:otdluls+WWQUqkkq17+UfQFm3P3FZWTRJ1/bmnoKwreNdUg8f924rjmqu1cTySR6a2eNZL40xJ77frIh2AEjBiGZIf6UgWGJ7Cu+KHAUluAsMOJJhcGUeU464Nk7KPXzJGqXRr8eumlDiP+YIXYmXzCKpsypfEzLvtnLsg52Iug=,iv:lNlS/UKFaem0+ocZydpBgr+pJVEj8s7ga4CW4ANZ6PI=,tag:nuGk8Ad24d5uASE7UnlItQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
