apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:jz4HvMo=,iv:frkNVoGAvwGm692wOoeFHYkNmTEo82hcgTVViEXLe84=,tag:HC4GybfIf8bF+vt4E2khvA==,type:str]
    admin-password: ENC[AES256_GCM,data:I/tQxu3D9/SqRiggAy8197hLuqx0VYu5,iv:BEUruHXz0CTvr8CRnUE+PunfC/VvLRpfneHmFaoP7j8=,tag:29ivumUZe4O9CmcNUisObA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:20Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQF98FUij+BCkbNnSS2TrXt/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMhHZIwlhz2lhVgN3hAgEQgDu4Q9niK2kPqmW5QziKTYLcOtUMEIUK+KmoGPlj9WS86p6Nec4tv6aHG5Vm+jhQLgWTJfDDtbC8LyOY/g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDZnaGkxemNmNGppSVpB
            V0VhTFFsRUVoeTdMQWtiM3VTSTMrdnZ2ZDNVCnZ3QXJjekxTemo5cG9qdmwvMzFq
            ZW50SjlYQW15YVI3THJ5MEZWZVFhK2cKLS0tIFU5aTlWelVZQkpzOTN4TDR1UUlR
            YVJWN3JYRVN5WlJzd0Ewb1dmamdRdkEKtszltp66LxzBGHZVzoHScGNGugVq6UXX
            cDP77vNPBTdA/sFezg0jxJckE8h7g1UQysyolLEd7l2hbY1nkHy7qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa3lCSjRpWUt4Vzd3Rjk3
            ci9wcXNiUFBMWm8rekphWktzS3JGTGhQSGhzCmYza0FTVDdHNkRLbW9RbG5qL2Z4
            bitSZ01VaWJSSmFaTzdIbDVzZTgzUW8KLS0tIElWeWt5MkVSTUltbEJ2LytOV3li
            UnpaRkhROGhQTUtZeGVGNm1yV0puNEkKWcasd9ckYpoeFgfrYM08N0dW3CiOnzsw
            uiGCcQQuLCfnK2B5ZwFPtxle67ErKjuFla3GRpz/SZHygpTalbo05A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0pqR1lkL2RUNnZXYzh3
            Q015Ry9na3lMY1lFekdCS1g1MnBEUWNTdERJCkh6UzcrejdPWVVHem5IcjcyVTNq
            OHd0OGJTdFlNWXQyQjgwcnpXdEVTa2MKLS0tIFhvMEduVlNpT3NvMVBVem43bGhR
            Q2luMkFTRUdqdVkzSjZzaGVUM0RDdUkK3B+RoXUIsq03wsz0p4ibCP0IFABwh7Nm
            4j8Kd584uqun1cY/lsgFkUjN03x2zogoE3TJqDc9ZDK9K/CYehCVHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:28Z"
    mac: ENC[AES256_GCM,data:wRqSKR8T3SFzNP6fr8UM2buQqoU6rXs+wMATSVfnx/O70yBV08xeJ+Fky/L7tX/ogQEiRCry++PfusSyZh/F2asbOjg6uf81k+IQiYwCMkBxwcBfaz8qbPubEbCMW1sGniycrNU/RioiPUO9ngosEDpH3IPcMPjuVKe3BNgmpBk=,iv:mvFM/c55Z779ekxPcdOzEnARkEi+hRQCMR8o7iKzQlk=,tag:MKi0RrUpX+vWztjuIMfOEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
