apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:QdWoxNk=,iv:4wiinLFDBRop6rrT0A279f6xreBOjPOenmLsGdGM2YM=,tag:VRj3TGNSFMGNRl2otJvmDA==,type:str]
    admin-password: ENC[AES256_GCM,data:ro8e6M9Ej5Sk3jheGe+dmLdUJjB6iPC9,iv:Fr1yikYqU57P0W4EvXLPh4Gr7ZmcDtPFZd2BtuKn2yY=,tag:mSdHMZykDJJKlDFm6qG6Cg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-30T15:14:38Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGbiVLjuwiRjp047i3ys9vGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/fYKoKLiMjMArWH5AgEQgDv9yT8QZn7zVxL8L+QdF27JO7i90QF3QWIafeKN7rvhqXYb/vKQv9NGovYd6PiNM2Li6ePUx0OC9y93zA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGRKVGZBVmlzRW50VUlZ
            aTVxWUhGR2FnQXZvVTNzRituMkJJdEorU0E0CkY2MWFkSjNPRjRNTmhnNnNXQnQr
            ZHF0OWVxdmZlbm91OWZCNkdyUFozVE0KLS0tIEswSW9OV0VLd3NKem9ISnVHOEtT
            a3d3VUloMWlNM1RERCtZTHY0R1FTMncKvW/YVR7g4C8I2Ippk+MQGt5ORGlfoP8L
            +B5H9v7nhRrsySeqBKyY3i3rw2b0QiF5WGylo21HhFRW7d7NgRp35Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T15:14:39Z"
    mac: ENC[AES256_GCM,data:BYmcV3S1Hskk1a0b6ylSCFu0lr9wwBJFfFQL0ijS6PTz4olmp89mOFWxk0VpLaGnoAkwiM1UgUpyb3iRhzDTNMQUCwSsyoyJKOE3HCvOQa1W/elA6nc7B5o1Ths6oY/6bFuc45X7BhGIkCNRxt4IWeUvIU99FxwchCtX0Zb7q4A=,iv:dc6q/lfNA9PytNPR34IwEEsGvQz+anWrcVTRXRwOKaY=,tag:pLkWWB1ailRnMP4KFH/BmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
