apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:M+CyCbo=,iv:jv01o4X+x96tGnctluwFahT92TO7ES+mmb16j8HpJ6Y=,tag:NoyNBMcY7LsggPYYlDk+hQ==,type:str]
    admin-password: ENC[AES256_GCM,data:bfEI0JBpyuW87BRkTHwalCOsbAePIGap,iv:3QkRfbDrhRK94dO9A64OqKrQwAyKiwq1BoLThVtLhhc=,tag:HL5V4NQHFCDQgrpAodhkrw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:04Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgG4qgNgKE9w3P9eqosnaESiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwqPT6OAtp6jscUWOAgEQgDter8pAjrT30ezRXzjuWO9Yrpp5kj/iDydI5A1b4agYsWJoZCu42QkqFWZCG+Ynkghtl00Ms5b6R6VKuQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT0lSVGwrN3Jhc2xJZjYz
            eUs4dGgxcTJnbFdnckxlWE5YK0tYSFVEM21RCmxnMlp4aEt1Ty9ETjBadnBaZUhB
            OHkycktTaWNDaDlReE53aEJpZnVuS28KLS0tIHc2R3NVM1RONHg3cXF3TEluMm9I
            WTZLM3dndUEySDlGSWJmdG1DaVpPc0kKCtJkQ2qkwbBwX9OVikHKJdU2XoMw6f/U
            QNRw0zZfDUnhaqrguTS1/lOeRxiENKLxaybBnwJZWHgd2T5pvhswIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:06Z"
    mac: ENC[AES256_GCM,data:hQ4mJf2MO8dQJo73WJqkCX1ZfEovpHd8s6XCsvMxXapHpxCnU4aBLLEG+YfNEX5ey9TnWG6E2byWJIi64UEuz4LDkBrrD0UL/DAPJLo3HGRFC6v4YClGIjrNMseQh0v/pX4OC02v+I0AhFST4lCQxjkHo7CNaxLDPHp6S6a3e9w=,iv:hWoL3qyMlWfiTzxLD3hzpvpuF3BJsMLVbDVEn2Oafnk=,tag:VXZp1Ukvq7zlDyna2dNgiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
