apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:6uHsZ+Q=,iv:W5rARuCWJ0FdYor020DFX3DAHzeBQfr0O4uTcydAzrQ=,tag:Z5v+7a7UolrP1xRyNUvImA==,type:str]
    admin-password: ENC[AES256_GCM,data:V6NilwAn2STI3PFmKAr9ttf0npV9r6xM,iv:QCEQfVZwo7n/va9IbZBo977m/YxBMw1vBsbv8xgZI1I=,tag:KLQBykIfYgA+K6yTeBhe5g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:45Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwFTBGCKhH0CaxMQrZ1sWp5cAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5XQchW1ui3xgGFKUAgEQgDsegKdeR/IHuPfprxQAmyyQus5/rrXbVgKFAJdksQdtXBBx6r4k/K9rN0ki8L1chgzhSeNMiBVYha5dtg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvenRNaC9zU1FHMEZtbSs1
            bkpnTHowVTJ6TDB6cGxlaWp5NWZVWnY4NFNBCmVPOEJjaFNxVlJhck8xQlZyb2tm
            Ri9WVGtJbU12RlNvaVhDeXBvSk9uL00KLS0tIFArSFk0WDgzMUVvbTQ5ek5uWm9z
            Q2J3bUhZZmFCNmRlM2R0TnhzLzVLaGMKcCw14o4bt5rYA76M4zDX4xbnxB9tXP5J
            BMmB1gKLrNZI3TleBr7uLCH64gtFfs6N2QiTaxs96xz27ySwaM+8Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:47Z"
    mac: ENC[AES256_GCM,data:CHyox3QbLX2jJt81nNj84opJbC787zwIuOVZhv3baYfXonw/YtplwqlT41q9Gn0RWbhjAzCukbHUQkwd5/K6L4nP/GkY47UuYVJxESSmOo8yPwS2aXyadtsYP0Vbm3Pj7LJPBSXpl16BNavkUMZoP7gUt/zlovMIPM3uH1CbcIU=,iv:iOHGwwvx9UDoFFj0DNd7GqXIGDzsGqCvyqjO64JuQEU=,tag:3KgC9IFJhe1OwPkPz8CRDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
