apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:jz4HvMo=,iv:frkNVoGAvwGm692wOoeFHYkNmTEo82hcgTVViEXLe84=,tag:HC4GybfIf8bF+vt4E2khvA==,type:str]
    admin-password: ENC[AES256_GCM,data:I/tQxu3D9/SqRiggAy8197hLuqx0VYu5,iv:BEUruHXz0CTvr8CRnUE+PunfC/VvLRpfneHmFaoP7j8=,tag:29ivumUZe4O9CmcNUisObA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:27Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEhnKOw0yTyGZWpnvi++f9sAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+dd2QgJDjeoiVT84AgEQgDtGK+u7buO2w8sPvn9EEDdqrkTOBKDYqrkFR3Npqvtz3NruZ+vQvLS7jGRXxFRVn/SvYWjaY4WFk3DhQw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYm9yU3lkZURScnc4aVpt
            ekNZaSthOWZMcEZWVVRFQkZqcUJ1anFyczJzCmxJRWc5SmdDeDJrY3dpV3dwd2Ew
            bi80Uk1nMTNnRlNSSE9kbGNTTUJzMTAKLS0tICtFTGV5SlJVcTdld2lCeTRpVkMr
            RnhscDhBcUFpS0ZWMGhNYnRVdXZCZmsK+oo1tkKobXo7Dj7exMEYa6jezuYcWQ/D
            gJp8j5rVcbWmbGaitnmJrBFJDA/onfAiIXLtRClgm5DAbShH2bL4lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:28Z"
    mac: ENC[AES256_GCM,data:wRqSKR8T3SFzNP6fr8UM2buQqoU6rXs+wMATSVfnx/O70yBV08xeJ+Fky/L7tX/ogQEiRCry++PfusSyZh/F2asbOjg6uf81k+IQiYwCMkBxwcBfaz8qbPubEbCMW1sGniycrNU/RioiPUO9ngosEDpH3IPcMPjuVKe3BNgmpBk=,iv:mvFM/c55Z779ekxPcdOzEnARkEi+hRQCMR8o7iKzQlk=,tag:MKi0RrUpX+vWztjuIMfOEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
