apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:jz4HvMo=,iv:frkNVoGAvwGm692wOoeFHYkNmTEo82hcgTVViEXLe84=,tag:HC4GybfIf8bF+vt4E2khvA==,type:str]
    admin-password: ENC[AES256_GCM,data:I/tQxu3D9/SqRiggAy8197hLuqx0VYu5,iv:BEUruHXz0CTvr8CRnUE+PunfC/VvLRpfneHmFaoP7j8=,tag:29ivumUZe4O9CmcNUisObA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:51Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGHhGktmcDQlnAML/p42VSmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHW0wioTCCcgHyKvEAgEQgDuuRx55s2LHYfOYiy4s8ZGHET/xaAH5AuRmHvjB6SMDfWreovZp6w04hy0sCMi0guOmdUxmGMZpIm88wA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VG1zRStvU3JWOCtEQ3Nv
            bWRWRDgrVjJWVUh1SEdNNEZjZzNHWU1QeFhRCkFmcWxUaGpZWUQvbXl6TkZOUzd5
            dHdHclFqZEdaQ0tnMVVtSWlRQ1lJTzgKLS0tIGUrdW5pTDQ1UmRmejBIK3B4a0FG
            elltL2F0WHNKMkhrYWhNNkFuV09USWcK1d9Ct3Oe0NugWqcghpr4EpTfjkS+74ve
            Fh3KOUDSrMK0ryom8ESk86jLCdVNZm1vcaFQ4ihYdEuCw8UhPSkGgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWnVuVzFOdnlaV0V6OFNr
            OWowNTV6WFVTZEtTRjNWWTBzdnFLTlAyTlZVCkUrRW1MamRxYzI1bitUaU1LbnBU
            blB0K1VNcGdDdlNyeDdmRVlERWp5ZW8KLS0tIFFjb2duVTRvdCtCdWRSamlmNVFD
            MzNTRGZ0UUJyMUc3WU1hSy9wZFduRTQKCLa76Ygrd7lPG6z1AFFpOBqdYt9fD7B4
            2HyYetT4PSiAS+jNN26POnLyisLnh4IuS1BWfjGV2WFUsVOibuGN2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:28Z"
    mac: ENC[AES256_GCM,data:wRqSKR8T3SFzNP6fr8UM2buQqoU6rXs+wMATSVfnx/O70yBV08xeJ+Fky/L7tX/ogQEiRCry++PfusSyZh/F2asbOjg6uf81k+IQiYwCMkBxwcBfaz8qbPubEbCMW1sGniycrNU/RioiPUO9ngosEDpH3IPcMPjuVKe3BNgmpBk=,iv:mvFM/c55Z779ekxPcdOzEnARkEi+hRQCMR8o7iKzQlk=,tag:MKi0RrUpX+vWztjuIMfOEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
