---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unpoller-secret
    creationPolicy: Owner
  data:
    - secretKey: unifipoller_password
      remoteRef:
        key: Unifi Controller
        property: unifipoller
