kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: unpoller-secrets
    namespace: monitoring
stringData:
    unifipoller_password: ENC[AES256_GCM,data:PqDsv71dRt94neP4U3GtYEujtZ4=,iv:qKRiKSvxUhk7+N83gDC5c8eX0Wmafzz9vj+HsnxEIx8=,tag:q0a6VVXksfGGym8BpGcbrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHmRJvSq7j5NSs9S+oUjg8PAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBwffTsDr/pYL7l9OAgEQgDukC567JF/1nAi1vDGXIXeb7ZICLQ7zbhuQcblF2zJolkUlXzRNLMa41u0NPRNHKH4lPJ24udzQ4CXi/Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTlE1V0tpdyt4YSt5V3BN
            NVR3cndjRVJTaTJ3NnMxZDAySno3TUtGRFZvClNSNlc0T1NCRG9nODRIcDBlYXBs
            SUkzRlB3WmNsYVM3N0J3SGV5dFNMeUEKLS0tIDlmdkx2T3ZuSmQzWUMxWU1LZG9F
            MFZUSTA3Ym1UelI5QkUxMUhLYUxMMnMKs3sbc8+p1ezJxE+f0j+9ZHfdjVZErulS
            KTbyOb/xSGJ5xOJJIflp/aFENih4Zy8gXhjUfNwmd9an9K5cevbjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:26Z"
    mac: ENC[AES256_GCM,data:FsiTQNbTQ4Cjmcrh6nt6iXqJXILZgyPhjzGlFzJK0C43TctqrV12MyheMYXXTpkTFO0Nwdg1+bFntspM1UBTKJSmjN5nUZIs2xYxDBwdR7/38gufIhWEb3yGVnAJgSakjL4S7/GVBNPRYUsjuk8MMgKh/obsTQtnSmF7+8ob8vY=,iv:y4NnHvalSMxzvYRqkVZqnd1DS02t+Y+R5DWL6anrX/g=,tag:QwSPG5F8aQOV7dnm7GFwqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
