kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: unpoller-secrets
    namespace: monitoring
stringData:
    unifipoller_password: ENC[AES256_GCM,data:PqDsv71dRt94neP4U3GtYEujtZ4=,iv:qKRiKSvxUhk7+N83gDC5c8eX0Wmafzz9vj+HsnxEIx8=,tag:q0a6VVXksfGGym8BpGcbrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:54Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFrq7TXu7ARuCwQbjgnOGcsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsHDiz4gb1jqfn6KJAgEQgDsmA1OW28IZnsl1N6CydXGl3hPOH2C4y9RvC0AUn1mb+Czqa6PbaMhUGWccPvvL/Zm1d1oaX1+7f0qnAw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSVBYZHluTzZEQU5Pbmtr
            SWZiQVorMG85QWhUbnphdVduNFlxbHk1L1ZZCkpjTTlMV1FlUWpEZ25IbjhWZ3Ay
            NW5ZVHhCQkpwdGVuckVOZ2sySnFWOXMKLS0tIGh1dWpiQ2NGaVljNEFmbjhlYnhH
            SUZoWEt1RDNwTkR0SjZWbnlQT3V4L1kKGF+4dsR/fJCZQQI0uEzpm2/KAaTrSiL6
            C7YfvAPSpcFsmfpaCQKL3+WGVVrexwu9HVB5GGCvSpKdrRV1zygR9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdktMUjk2bVFPZUV3dnVW
            ZnFEM1hKMzhIVXdUQ3RMMGFrM0NFTWlJQ3p3CldlQU5mVFNiTE1GZ0dvNERTdFdk
            YjgxTlRCeGY5SVJsa2tGN3NtWjAvUmsKLS0tIDlWczhTZnlrMEFFOXRVYllTVWJ3
            dXRDMmZ5QXdUQithUkFGQ1h6dzNUL2MKh0V2DFzJJHW6A2zy9CZLWkXM8p81INTl
            lYp59WwHOSvB6VzXvHA6xMzPyOL8emWJRc99eOSujOdTsCLo/rQnUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:26Z"
    mac: ENC[AES256_GCM,data:FsiTQNbTQ4Cjmcrh6nt6iXqJXILZgyPhjzGlFzJK0C43TctqrV12MyheMYXXTpkTFO0Nwdg1+bFntspM1UBTKJSmjN5nUZIs2xYxDBwdR7/38gufIhWEb3yGVnAJgSakjL4S7/GVBNPRYUsjuk8MMgKh/obsTQtnSmF7+8ob8vY=,iv:y4NnHvalSMxzvYRqkVZqnd1DS02t+Y+R5DWL6anrX/g=,tag:QwSPG5F8aQOV7dnm7GFwqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
