kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: unpoller-secrets
    namespace: monitoring
stringData:
    unifipoller_password: ENC[AES256_GCM,data:PqDsv71dRt94neP4U3GtYEujtZ4=,iv:qKRiKSvxUhk7+N83gDC5c8eX0Wmafzz9vj+HsnxEIx8=,tag:q0a6VVXksfGGym8BpGcbrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:21Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHjt5qTT5OjQxXIeCTRFUcIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKBgVI/F62k9+awNzAgEQgDtcDau0QUv3V6TTYhOFLV98+BssNBUSqXSTV2F0INHobQ4QYRnUy03NAcATSLysSE6Mu5qZgxJ4yGlCaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TWl5NjJkdlVVckV6SVhw
            SFMyeE40U3ZEVkpaUHl6d1lTei9PWHozWFNrCmVEK3dyYWVVbzRBL2p5dldjSXg4
            MmpPNklnM3NMd2M4ckRPQWVHZkFxSkEKLS0tIDQya20rc1YvbEpnUXpvcm9CTEls
            QVhhbVdRZjBLU3Y2VWtFQ3RIN2tjdUUKNCo54QKocXW2txhCvZW9VbpS8UzWGDkm
            Kkr31/jT/fd8J4/4ol+qkvWUiicsIYb135TYqeKDG7M/4GtGE8OWUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT29JSmRJS2xkS0ptWTFO
            ejdYKzhuSlh5UVpOT3BENEtBZjdGd084Qld3Ck1OMUk5eXpKemIzbVpCRDBJQ3Ru
            dzMyVGRTbERHQ3M5M0pNd0RTaEZJUVkKLS0tIGpMNmJKWExNdDRkNjVsNVVUa255
            S2FUdE1zdXJITEF2VEZIRHhFeDBpK00KsVLGZbCyjzjq0q213hloMWx9OgU7HTTE
            uJcJe7A78niP6vQV+oweIF8+vD/5ioxjpYffudr/0ZGvRl9YoJUW0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cXdxWE5XSTZocEJFek5Z
            WXJCbGJNQy9EUklQbEo1U001WStab2VMeXgwCmtySE01N2dLNzhHb1pQY0pzam9S
            WCtUemhJWFJpR0xyaWF0S0syUjJSZm8KLS0tIEFLUlFRQVFKRHI3UnpzQWt1WGxC
            OU1HNVBVMDBtYXJ4Ym04SSt5RTNCSDQKVT9WTmEN0v/XdgoFl4MtaWjTnONAucFO
            pWesx8wTQY/8uwRZIMg5jxN4GNFJOnnod06v8K4VuYVT/myj5h1VzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:26Z"
    mac: ENC[AES256_GCM,data:FsiTQNbTQ4Cjmcrh6nt6iXqJXILZgyPhjzGlFzJK0C43TctqrV12MyheMYXXTpkTFO0Nwdg1+bFntspM1UBTKJSmjN5nUZIs2xYxDBwdR7/38gufIhWEb3yGVnAJgSakjL4S7/GVBNPRYUsjuk8MMgKh/obsTQtnSmF7+8ob8vY=,iv:y4NnHvalSMxzvYRqkVZqnd1DS02t+Y+R5DWL6anrX/g=,tag:QwSPG5F8aQOV7dnm7GFwqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
