apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hBs/iyfZ8Zc7hSKxOwKGhXvkWQCIUY8rVhEJPKp3HquhccZlptoQlw==,iv:vCMy62RJWhz9QZP+6Yqgg7wD9VIi9mE1h+L7Arpo5pE=,tag:vcGEI/1K0yfC6VMNvGE1yg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:44Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEM6aqp4SAuuTAKLdiRhnDCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmkcoE+/BnJZBTarDAgEQgDtp4R+HuFBXzgUXwvVecEd/ZxDgcQZUzEwAb3XUxN40aI3NPlSn8/UBIeNKa2zbtT6ENyGlvS4ecWKnAw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRnZ6YjNLaWhRU3lYaSth
            WTVtc0V1eFhTTUFZTk5yc2Z2MnRGZGV1andBClNna25EaHVYaGpwUWxEbFBOZUZU
            c3llbXlUa1M0MldMbE1CRG82RTM3MU0KLS0tIDAvYXdnVGFBSkd1WGVFcllCQzJU
            UVJFbDhwYStER1podDR3Tk52aVZSU00KOVzfWegIOnRr7Eil5Jo2tYLUkuLKYnnf
            PO8HstaTkEXxmfMUnHPTbA5SxjWgLxU1hUYRXhxal7Utb8x64Cjx5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:45Z"
    mac: ENC[AES256_GCM,data:KgIqBqoP5VBIhZTlPJsT1MnjXTtbdCQJ4JLvsq2O1QWcG2yqXrWVYdj3KcH3JyfBY+TCN5uOzaKCI7dG6J7R1FYptpWYN8ZlS4b0iBR/O4mQGfbQkmjtcXT9HMk/HnyaT0WDhLG/EHUx1nJIOl0yIStp5D4P+VnPePlAlykuv7I=,iv:H7Cc4pCjzsQ0dUKK0/1RZevFJjMc9P8fU26C9N3JFl4=,tag:OCkQGpJGv6Ss+D3icf4Viw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
