apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hBs/iyfZ8Zc7hSKxOwKGhXvkWQCIUY8rVhEJPKp3HquhccZlptoQlw==,iv:vCMy62RJWhz9QZP+6Yqgg7wD9VIi9mE1h+L7Arpo5pE=,tag:vcGEI/1K0yfC6VMNvGE1yg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:27Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQETopKU8NZrbgJnF85EWGUgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUnpp+W+PvycOLS7JAgEQgDukK7Qu7FpeXeXxf8f7S8rvEZ68ndx68/+SUYc6S6/f44UORzbXUwXMgBYiJgmJ/JtTtdq09oNmtYmgGA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQm8vWk8vUStGK2ZOM0c0
            NkkzZ3lRN1JYSFhORXlPanJ4dnc1RE1aT3lVCkJhWTd2R3pURVc5NG82bTJPd0pU
            ZGlUL1UzSW1jMDVlZG5jdWx3YkRCVzgKLS0tIEk0dmtzR085dGJxRklkV2s3c1Vp
            ckw3R2RJZC9maVROdDBWQUdQaE1RekUKzcWJ0KxE5Wp8MYbAlDBrXaJ8yEpHbvG8
            BRCkbZuJMxMus6kapVHLbSXnuq9T/YFTbg5rgOoChMzKPje+tSNazw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TGo5SmVGZU05dVJsTFli
            ZmJuNU5kdElUdjh4cHZiZXMxU2dMY29odkZNCk1JQzUyZllaejJ6Yzd5Vm1HY0Jk
            Zll5YkI5RDNMWkVSMzhoNjJSOVo4Rk0KLS0tIEszelBFK3U0bmViVEdKRmtMNGdq
            ajBkS3ZVWGFBYWlsSTF3UVpPY004QTgKyQoGdPvmbr1w7ovUt0KFoSW2U4VRoqSE
            y5fHGPwFItXAjDvjAMIvxdOYbkpIP5Rv+FKp9j4ESHHW30yA+gm0TA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPV1d4d3hRd1ZOQTB5ak1h
            Wkova040clEyRFBudG9WMXNwaTg5WldaeFZ3ClRObHF1NjBPSzQ3K3pBNmhyZm1T
            MXpNNS9jR3kxVENMRGJibUdwN29sOGMKLS0tIFE5dWdoU3VqQ1pyQndxRmFJelJU
            alp5QkRNSUwwY1gwS2FOTCtoR2VXTHMKRpGWWBVXM6CkTH34/fVjQz9nBFXzzJ3x
            nh9dPUCuz+LS/fC3ZhDEOUXzeVIEm0t0Op0DZbMow2SKs2VOQOudlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:45Z"
    mac: ENC[AES256_GCM,data:KgIqBqoP5VBIhZTlPJsT1MnjXTtbdCQJ4JLvsq2O1QWcG2yqXrWVYdj3KcH3JyfBY+TCN5uOzaKCI7dG6J7R1FYptpWYN8ZlS4b0iBR/O4mQGfbQkmjtcXT9HMk/HnyaT0WDhLG/EHUx1nJIOl0yIStp5D4P+VnPePlAlykuv7I=,iv:H7Cc4pCjzsQ0dUKK0/1RZevFJjMc9P8fU26C9N3JFl4=,tag:OCkQGpJGv6Ss+D3icf4Viw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
