ses_domain: ENC[AES256_GCM,data:oh6+CPwYihE=,iv:CJb68N6knVR/iriISSBfpNF0LklUCdiewVHLmDWVHSw=,tag:3kt76lvBm0aGvNSKaFNo2w==,type:str]
smtp_username: ENC[AES256_GCM,data:UnF6ay7rDYH3DVXPOTEFAqHOPsM=,iv:GUtXTkJ3tJIvfDA3R/3hajucpd7XqRPfDr3D3PnYFxs=,tag:Sz9iNk3+GPNdM7ug41BH4w==,type:str]
smtp_password: ENC[AES256_GCM,data:xr1fYWm8MEy/8sAJjAoRDGjh0zACf7JvX86M2PhuTBcwQxODIxTns4y/tjQ=,iv:uo7XdyVxDoQVcg91p02KO4f1HciR09q0i5tx/7VllQY=,tag:S1fIWP+TeAqoi9SN8UDgsg==,type:str]
admin_email: ENC[AES256_GCM,data:6MVcLaRLOSclyapz1oQ9VOOdhPtDI99wBQ==,iv:WMiRMJAugEqHCa9mztJDuw/iBzqmbWqzHJ3SHvYbRcg=,tag:Q0oQpIOhAOE6cW72F4Hs/A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-26T15:39:00Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEqE7Ejxya4tWZ85fnNBUH8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzPJny8yIvSJoE4MMAgEQgDvDAwpok12j5zfhbTE9w86KBsbvPQsEJ5CPDRupHXisOffFlcnx45gchERw1h7msCcCzAkna3YIAU2j+Q==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dGhlRmNNTGVmeEpSRGxW
            Wk9RUUdzeVhkaDRwV25qaUtSRGkzSzNxbW5RCjBlbERPTnB3SXl6WDJ2elIvRTNU
            QWs3STVlWUxLcXh2ZVFNQmVrQmt5aG8KLS0tIDhTRlE4eVp0ODN4bG1oc210dERS
            d3Y1Yjdia2ZXSDZSSG1Ya2UvVVVCTEEKMVJFF6nRTRMAcdwRj7OmBkLC5oxOF4kq
            24VlyOGfBqYC6xPIxxnyA2QmYju7v9PCg6Y26tuQQVe2FltUCKHViw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVTJmaWtOLzFyRnRYMVg3
            cC9KQ3ZZblI2N2J3MHNVNXI0U0NXbVRGSkZJCk1yNHJueCtvRUZqb3NHYVNuWkZT
            SE9ia0Y3d3dnTGVGMUtzbGhwaCtmY0kKLS0tIEJVYVhyNHN4TmVsTFVmR1Y0K0FV
            OWRsR3RqSlFveWNtd2FRWHVxajFGL2sKlJ0I30k3REJuA376nR2tQDrArMnrbhV2
            lQ/+ajNG/qb6gosy3/+NZajn6n/D1JL2ewni6bSOjp2H/8tJQnt+NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU3VrSDlWTHdJSTRhRG8v
            WUMvNmVBcDBVVjBZTWlIdUhYV0hPOVdtdlQ0Ck9zZTgwVVhjbVBzL2g4Nis0U25m
            ajBCeUFUSTRSRzRMaDlJNmxQNFNERGsKLS0tIFloc0x4bmNDV1dqSlIrZDBmVG52
            empQYkRVeWdjWHB1djVqcDlQTkZjV28KXZ/+sLAJW8DtVFs3l0fyBK2YamMZFIZS
            2hRpHpGNtq1vruXuOxhfhHX0GyDqZgWVh3q/Vdl3S+qe0ArE57gRBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T15:39:00Z"
    mac: ENC[AES256_GCM,data:uc63Cmcu4NZjUZ5mWoK2IPbVD9Rta/aA4rJRZuenVtkCQmGcDxp5sJM3bhmzSPPt+FBo0J+GrJvr8XDuJqnuGKDeOekrE9vuoLk2aCjhRBSEXTjwJpwy1Yb7xBiW4rzt5Abg0rBxT6IFm85kYBCerwSX8f9+8ESFJYR1KbG32Y4=,iv:8pX0WlfrtlWniB6Nmbcvnv+wZIkkDTLRkrvtLg50qG8=,tag:P1vafI++XRTnlz0fskHnUQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
