---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittools-tagging
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent

  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@hourly"

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/buroa/qbittools
      tag: v0.10.1

    args:
      - tagging
      - --not-working
      - --unregistered
      - --added-on
      - --last-activity
      - --tracker-down
      - -s
      - qbittorrent.media.svc.cluster.local
      - -p
      - "8080"

    service:
      main:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568

    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
