apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: ai
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:YutTMN8cal4Bzq6n,iv:jhBZSuHWxT3ICW+TrCVjAvYAqvhZWopqZLF43hGwFm0=,tag:YxQn45z/z69vOUbAv7U9tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSHg4eVF0VEJzTkNoZFlK
            MStPNGhNMGRtT2xwVERsQkVSMFB2c2w2L1Y4CkdXcjlXN1FUUlVVNTZLVFVRU3NH
            MEs3bm5uVHZ3emh6SzhpWXBDNTdoTHcKLS0tICtrUHEvaXN1YnVRMXVnMzhjYUlE
            elVKL1RXb1J6cWN2dzlvbk15UjlxMEUKjjNEhHOQQJltR1YniruIlWAVf8yi4SmK
            sTl9y8o8wu5TPopIthvQxKnpJ+xpPxNjN6Q1JiKwl9UiwoqzvY9tLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK0hPZ21CVVQzTERWRzlB
            Z2lvTmt4cGJJQythK1Zsc09MUERhOFVTMlVBCkJ3Z2pRcHBRM3dsdWdFVVoraUFw
            SHFYbHIxcDg3c3A3VWZxZWtvSnUrWU0KLS0tIEl0Q2JKa09PWWNnaU5uZWM4UkpK
            M2x5eE5uM3Q5REpKRGp2bEU1WDdxdFEKsb6t8nvbHYM42fnSxwOV2FglpJoO/lHL
            s9vM7JoSXBDGpQiJqEaX3jFJ5vYcM/6zyxoFiOzoUqnfqrjw8qi26g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVityZWJLdm1Ra3J2NmlQ
            TEVZTzhrczFwV3JOdWdVbmpyNE5ZYm16bEJjCnJQU0tNWWFCc2NoSTRSdGh0aWJN
            c0t6UjVLN1FLZTlMVmp4QWtJYXNhWWMKLS0tIDg2NXVEQXNqQW0rR096bmRIdlF6
            SnB1dWlWQldsQmJWeWRGeFFwbVE2WVUKRp6y5KlLXPUZNrpvCiVURLzK+2iNzoLl
            TzFeBQrfp+hPLXYpzYxSqi76OlbY1N2AhS0Hd8QarW4lgF38DM2yUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T22:10:52Z"
    mac: ENC[AES256_GCM,data:Irkm0hNpEtmuZ5IufNpsCEA0Fyo+/TUhjrfjs1EeTz+swrDfgOCwwsCStf+Ym9akaBZZ5SWU9zKzZDnIY+uFv35Fssq+0P/f6tZWC9AYIn8dVp4gIhpW0D1Xt8pOpS+VQ59V8ra2z4eWXne7wRcQ9FMX9vEUo0eQUsHlfqWoIkY=,iv:4raPO4inOc0Vy+nltNOEbf7zXsrDfB+NHQRGPwRgBN0=,tag:M3R46USKBsUCHnLUcUOvrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
