apiVersion: v1
kind: Secret
metadata:
    name: litellm-secret
    namespace: ai
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:YutTMN8cal4Bzq6n,iv:jhBZSuHWxT3ICW+TrCVjAvYAqvhZWopqZLF43hGwFm0=,tag:YxQn45z/z69vOUbAv7U9tQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-06-02T02:03:38Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEG8UlZTk9VNc5dNghmJmcAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMclr2llFzbhdlukLhAgEQgDvMrp7k4byaonZY1zJpzjHu4Hd6FutX01i50FPI8hE6AsfOYS2ZfMT9RLuk+lZtQh3hL71HBzsKFyUSAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcGRNVjVPQjU0ekFqNWFL
            MlpPM1JxbnVZQlUzTlpYMjJXQXNxM0tVNVFnCkc1OTVQMzJjbTNlamJHVjcyYmxv
            UnVENTh4UDBCaDl5SVJMNDJiLzdQZzgKLS0tIGp0RU9rNmt5OE1CR05vWkdFZWQ0
            VHp1Z29KNndESXJ5cG1XalFDTkNyOUEK6kTkudES+YbqMTyNjRXJpjNgO3kZcYe1
            XL+2dXiOmOfpIIrteTc6E+gKA7C7s3UyVtJIvipqbywwfseKIRSo5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCakRCYlJtL1pHaEREL0Vr
            N0ZnRzJ6S2x5a1E3dW85ZnZHcmdxbUFGNlVNCng0RUtjRHMvOGpZb0dMc1hsaDRX
            cHAyZ3R4cHQvbXlXbTF1S0VtYnM5MkkKLS0tIHFxNHlKNHhLc3RNOEkyYkFPTzVZ
            UXo4VGZVR0EzNGNjanRrZzgvM2hPd1UKwbefJoVssKPoKy5M4EAxsOl/mIa2ryLo
            p0pI7KyBLxjnfGxFB5RVHMP8va4DfzctZfRxhQGYVZ+3lm36jzAkJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSjlSY0E5TW5TdXhTZGZo
            cjNkN2tOQW5TbjFZcm5BYkNGM1ExV0RBWGc4CjlsUExqS0x3RE9Ia0lLd29jUDNi
            MGpLN056anZ0UHpldzJpT29PekFFT00KLS0tIDJGUHB2dzFINkJpZitKT2dWdjdD
            NnUwMkNMR1BrWTB6cm4wazA5TlduN28K2NDTPMfdDSJCG/9OPanqHSZPqAR/LtFN
            rzGOb9JDxLdViZ0FhPWbrC3369xHGbBQTnBTWiBp1c9l5RvefWOcaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T22:10:52Z"
    mac: ENC[AES256_GCM,data:Irkm0hNpEtmuZ5IufNpsCEA0Fyo+/TUhjrfjs1EeTz+swrDfgOCwwsCStf+Ym9akaBZZ5SWU9zKzZDnIY+uFv35Fssq+0P/f6tZWC9AYIn8dVp4gIhpW0D1Xt8pOpS+VQ59V8ra2z4eWXne7wRcQ9FMX9vEUo0eQUsHlfqWoIkY=,iv:4raPO4inOc0Vy+nltNOEbf7zXsrDfB+NHQRGPwRgBN0=,tag:M3R46USKBsUCHnLUcUOvrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
