---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-storage-rook-ceph-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/rook-ceph/cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph
      namespace: rook-ceph
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  dependsOn:
    - name: 1-core-storage-rook-ceph-operator
