---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-apps-transmission
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-pod-gateway-downloads
