- name: Check connection from web to postgres on db server
  wait_for:
    port: 5432
    host: "{{ db_ip }}"
    timeout: 60

- name: Check connection from web to redis on db server
  wait_for:
    port: 6379
    host: "{{ redis_ip }}"
    timeout: 60

- name: Init remote Database
  expect:
    timeout: 600
    command: >
      bash {{ tempdir.path }}/kasm_release/install.sh
        --role init_remote_db
        --accept-eula
        --proxy-port {{ proxy_port }}
        --db-hostname {{ database_hostname }}
        --db-password {{ database_password }}
        --database-user {{ database_user }}
        --database-name {{ database_name }}
        --db-master-user {{ database_master_user }}
        --db-master-password {{ database_master_password }}
        --db-port {{ database_port }}
        --server-zone {{ zones[0] }}
        --manager-token {{ manager_token }}
        --registration-token {{ registration_token }}
        --redis-password {{ redis_password }}
        --user-password {{ user_password }}
        --admin-password {{ admin_password }}
        {{ '--no-db-ssl ' if not database_ssl }}
        {{ '--offline-service ' ~ service_images_copy.dest if service_images_file }}
    responses:
      Continue(?i): "y"
  run_once: true
  become: true
