---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - ceph-cluster.yaml
  - ceph-blockpool.yaml
  - ceph-filesystem.yaml
  - ceph-objectstore.yaml
  - storage-classes.yaml
