kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:NSrKLp8ccFGdaAs4kLNkIfVs7yUMu979Jf1O2KyP,iv:mNVeGGk4tq3dz17NOVQ43b4agJt9kmBO2z8mzezYWQM=,tag:dS/VIBihxwx2QSQVBBz+dA==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:nb8XfCuefQF0MtSr/VrPFGFPbZtsFw1nCXYFyQkg,iv:C61DIlrL+196HbBJxz+EM2/dwDYuZ+V7RaCLIIteNaA=,tag:BrZK/NQSzmRoc+pLdnESAw==,type:str]
    telegram_bot_token: ENC[AES256_GCM,data:bCRj2EtPRdNXYfC3xB+encc0PuFtcuobuo2VB3K+3hpRAjbBZEXfvCDcMMWJjQ==,iv:cILQKkTTpY4ipFBVbn1KL3cFnBaad3L38lqRcUIxDuY=,tag:BHIGS5LzzAQ3IhqL/cf0dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZU4yZ3FtR0ZUSm1CNWND
            dEhqSTlhaWR6QzZka1ltQ1B4bnZiVWhmZGhzCnU3dGdIeEJteGVIMGljdHByWDFx
            Qm5sUHZ0Y1ZKQ3A5TFNzN0J4ekEycFkKLS0tIElLdk9QcWxPUDViK1IvSCtCNDlG
            eTlsUW5SMjhrMXRqZjBCVXVLek9PeEkK+uD1Nf/1xtSjbcOKmbV9sWYTBiwmo533
            hQovsEC2s6nE8b3bcWXGgw8Lp0kw5bafhuMxUYH2N33DHwSvOs1RIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL2lrVVRIdys5VUo3SVFY
            TGkrVzJIVEhIYmduc3NTWUtzZmdSVmRldEhFCmZ4YXhBWFRsUFJFK0JQb3FCY1M4
            RUJ3N254WEtJNjI2bExvZzFOMG5VUUEKLS0tIDFHSmVTOGFEblVoRWxobDNxVjIx
            eVFlZk1MODVPOCt0d3JMSSs3T25pSTQKp1ESlar6Zh5NYNM5CV7048ofQmf98jK7
            MMQdmfeIwY9+86Z6GlfD638EBp5KFuZk6UK2UGnxMry5K/GEPfpfEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVTRlZ0dma000OCtOTzlM
            SXlMbFFiTlFYY0JXa004NUttZjJsTlloa1RJCnd0V29oU2FSeTM4RWYwb3FNbFZh
            ZWlkblNvTUhqU1N3WTZONURBbjZWQ1kKLS0tIFVhRFNUZmdONlVZYVFEK2pjOW1m
            anN1dzVweGVPU2R0bW8vMG9DQkcwSnMKJsJjd3yx/Hnsv6/ERXh3pGqSeJ84EVK8
            wTgnWbA9kNnyXPX4KByUK5ORIJrcezRGyK41AsNcSW88MY7FF+KZtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T02:37:11Z"
    mac: ENC[AES256_GCM,data:vxvr41l4J2Q+aMmhQzbwr7ny9ONnQ69RzAa/X7+XUaHZdJJmkglcNvWJvL/weXuZ6oGxTsghWIVqq3ANOI4Uia9lmEo+M0z/IKp0HR1Z1X5EvLhy0rgM9gXeTVctkaiHkxR2pD++3CRXUrglxRUX7JgXxLrjwr/FzZ4QVyQlfS4=,iv:QZbufJysjais62Wv+kHqUKCSbe0/niMkMZykIPltX24=,tag:MGJu7N1qZMbJOLzb9q4Odw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
