kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:BjF+hliJcpIEv9H0bh8BqvdpS/FMb47rklOhL3yl,iv:z0XDByyDR+JtvuLJF/NcFuqm6YHUh40ujpYyhKPAttc=,tag:AjIxIif5osTtpDsAn8jXqg==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:ehWRZW97Kw9R3DbDNcc1gGQ1W5ntMxYoPqm764/f,iv:fcMkCu1zZkcz7u22r6T1NmBQ56Pc8vxTL0Y7gBonksk=,tag:gSIZW21nO6cnG8N9bOjIFw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-26T03:19:29Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwHoWH+KTHkwzBJLzekmERc1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyF+JGHd6AKTjpUWpAgEQgDtLBoouBF9hUrWOkfq5zgg5g++fWsbKwKEwfgOhwn9+HpKzw9hB+w896/qAFenH23/4PykacRbzvKfcOQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RmYrK3FYaFF6ei81TWU4
            a2RUV3dHK3Jmb3ZrQ25XbGFEazFEUzF2am5FCnFvTnpFdk1TdkZHeVR5Nm83enlw
            bzd3S0Zna2JaM1c2M0V3Ui92Q0VDb0UKLS0tIHhYSEt1K3FRa3ZCS282dkt0eWJ6
            VEhMbFJ5ZUNDOEFqQkppQ0dxd1VqNzgKk2HGRhEp+ZicLFPNDHyWoSgIqoSIfn5f
            noGs5k2dvLXW1cdjmyAxJN9J8sjimyMJbBtNt8XzEmyh5/zLCAWZRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T03:20:07Z"
    mac: ENC[AES256_GCM,data:tilTAuw3dBq1D3Tus9beHq2mMT4C84Qze1k0nYGL42WLDkx4flKFI+w1D5PWkyMWk5ZuUdlLG8EhfL8dSbsEkHTa7GXJehn8SbkmU2YMY0YIvPdUX1WD5vZP3IdHJ8AWNB+uRgwJVf2Ffu9QC4H37MWE+DqwqtCRN3OlAJCIbn0=,iv:h61Ri6FjKJyx7peO31oXPYcasldcAy7rGPKW3gGsTmY=,tag:T5F6nhx9pyaTaNJ0qaHsJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
