kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:0RFzNvZspvqyYwu7mZeLiSWh+GiL6bnXnBtBPpI6,iv:Z+17qI3/x9DPXyDGs4oxHF7pvTD0GMOcd3/jHOfeIKM=,tag:g78Tkg7ytlLWhtDGr2ssSg==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:eFRqTOXknFubVWKAhzEqH1tXz1gN4CdQ8QkWIR+p,iv:ArBFMCFmND7MyCt+Yv6PsAx1qvgIblRIr5XPhp6C0Ok=,tag:9pWBR3xRrkc8jB4px6LF0w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:26Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQES9MpmqAPZCmXexQWN150uAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfEeHwJVaS/ZJezraAgEQgDvAPdvmSq7ojRCDdgTryWmXU7/w8fK+ydN8HTPkjt/+Y8y+bEIO18r5GkjKMJ0UFFAZVDXCH/cTCOGNhw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb0ZUY2xqaGwvc1R3T0dx
            aFFZTW9DSm83QnNTb2g1ZGVlUFR4aHBmdjNVCllWS2g4WGd6dzAzQllBSkd2WmxG
            eVBHbmNtRm1lYndnSEE4bVZDcDd6bTQKLS0tIDZCSk1USkdEM0Y4bkZrZVRQVURi
            YVF1UjV4NzczQi9LbHg2VUF3dkFINXMKToxB2n6UJva2z+Bt1xhtn+oZdXBpKWH0
            E+1eD4fdN1A8pi7X/qEsjOzOZgiGjZR3Pvf8hUldaEbz7TeIpZzuiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:27Z"
    mac: ENC[AES256_GCM,data:nylNfr6xrmjH8m3k/HZ1DGP2QU5FMOG1st2oia4X7PcSiDbQIbFC33V4x2A90Pdjiutk2qug+l4TlhpRmwYcjnveYWBijYvmUvXDuk0m+X/DNzkG4enkfpv3JU0mpmDU5q+FlEnWMGqSLlU9hqUFIoMxWTIi1SUrP18nFlfmITA=,iv:2YMv80T1bHk9bA9LY6dfXHoXpj4jeQIi3Lh+uZ24gcU=,tag:/ytsn4Ske+XIa2HPKweafQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
