kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:uHgzcs9uiF3ZMnWRhsiSfqZclKvEeBMaawF2L7tt,iv:CM7pjZKZ9YK+yrLkQw4k+cETJn8uzWuCNLy6NU+m0Eg=,tag:KCV6pqR45l594wueFTXGjw==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:cFslnVI+xrPgpaKaLLPI+XPf8jAxp+TDzYnRf77W,iv:eLBWthDal25qjOchPM7coLnBg/lnl/oWI6gC0/OQsWc=,tag:p8ArUPwcgi5msXf3MmehVg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:03Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHblfszIAyl23kVy43uOJAtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8oaCK4GtGr8uYqy0AgEQgDvTOBHxN8/Eacx4DcfUbGYww4vYGntwulxesjHYaPqsH8SxiI4rj998mSOZS3yP1NuEHpPhBPOTO77L6Q==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbStXUGZseXJVV0NwZ3Fv
            UjU4aXdoU25pcytvWGpBdE95c3JMMWNOcFRrClpYV3lzS0UwT1pZMkF1RXR0d012
            R0sydFhHYmdPMm4xamNKbEpDbCt3Sm8KLS0tIFdZOGIxM3FxTTNsdjNGQW0wQk5H
            dkVnWmJYbE5mR1JORUdiaTd5RDRDSzgK50jzm7FmVLAfITOhuiRFwbWEqwucJVrh
            9af9rc6v9CUAP9Zdt4UFgPtuwEuKuu6r2AwKLkRqWruxejS0XUuqng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:04Z"
    mac: ENC[AES256_GCM,data:AHa5tB8MPMuWn/z4Rx7LxEtaqCJnN40ewWuFpshyg8Rb/c9AmBU4mRHFV73wzmG4Wacg2/Doi+yAczX4eQlBpX181tHYk5DABHGf41+fTB8MXWlk5VDfUBOo4POR+KGk/rrHY7eQIHsI1M0qEjorOI3k9Pd7dDgKfVF6x902D5s=,iv:qFYxTAj5DwDAyDfKWwpLtNTVDgPPam2SgrzVcZ5UT7M=,tag:sygDlq2BncdlNrk1HpjKIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
