kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:0RFzNvZspvqyYwu7mZeLiSWh+GiL6bnXnBtBPpI6,iv:Z+17qI3/x9DPXyDGs4oxHF7pvTD0GMOcd3/jHOfeIKM=,tag:g78Tkg7ytlLWhtDGr2ssSg==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:eFRqTOXknFubVWKAhzEqH1tXz1gN4CdQ8QkWIR+p,iv:ArBFMCFmND7MyCt+Yv6PsAx1qvgIblRIr5XPhp6C0Ok=,tag:9pWBR3xRrkc8jB4px6LF0w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:55Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQE1TElzQi91gm7Jyq39E9t+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQML2D0rUqWgbUCCGE6AgEQgDuGDtNCXQjSOeqGfCzeK3oJdLAwRfD77SroyEwrf8LtfXyduC4ZwUI+WzT6bUNolIiH+VZqHZyJ38dp4w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZGNWN2gyS2lQWUdIaWdN
            MXptL1QyclN4TDA1WXRIczBBVmJhQjJoa3pjCkpOV2hjRGx2aUdtOTlJcEp2c3Ba
            MEI5eVR5MTcyeWJFUGJIcXJrRWVOVTgKLS0tIC90djdmc0JNenNROUVYTThxOERB
            TEhIOVJabEoxTGFKMUphc0hJNTVXNTgKq9gl6uf0fHlrZPCMuRry/3gRravzqhAd
            IB1RMHMl0gt2A9hu5VqWnxmLUpMHmg8tSZKyTe3UXlPxuRJ0C0TpMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN3ZWbmViWGZZbkgzUmJt
            clVtakFsbVU2Z3FkbHYzS3U4Y01yOXlobEc4CmFYRkNUdEc2TEVMYjlmcDhHbXpt
            M25sSTc0RnM1NUg2M1ZuQTRRQUNzOEUKLS0tIGR2SzM2SGFleXNBcFlaZUlsY2Jh
            ZFRhdjhzTlFpbnJuNFdieHFTZDlyQjgKb+fYg3EUUTYEAJyFIUKcewrkiXNbZy+r
            KWWzMMOdIUDLYXNhGum7YBHOfp2PlP/QEVMvhrQ9VBB3S3GmRHtQ0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:27Z"
    mac: ENC[AES256_GCM,data:nylNfr6xrmjH8m3k/HZ1DGP2QU5FMOG1st2oia4X7PcSiDbQIbFC33V4x2A90Pdjiutk2qug+l4TlhpRmwYcjnveYWBijYvmUvXDuk0m+X/DNzkG4enkfpv3JU0mpmDU5q+FlEnWMGqSLlU9hqUFIoMxWTIi1SUrP18nFlfmITA=,iv:2YMv80T1bHk9bA9LY6dfXHoXpj4jeQIi3Lh+uZ24gcU=,tag:/ytsn4Ske+XIa2HPKweafQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
