kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:Uy157KlZ8jkWMRg730dZ6yOLtkcC1nY1U41JL2Hz,iv:ffJpM7B3PCvMwXAX4qiBZl2zmoNL0GY684tVlku48ew=,tag:t5NvuSPt/TLoiCy74vSjEw==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:v+blf/fCNzGGfDDTxHXZp4Bmm/R4sXUKMS4K3Vup,iv:l/h/ESVWx30jhtMRz6nJb2kRtAvlpKOAK0YEQTbh/gs=,tag:XFeRbYDrjSWNFpPpGklApw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:19Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGsFw4xYttFMzCXZ2zULv6tAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIJDB7D4xzety0VtiAgEQgDuwxrwBNQkCasg8VlGAM824Sobl8+LkLq8Mu32lVTsS0W75eu68PV+s9Uj8EaJITw0vO1d+WIJBfKp3SA==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRVVkbVdrbWFPc0lRa21q
            OEdINTRNcStwVW5LM3BLWTFFNmhpSGlieXo4Ci94bC90b1BSUllKN0VyZk9zZVRF
            OHlKTVpERC9pUVdhYXk5NVpKUEZkdFEKLS0tIDJqWldnV3JBWTlzOXlvK0VyaVFv
            dE1PeGJETm5KcngrdWttaW1zNHhEMGMKR/b+QjHQ7u1tn97s93W4yi0oci2oPHua
            1jvppq3qT5YyE2lUNg0l2DPqxLD9HWCBSk4Nc6eHtLgLxoopZE4y+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:20Z"
    mac: ENC[AES256_GCM,data:sI0uDEqsPM4kMoeKgtseIfr77iWnaJfdbMbJGJXXeIphm1FKGjwtLUQWTOsk6594lZR9xI4MtxA4uMiKTBDgJ4eYWlXdtuXpvSBrWsVheL8WsRszAdDWFlmGr8Y5y4pW6ihRajNcioSua5frJ4fUdHZ5FDWr8N4yevA6SisK7uE=,iv:KyM5CBpNkrjnTQFQj4ULVY6Rv98uy0MbuE25K3MyNIM=,tag:foXMRoRAjGp/IK2zdImv3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
