kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: alertmanager-secrets
    namespace: monitoring
stringData:
    pushover_api_token: ENC[AES256_GCM,data:0RFzNvZspvqyYwu7mZeLiSWh+GiL6bnXnBtBPpI6,iv:Z+17qI3/x9DPXyDGs4oxHF7pvTD0GMOcd3/jHOfeIKM=,tag:g78Tkg7ytlLWhtDGr2ssSg==,type:str]
    pushover_api_userkey: ENC[AES256_GCM,data:eFRqTOXknFubVWKAhzEqH1tXz1gN4CdQ8QkWIR+p,iv:ArBFMCFmND7MyCt+Yv6PsAx1qvgIblRIr5XPhp6C0Ok=,tag:9pWBR3xRrkc8jB4px6LF0w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:22Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHloBJ0q5df2Z+Bfwuq0Y6AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMV2bXOvHFg/UV7MjmAgEQgDug7mSYYFkwIgFn1ySQZrcj+i4E3OhNVwOgruvaG9UHII8ZM62hj4R+UpCEE3VqF+CExuulT0umzgK1QQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcE9EcW9UbEZlM1RkR3RR
            NG4yT2RNT2svUVpLbUFTQUFWWGVBZVY5dXk0ClFmMnRKNWg1dlhqYVZ4N2dOb2RC
            TXNtZ211cEJXaG4rY0FtbHd3dlRZVncKLS0tIGZZRWtSeE1PemZrMXFlQnFPQkZp
            R1g5VWdmNVFYUkZyRHNmajM1R240TGsKTAvtPy/r/DtwC0k5X3RmOAs8WMqPIrM1
            0x2WTkcgauuUo78SCrRNYV3GDc7eYO/snp/AvyWrsTTH4EmOU/PPWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdkpIN1pjRUNTU0RGTjdS
            Vnk3Mk13TUl5alpxOTc4WVZlSXBlMHBpcjJzCjUrNmJ3WHZmU21WTUpUNUFzcWp6
            WXRJV1krYXlsd1RCSDd4bnZnazhrTkEKLS0tIDdtaXFPb2EyQjU5QWE1Vk52RDJN
            Q2s0SEFZaGNPQU1sc0lvNEFqdlVuU2sKsxNO/OlfoIZpVXzYVkWrPht1ukuXPMy4
            mVPE/MdR9FDaqNd7/V9NEupyIwFt9ghubV6rbyf2GONhGuJTwnheIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ1dQSFhKaEdySXVuZ3dS
            Smc3WGRwa0VJK0Z1dldvZTVQTzNtdXdOckcwCnZHNFdvYVRldEtQY3FMdzNVMW13
            bXdWMVhxZTU1YnZsS2JzY1V6VWdSWE0KLS0tIE5IMnIvUnRJSGMzY1FtOFp1ZjA4
            azBQTERDZ3JYczBTVjB5OHNxWGN3aVEKRYc3E5pAUfxTD64UYf6zpMLqWZ6jF1m7
            06WgS9XjmYGMkQkRORuSmMM7xAyEqhXxZTReCJ2IR+FfDRovDQDPKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:27Z"
    mac: ENC[AES256_GCM,data:nylNfr6xrmjH8m3k/HZ1DGP2QU5FMOG1st2oia4X7PcSiDbQIbFC33V4x2A90Pdjiutk2qug+l4TlhpRmwYcjnveYWBijYvmUvXDuk0m+X/DNzkG4enkfpv3JU0mpmDU5q+FlEnWMGqSLlU9hqUFIoMxWTIi1SUrP18nFlfmITA=,iv:2YMv80T1bHk9bA9LY6dfXHoXpj4jeQIi3Lh+uZ24gcU=,tag:/ytsn4Ske+XIa2HPKweafQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
