apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
    name: ceph-pve-external
    namespace: rook-ceph
spec:
    external:
        enable: true
    dataDirHostPath: /var/lib/rook
    cephVersion:
        image: quay.io/ceph/ceph:v19.2.3
    crashCollector:
        disable: true
    healthCheck:
        daemonHealth:
            mon:
                disabled: false
                interval: 45s
    monitoring:
        enabled: true
        externalMgrEndpoints:
          - ip: "10.15.15.50"
          - ip: "10.15.15.51"
          - ip: "10.15.15.52"
        externalMgrPrometheusPort: 9283
