apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:jXLwUo+JQxzC6qmPzIz9kw==,iv:HAXe2iLY+08Sx4+uqTknM+VoAqAjsklZSRSVyyJVRU0=,tag:bx9BTJBnPB1nO4DJq2T7nw==,type:str]
    ceph-secret: ENC[AES256_GCM,data:nV//sJFWarfM1tnk1QWBtDwJ61A9D1gV99o5KQ9EAaRuWk8mZmA7P9uf8zRvy+p6B3I2TSj0WsE=,iv:G2etDy855R/6n7a7mh3/ounHRqv8IGYwRgGlOiIy5Co=,tag:jdj4UMy1p3PEFFwTtbqsoQ==,type:str]
    ceph-username: ENC[AES256_GCM,data:bC6s0XW5gqWKCj6vBH04wLRByhJXkpqK13kqyg==,iv:aYfkOk8xQ9hJgtbI4L5+CSD+hHuMdW1vD9LzciR1nho=,tag:ECwGuclI1PPoEmXnfOyy4g==,type:str]
    cluster-name: ENC[AES256_GCM,data:6rX2eHQlyDCA+tKLg6HjpJuOsdaVUuHm,iv:w8h1iCRjmGh9jFNc3LieXgwuqf0kalFX1e19W/KRvEU=,tag:waNXgs9gF7C2o/j4/2fh8Q==,type:str]
    fsid: ENC[AES256_GCM,data:P6cZB6t2r+nS00nGjV6zgCGcLqyLVyHr3CLgNmQ6LlZBIVE2qRDc9Bqm3mWEqDkf,iv:HkkuqMbqEDWrVlUYUueMz609W6ZUFyQcGIYHooDFn7k=,tag:W7tMHxp8RQSU5yhdRqs0Qw==,type:str]
    mon-secret: ENC[AES256_GCM,data:SuYgR+cjgrH4fKFUwLxWqw==,iv:V6kuVnepNtiZCx5+fmL9fvTuIuwpLLVEmgoY7QrWFLE=,tag:V4URSFlxEg7d1B7i2ra9Pw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    data: ENC[AES256_GCM,data:6diloGz7sJ1YYCYRg0IKJWCXHMJatjnk7JM=,iv:/m4BHzf+cOjanen52et52BSktrs2jeyJSCb7Tn+MVzI=,tag:BFskGIDVk9HeYgjtl3roTw==,type:str]
    mapping: ENC[AES256_GCM,data:0Ak=,iv:RAcl7I2PCH5lctKdMImSH4ZRIVG5voa/ijKSBN3sc4M=,tag:YJegUo9kyc8IZE//j19yRQ==,type:str]
    maxMonId: ENC[AES256_GCM,data:Nw==,iv:QFaPRm/a0rPFhsPsDP4t5fiiGIhM17rG7szgAhGV83A=,tag:A5aSTQPp0V75qniH4aqtUA==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: rook-ceph-mon-endpoints
    namespace: rook-ceph
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:WYyaVmzT3FzR83aLUcRpzQ==,iv:tRA+AaUIiVY6q+aTDzgosBNiDeFqxmoFInSqqk2lCSU=,tag:0ufn4QfervtgNNh4lOCD2w==,type:str]
    userKey: ENC[AES256_GCM,data:Y271VHCfhTVf9g66/QEY5aOlEaN5wLs/oZhl1EfmeFwbLYYyY/UJy1gjTAsSca546gewNZ5SLOk=,iv:vLGne/LMmUgjgKdUZghrGtqZ+GmMMvpa4E/bl5xdigA=,tag:1neX1S/Pzt/9GwXN6pWGlQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:ACs11CC8BE3/4g09dPSEYHyBLoqyQCbclP7e2w==,iv:qnWK4MPJnmF6g7d2YHy697oTSKwmx53OwqlWNhPTNII=,tag:Y6QvPp2EDM99HZaNNcC+6g==,type:str]
    userKey: ENC[AES256_GCM,data:mKq+0v1X0gBW6X7dZE6x8Tn2q5GJz2LgZWfgi5xq3PikzzevoZx3FCwx8ul3HZZkqQeTHJHXjpM=,iv:arfkYC0D5qgIEE443RpMGejxIs+0rhTP/9uMS0llkOY=,tag:bVVbpf24dwFGF/Haj2ahFQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:S2hpVSbYzQYdrKqZaHwjQwtYUF0=,iv:ZNh9gqUk3v2caM+xCZYtf/28muOR7irOAzmz2xvout8=,tag:ZdyrnAlsKGAEPD/bZF3Nsw==,type:str]
    adminKey: ENC[AES256_GCM,data:GVnGqtLLAb76wNgN0a/vk9GWo7fDc8iZ60zBjVJ/8fqMpqHWNRX9uz+VYUpjTTq8yTqizP5Eims=,iv:8SwW9PLiW9dC8TmhedQ84Q7yOzdUXnqPHkB1Bt9yO/I=,tag:Q7y4oMMJecdSt6sEPmkj3A==,type:str]
    userID: ENC[AES256_GCM,data:feeRoIoSBzw+0kmxsXaMzZ8W264=,iv:4o1i4dTULhObeel0VtEwT37vzCeIcMUprKT9n6Cfq4I=,tag:NWlWIQHCkYUJWdj6lnCj7w==,type:str]
    userKey: ENC[AES256_GCM,data:l77NqH4gWoa/RK/JsboMz8Srl5+S7to+c2JqGoVdeZSd5TIOfqlrOHqSVSgrZzlwetTq3wVSSdI=,iv:MYqSRAsT3cHWIJAhrfCdHDLEDxeRP08KypeHLoOnHm0=,tag:gz4hnrUumMnLcNZZoAa4KA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:f+win+c2t1cZ5gUI/0bG0+UVuXyOOBuMWkND3fPloV8=,iv:6R70SX3ZFAxPDptZxOTb3n9xWsQWwZlfKSRDFQAhmnA=,tag:JGrDCaj/p3klkX+enlX2HA==,type:str]
    adminKey: ENC[AES256_GCM,data:yD8itSw/5qqdX+TYRMAbngucKCcrzhbhOYUG+NPO1KB5dG9sEQVIoDvc1HOFyJY93oQbQBrCBWs=,iv:W6DckTq+i5UWNXoulj+zxvN7vtinSRK+BigxgJh9lpI=,tag:oGNcGuQzxTWY36J+BwK/uw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
data:
    accessKey: ENC[AES256_GCM,data:xkJntBDMMi03JOoOl8r/spNr88n5+TlP569o3g==,iv:cVQnuLbKPa5aJVLq1KNHsk8WcW+SSZ/buLUh8nn8pSo=,tag:B9YLN/e8heLUWhwUe8NuHA==,type:str]
    secretKey: ENC[AES256_GCM,data:dLp7fdf/yn678TSq7/YVT3KwVNFcG045qSpTBF3ULSbo7hed/adySOpJ++CV1Fp5z1bRA2FtSio=,iv:jV54w5AM24IOIuTXPWJvBijA0ZlcXlYTIFkL3X5L4h4=,tag:sqCBSC7kETh0w+zBUMluVQ==,type:str]
metadata:
    name: rgw-admin-ops-user
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:22Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEo3QfloMXabh9l9DWS7XCNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx/tCjR6ENG5FO+7BAgEQgDu1zwg4eCpMN0f4QkEsVPogDDZ+zHzl3IIDI8uxa8hyDOr3x7bNDa1WCyyEP/+wFeTRqphgMQXdjzIImg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SXd3Njh3UlhibmtmblZW
            OFVaWExyUGlwcDBpQnBkcXU0SjlFT0NWQWtNCjdrLzE3QnV3YVlmdlNJTVJOSFZz
            R3RPV2dZOVE4S0s4U2RSN1MzbFVOaDQKLS0tIFpJZmJGUzFKRlR4bHNDMVhpK1pV
            czhBYUVFN1orNjIrL0lhb1FEdmpsZFUKZ5i4V8qFsO9R3KcSo7cGjjuDu2D1InC9
            96PkE8OfcmgwHQkh8/ZQMgacclvFKsthILzJSptJWXlQCM/sFeaX2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:24Z"
    mac: ENC[AES256_GCM,data:0fcoiXa6oZe8bGasBN8I9IEGE/Bv1S0bbsk1qoTKmb2Dpd66jmL3dvO6+lHuOTqMSw0J5kDn49zl/MlTPDZj7+SgLtLOSPz33snI04lw06rK3nE5v2+54bqHF6ul2NrCTx/ZEUPikeoUxtYJQSdeuI+jEe7Xp92qgNRNVUJZD4U=,iv:ngjECeRdFDyM1itLQxzbp4PQx2lRiHUZhnd0c75eeSI=,tag:sZlsDQufE7ICP012LqGtNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
