apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:2WGjirXJ6hGVU9yzTXyFog==,iv:wsnrlDbIEn4Z3LUMzEeEywP4+bvrLYn1GJHgFfPMoA0=,tag:y6LknT+lcGUtAu4ZR5lksQ==,type:str]
    ceph-secret: ENC[AES256_GCM,data:Fr2o4EF7oaWJn4OVF/uffKN0fjqdnN00bJtEe5EvAx8I0hdCFjPg22FhDq933in34nqfdYZmhb0=,iv:MWli6K7rFsUBATfh1zkDKVUDknNKDL/xvsqqokf7nyk=,tag:yyXQGfYxFxgsK4/GwHQY+w==,type:str]
    ceph-username: ENC[AES256_GCM,data:AcVIueylvb6+S702p11aaadeA4Yp/uEiPjzPMg==,iv:9ZW3sZzmPQVm4TZtsyPJ6PaxIY73dgJ0oAXLbZsXsU0=,tag:AboqPvFVIygB70as5EmNIg==,type:str]
    cluster-name: ENC[AES256_GCM,data:wTo8orkaIPUJycVG6rN6ZuT0TFt0oCev,iv:20UoAFVFc0tg81nW014ftj6aO4uBK/v2VGDqR1s4DDE=,tag:6Ijh+oPo1BVPWCKxbdtg3w==,type:str]
    fsid: ENC[AES256_GCM,data:AmNcIl6DfQiZqmo7yg6Ktq1R1GczNm/FUoupmPaoJKX2O+Y36P8sPlTtsOyEhZcX,iv:r18TeC/6BkEkJJrPAQmc0wn0f2WIpNBjMoVicXKPqnQ=,tag:MfG66F2Jz4sZtWTqEnhJtg==,type:str]
    mon-secret: ENC[AES256_GCM,data:Wk+/l7bESDsVFspqLRST4Q==,iv:CEpD/k4sFRzG5dxcCTDbAfBGSEA+Xq3mousQ/4fbPU0=,tag:mkke4HDH11+7N3opD6qBJQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    data: ENC[AES256_GCM,data:qN5YO/lJ28iPJZ7uzQ/04MEtGwhCCOGABEU=,iv:/H2Wf+7EXRORrh4E0LqKDQMUJDn4KfWj8dTtFNTWWlk=,tag:yoqqZ+ivvEYnsuK238CShA==,type:str]
    mapping: ENC[AES256_GCM,data:UAE=,iv:fDpmmWnI7T2f6L4WhFgNeByLreCmoer7CHJxZHU56fM=,tag:gsFVwGonPNr9dWC+w7czNg==,type:str]
    maxMonId: ENC[AES256_GCM,data:MQ==,iv:7LlUw93MurVY06VTW0CBC+mEj5KmcK1iFJRUvEFGquA=,tag:JEM2eGDbOzsOH3xnXNCZuw==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: rook-ceph-mon-endpoints
    namespace: rook-ceph
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:ld8/j80zxYSdljziULyR1g==,iv:T4JNMwI0qCk3Bh6aVFqpjMriu197JP51zp0fZ5n/wDo=,tag:KNAo7roaKYSkAYW+rI7muA==,type:str]
    userKey: ENC[AES256_GCM,data:Whfta8F6c3bIlIkVye68v5zQGTIYKPIMUr0ET2nfw6Ns4EggIZER3O10JKsFqtP2gacMs8mwgG4=,iv:NIrIhCeUD6nf8/jhgXs/4wkN4KMgMUXFRkm44rjpWiY=,tag:kWCeRbDvlyb5ORaLEgTKng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:ArTmuZtoLqR3cIaofb18EdZAvbgG1rVZ12USAw==,iv:7HGQICXzSNz+GPRCpwKzW2Gfae/zPXKENAE7lJoEzvI=,tag:8OHgF/R8+YhOJ9QTdR//nQ==,type:str]
    userKey: ENC[AES256_GCM,data:+zf5JThkL3InJ3rqu/4eAfGbj5OOnTfsx2KEGXfMGdag57p3pi6/VpHQ1r8vb8ogGzkEEepPgQI=,iv:ieSnqziNhjBqe+Oma4wAxEB3wDC0+gUhqh5x4bM/fn0=,tag:CyagDD6JqhIWsmdOqln4hA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:558P0dz4gtVCdLzKq993s8xJ6M8=,iv:/hsU6lsaM9sBXu2yOVHJ7LcBk5AXRZXriVBi80KlyXg=,tag:L2NhlPBSMXnnb1ugs3KlSg==,type:str]
    adminKey: ENC[AES256_GCM,data:vSD1ZujCa/h+kquUaqQzc7AD5FkGGIx8HtTNEfLKdgcdGGWE3fn7LK3yk8Ul9JjmQYrDqBpWGSM=,iv:RFpwKXHf3oDWg7tYy1Y+Rh3xgNKfz/3p8VMuLYIudhE=,tag:z9esPGtBYvmml4vwAT7BDQ==,type:str]
    userID: ENC[AES256_GCM,data:5n2RFPdv4JIIPHy40WCWbZOhuCk=,iv:opjl/Rrd7G8miODit9Bp3jH4bLCD+bSN7ffOfs6A5H0=,tag:6CVuwq2JSwaGZPFOWSbCTw==,type:str]
    userKey: ENC[AES256_GCM,data:WdfFL4yWVgZ9o+KzPgdnxP6uJIYx2RKlG7HitBdTxhCn7C+fCgjDtesNYYjEBtE88hfoOWixfzI=,iv:u8pIlgr54Fhvvf0PWVyvU8gN3BLwu7KqSxzeE04lOtg=,tag:ZLKx7SOGUfv2uqdXMBf3Ag==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:ogXnt2BysKxUcJy19TLzBITxj/QgeYSga8tHtFo2spY=,iv:KHzC55CPqo8dt7KacTl9PEDMuJXxZyqZY/2dYdVsPGY=,tag:iGojNTYUQ+a3IYe9DM/kQA==,type:str]
    adminKey: ENC[AES256_GCM,data:XHuG5VtC+bPBKIAwchSk4r1Rrbvl65rW0OkMUu79yBJuRNkaULYqU1A8nLM2E2BCnulN27stO7M=,iv:RslmPP+ROBujLZb1BLBEYBkzx/W+2ZHXXTuyjKzhkaY=,tag:28yxd5yCC6RbZoQeAzyNsg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
data:
    accessKey: ENC[AES256_GCM,data:YYosMk347ld8zFIo18HrhT+CeVcXC4Tot6InzA==,iv:2flT/ytSc8cx4dq4qvJSiDRySh6AiFzCOAk9qIGUwo8=,tag:M6fyDT8KeuTsiG1gWEpfFA==,type:str]
    secretKey: ENC[AES256_GCM,data:alAgHhMdympU14FgNKsTbjrkQTKMzwY0EKVdeJFpMhFrqBqJU3jisVToIyiMTZNSqXy71xk1ugw=,iv:fuC/xA215A15h8Zy1kBp0feeV88XqilpCKw5EU/OePc=,tag:jXycjwm2945abfaYU6FgZg==,type:str]
metadata:
    name: rgw-admin-ops-user
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:24Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFILV1EugZ3gF/7y68AwFdWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPle2VbgNxPujj2QVAgEQgDuCk1UnH0vG++hzLtEEODlvV6ZBfjCqEIMDFT2QCsv6Z+F4gW95Kr+PwtP76HXGJezAlItV81oLtAKenQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTZpejljMHByYjVHVTda
            azk1YVlQRFVOeGpJNVl1c2ZpSk9KUjltM1ZVCm5QcEFZVnh3V0oreGVTaC9nbWJh
            NTdoRVhUYS9ub2p0Rk1nanVFblNnejQKLS0tIGVXTDlxMDhVakZocnFISlhodytt
            RGQvRllVdkVmclhxVmVTSHdPd2FsTmsK1npeGqJhitiBLk3dfZPcJsPZzoj5yTzX
            jDSny5tMR5N1N/UnS7cwfC95g8+Huqfl3CqLXKI53NQnr0ThXCjOkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:25Z"
    mac: ENC[AES256_GCM,data:w3i2zsVVRKpaQHzToqo2sqwCRHWLpPkGsmeoe9DFEIkhpXTLcz7YZyr7DPYIuUaj2XQPDDLwdXYKvF/A8wB1qjqRWacGSe1qRqkiwUBMBjJ0bNICS5NkUY4Kt1d+rHvFjsvi4IbCBkRsRdzBueObiNVL/C05QSP4f1lJArSt2qI=,iv:t0/AMDiVvEcQtnNpSI16ECmEvowFgwNncsM+ExFZUeE=,tag:4CvoPI+b38Y7JCH4gVmB8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
