---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-hdd-subvolume-qbit
  namespace: media
  labels:
    backup: "false"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "cephfs"
  resources:
    requests:
      storage: 200T
  volumeMode: Filesystem
  # volumeName should be same as PV name
  volumeName: cephfs-hdd-subvolume-qbit
