---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5@sha256:30dffe7ad04ea0e39db0b50c0bd5e79362f99f7ff6b250526d2f389b58d96f14

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    initContainers:
      copy-config:
        image: ghcr.io/onedr0p/alpine:3.18.4@sha256:a45f246424c791487a44ba5cbe5720ae5318813dce3924c0e04d943e0fd0996d
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            for f in /data/configfiles/*; do
              filename=$(basename $f)
              envsubst < $f > /data/config/$filename;
            done
        # env:
        #   WIREGUARD_PORT:
        #     valueFrom:
        #       secretKeyRef:
        #         name: qbittorrent-secret
        #         key: WIREGUARD_PORT
        volumeMounts:
          - name: config
            mountPath: /data/config
          - name: configfiles
            mountPath: /data/configfiles

    env:
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.bjw-s.dev/css/base/qbittorrent/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &internalHost "qbittorrent.tnwks.local"
            paths:
              - path: /

    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-configmap
        mountPath: "-"

      media:
        enabled: true
        existingClaim: cephfs-hdd-subvolume-qbit
        mountPath: /data/media

    resources:
      requests:
        cpu: 49m
        memory: 1222Mi
      limits:
        memory: 1222Mi

    volumeClaimTemplates:
      - name: data
        mountPath: /config/qBittorrent/data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool
