# iVPN WireGuard credentials for the gluetun sidecar.
# Server: us-sea-us-wa2 (Seattle, WA)
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-vpn-secret
    namespace: media
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Knlvt8DnpA3WzIZsdLYyy//Sm0+v4lyJqYgxqGMoBqT+kh0sMB7eL7kKYz4=,iv:6oM9rW8n7ACN4ew9ICWu0BVf3HO1beZPxq00FtdBpn0=,tag:RYwwOEjSftC8bErS/mi06w==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:Rmr1oVGQTfjpq/0NUncA8Qax5m+KrdnEkdaM/okP9ZPkozNkX9SmB9lJYR8=,iv:9h4ot4gm5Qq8NExJ27jWfiyodwO1bjNbJrHFMgWki3E=,tag:0nLmHn6tjtqRGYmtRTKKOg==,type:str]
    WIREGUARD_PRESHARED_KEY: ""
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:+J8Otlok7n7qysseOTTPzg==,iv:90sRfyXlnhp2TdceTjhDbdXYaepx2KqohinrKqjyAx4=,tag:LTsmQWCl4+qT4x1d40ITeg==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:9qUMvaY+wyABpMxr,iv:4gUuGVNMsPTtd25RTw94dAQPowL0F+IWMy9I+MDnxDM=,tag:CPUvPlvk/3XifFzeOgz+yg==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:BbtiWw==,iv:yWX3NMQxpZp9w7FaR3S2Y8litvA4J8DyVk6VTThmOg8=,tag:XaTdMg1qmOmly/pE3P7WtQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-25T03:35:53Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHraM6gZGkLAOfaJa8wcnnMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZpaR9h4mxvYAngyIAgEQgDssUrsdUqKW9Gihk18tCaI33WQs0yyfx9doakektxJScoPWICeJBBqe0zu0xLn9Xd5tVSEV8J5rDISo/w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMHJTa3pCeHZObGdEMG9P
            Zk5KMis3d2d1Z0RMQ1RVazZvbDhBMjZoRENBCmxNZ3VObkh2Ui8wRE5CZW1XSUlU
            azh1bzFPOXdrWE9veTB0ejhuNXhXMEEKLS0tIENvYmpPbW1EeWV2c3JlejRTUUJG
            K2xUWWFLWDVEb0hOSHBudmR3MEJaZzQKz2xB0UhU7NLC8HpI7u5/ZsHK2ReXntzr
            2U9BNteoauxDOLKlsAT6ezcF9RSgsO9VOys6nXE0PiZpxRvO0e5/ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNVhLVTRqeU1tR3J4RFRU
            Rjh0eXBUQk5vSEFpMjYxeXZhTVNma3pOd0NNCjFTRW5wUm9RR0krZGtjQ2xocEdv
            RElsZXZheHQvTW1ub1FTWmlOWk5YNGcKLS0tIDBDWERqREY4R250NEtUS3RTK0py
            SlZkMkp1NEFXOW5SUHgrZmJrRTd3bkkKdeOyFQQjLsEQ/LFwRsL7t2sfrmgWcLhQ
            fZZ4YPQcGcX/syLLsz4Hr52MdY2UFbq5cG6QSzgxdnCGv7pyxUjj9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Nm43U0VldlRFS2ZlUXdK
            RmZ3cDNhOFE3OGlsVklkZEVPamlYU3orRWxzCjV1VDl4c1hpYmNneU50bmU3bHN0
            TkMxajdsdmdXWFRJMm9UV3A1MFBodWsKLS0tIG51ZzM1Vlp0R3cyNWQza1pYMHVY
            QmJvMU0vd0dQSUZMazU3NTR5Z0hEQWsKtLpU/SnZJRLQYU/NxM3JcOaLhMUKpVxJ
            Poabn5JtgLgUdGwgD8IzbNOqM8ziW6tvuVWnEIuDSB07i0q1V2ep3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T03:35:54Z"
    mac: ENC[AES256_GCM,data:xg6isXJGcuTwkwRJ9VTeJbaN2BuB0EOZndllHDg2IZycpG4WWkJ8WZ4aYINYkSDPa/PkbYNm9lpQXEgtzRk8db0tDDTlQB6iX8LmY5amTkO0nYweY+5Ml2AB0VonHaqZ5G+ykHPbyx9UHBR5uXNXyDihu0IYODA9KxA9RLYAyDI=,iv:ZfxoKw0YrqDeH8y4MxNfY/W4C32brFfKQ0KIASJ1s68=,tag:LeByOcJTymtuSUVmXPFI9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
