---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      recyclarr:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: ${STORAGE_CLASS_DEFAULT}
              globalMounts:
                - path: /config
        initContainers:
          01-init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.6.0
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            resources:
              requests:
                cpu: 5m
                memory: 360M
              limits:
                memory: 360M
    persistence:
      config-file:
        type: configMap
        name: recyclarr-configmap
        advancedMounts:
          recyclarr:
            01-init-config:
              - path: /tmp/config
