---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    initContainers:
      01-init-config:
        image: public.ecr.aws/docker/library/busybox:latest@sha256:d82f458899c9696cb26a7c02d5568f81c8c8223f8661bb2a7988b269c8b9051e
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"
        volumeMounts:
          - name: config-file
            mountPath: /tmp/config
          - name: config
            mountPath: /config

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 6.0.2

    envFrom:
      - secretRef:
          name: recyclarr-secret

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        mountPath: "-"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 5m
        memory: 360M
      limits:
        memory: 360M

    service:
      main:
        enabled: false

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool
