kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:tVwuqKX8Mb4OT9KPzsyAZ082Ozt/Hpri8FMxMAKUOls=,iv:Kxrm1Ne7N/24VZ+gBBkTvSpzp62mO81qKS+P/mUHIVc=,tag:vegwg1Hy+tjvFFONeEbhNA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:vRne0AQojT9hTE1roxe1pv89UyR2fYW8UNjEV0THHLE=,iv:1S0KQz7ci/ETqjECONxdpJ1y7lTmWyk43MlkUL00pwE=,tag:iLw6H10gtEFnCDKjM+L8qA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:59Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgG2PAK57qV1MF+4ki3G4VcFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3zZ45j883MVEXxjwAgEQgDulWDYrX5NEMUeV+R5AJT61M1/1EMOoieZoMnjORFfvBqMS16me02YvmAa86l7Uxj0V1EyH8fLaQeNOIA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY2p5UFEycjdidFRiK280
            TjB6TmJPRWljdTRUb1REaWhyaHhZOURGZzB3CjdyMWRYVUhkdTFVQWhYaEZKSnRN
            aFRaRERoQkkxeW9oSXp4OGRzeUpFWFUKLS0tIE9DYTBhNlRXbE05RzNsRk4yaEVT
            b3ZFSUk1cVBKNW15alhkWmJRVUY1T2MKQk9T6AYoWITjPD8WUG1Ag0eyLLI1OgPM
            b/OR6DaJlNuLkFXBkxMjiuwOhrTUsmsZ3C/8cq65bspqW9cZIqMCBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:01Z"
    mac: ENC[AES256_GCM,data:0RU55BXhbcs2bAm5HogPA2Tedm5VC/ID2bZ3vBq1ByhzkKUg2O5CMVRZstDgKRqVcvRjVTJiT+8602wA0LKJH131iO57Z2f0PPa2rnmc6uRv3n/vJkdUDd4l9tVes3ojP0JVcpedKEVLYvZPzSwe9a8ZBazFAVeOZ5b3t5naR9o=,iv:T1aOSHi9RF22B1owDpeSNN0ivcVY6MRy7LIzOfYHl7o=,tag:Ed5PY4Q8Zt0EEZfs5IKsYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
