kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:JDrgtCASry9uGiZ/+E1a+ldefdjWr7FC/sE/DmyJ2Yo=,iv:/Z07p1Iz1LxFk0ZL5ZIhIlJmNwpANYcrrJtcMqz45Nc=,tag:Ai21sPyTtRsFJanoREkUxw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:kShxFOa64ceIuSsMXa6mz3+yMQYBr/Z5FZHFSzWbPic=,iv:bNjWLrVu8SLawSPS9SXE3uxplS5rmfMDaUkEj6//Qos=,tag:W0B7BOc4GXnZjQsod8BTYQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:38Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwG6Jrkq2GkAz1O5As8qLTYWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3YeI0ZAh7Rb2YyefAgEQgDtJWvhuk7tbj6FMZODKwCtbMXNRaddk7jcNKeY9ywlaiEMVI4f85xtoFO2ce9fgBYSBuuP2pNOGcLPfBQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dm9BNXEwVWxMaTg0ajRU
            NkZDaGRMdjlxSXlOc3d3QzZBWXJRaWhLM2tFCmNJTnd3Vm5rbERHbWRta1VEenFF
            U1pFZVNkNUl3dnhsUDFweU83TWZSMlUKLS0tIC9vWnluajJsNUFlUUEzQ3hFRmxW
            ZVNjU2p3bnlGNTBjc3ZXaDhQNWppQUUKBUf9juphVmEjZnTbided74IQs/LCPi5r
            wtfeoYVG4ou35b52kerfAl6N8SOOSn36xiTA1L7h93AXTl2WHENAhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:41Z"
    mac: ENC[AES256_GCM,data:AZDZSgIgZFQp6JYRWuhzN8MZ8+l6F7gSsyzd855bf9d3JxekQBQNzK5r96d9e+QD/kDyasvscrPlDvgolS/HFB/q0HNJynPPsCJLGZxwcV3hnkFlfHjZirxuwQ9b3esNWwrtnwub8ixSRW/YDJiOB96AKkwd/n1O+/IpfmXcWso=,iv:PqA53+AHKaqL33qPQNl/Jq9pnyL+hSxW3mr7vdjkziE=,tag:voYGH7t73JvsHGs/aiEu4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
