kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:b+E7k/yx1cWxT3DJen9cqoEpZs++cOmfo7hsLMkixmI=,iv:fNQSLMpZp2zr0Hle50V446Op9/rLqMdd4myC/bwHx2Y=,tag:DJvxOEN6BNzTTTXQXw92Lg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:ppr18g==,iv:t+DTuNeyp7LE62OpJle1p8sxUE69jspvWFU9Wnvn0FM=,tag:wxARtFSMmwYRV7zaxF2Mwg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-03T18:29:58Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwEsV84D+pxNWaA7Xzne8WAFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmvDik6D8G2+Ufp6bAgEQgDvq8b4wq5JY9W1H8yKiMjxhy2EYwEFYHAxCSnlDBeTzSgfiedTRiDrGHGCWfB8A/f7XsxVYP2+c+rYYZw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUENBQ1BpQUN1dGVDV1dp
            Sll1YWdpNnVnV2p2MUM4NFkrcGFmMWNhSW1BCjNMd2xNOVFOWnpheE5VVElEek1G
            VFFzQmUveGpnMHpER21nVFphdVMydkEKLS0tIEowTFVVOHVIdW0vcU9ybjFvL0ZV
            RUNlK0ptOTJvWGEzWEdtTHZDSURsamcKJffCnARWNA5C6tFaWIXfAPxqPHoTNlh2
            jIlbW3wxKOI2SRjpcj8StxwsOm1XQQ8IB3s/CsSSi3rGJmoe8+EnaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T18:29:59Z"
    mac: ENC[AES256_GCM,data:QAriYunV8HAsKaBkEW2Jzrssno1u/P0vZP/9xVi+8t0eCXfgnDE51zK/XWj49cu79R+tpm0vlquNCwJoZSiZC3eU4VMcEwUlqt3/v4P3AzykYFvp8qT/oWYCSqx7LPT5VU3i72BSLWsOPcsqvSjjVYcwb2iMQ8kAjGuoo4EZLm0=,iv:7+ACxuqhroyObWBq+DGO+PMcjEkcUC40urqCkNOqNyA=,tag:v1LVLeiDTGwkVbdrjgMjeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
