kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:rjCBiH5d/JO8grbLzs6qIlhZkLqizYiCtJyDWDwbZWw=,iv:rncmaArShC+v8FooWVd30KpnWCVC0439Fqj5zGMXHw0=,tag:BjL8oUiZKQd1m599F5v2Wg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:urUSaxiwnmCefqrPqCSpp1Ez/+CeayacSzECcMFLwoo=,iv:WvHKA5+p479vy5JSu/2CjR7sC33q1Nel3FA+UWmuuS0=,tag:BJEL+Xp7zP1OaU8bOzV7+g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:33Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQELZcr1uKBU4lVxiYZllTD6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXPrXTLedgYsT8hbLAgEQgDvU7cxxYWOJZ5bimivZ1nfwhIabRzYbkXxXY/ADp7oefcS/hOqhOjB4AixArjwJYjhXCM3nIWdP9/yvXg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQmFTZWNmT3c5V01BQWgx
            Y3RPK2VtL3hpb01XbUJZd3FjYjRlNThLaUhJCjY3cmF0bzIzeTY5SldDMzdQMlVL
            enBLbFlRTDJrYkUyRnp5YVozT1ZIVDgKLS0tIGFOWVdjNGZkZDk4TXJ1T1NQNFhT
            RXlCSmlZQVlpV1I5Sm5scGhhSHV0TzQKirsrZseFMOozxcwVTwf98I3gQpfJH1wJ
            MVkBAKVUtmQWd9wGP5NS9+zSgDbVc89RfVsHxSBJpmsk/ouPVBhoPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRGpxM2ttK0hnQW1BeVRX
            OFBqK1hRaEo3YkdqRWN6Z0w2RW1HNk1DRmhnClVVNTFZYmdxQ1d4ZDQxZ3pVeEhZ
            Y1NJOWJWeXA5SEM0VThEQjFvQkNUZUEKLS0tIEpaSTRKUFhTeUlEbVMwaGxEZDFF
            Z1dDR1l3dFp0aHM0NXN4OE92cFRzZEUKNkKyQ3fxD5z+xpaL+LhkEAMUrOBXf+74
            YGYa3p8VWXB2f2PUgRVZJTVTG45eh/FBbRvSeKU/QjclHFMCIuhkVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:32Z"
    mac: ENC[AES256_GCM,data:FKFiLb1HeHwsCu0FuwWgdqXiFOtOaYzQqBUB25ChhLjrEJcSA1jb1QBvOKq5ikK88gtPbLv4ZxVynlr4mC4W8SCNYvjQbiP9zAv7q05/9I5IGtjimaO9ttvuhjF8T+0QxXm4oHNiQwWU1/JC72WuRoE/SwNtiGnI8pNO/oKU7TY=,iv:CrwhoM00UC+GOJoTWKgyEIHxJOAOh7Uv/4Pkv/4F+Y8=,tag:cPCFwcl+GpjgF6Xks0bobA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
