kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:rjCBiH5d/JO8grbLzs6qIlhZkLqizYiCtJyDWDwbZWw=,iv:rncmaArShC+v8FooWVd30KpnWCVC0439Fqj5zGMXHw0=,tag:BjL8oUiZKQd1m599F5v2Wg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:urUSaxiwnmCefqrPqCSpp1Ez/+CeayacSzECcMFLwoo=,iv:WvHKA5+p479vy5JSu/2CjR7sC33q1Nel3FA+UWmuuS0=,tag:BJEL+Xp7zP1OaU8bOzV7+g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:31Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGfK54pko6ZVRuJFn0V8zleAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuaeLoZTNc8T3TuVdAgEQgDtxiKOLYeTSr9xlvm00q2RZLUTb0hmuFGGxoCEidLKOP3RssyTyCDum5B9S2NRrF8BU+5SmzI1qv6v4Zg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcGhtQzVLMjkxVE5vWWdp
            RDRmakt0M0xhZ0hlcnYwVWNuY1JkcXA0dmt3ClNJQ1F0K29XVmpNa0pxL0k0Sjd0
            UGZ4TFdCNE0reldGRFU3WjlvTXlkcWsKLS0tIHhwTkpyQnZMVGplQ2xKTEJCZ1lW
            dTF2bmNRK2F3eVhuT00xVXZPUTRiQm8KkUnYJv3QoTTjw/aKTbc2GmNGxYixmu/U
            ngj2F5TARTfqWy8MSuoNArMJDkrtzYTibZ5imkPbhOswyMZNSi1tog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:32Z"
    mac: ENC[AES256_GCM,data:FKFiLb1HeHwsCu0FuwWgdqXiFOtOaYzQqBUB25ChhLjrEJcSA1jb1QBvOKq5ikK88gtPbLv4ZxVynlr4mC4W8SCNYvjQbiP9zAv7q05/9I5IGtjimaO9ttvuhjF8T+0QxXm4oHNiQwWU1/JC72WuRoE/SwNtiGnI8pNO/oKU7TY=,iv:CrwhoM00UC+GOJoTWKgyEIHxJOAOh7Uv/4Pkv/4F+Y8=,tag:cPCFwcl+GpjgF6Xks0bobA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
