kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:R5QL7S/CYAkn5AQ4okv7tW141B+NpZbJbnngWFNyx1c=,iv:+1V6CJ0PSwwyP34hltajhCcsEYIugNafKu/QPRmdZOI=,tag:TLG0z/VZpltBDsrAVXAAgQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:kuIP4alV4kT/DnnOtbRGxSG2vwgdnM/56UdadxYWIkA=,iv:2KAJtttdp2C0MZx29vUHthw7eX0/RWhA6mndl0AHzZE=,tag:urO1lGqWuSdstiR++wAMjQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFczT8S1FwGnTEzLZ9RalKiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBmJFWJoFA5PxjUfuAgEQgDttDFxH2frF2TNi9GOeqIxrim5edUGwateJr4FhdKkoBfjG6XnCDY3ugwMWECkBKrO6WNa+7Vv21vUrVg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2NNcy8vREI0OGdhbjk0
            YjFTWlpvYlhMU2hsOTdEOVljKzQ5ckREWUZvCmxwQ1JXZitKOERLTFVoN2tBR1h0
            VWtEdFJENGdsTEkzUEZqK3RlWVd2L1EKLS0tIEhRSnVZOHc5cVFDeXJTYmVEaDZu
            eEpIdG1xOTZTYTBvWXA0UW5WNnh1TEUKaw3Di1xb9RnYXeiiguwQZluil5+AHG6k
            wCp7GN/MukSSq0wcZJYHJkqlWeuYfjv3dX/1pOoKR5rD4OA7YIYgrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:26Z"
    mac: ENC[AES256_GCM,data:ZmTMeh93F3bd97Vkzh3pxLJealjxJW4NzVG4Y2jFnnJYvPqakF1XvECy09yl2Gzn+CVHxfwpcf/D3NGUiwyBbqZhPKWFAgEjoYTL61bYP4rAzOe76tsve51HliUFg9mfOEY+fRZ27BiwxN30QiSOimnRAYscXgkXPxbu7luKv6k=,iv:xnZNTCQko+TQfRG5iDOVKFc5i+xfj6603xLA4IlSd7g=,tag:zfMONMUmcbrk8G7cJOeL6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
