apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:A0+Aga+DNkHqPHtTKw8OW2pFXuvTK5+C,iv:NSi7QUm4Qs/M8mcmouAfxGPceP/qCAsxN3WHzHXEqjs=,tag:A5nNdee8I68TnvRUH6f2DA==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:9rzDG2T/IucwmaM=,iv:1rcr0z21C+SerR4wFRbnswTNhKqOT7EAa7/GlERdLQ8=,tag:EwJQIJcBbHR3P8mce9GT1g==,type:str]
    #ENC[AES256_GCM,data:ZJPpTcQFuSHzj61iBNOK/inb75kVHFrfdVluwybroGvIn8+eTY2fzK1DeM1z8UIO7g==,iv:A5FiVnOspHmoHMp0um3oW6RDvuWfzhgDbZkqsFLCTU8=,tag:4GwNnTXORvqpqemA86C2zg==,type:comment]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:w5WgW7lwdERZeCgtVFXBRrWeIQhPk21riS+6emH0qR0AAdJwW6DVhIFKaNcSw/0=,iv:v9H0SqVBSE0AL1d3FhwKasOZsMjUgFNWlPJu70gWLks=,tag:jFm3BjYvGPNL7vIBsUIdPw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:XK1GnlU0WWhajSbrFsIgAksE0CyBYFq+LXV6XTvsu9nJ4yj8gIgmYPnDV1giryJ5r79r,iv:0aBj0tVVOMVNtIHu5GA7GEsVyBnzByZtsITBe/Zq0vE=,tag:2P9FmA279hi+uZ5QoEvbuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:02Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGxqXN7/ExssBwu2vDEC53xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMop3bYWEOGwwEAxOsAgEQgDtEUMnky/aZaGZqJXENci5ZZPY2xAIEje2QlvpJC2DnhO81xu90B93E0iFSIvysMfX47cCXtiT7rWugDA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZElvZnRvTU92eFBxa0NP
            YldHT3pRWEEzODVWQXI3djc3ME9jU0krTTJZCmhuMHV3RFRlKzZJSzhYZGR2VGZw
            aGluTk9zdmI0S3g0QVFKa1Z5YmZXZlUKLS0tIC93dEFUdC9iMzRFQzdyMUlrbktK
            ckZLemp0SnZKMlIzdWhzYUF5Zjl4OGsKmmiL+3WQT7fKd/ftgrilXLk2uWepJWPJ
            Ug7IDSLo/NWiqQTIJqy0wXo8esIMyrGwtOAET/UoQ8diuv8zzZvA9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T04:32:55Z"
    mac: ENC[AES256_GCM,data:PzCv25TwqNdC93HX6zH64kB9DO61LX0ZCN8wvao8gyp00kvJ5B002o2RAuwU2qY7WWr/Z0vlpqq6o14OAu2/wC9nXaAfwg4Ags8BI4rsiXhJuFBgz6/qdvuNx+eS+PKxr5hEw/Yeoe1xhAgXHy+RyVQKrb33LFAeg+Wb3LLYg4w=,iv:9/W4R8AGF3wEYQa+F25y7cqmqppfklvRKj4VZLWmFy0=,tag:pbXJIc/QI3pkDT8ul8kXPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
