apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:oSmrYXIn3P6znKul2Rz0eZ+lPpvQUIgM,iv:GskeHkoAHswLNAsrDw7f0YJAR5E6nUcy5BnLSGZw1m8=,tag:Zqh6kFGSwjYrDhuIsqfqFA==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:rBkEM2Z0pnzj9GM=,iv:wmXSM9n4oWLGauoDJszm59xv1UjbWImwx3D/ttyG/IY=,tag:RGsdznhMuy7oyhoywE7VTA==,type:str]
    #ENC[AES256_GCM,data:QKh432Ek5JSqEhEzEmuCwv2UWV0Dm8UMPdsiVUy8PoaYUJjZtofo8eXYWHH9i1zNZhg=,iv:T/B8vzWZ8rHESdRRq8Az5vNxwxM3PFUgl0AMmHQTSKY=,tag:WBAYtNUOWWyucC4xaLQ/Cg==,type:comment]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:b8iB41kaAk5G5xMGMm66f1CdWjO5MSLEh/sKCyqA7nlRM4FQ1wxWQrZbZ2wpYp4=,iv:VuuvwULrVOUuqd6IL1GN9KxiJs8R2iUkiM1m/s/i20s=,tag:2kqgwyFNX882vD7V7nRvpg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:8ly072Cwzfdm7W7sI84rM1faOjNsbLUBPltqrHNW7bTGOokJ6YfzX8OoJ6TPSA5LNRkf,iv:MCIhO2alifzMgi7GKNIcEJqy25uqdfDWWl/HjPLG9OY=,tag:z5YBHeQCdW2EVqHg+TgUwQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:46Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFvYQWNvtCm9BLZn9K9ZipMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3vjGRQC2dvD0RsJJAgEQgDvAs5encbwmhmpllJ1wHgOSgRU5zRlFv7i7hdR7aIQS5nY+AGHxfYdRfTeisV48MjVio37EeKu6AqJACw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWlkY1dhL3FCdnJwUDhD
            UzhVSmJtdGtWcGpHMHZZTDl3Y2xGdE81ZGhJCmxWVTBaUFFrZWw2ZTJYQ1BRNDZw
            MWtEMWpvTWpWeERiN3BLdVdEVWZSVW8KLS0tIG9odWRVRE1EYUh6YnAxM1YwRnBU
            Nm1RWi9CL21YV3o4K1c0bzI0M0tsV0UK62/ktgidbW7on5EyUFj1AuNjDufPwfIS
            Re22tN8RZHYf6GSEBm7/NIkRSxYJcm7lk1PUGMkpNEEZF4cVoIWYUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVDZLNVNHNkNGb2g4bGpG
            MVBLSUpEaW5NUHBuWjhrME0wRzNZNTFZV2hnCjRLMk8yMm9KVHcyYzZUQVpka3N5
            bXEwYnBBYlVsK3Nla2RBWGZIQVdwMEkKLS0tIEQzWTNnN2JUSHpCSEQ1SEM4b09o
            UWlNWnhWYkwwMjRkczlpRzFWNllIS1UKu09tUfbiQTYPn8qqmqsMVF0XfxujTCSI
            SkaJordLke+btNYtk7kBbYulaEqTwQ2FTzjN44bTAH43XjM6jofqoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T20:49:09Z"
    mac: ENC[AES256_GCM,data:cMQbdb8/2VkXin8Hd+dGotFn6OA8GgZEGXwzoLCEKUvVCID6q2euVDBkuWrxFUQrb7fP0U/OtmEJq+JsWQAeVGSvX8+/xSplPv0tx/3vKwML6+LmgVK0gV1UE9CjYspT4hf/J8bx1dlWfi5Kp3GXkvFCY1ZgreXGgG6J7zaecI4=,iv:xirv+S65aXBEbQao8N5Y2uf/q4lGroXtN3gZ3SGk684=,tag:U57XopC77I0GyZiQ4tRTKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
