apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:+nLaVxj30dwbXrVPq40NlfiwGzNS5XSM,iv:s4cGmR9Z3VX48vlG8+bNDT32R0JOfpX2CsE40L/1qeE=,tag:PAAsCPt+Snn49KV6e3OyBQ==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:N4pUNbDfOA==,iv:Re7TqZhdyEW6ujO2SfV3txOK9AIukgr0ndxz36KvW/c=,tag:okoedAIlz6F5dl6HVOwgdg==,type:str]
    #ENC[AES256_GCM,data:qC5swKdBVa6OuUcqpu++jA9w4Hc7RaIm9hlTvEoX5Jbsf5sPm8DqHqVoflcLuHmNOg==,iv:gBOPRLBUgbidHcdqiTY2pzeZYhOhu6ughLdksV8ETsA=,tag:U4pTnkKAXXWauHAVg3kZUA==,type:comment]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:ZfE5qbC4SivHHolln3Lu/UEYV1PgpNBzjE9/WMPueoVE0FdRsTKoj6+T,iv:ksvX6rMhe7QtPLm0Bi+FihTqDMJRS2u1PreEY1dmDO4=,tag:XknM9K7yspPejRnryvrYBQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:43xPaICtIpt1YqsOqwhEx61/G55fFrgOJy0zsorWl9U56lmYkgEP5fuwxYPQIw+vhBMV,iv:QtRzzhOaHhwhM6+gesTMkB7Ztoogo0SpcJc1vSFMfQc=,tag:OIc4jVoDEZnjKLFvPiKRuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:39Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQG9bUy0pvyr+tab1c0omWURAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMO/FjtutnRj9bpeG9AgEQgDujm80QiOHR3ZZm51u/6c0jvbO1poClBOIvUwoPBQEF9pIbyHG1UweCYjSKVhr6MHsZ3b+zu/RtOasHXw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUFnRnowUkh1NEozTmpG
            VnhMbGRoWHd1NVcwOFlQaVVoOGFXSFpGYTNjCmxaRzZ3VDg3eWd5ejFzekZPNExk
            WmY0aGgzSXhEakd6QUYvZm90dFdFQ2sKLS0tIHBEQzlaRE1IUWNFMjhHdnlNZnRO
            UndiU1ZOWGY5ZzZMbVpVbXBQRFY0S0UKb01zE5X9ReI5cB1gtJ7F2bnOi8kpzbxf
            9nZ4lZ9H51sw+oecy9Kjzdtbr4cZQDaK3WGLufI40oZE+cFxdpnq+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T21:25:24Z"
    mac: ENC[AES256_GCM,data:3Lx3ioplgGfFN3K7DDF1H/YnIwjZZu2Luz4oD2wLxvI/5OuwWzGF41jYPGuVAhwnFeB9YS8vA2thiucuV7drAkzQNsVRm7XTmgPPwk9qyGzDtNGamwlIe8+x45KTr6OgUKQuvYtfwl7haIqTHuyc6M9snoB0syuQDuu174WfYBc=,iv:au3pv+6/X19aGVoeD329wq+AQb09cUIK6j4F73ubbc8=,tag:Xg7tnY1xdj7QrOwBgmsdZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
