apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:+nLaVxj30dwbXrVPq40NlfiwGzNS5XSM,iv:s4cGmR9Z3VX48vlG8+bNDT32R0JOfpX2CsE40L/1qeE=,tag:PAAsCPt+Snn49KV6e3OyBQ==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:N4pUNbDfOA==,iv:Re7TqZhdyEW6ujO2SfV3txOK9AIukgr0ndxz36KvW/c=,tag:okoedAIlz6F5dl6HVOwgdg==,type:str]
    MATRIX_BOT_PASSWORD: ENC[AES256_GCM,data:Nateh/sLAQ+YR7DiL0/AymMM5x5jMt3WJj3PjA==,iv:FalVY5Jdyww2FJUaRpUNWn8fynPKWA9H+WyM34sJsmE=,tag:4/4eJiu/zfgq0sbQTOIT8A==,type:str]
    #ENC[AES256_GCM,data:ymLAEG/9Sp6311GoOs9HlAc2EJogff7vtYYoBapt27ChmT/SpMIG43euxia2pydhTaHiIZc1OfPBTU8uzfGn,iv:htNK0xufEsUjqcvddXKo0Te9akgn4/0Z8aSUTZ+yobI=,tag:zaRtpQnsfAZl9Defg8Fvnw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:43xPaICtIpt1YqsOqwhEx61/G55fFrgOJy0zsorWl9U56lmYkgEP5fuwxYPQIw+vhBMV,iv:QtRzzhOaHhwhM6+gesTMkB7Ztoogo0SpcJc1vSFMfQc=,tag:OIc4jVoDEZnjKLFvPiKRuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:39Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQG9bUy0pvyr+tab1c0omWURAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMO/FjtutnRj9bpeG9AgEQgDujm80QiOHR3ZZm51u/6c0jvbO1poClBOIvUwoPBQEF9pIbyHG1UweCYjSKVhr6MHsZ3b+zu/RtOasHXw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeUFnRnowUkh1NEozTmpG
            VnhMbGRoWHd1NVcwOFlQaVVoOGFXSFpGYTNjCmxaRzZ3VDg3eWd5ejFzekZPNExk
            WmY0aGgzSXhEakd6QUYvZm90dFdFQ2sKLS0tIHBEQzlaRE1IUWNFMjhHdnlNZnRO
            UndiU1ZOWGY5ZzZMbVpVbXBQRFY0S0UKb01zE5X9ReI5cB1gtJ7F2bnOi8kpzbxf
            9nZ4lZ9H51sw+oecy9Kjzdtbr4cZQDaK3WGLufI40oZE+cFxdpnq+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T21:22:41Z"
    mac: ENC[AES256_GCM,data:mU/8ZF242HtXNM0ilHFIgNsRriY4umzn4qvTy9GeJjgjWwTch99hlrZpC6HV+0YGD297ohS8h4I+qcfSwl7XxrcX9tUcnzlhgez6lFSJqvFwTrfJcbrRyWlG9OUWzTo5EUmycUuLUMDXHHtbxNFEe3Ji988oJWySd+14/crIXYo=,iv:GBdHlaeTCXvgMhQKvML00JEGQifo4pqFdY0leApvHHE=,tag:u7pXyk4f4ck7foVdzzNAiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
