apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:A0+Aga+DNkHqPHtTKw8OW2pFXuvTK5+C,iv:NSi7QUm4Qs/M8mcmouAfxGPceP/qCAsxN3WHzHXEqjs=,tag:A5nNdee8I68TnvRUH6f2DA==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:9rzDG2T/IucwmaM=,iv:1rcr0z21C+SerR4wFRbnswTNhKqOT7EAa7/GlERdLQ8=,tag:EwJQIJcBbHR3P8mce9GT1g==,type:str]
    MATRIX_BOT_PASSWORD: ENC[AES256_GCM,data:yd9JqGL0Nvf6OoR5lB/CbySm9WqW9PVmZE/i/g==,iv:glkhV4I5xbtxS2OkQ0bAVAtnfFSXpqVr79vKUSUBZfI=,tag:UXtm5XIcTXOLZJaaipW7Vw==,type:str]
    #ENC[AES256_GCM,data:vSTzrK4TGkYXEFiRRhRU8ksXO66yqgKnmxsDgdDtRr2BQsqLkDvklHHyv5yAaKL+CPAWvRcDFuyGwKEBBvdo,iv:ILaOsWa+ZU5yFlM8Y2vJB+ckX3L0iiPdugvOAafXPxo=,tag:5g5RIavRZ01IW12rVP5pVA==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:XK1GnlU0WWhajSbrFsIgAksE0CyBYFq+LXV6XTvsu9nJ4yj8gIgmYPnDV1giryJ5r79r,iv:0aBj0tVVOMVNtIHu5GA7GEsVyBnzByZtsITBe/Zq0vE=,tag:2P9FmA279hi+uZ5QoEvbuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:02Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGxqXN7/ExssBwu2vDEC53xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMop3bYWEOGwwEAxOsAgEQgDtEUMnky/aZaGZqJXENci5ZZPY2xAIEje2QlvpJC2DnhO81xu90B93E0iFSIvysMfX47cCXtiT7rWugDA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZElvZnRvTU92eFBxa0NP
            YldHT3pRWEEzODVWQXI3djc3ME9jU0krTTJZCmhuMHV3RFRlKzZJSzhYZGR2VGZw
            aGluTk9zdmI0S3g0QVFKa1Z5YmZXZlUKLS0tIC93dEFUdC9iMzRFQzdyMUlrbktK
            ckZLemp0SnZKMlIzdWhzYUF5Zjl4OGsKmmiL+3WQT7fKd/ftgrilXLk2uWepJWPJ
            Ug7IDSLo/NWiqQTIJqy0wXo8esIMyrGwtOAET/UoQ8diuv8zzZvA9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T03:50:30Z"
    mac: ENC[AES256_GCM,data:f2cRVbakKnYTSLY6QO9C/KRiPByl3KKUeG/m8Qt6Kg731VC5tLbvlhewje4fmS3/7d0UC8jr2rozv0QcTDyFbcQPX07yDtAk/qVxmjQ/5Qw3fPisw2ib2OuVpWEOwVOooB2s12mWfpe1E4Dnuk48dRq5YD4lNswsXjpfOEdDPBU=,iv:z2Z3Kd7pC6UeOl5WJsdVhXWH7qtIlJk6Ca1tOPfodBg=,tag:ngB2jZ+DDEr1CtW51vl5fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
