apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:lMJdmsmBXjKM97aMY0Ki7mBm+Gu1Er81,iv:WlkuqgUZxMhBZrwSwWmSu1gm3owgUyAbs/qTJ5n8Hrc=,tag:DKMT3mCvqz8YTNrDRAKTMw==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:BkCmBXTF9g==,iv:6d5wGNFmbin5UWMPxU2oW0GcmBKpuMycjuPAm+j9nHA=,tag:Ke/M3lRz3lh555T2wMbvlw==,type:str]
    MATRIX_BOT_PASSWORD: ENC[AES256_GCM,data:w/rl6Q1KTQN/gP8brt0XK/fpHKxY1IKB1kjQag==,iv:/4TDMl9mb5j/oFIQoYv13je5p09NMJj0nkL+VK7vmZo=,tag:fuNYRKHuhTauwgzFV2+PFQ==,type:str]
    MATRIX_ACCESS_TOKEN: null
    OPENAI_API_KEY: ENC[AES256_GCM,data:LxZ2ZDbiJQZ2z5QlG42Qs7JKLhT03F4pE5JzlmDhrcmICOwUK1hvJcnHS07YssOFqLB1,iv:x/Xx9fHen5Hj9QgTk3Vh2gS9oLIDvL/gYqaRRrKHUdw=,tag:dUzKD3V9PFEskgKf/5+30A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-08-20T23:28:53Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGilCuLVxSGO9vWxoBNOnzEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKvIaqLvhEwco3+hRAgEQgDuTEkImW2q4eVo0JQfStUAUrafXkU4gIYzgnyf7txAT0xca9p4NrsvhRa3NHW4DKy1VBqnUq/fTg37MZQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybGRXa1ZKejlYY09GUUx1
            ZFhDT1VXVUVXcVJVbzg1Z1YzRWo5TFhhS3lNCmFUbXhWc3J4Y29FN2JOenR0cmJP
            OUl4M1RWZGkxVzNpR2JWZkE0bWZOQ00KLS0tIDJVSXFEYTBJNTNpS2c1dDkvQzBO
            cXkyMWNrWkRMd3ZQZVJXcG1qS1RnTEkKmVc1bab94ekUHICj+qHVUCg0LAdDuya6
            0Mm0+YTpJKRbu4RS9OsSuEXDmfkbE3t5K3gnOWGQn5feQZ+6Ocww4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-21T01:39:19Z"
    mac: ENC[AES256_GCM,data:K5sqw0OFVau6NWr/rFtGbvZDE+L7+RiDgCamG9NsEO87O+scFCEVU/zU6wQQ3WbLO4dXEW3uZd5eieBZfB6XXD2uFL/w4ZOAKK97n/LROswENZ9a5U2flwKnyfIgbbu4ji0lgvm4SnxnG/6INh6zeHDMpVI2LIBTTjrGEdB2c74=,iv:dwLW6MpGbDYWbJojAwEwphJC0SJP39INXl3eB0E952M=,tag:Z7p2SppaRytWSFL1vXdCFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
