apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:A0+Aga+DNkHqPHtTKw8OW2pFXuvTK5+C,iv:NSi7QUm4Qs/M8mcmouAfxGPceP/qCAsxN3WHzHXEqjs=,tag:A5nNdee8I68TnvRUH6f2DA==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:rPIAfUHFmw==,iv:HSLjaeIutewZZvZMFo23uDUut63NZ2yloLhqOITQegg=,tag:R+uLigOZoQw1F5B2v2HjTw==,type:str]
    MATRIX_BOT_PASSWORD: ENC[AES256_GCM,data:i7u+95acfHwSkjv9Ro4eP2zOYRg7nUxBb6ZXbA==,iv:D0PNeOMyzgkumJmeDUGO4S5PbLmOZXdL/PlIy9n5rqM=,tag:zBXKVZ9eMU+VWIqq10GMOw==,type:str]
    #ENC[AES256_GCM,data:cIloowgJJ+yDPcG4FGtK62e0WjQXhUy9Z4BNnoHIxKqLb16BEqylwzLVbJLnTDNZuJMRQKzouLBXypQ7n2u/,iv:qelohlZHxay9euX0f1FIgA2xL+iMFCiN4TGj0Vgy0vQ=,tag:E6F6Cn1fAnSWmW7j9Oe8EQ==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:XK1GnlU0WWhajSbrFsIgAksE0CyBYFq+LXV6XTvsu9nJ4yj8gIgmYPnDV1giryJ5r79r,iv:0aBj0tVVOMVNtIHu5GA7GEsVyBnzByZtsITBe/Zq0vE=,tag:2P9FmA279hi+uZ5QoEvbuw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:02Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGxqXN7/ExssBwu2vDEC53xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMop3bYWEOGwwEAxOsAgEQgDtEUMnky/aZaGZqJXENci5ZZPY2xAIEje2QlvpJC2DnhO81xu90B93E0iFSIvysMfX47cCXtiT7rWugDA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZElvZnRvTU92eFBxa0NP
            YldHT3pRWEEzODVWQXI3djc3ME9jU0krTTJZCmhuMHV3RFRlKzZJSzhYZGR2VGZw
            aGluTk9zdmI0S3g0QVFKa1Z5YmZXZlUKLS0tIC93dEFUdC9iMzRFQzdyMUlrbktK
            ckZLemp0SnZKMlIzdWhzYUF5Zjl4OGsKmmiL+3WQT7fKd/ftgrilXLk2uWepJWPJ
            Ug7IDSLo/NWiqQTIJqy0wXo8esIMyrGwtOAET/UoQ8diuv8zzZvA9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T20:23:52Z"
    mac: ENC[AES256_GCM,data:gy4QOrCZwedLsy/JjbqOcaeEeUiUc3L3KMfXLnFoWibb861C8+/QaOGHRG/h978Q1ZqBJ55C/G2GPe6TbDlh1b2geRWKkUTMdcmJLd+Jb/6dYa4bKQ6CKU/cUCR7+3MaGP801i2IpoZTh3WL93cbsFDYTspNZPnYHaF0Hd7kvBM=,iv:ZCccRBCzhFHZ2n8S8HQttUIOZpns9dPJR+fWP1Jinpw=,tag:9CVJpBWIzXDr9/hZfnp+JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
