kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:FNrNjixZXV+y7cSpLKWNHQyu5/uAeUmZm0hh2MVREHA=,iv:d/Z7KvOkM7sMOlqjOSbdCxqQyZYGDZ7Pb6yNSfT46Y0=,tag:OtROA+ExS08dmM3yaUI4SQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:01Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHGKZPIWQ1ULx9hFJ5tecv+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3KWzKEYfu8w/AuLrAgEQgDtDrw+pybCH37zF+An3Pxo6Pc5bGKnnhZSISxpdzbrwlmuwS0yXMCsU9Sx6lCuPce8WaI896oD/qRjGEA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDlVdUd5YjBzUyt5b2FD
            MWpZN1JhZmFBekJUbWJDWlk3UzhBazFRVENnCnZiTmNmV2REUVhvc0JtTk5NcVll
            MXVRSUdpK1Z3bnVDRFlWSGs5dkNNQ28KLS0tIE1ZNEUwTW5QN3dDMGMrTjFadVJN
            TzNldnZMMDZtRTBTSkcrb2tWUVExS0EKF/UfCIv8XIf3f0UkvHIKWul32dRoDeTc
            oUG+Dk2ohYhAo9us6BbqP+iCaV+/ZFs3UcReO1jDXwbPvdvK553LsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:03Z"
    mac: ENC[AES256_GCM,data:28Asfb2cOg8IPTyI22OeIClWuwm1A/NrPBAuMhKID6fhctmLlwuC7R3Bb4/JgE91dMZU9tTlNSeLNs6BMXXA0Dd1ZiggXKNdCeIZz/KJqmLjOEko81O/KK60+6L4eRTSeAiyDrur2E89BvT8Ktbsxlw5zIdZZaHLOxT1JM1uiSM=,iv:UU2/E+YXoewGM7RCRnkm5ehtid6HwJ1tN+7jneaJrHE=,tag:G37g4ptFY/l85fJ2aYEqFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
