kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:Wku+FAoY45UC2SdQCJuAuPM71mZlXhRBlYXsPw1peJo=,iv:SthPPvA5rzhmwhp4GiPQo3XXYUaWtbrmFG1ujU6Plg4=,tag:aIIH4e6XoTrz34nHKBIkNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:35Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQETzYlOAHBr4nFHZ2od9GpwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5DilGcSsOoehhdrGAgEQgDvkHWyvqf8bb7xhnBSS9cpf+kgRZirmal7Thm8CABs3eldg7o24+SxHEWWxfSBwpuVLgXC9JjEBhUl4Yw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMXM0UEtKeUI0dm54dWpZ
            UWpHRUxMWXlXbGZlYm5veGY1QjMxS1ZZbEFRCitxQkxKeXU2eEpkWm1ZRUs2U1Zm
            TmNkZkw1S1JaeVA0Z2ZHdlNickk0ODgKLS0tIG42QmtoSW9Ua2JrQnBtYjIxbW1s
            a2NZK0N6YkFBUUNtUlFXblpQclJBemsKp7d8Xcri5hi4RonHLx7yhfyq6JcdNxjP
            IksnxlaBjI6OVvK+kjE4xYURCDn3fWEIAwEv9nB7nRaK7hnLP8TZww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekhGb2lpeEQwcHpUWEhC
            bGJvb0NqWERmT05QMUZRd2VLd011SHlNbUg4Cm9xUkdPT081enRTUmtsVFlBbVNB
            WjRYTkNBcnB0c0E3c2VMa29Pd3krR3MKLS0tIFlubzhkcURJQTR2S1JkaXgwVWRC
            azFlTDNlaWlHOXNwWEsySzU4UnZRRWcK9oUATmZNf2QnzNrAkfPaSpHMibDn+89p
            IzgmA1bLIJLoDqtek+JONHHrkNVE59ooQQmeMggyZwk+OxiGJgUf4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNUREY3I3REFMTDF0YUhw
            aDRjcFNnbmtnREJUcHpOZnI1ZExRYk9OWGk4CmFpa3J4d241M1VXUXplMkozczVN
            VnRRbUtsUkxxdTk4VzVLbVp6ZWk0akkKLS0tIDNxeGRTbWp3U0NiNktIaW1VTm96
            SmFpU1REMzhBaFkxSDhpd3E3WVRiblkKAW2Cz3klYGvexaCOiI2tGLJ/wKc0jQY9
            vyZ4N0MB1Kvoo2MloWP8JbeZrGp7oGE4s+CEiDFLnUB2DlEtx1/Xtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:33Z"
    mac: ENC[AES256_GCM,data:hEzcF4wGZ9/j66BAbUkN9cDK76Yj1bTWaytOWYJ+ZdmyHXmU/vdHw2ajU6wWqJXQs1tiVxOkWmZe8jwyz9CEsqaUiigQXnCGYT4bRxClNnVrCvQcAw6KpF5Ny8N9cqDJKs6EZxWjr5Z+FyZR+Wsg4/kf1FMEwNj8mQYdipFgtvw=,iv:V3VKgAwOIkX2210OsWEiCmTbHxSV6pacBnze3++Wy8Y=,tag:I3Ojsq1Q1/Hs6zRTphbHWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
