kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:Wku+FAoY45UC2SdQCJuAuPM71mZlXhRBlYXsPw1peJo=,iv:SthPPvA5rzhmwhp4GiPQo3XXYUaWtbrmFG1ujU6Plg4=,tag:aIIH4e6XoTrz34nHKBIkNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:34Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFEvFCB39pO1M3A/3c8Gh6FAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlwcIWiL5/uAsh4ZnAgEQgDsCioz4thGeHEzUJa/6KsOjeD/PXNtJJfuBd0BJrgFmRmaVdgRpbHrL/BrOKD8xUeBgYqIsdug5S2a0Yg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWVKamgwYUlwTXpMU0dj
            OUZOQXFVZ251RVljR2VvY1FweXBuZFdka3dRCjBZOC9mczF3UCtiMUY4WDlWT1lS
            QlMvTHQwYkVTaGxxK29uTkI5WlA1dFkKLS0tIFF6M2NQbE5vYS9JclkzRjhmU3ZN
            Z05xUUJuTVZJT1FGTGFlRzNTeVBMeGcKUxPtuEPx+p4frto0RoOoIjujUDiozM5F
            XreNYVrz/ifjHNzSVA1Wj/ArxaJZaOfC5wUP8xam4wGVuym5xt6iMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRGxyWDM3UWFHdXlOMC9n
            a3Jhc29RUkt5QXN0K1kyZ3d5SGNPaHJ5cXo0CmhrLzdmcERHS0s1ZlFwM1g5bVE3
            c3haRDRIM0VHM09uSnRKa3BxcHpvY1UKLS0tIHBFT29TVWR1SjRQNXVCZDRTaHBy
            TkMyWFBQV0RwUkplVWt6K0wzMUVtbFUKAn88H96S9eRx14OnfsbUaKxU+ekBXsZ0
            dRdTQCzMf9RuoD0IAiE0kYE5NzYdsFqnqlUanJtHJ14ULGPeNjHMkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:33Z"
    mac: ENC[AES256_GCM,data:hEzcF4wGZ9/j66BAbUkN9cDK76Yj1bTWaytOWYJ+ZdmyHXmU/vdHw2ajU6wWqJXQs1tiVxOkWmZe8jwyz9CEsqaUiigQXnCGYT4bRxClNnVrCvQcAw6KpF5Ny8N9cqDJKs6EZxWjr5Z+FyZR+Wsg4/kf1FMEwNj8mQYdipFgtvw=,iv:V3VKgAwOIkX2210OsWEiCmTbHxSV6pacBnze3++Wy8Y=,tag:I3Ojsq1Q1/Hs6zRTphbHWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
