---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: oom-alert
spec:
  groups:
    - name: oom
      rules:
        - alert: OOMKilled
          annotations:
            summary: Container {{ $labels.container }} of pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was OOM killed
            message: Container {{ $labels.container }} of pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was OOM killed recently
            description: Container {{ $labels.container }} of pod {{ $labels.pod }} in namespace {{ $labels.namespace }} was OOM killed and has restarted within the last hour
          expr: |
            (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1)
            and on(namespace, pod, container)
            (increase(kube_pod_container_status_restarts_total[1h]) > 0)
          for: 5m
          labels:
            severity: critical
