apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ZLsRxXCCvfGupQTpaOHR5r/5ePCmeS7mzrIjC+pX/8fEaprcFIWgiA==,iv:t52l7pQTcg78PYT/np3tnX9bDXMwAPcFXElTxpcXSb0=,tag:5FVa3lQFBa1XDANx6WVM7w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:39Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEJAb9hfBgdVwdRMWIcqAmgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuKHGjrXjlVpq1mt5AgEQgDsUzCsSRqy3aYVrt/mgahEhI0KaxcjRDHqbWFW3N/Pau6zhwqE1q9gOGaE6vKCCNEftU14rWb6wd6V7sw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNk5SVk9FQUI5cjlWNUl4
            SFhqTWhZR25wQTByenNJeEF0NmVrd3lwSlNVCmNENER5UWZmWVpGZGt2MCs5M2JJ
            UHR2ZHNzS0N2ZHZXMisyWm53S3cxd2sKLS0tIHJXSnV6NWRsYXdzWldweVAzUDJG
            U1lCaE80OTgySVNaRzcxNlZxSzAxeUkKcCWitV9WlvrbxUJS0hua/PfJ5/U4lUTh
            5wwDaKlbRKkdhSchA9yaZjt8dCq1Rk3t6/Ln4iJd5es4aLF3jsE8Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRENjNDREL0tqZ1BPT1cv
            dHQvc2c5Wm1ZMEYvSWwwSXREQzJKUS9WRUdZCnFTQi81ZW1NOXZiYnhJYzFVS05X
            bDlGM0lDc2h6cEJLT24zUTNqTlBtZjAKLS0tIGtORmVaeWU3NkI0VzZHd3R2YWt1
            UlJpNGNuU01sQ3pmdlB6TkJpU1BZUlUKA3li/uLkScqqZ/lFrq1akYlzshIKnY6R
            HcFA/S7a3MvAkCtWpAFR6Dp4nlvNcDgO1AXq1rVuokYWL84dR7CxOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:46Z"
    mac: ENC[AES256_GCM,data:+R8C18OjqphTrDrqwXPPj5x05vKhh/SRdgjzVxU9x97x+826zLkaU68LTzQmZm/IFB4vLgqBI2g9Iezr++9+Bp0k/3BtGL3fT2dNPhCZUFyFIl+RPLmxJRZ0OhxIMiVKdG5nMnGpO4rNchPGWeifJFH0G0u8xDf+fpg3XyD3BPw=,iv:BIzRlOAZNbTKbeCW/FtpL78IPDu+tSf2XkDvtcbjBxY=,tag:0+me/P71DR/TEIRvdlyJCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
