apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Bt/qdLnnraFXk1BSCkWO7Lf388Dm0P3aWFYOnA==,iv:KOz8WKwYooPLtUYM5VAk1uzEH5VsP5pYFgbkd9aSrug=,tag:YFpqoUw99IfE1jhWEGRdqw==,type:str]
    api-key: ENC[AES256_GCM,data:OB8o+z1TW8ZDTCE0v3BVUc8PDIuarum0GDN6QUFiB+3nBSBYuw==,iv:LAc19khkK4n+Il3Xul6pTyU0GCPuDgFSSAir+13x9a8=,tag:nOko5UNU9lq/e0sZlxIL4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RUR0QnpFWTE2WkhycG5I
            NUNhRXFpNEdRMFExSHNDeXd5blhpK05malhJCjYxS3BGdFhtSFZWRC9VdThSMklJ
            bFJBL2Fwbkg4bmJ2VGplMlBrUGRCbUUKLS0tIDNoUmNBNWRkTE1Wb1VZZHNoMXBF
            TDhIdW51c3hzV1NhdHUxbWdpcWFIWDQK1q884TXeEAX9iOh0w6jW6sgrGdWFsKcp
            XJpQppa7iVpUiKH+6v5c1iGpF2A/nQrhyQtV5ReokFQhPE8egnKNXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T22:56:18Z"
    mac: ENC[AES256_GCM,data:gFDel4c+VZ8hlvbEwj3cSCTe3WhHgOQ/Svcc9L4zr16rEE6aMwrQs3xsly9DJdWg/hjYioTVgMORPwhQIU/TKZD7grNDcDDVj+E6VLFnxlQ+yB82MCK7Iu1NlaDijru55ZPc4mLaqG73NsmbOrcCQwFBVJLwlPEVVXt+ydl7ngI=,iv:2QV7aFerBjXjtD66pX6PFv2TqnhnpIkotQZLvMi2P64=,tag:9eG1vjpCWzwNKNmgIkSMXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
