apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ZLsRxXCCvfGupQTpaOHR5r/5ePCmeS7mzrIjC+pX/8fEaprcFIWgiA==,iv:t52l7pQTcg78PYT/np3tnX9bDXMwAPcFXElTxpcXSb0=,tag:5FVa3lQFBa1XDANx6WVM7w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:15Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGPDHGAzqAROHhB3LmXmnteAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdTDfY0fcqsV9zoqFAgEQgDt51VgOMVb2XYQ/l2abr/VZs7MJkQt4KL9/uzjSaLpoIjxPFr2P5oMXRoKJ/9JJluRoxvSoFQygk62eQw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOVB1UGNmQTVHbFJNeUdP
            S3BvTkFEZTFKY1ZGR05JQnRrYUVtZXBNS2xZCmJ4VllnWTBXMWtNV1ZsSDRxUUNK
            b1Vpa3RMcHdMWE9HNUtFTHVaV0doQnMKLS0tIG1UOHdaZHBkVVdpTGZkaTZXRll2
            SGE3Y3g5azBkeUpqTzFveDVKYTNKcE0KoXYuFW18XHBfoE0FlDLllkBfM26KU6vi
            s44KFqsgnU0lIPHvZFprWc6GXn8bHX8gA1WHBkUKeeENrS9eABQFeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMblFqcElJTDUyelp4a1hJ
            SFY5MVhXNGw5YmVEOHk5dE1XTTk2YkhVZWdFCkh1Tnc0Qlg3T1JjK3ZtYVFrSy9U
            N0ZPdURGVERNVFphTmlPTzU2bUx0Z28KLS0tIEgrZGNWTXltQmY0bnI4dDVWbjd1
            ZXBNRWhIVWJuNllJcW9rdE9GZ0JyOVUKJC+L312193ZmxxNSRrOMcjWNFkReaJbo
            8HsTbeyf77a6oFLFyvdA3qNewCHJLAfi74AdDPJPjqPvB3UeUp37hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRFNPL2FvVmNyN1owVmpL
            WGEvRExoU0lJczNyUDAxcHYzOUVHTE56QUUwClg0V1VOMko1Y0xXaEZ2K1BjaHBG
            SGFTc21sNjJPR2ZwR0k5Q3FHMVNEUjgKLS0tIC92Zi9tNHREVjBwVUs5L3RMSnBm
            anA4SkI4Vm5rQmQvRDVSSFJ5RGd0VkUKKlfPL4kJLAB3Hw63ma4My910SwpGo92d
            hxahaVt9X/GEV7cQuAnKd6hqnjsCpidoJqNt3rnCdpOD408ba+vlbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:46Z"
    mac: ENC[AES256_GCM,data:+R8C18OjqphTrDrqwXPPj5x05vKhh/SRdgjzVxU9x97x+826zLkaU68LTzQmZm/IFB4vLgqBI2g9Iezr++9+Bp0k/3BtGL3fT2dNPhCZUFyFIl+RPLmxJRZ0OhxIMiVKdG5nMnGpO4rNchPGWeifJFH0G0u8xDf+fpg3XyD3BPw=,iv:BIzRlOAZNbTKbeCW/FtpL78IPDu+tSf2XkDvtcbjBxY=,tag:0+me/P71DR/TEIRvdlyJCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
