---
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: mosquitto.home-automation.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  output_args:
    record: preset-record-ubiquiti

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 2

record:
  enabled: false
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 2
      mode: active_objects

objects:
  track: ["person"]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  streams:
    frigate_groom: rtsp://{FRIGATE_WYZE_RTSP_USERNAME}:{FRIGATE_WYZE_RTSP_PASSWORD}@10.10.91.109/live
    frigate_sv3c_east: rtsp://{FRIGATE_SV3C_EAST_RTSP_USERNAME}:{FRIGATE_SV3C_EAST_RTSP_PASSWORD}@10.10.60.35/11

cameras:
  frigate_wyze:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_groom
          roles: ["detect", "record"]
#        - path: rtsp://localhost:8554/frigate_study_hq
#          roles: ["record"]

    detect:
      width: 1280
      height: 720
      fps: 10

  frigate_sv3c_east:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_sv3c_east
          roles: ["detect", "record"]

    detect:
      width: 1280
      height: 720
      fps: 10


  # frigate_porch:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_porch_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_porch_hq
  #         roles: ["record"]
  #   detect:
  #     width: 960
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       person:
  #         mask:
  #           - 39,445,199,427,198,263,36,228
  #           - 304,218,304,408,198,434,198,262
  #           - 305,411,485,382,615,393,612,335,578,321,574,233,549,118,308,209

  # frigate_driveway:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_driveway_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_driveway_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       person:
  #         mask:
  #           - 822,204,1280,360,1280,0,0,0,0,313

  # frigate_garage:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_garage_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_garage_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1024
  #     height: 576
  #     fps: 10

  # frigate_river:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_river_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_river_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10

  # frigate_study:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_study_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_study_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10

  # frigate_living_room:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_living_room_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_living_room_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1024
  #     height: 576
  #     fps: 10

  # frigate_basement_1:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_basement_1_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_basement_1_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
