---
# yaml-language-server: $schema=http://frigate.tnwks.us/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

mqtt:
  host: mosquitto.home-automation.svc.cluster.local
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  output_args:
    record: preset-record-generic-audio-copy

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 2

record:
  enabled: true
  retain:
    days: 2
    mode: active_objects
  events:
    retain:
      default: 2
      mode: active_objects

objects:
  track: ["person"]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
  streams:
    frigate_wyze_groom: rtsp://{FRIGATE_WYZE_RTSP_USERNAME}:{FRIGATE_WYZE_RTSP_PASSWORD}@10.10.91.109/live
    frigate_wyze_rroom: rtsp://{FRIGATE_WYZE_RTSP_USERNAME}:{FRIGATE_WYZE_RTSP_PASSWORD}@10.10.91.179/live
    frigate_wyze_baby: rtsp://{FRIGATE_WYZE_RTSP_USERNAME}:{FRIGATE_WYZE_RTSP_PASSWORD}@10.10.91.105/live
    frigate_sv3c_east_hq: rtsp://{FRIGATE_SV3C_EAST_RTSP_USERNAME}:{FRIGATE_SV3C_EAST_RTSP_PASSWORD}@10.10.60.35/11
    frigate_sv3c_east_lq: rtsp://{FRIGATE_SV3C_EAST_RTSP_USERNAME}:{FRIGATE_SV3C_EAST_RTSP_PASSWORD}@10.10.60.35/12
    frigate_sv3c_west_hq: rtsp://{FRIGATE_SV3C_WEST_RTSP_USERNAME}:{FRIGATE_SV3C_WEST_RTSP_PASSWORD}@10.10.60.34/11
    frigate_sv3c_west_lq: rtsp://{FRIGATE_SV3C_WEST_RTSP_USERNAME}:{FRIGATE_SV3C_WEST_RTSP_PASSWORD}@10.10.60.34/12
    frigate_reolink_south_hq: rtsp://{FRIGATE_REOLINK_SOUTH_RTSP_USERNAME}:{FRIGATE_REOLINK_SOUTH_RTSP_PASSWORD}@10.10.60.33/
    frigate_reolink_south_lq: rtsp://{FRIGATE_REOLINK_SOUTH_RTSP_USERNAME}:{FRIGATE_REOLINK_SOUTH_RTSP_PASSWORD}@10.10.60.33/h264Preview_01_sub
    frigate_amcrest_kitchen_hq: rtsp://{FRIGATE_AMCREST_KITCHEN_RTSP_USERNAME}:{FRIGATE_AMCREST_KITCHEN_RTSP_PASSWORD}@10.10.60.32/
    frigate_amcrest_kitchen_lq: rtsp://{FRIGATE_AMCREST_KITCHEN_RTSP_USERNAME}:{FRIGATE_AMCREST_KITCHEN_RTSP_PASSWORD}@10.10.60.32/cam/realmonitor?channel=1&subtype=1
    frigate_amcrest_balc_hq: rtsp://{FRIGATE_AMCREST_BALC_RTSP_USERNAME}:{FRIGATE_AMCREST_BALC_RTSP_PASSWORD}@10.10.60.31/
    frigate_amcrest_balc_lq: rtsp://{FRIGATE_AMCREST_BALC_RTSP_USERNAME}:{FRIGATE_AMCREST_BALC_RTSP_PASSWORD}@10.10.60.31/cam/realmonitor?channel=1&subtype=1
    frigate_loryta_pool_hq: rtsp://{FRIGATE_LORYTA_POOL_RTSP_USERNAME}:{FRIGATE_LORYTA_POOL_RTSP_PASSWORD}@10.10.60.30/
    frigate_loryta_pool_lq: rtsp://{FRIGATE_LORYTA_POOL_RTSP_USERNAME}:{FRIGATE_LORYTA_POOL_RTSP_PASSWORD}@10.10.60.30/cam/realmonitor?channel=1&subtype=1
    frigate_loryta_fdoor_hq: rtsp://{FRIGATE_LORYTA_FDOOR_RTSP_USERNAME}:{FRIGATE_LORYTA_FDOOR_RTSP_PASSWORD}@10.10.60.100/cam/realmonitor?channel=1&subtype=0
    frigate_loryta_fdoor_lq: rtsp://{FRIGATE_LORYTA_FDOOR_RTSP_USERNAME}:{FRIGATE_LORYTA_FDOOR_RTSP_PASSWORD}@10.10.60.100/cam/realmonitor?channel=1&subtype=1



cameras:
  frigate_wyze_groom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_wyze_groom
          roles: ["record"]

  frigate_wyze_rroom:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_wyze_rroom
          roles: ["record"]

  frigate_wyze_baby:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_wyze_baby
          roles: ["record"]

  frigate_sv3c_east:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_sv3c_east_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_sv3c_east_hq
          roles: ["record"]

    detect:
      width: 640
      height: 360
      fps: 10
    live:
      stream_name: frigate_sv3c_east_hq

  frigate_sv3c_west:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_sv3c_west_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_sv3c_west_hq
          roles: ["record"]

    detect:
      width: 640
      height: 360
      fps: 10
    live:
      stream_name: frigate_sv3c_west_hq

  frigate_reolink_south:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_reolink_south_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_reolink_south_hq
          roles: ["record"]

    detect:
      width: 640
      height: 360
      fps: 10
    live:
      stream_name: frigate_reolink_south_hq

  frigate_amcrest_kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_amcrest_kitchen_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_amcrest_kitchen_hq
          roles: ["record"]

    detect:
      width: 640
      height: 480
      fps: 10
    live:
      stream_name: frigate_amcrest_kitchen_hq

  frigate_amcrest_balc:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_amcrest_balc_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_amcrest_balc_hq
          roles: ["record"]

    detect:
      width: 640
      height: 480
      fps: 10
    live:
      stream_name: frigate_amcrest_balc_hq

  frigate_loryta_pool:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_loryta_pool_lq
          roles: ["detect"]
        - path: rtsp://localhost:8554/frigate_loryta_pool_hq
          roles: ["record"]

    detect:
      width: 704
      height: 480
      fps: 10
    live:
      stream_name: frigate_loryta_pool_hq

  frigate_loryta_fdoor:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/frigate_loryta_fdoor_hq
          roles: ["record"]
        - path: rtsp://localhost:8554/frigate_loryta_fdoor_lq
          roles: ["detect"]

    detect:
      width: 704
      height: 480
      fps: 10
    live:
      stream_name: frigate_loryta_fdoor_hq


  # frigate_porch:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_porch_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_porch_hq
  #         roles: ["record"]
  #   detect:
  #     width: 960
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       person:
  #         mask:
  #           - 39,445,199,427,198,263,36,228
  #           - 304,218,304,408,198,434,198,262
  #           - 305,411,485,382,615,393,612,335,578,321,574,233,549,118,308,209

  # frigate_driveway:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_driveway_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_driveway_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
  #   objects:
  #     filters:
  #       person:
  #         mask:
  #           - 822,204,1280,360,1280,0,0,0,0,313

  # frigate_garage:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_garage_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_garage_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1024
  #     height: 576
  #     fps: 10

  # frigate_river:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_river_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_river_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10

  # frigate_study:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_study_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_study_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10

  # frigate_living_room:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_living_room_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_living_room_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1024
  #     height: 576
  #     fps: 10

  # frigate_basement_1:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://localhost:8554/frigate_basement_1_lq
  #         roles: ["detect"]
  #       - path: rtsp://localhost:8554/frigate_basement_1_hq
  #         roles: ["record"]
  #   detect:
  #     width: 1280
  #     height: 720
  #     fps: 10
