---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ./helmrelease.yaml
  - ./secrets.sops.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: frigate
      app.kubernetes.io/instance: frigate
