kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: frigate-secret
    namespace: production
stringData:
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:0anM29cqgViCZAdi6LFGBUmU,iv:odU9Af12Tupnw17xd7IdVeALp/WfK0m/eyH2Lzxm3H8=,tag:Y/0gDqPVugqV6Fu9c7cD0w==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:pox/beYvLkJTyo2fR6w+9FAG,iv:rZGFmyRm6g9BpOszPoGLeNJkaacrwgA6mVmq4MV+QJo=,tag:mg7LsPk9EMPZbE1SGmpdRA==,type:str]
    FRIGATE_WYZE_RTSP_USERNAME: ENC[AES256_GCM,data:JDX10PG83N8=,iv:jzVwTr5tc0jjbUgyKlAA+0C4AqoVN5rR6LR3mFiQ8Tc=,tag:8rAqOHhFqSMzzrKXtGuejA==,type:str]
    FRIGATE_WYZE_RTSP_PASSWORD: ENC[AES256_GCM,data:U+IRNtaaadc=,iv:rx2AIzGecPiRHKZ43Jt6/DGJC4ac0AsUMF+vX/I/OEM=,tag:4JlBmixCQ/vG+tr6aGN+TA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:19Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHu5cjAPrJ6tiuLrj34PK1HAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNluC974KVObfMncnAgEQgDtYL0q7JxONkdLmYUPdRYKK3+p+DcYW8yeFZs1v+wTpIH6Cwv59YBH+RIyQwej5VS6MzMeFiNnpLckzpw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicDFEcUZCTzg0RGZSUlE3
            WEwzbXBGL3N2RHhQdEExR0VtTXdLaXEvZ3lNCmU0VnBMcHZULzJKM0E2ZzFuYWpR
            QjBqd0paU01qYnRYOTJMcHZpMTB1L3cKLS0tIExMMytTLzZ5MU92VENRbS8yUGZn
            bWYyaElBNjNhMEtwNmtOdVQ0b1FLVDAKzVgmYujwu7rF6JRa+zo6Wz1WxKbRy6yZ
            Ppse/kTFLIzuL/w51bNynwoXbRluPd+nKd1TNQzZU62uEJKi/95DhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T07:28:29Z"
    mac: ENC[AES256_GCM,data:yfSs68iwKJLpoohDNp+JrF5O1xt1MkEoBX6o83Y8O+faDDUsDPBlYGPpxJd9YYwPakyO1Tc+mx+n4Ncuq72vg+6B0C4wd+3ehRrwpSPlGqGAdHy44Uhe/mdRcYUW1hirzQBQjTtJrdrTXiaUL/mjBvXptr3nRSDTjYjh+jnsouw=,iv:zFBgJYO39XZO7yd+3SuXZMhnFEdnEToLGrjNhJqFBQw=,tag:3Ko4mmMSevIHrTJbdBBa2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
