---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-apps-prowlarr
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/apps/media/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-pod-gateway-downloads
