apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    VALKEY_PASSWORD: ENC[AES256_GCM,data:ch+IbsRK4ftQPihZqFHK/HN/U957zy/D9AqtkiqVISgujQX7hKN5lmDJmm3vMgzi,iv:brt1wEE5d/WlDCy7d0wscxhgU8nLe1esUw6hwnamSIM=,tag:nfqe71WfknS8Uj3mtav0Ww==,type:str]
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:y06I6a1rp5+13RiIduacB1NvhV6AvfEWnwKeSw==,iv:2aLiLIm+RZ9f0fcd7DO8AudjcxeoGuQUM1urn+i7neQ=,tag:8z285EEk0Hl94dsG7kx4bA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+NKGrE0xAxU=,iv:V6AhWDC0vXdxOwUmoPWOa+2aedwCUMF2xuaTfctfvJw=,tag:IWHt/yPadWQ9frnPp0f1yg==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:4wEOpgJ+kRrq,iv:IdPyq3ktEiVYbvSt27Yb5iKSWDm8PVuY1lZqdbUSHQs=,tag:hfgUrAAeCxLcbTfbZcU2Ww==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:gD3doRAvgI0VHPkKY+SqQQ==,iv:0bgGEQIErA40jdvH8WNnitEzvUSNFWUEBxMLWmzPV4E=,tag:y34GgQxVz95C4wUFFmbmuw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Efpk51mBlVy37DEZzBIT39150c/27D4vi5g7BCkeRtjlA8g0,iv:HujdCWWCvGndcK/3DxOkVEwRuE8HFzMP3EC0QYLz3Mo=,tag:8xP/bVJMLB4yr0i3jm5i2g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:/HRq0CM5,iv:SKhZ88tnD9UllcBN3BVD4XVUJ+IzTLX/7rmHmXQcHXc=,tag:QVhPfYZD9dU4V/7FUgrN8g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ejR/9ImO3WrcZkbnMS4mH7b+qbwuHshy,iv:H+6tw/I/6aHglUoT4aZqzww3X3w6Naa2o0LpejPGEGk=,tag:pEEBw1EmEb7ohhv73kCQdg==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:kioPXyIe8+A7bfTD,iv:hELgB08UTcRI6ZxCbSjqy2FL/1URller6iwlfQIExns=,tag:6aNeEsVZ1CGXW3OCK41h5Q==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:MrzfPsEvkaVow+4tgC2gIY41opk=,iv:6U7maVywerzW0XarpHIL8JkA+Zpc4qiLg9u7hEspIhk=,tag:XMtQMQM3AhmUEb2uL8RucQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:3tuG2CzbKr9MMF+jVdYuJI7gAnQA1Mx+hGN16x0aixRRnz/a5U2sMsr/YBc=,iv:lQADgEe5+z9iQcLbWsmZYhN9R22jSAFb4EvthlbDH2s=,tag:l2PLs+eh98OfCOyk4uKwPw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:QSHmwExxFSinKgSyj/KLJigWGg==,iv:3zbD3Tg2IJeygmVVNsulzQzjuupEr/HI9X0PL7eAt5M=,tag:Pf/evBTAWda71ND+uUf97Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-06-03T00:35:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFYRP2Fv9S7J3Gi3WDL6jKpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6ioC+Ncc69Egb+l/AgEQgDu0p6bYFzo1HIgTzi7td3dtb2x0bbDNi1LKogVkcbTz9AXtjcKEfF9hAqZwp/9fiVI2YrHSv3IlZnPhhg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL1hnY0FVdTI4UUFhZ29M
            cEdNZkl1QjE4VkI4WFRNRGxodDZqY3BUZ0NJCnF1QTNkODRWbS9wbnFwdGpsKzF2
            MEZnOE4rKzdaOWc5ZSt6RW1Rd2ljdFEKLS0tIEp6MTkyUUlFOStrSHlmQ3Bud3BX
            bk82SGRtMkw5cEVvY2F2SmFBdTVLZmMKoDEJfF5a4TkQfr8l17mIyKfnRkTEL8Ub
            4JAwQVkUzomybZV8pABLEXcd7sRQT8hXTFAI/sf7oVQ4dCT1N6tMJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYlljSmtKTWZPOW9tdkpU
            YXQ0ejhScXJBN1VjVk9vUTdUQW91YXhuK0RBCjFRUzZUVGhWbDhpSjRZL3NPZ1lF
            ZUhtTjgvUHovUWNsNmUwbXdjT1NIYUEKLS0tIGZQNHFsdWxIOWZZVDN3WGhHMlAy
            VE9FNXdJaTZkdlIweHRadmRmSzUyZWsK+Nk6A7ssQ0iKToc8C46PM+F7vtH+s1vq
            uKKKsgaZYzui5JlX/eEDNZnkQRrUbM76cMYtxndjOo8fbjXHl/0kpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQjFyaHJyWjI1VFlNYSs5
            WmRFTzBLOFpmZGpVejNXUVVnd09Db3hMRnpFCkhSa091aW5nR0V6aUxYSGF3L2Uy
            OStaUzcrYWQ1ZndieS9lY0tHM0wwUjAKLS0tIENGSHZWaWR0bzgwcHc5M2pnUUpD
            Tm1zU0lFampxdDBVTThGV2plRWtCdnMKUR51xMTGrPLkECyocgJyN9K8DG4oyCZX
            +LUST/tlxH9Q5P1nxUGyVj/t8lc30xtj2PAOfVO1uIZpEmjK4/y5UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T00:35:26Z"
    mac: ENC[AES256_GCM,data:45vuI66JM3kUZ7k2t2qI3p7+yxGpmSAXP/PEaxuJx6S8+sDjsA6DBcPi64guMCPz2WRvAVzSLIp0tszW0GVRi0zoYRNRHbHoRHMY/uU0TMRIFMs+9GhSdpsXWiT2u9yWEiLIh559t/x2KwZeME0dkbHwh3GqvbNLuz5X2G+UixQ=,iv:s9pumlTCzGDNyuXG0rrQ9bMIkw62YQH9A0oVXQrW6pQ=,tag:k5jbdeE/RYbFX7zbGe6KnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
