aws_region: ENC[AES256_GCM,data:NDaHdV3tEZn0,iv:ZRvhOerT/S7KbBxBlmtu3fSjz/sseWgyOV9F7AoRY08=,tag:YI6U1QZh1IaCH5YmeL9MEw==,type:str]
aws_access_key: ENC[AES256_GCM,data:KHAciGD/OkMS9jM+jif+oZWV/Yg=,iv:x4gPJEQ2IaL9VzZ32ZZHnNPb8S5WzqlfMHc8NAQRGko=,tag:uADwija1jNIdveQPqC08WA==,type:str]
aws_secret_key: ENC[AES256_GCM,data:ZA7WX5gnqOcR6bcSfRz1xLtPCxiALHDPHo128Nbu3zpCffHoDZ5Cpg==,iv:P/8O96KsWO08a/q0etQnOoaRV4LuQv5NzIGmYLtaUsQ=,tag:gshqX01SxxgKH4Aia9y9tQ==,type:str]
aws_account_prod_email: ENC[AES256_GCM,data:VLXPm2tRIB6XrPlhV+bZBqwGE0GNQ/pk4xeFSHnS0+5UKxkG,iv:/E6ogrBDySnzCycq+wwPP23nr9MN9Jil89LADJurwAM=,tag:g5/ucuwsaTJWAhjGd+KR1w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:36Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHR4nFmo/HtQlh76p9CmYmKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMT8UPK95AYL0EGlzFAgEQgDsiwuNENy5LXTBi7btJRP2NB7nZhy1M2Mhw6tsLqZ3FOtnR1iydaS2R3kCQBg8ameDedYKb+nATQ7ztAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ09GYzZYeFFKdXBpdUw1
            eVFONUYvQkpBdzVFaXB4WWhtbW9xbysvZkdFCkV1RkJjeG9vZkJZMS9KL2p5SWdt
            bmhpZHpZVGtuMk85bjFUVWtReTN6MVkKLS0tIG9xYUtUaUsxcHFneDZMRG1ZUDNs
            RFpoS0dCelpDSk9LSWl1M0ZoWWRCdXcKxt5fM0ARGunRKR7mak6/qPIJLncnoZzg
            +uWmXh+fZrcSOp0G66B1QyJF1mGzpScsVd3l3y7UmUR96/pVtUKliA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aHphL1pML0hNR1UrUGh3
            ZjJHSHM4L1Rmc05jTkdJbWFhUy94UDRxdGtJCnhYVWc3UHZUTzBVVGJ6Ujc0a1V6
            UzFMa1lKQ1hPbm01eitQcTJFL0dVMm8KLS0tIENiTFhJUW1zT292c2RNV0Noa3RJ
            QzQwYmx0cXdVOVdRbExZdytiTmZLVUkKzCrhJh/kEQxkiXoJus6IVsxcKsfeT3EP
            NJgQ4PFWRbNddQY6ZnLfZuKTFsYehgobzO1w79yu0Ip7vzCi5b9Ehg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeUNaSGZ4VitNWmNER3Yv
            SW8vUVBYMHdaWTdabEV5VWZVb1RaRnJGdEVnCmIxc0hlNE5tMTBXNVJnKzVNTEMx
            SjB1bDBFR3FIczhlclRhbXVhYk10RmsKLS0tIEowSXpRWHBWemdFMGpvaU5MMWVV
            aVVrazhPMDZuWjFzVm9GUyt1d2VjbWcKYSi1Xz6ycHyhV7R+zsKyMuPo2tYsau2f
            tKgBtYX0MPVSSo1h62l6ipDMLtp6gA6z2QmPNlWcveOemMdSvLksLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:02:00Z"
    mac: ENC[AES256_GCM,data:9uG3v3u/WEyzKJgcTRiQ1pjK3rB+2zeWqkcRQCBQWYYcOiGuiMLz2VWclROJAX/4iJgxoQ3dY2m57E4oh9Y5v/0kRtV1FC3d184RKAD0GNavsSxES9hUmKznha4eFIcQN+kytwFWYjPS1UkgIf3euvN+KoceSyRx9ELh9Wguv2k=,iv:46+he11JAMqDMW5+QpPn+4kpoZuuScQgeYmU82LOeIg=,tag:kd8ZskON3f/CqHM9fjbBUw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
