kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-mh-secrets
    namespace: home-automation
stringData:
    couchdb-user: ENC[AES256_GCM,data:9GsYJW5PwbJwQuKL,iv:167bk2/lMTOdxpgNoFBOlOCUv8bKGEQ2xbJbA0k7aMY=,tag:dOnwK/C69XBoz28axpYAZQ==,type:str]
    couchdb-password: ENC[AES256_GCM,data:3KWRhHN8ahRW3OqITFQ7kOtN9nYJmaplGW/UsQ==,iv:IuELsC8SjRkD1aV5NADFvNZHMZazVCa1686Gvgj8EFk=,tag:jDbahhIsNcC19r3vGni3mg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:53Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgGD+hq9+o+VK701nkd+PsqVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUFMGC8PTdmz80EIAgEQgDue0fOt/TJSE70h5WqvVlM2dfUFfH7378LOReTCC/fOTr1vZ+iZE45RpeKKu481bCnukZ8hPD1MfBbwLg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y2ZzUmVyazRxRDM1VFI2
            Qm1mcHA3RGNROVlHWVM4RmN2b1JaRUFld2drCk1VOHVreGZMWDczWGFFMjFIMlM3
            QmVuY1FuUUx2WkhqN0VFZ2FCc1U3WU0KLS0tIGRnWGxpRVVYREtWbll1VEVTbGxR
            UkdOaHV3ak4vZmZVYU5QWGJmbC9EU1kKdywprFChTmXoO5w7ICbWxlNvNfHxcppt
            MtuqCNd8q9sdMBYx8lttP4D4t5JcTjKCwmCDVtnS8/iyxRBW4MDaWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T02:49:47Z"
    mac: ENC[AES256_GCM,data:mQjcVxrjfvzmRadjjMZ+Q8Vd3/hG7PWgwz/088aUeVBDWD8vtVPm8fjl8PM4mjGIEgmSN4USutBH4ucX8xdlAiJhLPNaeDaQNxR3AdM620emDefH7pFqZUa9162/ztai2jZg/tS46dWIOp40QSJVdZqC2WxOjbYfMkS+IGTJcUw=,iv:cJX5KJCTM6um5aeDDf81wDZUzXGVLXS7cRBcpgMXmqo=,tag:Bd40Ze3Vurn6BgKa1DZm8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
