cloudflare_email: ENC[AES256_GCM,data:B8bK2aQkCzU+xerWvi1hj5reKXrXeAEGJ+VA1w==,iv:cMjqqqvaZiZlUylfd4GEcMACR3NXZTFWkYTBG4Q4LNQ=,tag:JxzL18ZdnVv+10V8sIIUUw==,type:str]
cloudflare_api_key: ENC[AES256_GCM,data:hObsdHiCiE+8eDmwNoI2BDhFdMrlHqHmrZBgKqnI7fgPy0ft+w==,iv:gtpLLl0oInA2SyJ96cIAG1IyfW/q8CQtQUianIjDr88=,tag:NzOv1nX8474vSQFhBQq5Ug==,type:str]
cf_account_id: ENC[AES256_GCM,data:bze0ZcXG0ZkT4EKhPjZk5WPUjhXBraPT3gEwbA7WnB0=,iv:uL/KLHKs3rk8hvWIQ6o542clZSnqcPwaiYk86mehAXA=,tag:SF3bp+i0l5q1digCSVsBqQ==,type:str]
cf_domain_1: ENC[AES256_GCM,data:/aEeKUeazl8=,iv:DoTZkqUHTEWz1JC3n5mFo/6OvwqRe25rlxfvfTnKKac=,tag:0Ye7U5XEAhvZNkBKTr6yzw==,type:str]
cf_domain_1_aws_eip_unms: ENC[AES256_GCM,data:n4gkUrlUOGqDs5RU1Z0=,iv:ouobORbiuxNQDbxRtjWxr16aybkSACBuiajMuExVzC4=,tag:+0+UljI5X30XJoOhB2kG5w==,type:str]
cf_domain_2: ENC[AES256_GCM,data:RuPXQAr328EQzRJ2z/oEhsm+AfU=,iv:Bao21pAwNHvEHmTunI95GSrAHkdWSUZMIt70w3AwQek=,tag:i0m9R3kh0r9cxAAcC6Ip4Q==,type:str]
cf_domain_3: ENC[AES256_GCM,data:V2hVx7cgNQHA4a6l,iv:Av6295BX5krp03XqBtnii2GuE1T2Zo+h/PfVMpT1zUo=,tag:0mvmNg09Pq+VYdgwq4E6Kw==,type:str]
cf_domain_3_cloudfront: ENC[AES256_GCM,data:GbfJNruWcOL5R9wGrLJJPg/sPqlKGDLOf+HL+ME=,iv:JrypuqdBmVifbYMtOEeM5OEbG4L75fpzp0gTjSAdEDs=,tag:AnNr63IvSuSR6s97+QeF7A==,type:str]
cf_domain_4: ENC[AES256_GCM,data:FpyQxMtI4AI=,iv:yoC+FW11+SwvYShNigiCx2F8hu0TgJEYtGr7WQJM4rk=,tag:LthVotExikgmlLLewucfMA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:25Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQESwXpVsg1u5dBF1AA/kPvmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZSWiO7SzoYpnCtLvAgEQgDutuk2mbN/adVc678hL5evmnGLAetSWv/orcfryofD5ARSgk3LHoez4rX3R+lx5DkhaK81BX/4hntrQVw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQldxcVcrZU1XUTlWTWZl
            dC9SaElBK0Mwd0VjNHZQL21idHZUb0dpOEdRCnI3TnJrcm1YVjgrUnZETGN3aTVs
            VzY2VTNKQlNYZEFVRGN6TkZHUmZZNVEKLS0tIFYrMVNNekdUVVNEblYwNExFQTFy
            SzhrWHNMLzJla243MUZvcm1DWmhXWFEKIGJ11y8OHIxaytyUyNUbMTinCfnUWtcC
            iFNOJL/QrnDu2ymTNFxCO1cfoRVqWg4QvagLcb2gBX3qXaiXcvRHDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOTFYY2dKQ2FjY0w3anVJ
            OUJLTkIzenIrYUhyR1h2cHpnaWhQaDdJY1YwCkNqWlUyN3puQis5TTNSVkJ5NEYr
            WjBLTSttbDZaTm02a2Zhd1BVU1pOS0UKLS0tIEJRSkNrVjdKWVN5NnQ2VnJZSGFt
            MzlTM3JiWFprL3lCYkJrZXh3Sk42NTQKyLOWNBo90ukW0G4zO1N8ht0L3+fqlT9Y
            kF7esmXJwZ6d3Ux6LI1YtgttTfuFoyr4KITlNfZrWl6P1xzxk7zgPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T03:17:51Z"
    mac: ENC[AES256_GCM,data:/brfYKvoUa4w0pTKrQkXn+jKosc68ibu3XYgaGDpvlrAeUYfbdUHfSscnFuu/Wvgn7MuN5Zz51CsPuQS4JtJrXBWi24hE3yE0X7xKNcLrtpBJpHOGOTJ3JToPhJKmq6eWea0zaRI5VQxvv2NV8rIeex5rwEm05DX26vUX87BpQY=,iv:SzfYCs+fNBZnubpqgr4H1DXyG+f+ulrmNEnD6HCd9j4=,tag:Myqe297W6+XOYvucDu/bCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
