---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.8.3.3880@sha256:b17b18507fde48c020c49d3f632178d07cc7e9f17056abf9ec50d30ae63d6f6d

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    env:
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      PROWLARR__AUTHENTICATION_METHOD: External
      PROWLARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: prowlarr-secret
            key: API_KEY

    hostname: prowlarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &internalHost "prowlarr.tnwks.local"
            paths:
              - path: /

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool
        retain: true

    resources:
      requests:
        cpu: 18m
        memory: 160Mi
      limits:
        memory: 160Mi
