---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.17.2.4511@sha256:01dce2a9c0e29a2a5338a9457698ea3e027727bed6b9f0ab7ac4a259cafb991b

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

    env:
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      PROWLARR__AUTHENTICATION_METHOD: External
      PROWLARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: prowlarr-secret
            key: API_KEY

    hostname: prowlarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &internalHost "prowlarr.tnwks.local"
            paths:
              - path: /

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool
        retain: true

    resources:
      requests:
        cpu: 18m
        memory: 160Mi
      limits:
        memory: 160Mi
