kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:C3OEsBFeWo77s3XFf7HhXduRwHkjBA4a/qMidSA8uwk=,iv:2D7qWaTWJBWgdyKpdf8T8pqxzHZ9dN1mKfaDNpEl+q8=,tag:HvMwJYJAcPvLk2BbLfSSew==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:28Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHjadkpEAY6/bYJFJgusuXiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHsfXyprGpukHUWg8AgEQgDveQmKanNw2ui/aXKdrwsYSRcX/oIfn/OyDuSmVzT5XvaxDqsCyYDFHgn16X7THwiRpYV0u0iDZKOhwCg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaklpYU5xNlRKVnhidEw4
            OXdLanVmY1Q1MFhJM0xTKzJKbk1OeVZkSHlJCk9DamRWTlRxNGdnQ2RWdERGTHFo
            elk2SWJBaXFIODcwbVU4SWh4OWJJck0KLS0tIGhlbUpkSXVWVUR6dU5td0pIZ1Z1
            WTVuMnZUa2wyQXBPc1VrRU1tUmdDQzQKN/RGiTlfe8RahC+7YZH9FgMF2PXyND/J
            ozWGrCTwoH0w8pHODVSPB2Gss1M19u6QlmuTKbCZrtMNq4cW4JMl8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:29Z"
    mac: ENC[AES256_GCM,data:25EziFz3UI2A6uUIofoe1Gm0E8yDGkTILehwPn+ef26zAlshCIjOdPTN3bO+mX0NEnGPW3TBizfdSHJX8I4bS6zIrW2Rqu/qEB7d9X+d9NvOFpeiLFJIoZi5g56FbnwLXoudWBXiJXN9gxQXlwrf+vu2VkuYYaeLA3zr5+Es0W0=,iv:eibDFrzrVXsr5jMpgPLLMv08N1BstztTmXfDK/b2e2s=,tag:80P+rdv7UwwWGR4rQyCZ8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
