kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:N5b5qdm/SynwsdVTdmx9GFgVK8Cml0mMYmmeJrYLj40=,iv:uPmaUXhTKiu0QwXVkOhQQ6miKQHxsqM5nfLlQa8Knx4=,tag:5x4/koV9Ae6bhGuamB2CAQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:28Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQE2/O2LPwLdBf6CqDrpOS6FAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMe1rq3zNlZRylTyofAgEQgDuJZGUzluYSNa+f5hT6vbRqr2GYHktUeHRj0pE6Af0+ca83F3TTJ04NU+JKThrvLfjRRQbNtxgy1IVlAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYit0MmtRaDNVbU51bDN5
            NUQwM0J3QTNicnVVcXI5TFBqSUhhTHRnZm5vClAvN2dXSHZUSUNaZGIrRFhyOEpk
            VFFhcjhpVDdGWVFaOEk4V0xmamdaSEkKLS0tIHRRRC9PZmJaLzlpYU5XNFlJaVhy
            VUFJMmk0eFhYQ0Z0LzBYTXgzVVlqV0EKO4Ll0QsLejo0mKETk/EIAm4mrg4UMG0F
            ZENhdWdzC49Lv5YqiR1ymsL2zH/EcBWcnl5l5PEMiyKnC0SsNFQB5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYi9jTTRWMzRmK0NRMGNM
            SlVsQ3pZeEtvbmFUV2J6S1VKeDRKOUMrZng0CnNCbitPVHczWDN0bHh6QWpWYUE4
            dkJnTFFVTVNSUFBNbHQ4RENEVEt2dk0KLS0tIHFmQXZ0bU1yZXArY2I0bVA1R1pz
            R2ljZXlOaEpJWWUvSGpyV0dwelpRcHcKG525gho5ukJ4Yl/G9tcEQ+B6N8Sq3npb
            1/13Fot4djUGDGWkIOZGwOoJAFHzDuRmaAEahg2bOSBhsJ0tp8gdkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReHpvSSttT1lDWVg5bCtq
            RWJpejVYZzlSb3ZKeEJGQzBidGdRK1BOdGxnCldBaHY5K3FBQTRyR24zWlAyaldx
            RHBaQ3o2Z0crV3ZXSktaU1EvN2dnSjAKLS0tIDFTWC9QQzJzNDlWR2EreVprUE5r
            dDkvTzFObTRQOW9nck5XN2hQckV0ak0KOO6tAglHPaKDemDq22Yo5AlDDSyrbeSK
            F8wBnd9XlbB/YUP+rnBw5g1d6fE4ywpBGPvf4uatsWGfoJdkLDPgAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:35Z"
    mac: ENC[AES256_GCM,data:HqKHElnmWolJlEI0VXKYKXswz9b4VqDPZTcoQSo56GTnrExYZIF4mKo66h7EVewWbRTWQDDm8Ata/SVpvFObGEeHiA1Pl1faQ6zP2MOm/uyhNIZgJBkFQ/93rq8K1HYOttOmgsmCvgAIc+hV0e1JtNBNJDRN5NCmF+hGX64Wbt0=,iv:fKGsqraFQu4RFIMwOLswgbKY3gJJmb9pmKmb2Q1kigQ=,tag:Hns+gH+V/VCDd/2kTCpg2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
