---
- name: Kasm-start
  hosts: kasm
  serial: 1
  gather_facts: false
  tasks:
    - name: Start Kasm Services
      # Changing FQCN
      ansible.builtin.command: /opt/kasm/bin/start
      register: start_output
      changed_when: '"done" in start_output.stderr'
      become: true
