---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zwave-js-ui/ks.yaml
  - ./peloton-to-garmin/ks.yaml
  - ./syncthing/ks.yaml
  # - ./external-dns/ks.yaml

