pm_api_url: ENC[AES256_GCM,data:aHDIRGyedTJhskv99GSZxv4ltFD/yPsjLOJBRALx9/0mqUE=,iv:sRChN57U0QKAZa4niONQj5gJvFVX57p9RyAW+HZGAkI=,tag:fR0yX5Gu7JX5Z29Oqzvvew==,type:str]
pm_api_token_id: ENC[AES256_GCM,data:1SRo4RzuWPtbZ32O3a4ZQkyaapDQUE8=,iv:JZL6Lfa9J7my3BNfRzI+E6GuCNHIAYXqbVXtYKFeQ5g=,tag:ja3qRfIsIy523giH/Os1yg==,type:str]
pm_api_token_secret: ENC[AES256_GCM,data:7wywUToV3QO5uNpzXZ7YcnCOaT/46eaT4IY8rwPc4UIkEViX,iv:K2snGlpAS7L7jmS7ymTkpjh2Zh4f8KDUOgS68JkGHk0=,tag:4ypybwaKvofS7lqMG1RKIA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:02:26Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwHujtp+6wXQo+fsrqEzOf2+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcfjdQXs9uIeDvWXwAgEQgDskWh2s6jqG+71VFK1sR8s0e8JhpjcQ9BwuuvfHgManR7krFNa4gERdPSeKoMUpYgBggXhYa6f+c/vUKQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdWhYS2FWbUw2UXc1Y3Rv
            VkJycFVnWDdxYm11SVREMnl0bjk3Q01XSm5vCkU5NmRYV2x2ZkgwbnIyZ0luZnFm
            ZU0va2ZtRE80UUdScHZyN2ZQdzZITmcKLS0tIGl2dTdZV0lWYlFSb09DM1d5V0s4
            dU0zRDErUHNkUnAydEJ5M0V6OUlhL1kKuEdzh21dsE68czSD5EnD5tIJn+AahXwt
            to9WsOwW0V34Ehg8cKAHqPGV43LaB6haKyZecq2kZ0qJoLP93NHIAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:02:28Z"
    mac: ENC[AES256_GCM,data:9T2Q4jaTX7DHVXmwdIPG3Ffxyz4eUvViZnOtPwsBmgiVv8id6ppDM8HrPXj6qd4I/EOwuwb8hnEu6JyU5Kt1QCgkiP3jJmg0GqfTZrN+EI167tZsNO+83iB9CuDai7e/xI0qe2Z+NGUabQmuX4qbtceYAutv24KbciJ/1igq+jY=,iv:F5C0o5psd22ZA54x8nseSlU+v5LF8zP+9lCn4ByMT78=,tag:S/QnIeu4KFJuXLgIipaiJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
