proxmox_url: ENC[AES256_GCM,data:/ce7qDWqqYZ4vLQ0UmQizCM3+PZV0u/e3qcftxnKMsS264M=,iv:hnG79n8abJfGciGD/5UCpqAqsXiUZXvllvSbOe+knmE=,tag:ltiHaii/uLgIW6LqnCITBQ==,type:str]
proxmox_api_token_id: ENC[AES256_GCM,data:fogSK4BgrYVVLXv8ekD8MY0=,iv:ulampj9LraMNhvZU5WI5SHbeNTv2EGWQEoaRXWyU/2w=,tag:ep2/xFeQXNFips2+lGYLVA==,type:str]
proxmox_api_token_secret: ENC[AES256_GCM,data:bwjI8AcnVczz6WR/g803jMIHfdkJtyvEL+T5UTol+s7BAoub,iv:2TSir/X0x1LcNwB1l5S9zTAw/jbRB1u/MmevHT/HV1w=,tag:ILmZZDLqHe2d+dSuRCg0sw==,type:str]
ssh_secondary_username: ENC[AES256_GCM,data:HeLp16nXcnWiyMXPH4OP,iv:/7vVWv7tPEuASiUk1wj6NPVvjkFZw650O0+MvnyNTms=,tag:MVOEiHUXqRURt/kPM2lsVQ==,type:str]
ssh_secondary_vyospub: ENC[AES256_GCM,data:iri8KU9x/CwDJPL5tHPuLRnicj2uTZtESKTHp/OtvJiB3mvWgLsqeA7yAEHAldYRxeOOvIr0gkifAp42s9wXkKbiGO5LZ+yqChq1P9cSXx5iZZ1a9JhcNVGxPxH8dzt0SkqXxMfc1Cp+BNBSEZ3Dov0so5QBjE+WdyId7hqEmfuyrfMOoQ/l02guGKZLXhtMFAsQprkS/b6MFO5rqJPHnYhMnXQtit/m4KAXRyqRMOpMBdu9oYEsTKSIPYL7btiTIinLTr348jp0Kf5wZIVMcsyMiEMe6vLmnqdYrNUabic+NS8xxLuEekStmahapLWVI5jcIGdth+OL84DSazFTbPzNtQrtImFKFXGIpNTBS2DEPTT9vopL7us18QTU4idlP18/pRz6S3/4CLkQPLPR+ce6J+ShJmJzmBou8V3QbXvNEE1xm3u34OZcn45v5GaHMTM53E6hcnSkkXPM8hea8kN8Dy0KDH50kEhDrxiUro4X9s/emCnMlJic63JMw9e4lmkwhGK/J4eFPQ3z05Fy3hveBL7rNke/R5l4h5MHBsR+f4HU1v3tmopGibZp37C8QaG5EqH0djNUgxFY3YAGIDXFr++uQtEVERkzts0xmuqyCuBWZIgEYhxv8gbw6E3gD1f8A5keDzvdAnYt2fSPJK7AiUJdnQOyOB2OeI+zwKX4Ju4kSLKg4ViDdsl1uyIGzXMkp5NTmyOXq0cCeM7hWw==,iv:upIhnisPuYgWnPcHbJbl3N5n0+ltdBLgLGHHkyrsQUI=,tag:4VxpbOcooHoVBbcXjHg9cg==,type:str]
age_private_key: ENC[AES256_GCM,data:pPmSM0gNcGnoOMTVxk7r+svds8O8zCCX+wzEOo2j6RbnKqPlZ6eD0IK/ZofzPzi5fDThtzzBf+36TX4MD2jBRLayXIN1ujQIvss=,iv:9Ja7QlgdNADOjpgM9sCS78e235Q+zwN7uapk3BI13Xc=,tag:nVEo7AybvfkMC52JNy7KNw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:29:39Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgEi1Dqu3k3f7BQeHqBggd9vAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqePG6mMV1c+nCO72AgEQgDuM6r7NZnUJLBN/JHT0REdz/UY1Srt/OsNpKsCta61L6asnKLll21Szm5jisUzPzYrQYptJHhs1N2vkgg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YmljYWtGQkxxVzZaQmxo
            RXV4NmYvbXlSbXpVSmlKS1BveExJdnJ3NGc4CkNXQUs0VndzZGRXVWZoZVRwMThW
            NmNmWDJaZEVoKzJiTHVMUmI1SkVDbkkKLS0tIHBVaTBaTkRBbVl3NG5xU3l2cENn
            T1ZVLzc2L2xGd29ZWkRJSFpBSmQ2SWsKIoYzPU+iLvgfvPIGlEN1gIX0/nLJ31bf
            5p7gUCV6DDWGehRy7xgvYQLOXK3euXWaQODfxEadl6DLbDzI+OURwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:29:41Z"
    mac: ENC[AES256_GCM,data:NgiOWZgBMQ6BMs62gMsN4kgUdPxnZ8Ej04hdt0mn/11Ym1VhSaa4suHudwxmaKUAqynoLVyPUdTvcokmiTyxbdZveZITFodcWahTaXeUx2+szfunlEBQOg7+GStKOvQU8nnBtkbfAeZ81M2Ci4EdQ3zoz1Ce3uoGt5o9KGjpCFw=,iv:wDrb4+opxDQp6a5tDDPlrTR37JxIVyA8y6UbeDK98B8=,tag:/1l+f3vMFAkRQg2GPjcG9Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
