---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.0.2.8103@sha256:45d478025148777fd370e28c7915b5412295ab0794005aa5e283d5510d5cab7d

    # podAnnotations:
    #   setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    env:
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
      RADARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: radarr-secret
            key: API_KEY

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter_once on;
        hosts:
          - host: &internalHost "radarr.tnwks.local"
            paths:
              - path: /

    existingClaim:

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool
        retain: true

      media:
        enabled: true
        existingClaim: cephfs-hdd-subvolume-qbit
        mountPath: /data/media

      # media:
      #   enabled: true
      #   type: nfs
      #   server: "nas.bjw-s.tech"
      #   path: /volume1/Media
      #   mountPath: /data/media

    resources:
      requests:
        cpu: 14m
        memory: 431M
      limits:
        memory: 431M
