---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.6.3.7516@sha256:798fe8b616da785edcb84cc871111e63c9227b970dbd33b4ac876faba4c058b8

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
      # RADARR__API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: radarr-secret
      #       key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    existingClaim:

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ssd-pool

      media:
        enabled: true
        existingClaim: qbittorrent-media
        mountPath: /data/media

      # media:
      #   enabled: true
      #   type: nfs
      #   server: "nas.bjw-s.tech"
      #   path: /volume1/Media
      #   mountPath: /data/media

    resources:
      requests:
        cpu: 14m
        memory: 431M
      limits:
        memory: 431M
