kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:+wz+gZFkZsBF6oI26yiPY8AMoXp2L3FjAd+vW6la7LY=,iv:yKYUh5mVC8Dq7/3isHOd9ydO4vqJRpih1NGIPeeyQ/I=,tag:NR7VpToMv3ZWC70SmMz4bw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:29Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQE08c2i/jFXLnLbkR0K6OlFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3r9HbDZna22Zk540AgEQgDulaZoBAITAukLcwPAMKS2w/5eJvGmZV1b27hIARERkgccvTIJ9u8T2Zqiyz+SJE9L7p6hfF/OZYairJw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSFZDZ2dQVkpOYnNCY05M
            aXRQYlpIdHlVanpKZFVUTVRFamhHa0dUUEFVClRiSDhma21Ta3l2VHhNdWgwdElj
            TS8ralg2bnBCRlZKbTF0bDR4cDhUTEkKLS0tIGsweGFST044NW5WbWRmU2VSRDNk
            dkx4ZzEwRm5VVE82S0tKTlhwRE1wV0UKWB4gW7xX7GjZC8We1u79GYcclsFmZ4hJ
            waalI2n5TOSMHCNIZM/i+VbdajQCsPSOCAqVxZZBLhZYPMaUB1CPRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SmdJN0xGSFNUdGZyZHp5
            a0lNQi8vYWZjNXorRzJJWllhMHUza1hMV0NnCnp0YmlXeFdPdFpyTEdYMnNTVGtM
            MTg0TDJBTnlaWHEvakFUK3U4ZlVSMXMKLS0tIHFvNVpBeFp0cHF6V20yNHdDWjBF
            WUVnOERQWExQUUF5UVdyeDY4RGdjNXMKyOxB9prp+BDU0dpkgQYOcAvg2D3t/rdU
            biWLCOG2/6dIXJ71/JBe9vByRvgrMgltOk2IjtkxNRvhhIIla9u3Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTk9WdHNxRHBEL1lPbmVK
            SFBWM0xjNmkyOFIya0d4NXRwek9TOGhsS21vCjNOaTZBUld5K0hRN0swb09jdlhs
            dy9lT2I5ZmpvK3Y2a0NnYXh0NHpJMGcKLS0tIERmOWRGSXY3eDBzeWRKMGo2b3RN
            N1VxTFkxclRLSWh4NG9DWVlibmtNQzgKNEu7omNVrUKcD5eazw1FWM2iAe0OnO9A
            owJ/VZHMAEAxD55Yt4EdzvQ5quUSK86X8hQs9eqL56GGjSVmttQyxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:34Z"
    mac: ENC[AES256_GCM,data:4kuPMKCXScG1sdcLN5SpNEarb8KoNWBR9gya3ls5C5kP6E/J/yvrj8SgLN60OobgcnnXm7ReF488zUajNtp4SAWQfNDKNj4PaznUzPGB0VUAgoTRK5qOPwB2cL6wd1hjGTomFIPRPCQPTL4guv1dUrV4W9V48H77f7jRVYXM85g=,iv:bm8JzjSQLSLhv16QFu1mWLdv+rgKo82a+nGYkXiM/+Y=,tag:nvRsMvziQJRgOj1/jF8wFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
