kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: radarr-secret
    namespace: media
stringData:
    API_KEY: ENC[AES256_GCM,data:uAhwYUnu1vpYnGh3Z0YoPiHG1KbUWxq0MXKj+e6NLso=,iv:P+nQ/P9I1FbiTtWn3f7A1oBqyU65yFMipSVo8bXxpa8=,tag:/EyAPoUrvLPxDNEabAyCAA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-03T18:30:48Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwERmsy/IoWffiHk4h72+AeMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnawRdZFE65eI35ajAgEQgDsIB1mILOtbZNGe1qaelLJ+nwQy160uYsXoedf4erE/X3RiiOdc+4u+LXB815isqiPGQ8VLbLK0EHInMA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaFBvcGZ2STErVXBJMGZB
            VlZ1UHVySVh4NUNQTlMwSnR6eGpleVFmNEdjCkJ4eFlmWEJ6SVRvZ0IzRWJ5Qmdu
            UE5YU0hWWkcxL2orYlBSeFA0WWJzQlUKLS0tIGtGdWVJaHhEOCtlS2p4SERnaHND
            SU5oNlRZRDlqMXZobWxpQi9qM2tDNGMKehgqRoJZ+U9rf/ko0L7KgotM6CIg1a73
            NDUE6x1ZQuD3/q9BFjYfyqD20lXCkmancrKX98zkiTVzHzH9CqJKwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T18:30:48Z"
    mac: ENC[AES256_GCM,data:yYaYcHO00HWVi1MbXJzbLyVgDG4LLyXp754v00khVl6SGBd7nMeY5aeJfCu5Wvvc6nDkVwbwr6KzwceOTMoz0GoJScsmFQn0GOfnhMHjA2VUSsZSPa4VNpp4L0a6+n2CtsQuzLeqGmGt+8zz3Dd0Qr9wXrJeY+2bPX96sNUl1Cc=,iv:bLL/afqPSdRhb9Lj265pmQj18ySlVdCiDC/uBi6B/i0=,tag:hy6iNSjE5yaf+RO1FwFM8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
