receivers:
  - name: "null"
  - name: "telegram"
    telegram_configs:
      - bot_token_file: /etc/secrets/telegram_bot_token
        chat_id: 8524513370
        send_resolved: true
        parse_mode: HTML
        message: |-
          {{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} <b>[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]</b> {{ .CommonLabels.alertname }}
          {{- range .Alerts }}
          {{- if ne .Annotations.description "" }}
          {{ .Annotations.description }}
          {{- else if ne .Annotations.summary "" }}
          {{ .Annotations.summary }}
          {{- end }}
          <b>Severity:</b> {{ .Labels.severity }}
          {{- end }}

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "telegram"
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: "telegram"
      matchers:
        - severity = critical
      continue: true

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "namespace"]
