apiVersion: v1
kind: Secret
metadata:
    name: matrix-chatgpt-4
    namespace: matrix
stringData:
    MATRIX_HOMESERVER_URL: ENC[AES256_GCM,data:9T/4oXYjcIJlR8G99CGoXFatfDERfYuA,iv:SCA+SPUnFhcX4WBTlDb0VyVH9g3zgvgqDwJzIoLJTz4=,tag:6YWb/fq2PHhb3ImMUhBHWA==,type:str]
    MATRIX_BOT_USERNAME: ENC[AES256_GCM,data:6ySStIIZOgN0,iv:RjkIv8OiD9t+zGMeoEAtXts6kWnmaDBhk790GY7AZjU=,tag:nnXGrDfptYDikD/dyljzVg==,type:str]
    #ENC[AES256_GCM,data:U+5Nx/N90FZQUG3/B9g2NLZk2Ad9+6Gmv00QEk/2r9ZxXwaA/j2KdUVpaKVFds7I6Q==,iv:PdQNUKBcx4+Rf+92WrLNVr2iK9o+Qe2/vGWVzRXYYEQ=,tag:oldCYAMdrx+vDn1mTAuiXQ==,type:comment]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:FOCkrykzJWCixOfQ+jzqxcFIst0M10t7VgFdW4IKCXESqHWHTGLEMnoPmRY=,iv:S/VnHswpYCKnDK0mTR8xMn+b2Q1nf5yUjA14TuuNItw=,tag:bEBPFxJK1BTkZWsMs3YQ3Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:EkifMPVufog4M/O8vgMr6zWxgDZVsYrXewVzvDA8BY+uzEguCcbV4y4ZSey+zjE8T4Y3,iv:dHqKmRZKGChZwANWXvwoPgUK3kgBIf198SuGYwLbOo8=,tag:uBynrC4GBQugInjiWp6VWg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:46Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQESlJywyqxpK26poilafkZ1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMypZkgSIe9Dxs07ANAgEQgDvhGVCLwLB4KmcD2Zh54/aDeS/uqAiVV92NbiI+dN5JxwdE0Raxln9XlqyGc/b4SlrqqMiiHjoMn0wGaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd2VMTFVXc0RUU05YYnRm
            b1JuTVNLL0gxUjdsTTNocGxlKzhva2s1WVdzCjY0R0FuOEMwd29OaC9aUGFKcFY3
            SzA5L1F0REdMU29VZUlLbE5FbHl4QncKLS0tIGF6eE1RZWRjYWtyUUFUU0RlSzFV
            ZEJ1djkrYkRBZE1IZTMraS8yMCtYQ0kKXLotzE8WWeHEBvo92lcn8p86MXxt7w6v
            H7FhhZySNjee9iMZ28MXLzJEUfecrivPc/lZh27WfgL1a7BNC0BgmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UmNaeEQzSFhoYmhXNnl3
            WnZXTG1NQXpTZjFLT0tuVWU1bjdVS2wrQVFVCmV0UmlXbnN6UkVNOGxFSmhGNUdn
            U1gzVkl5eTE2eHl2VDE5RW41ajJwMlEKLS0tIGxDNU5lOFVtY1pabGdQbXhpaVZo
            cTRsNHZtUlNxTVB4Ukc3ZGJ4UTl6YW8K4iXK5JyJ0U77QKq+LiYCe2q9SBcpwgmb
            iqwrr3Kkx159xC9m8BHgUIorGwjtGQm15aeiQG9vrMNwWGQL1kB3Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T19:38:08Z"
    mac: ENC[AES256_GCM,data:Al7FKOQEDy2LHAagPzN9vQvNMbK42eqdPhHGAGHF/vr+Uw+g7MaLu1d37STFFjDynSE36LJT0hDIXr20OlTqoAIpOpfQfUewMJMGeNRtsVnRk1tFPk72KFeqHGzaGRf9e5j0nJ7F0CfHQUkyi06zQVL5kdCFAdpiHz8PeO8wmHw=,iv:TfHttNi0M0/52wZ9//8Wb4n0WHhFk2r0Lk0mPLkEHM8=,tag:/cLLjtayz4rNAl0B7CCiFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
