---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bookstack
  namespace: production
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/linuxserver/bookstack
      pullPolicy: IfNotPresent
      tag: 23.06.20230703

    strategy:
      type: Recreate

    envFrom:
      - secretRef:
          name: bookstack-secrets

    env:
      - name: APP_URL
        value: "https://bookstack.${SECRET_DOMAIN}"
      - name: TZ
        value: "${TIMEZONE}"
      - name: MAIL_DRIVER
        value: "smtp"
      - name: MAIL_ENCRYPTION
        value: "tls"
      - name: MAIL_PORT
        value: 587
      - name: MAIL_FROM_NAME
        value: "Bookstack"
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: DB_HOST
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: DB_USER
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: DB_PASS
      - name: DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: DB_DATABASE
      - name: MAIL_HOST
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: MAIL_HOST
      - name: MAIL_USERNAME
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: MAIL_USERNAME
      - name: MAIL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: MAIL_PASSWORD
      - name: MAIL_FROM
        valueFrom:
          secretKeyRef:
            name: bookstack-secrets
            key: MAIL_FROM

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "bookstack.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: cephfs
