kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bookstack-secrets
    namespace: production
stringData:
    DB_HOST: ENC[AES256_GCM,data:+C6vUy1NdoCaBwVe,iv:n3qfb/PQWFU3J3VyVaNyPhtrdwSWMrwJDCqBdvlLBKk=,tag:I4EvB2IN3ieCjZ8bwZr2BQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:RpS592Y=,iv:jNgt6kc47v8fUTOYVNiUHQ0034MO5bJTXUDiaY+5EkE=,tag:bSgFXMczFoCXbLfkY98XfA==,type:str]
    DB_PASS: ENC[AES256_GCM,data:b4R16v1sBmilCxutbNiEK/8HQqkCpLyL,iv:EnOICQ4yiSJ/PgX7tVJo2fYPWCbZac+cIi8h0UmgQl0=,tag:BfPxAPFizCCls0Ls1GumWA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:jE4Vwp8gydD8/EQUOnr1mA7E,iv:Vh1VhgPS0bZ59AGIEylq/JO4KNBuVE8ooflrSKhz7Bw=,tag:oYmZBcsV1DIO341jvuJOLQ==,type:str]
    MAIL_DRIVER: ENC[AES256_GCM,data:65sFyw==,iv:z0m5Q4dZHyhz6s3CC8hKHi7dKJNygVzaUp296knKFmQ=,tag:JD6lox4s5+1rm1QkuCdS4w==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:HLrPuOJ6OSaRkKbAzQPNul56fMnFWgX2qyZx1BNh8XIJkQ==,iv:GS8kU8e/toiEvrnPGyUDgAbnH9iYMKuqG37x9UluBPU=,tag:WOUZmLPSnzhFVxKllHoskg==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:hdxm,iv:I/8X1Ru9EpwnwU5qnHjmRkFUUlGZaV2LxqWY1pH++uo=,tag:5hro7Flai7H05Plt2PcaJA==,type:int]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:yk+E,iv:xJnSM8GUsxxvTfelgr85IDtG+yhabCVniMme08Q+HRk=,tag:sELtrkGap1doN4aJ/+WvsA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:PE8DYeBzoSstWb17D1SHAE5hIvQ=,iv:7a0O5B0JHgu2x+xsE3PDdQdTSjLDssbsnYkp6VijjYE=,tag:RZ8fTXxAWcSbhfqNfhQHow==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:EAs+PBRen/5dm5CjbAxXyGEHg2Vr25jC/dvjd6nZDOMSvTPTrY53r5vjEkU=,iv:FKS3DHpBBey5OKZYbDZpWMqMp50PXHr1ETldFRypZlk=,tag:Q1JrFyIMIUPms3lr/PkHsQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:B0MzJKkd2v8ILH6nLLTvMIyp,iv:U5/qDo0Ap8KskFxIzPgWpQt1M7ZEZe5Fe5/++9x9ZfM=,tag:q1QUPB58hq1iFy+7WjYiRg==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:+dqo/PzOdNkr,iv:mTrFOEkWFmfy/zYpWy4fzvZarcXotxrGRUDTxPcL6X8=,tag:WFLC0PJJbiTqmchOGPpguw==,type:str]
    SESSION_SECURE_COOKIE: ENC[AES256_GCM,data:kVlg9w==,iv:hMvGm6+PFvUMjhP/iHMRcMrbJpfeeBCkW7Nh2/H2w5k=,tag:6sUpNEkdICM2bnYD2I3iGQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-12T23:40:59Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwHfjThVEiWl9EWtm5n/TjhAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsrazlhXhXk2MVbcUAgEQgDsAPtaoJjzGdr2CSOaHyhKCwTSb+czJzByAir4hOKlnOm81ASiKVh1twow/I4T39Bv6SrWueh/oHsaDOg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdCtQZTczUnc3TVREOGVW
            RlJaL0x5QWEzb1FRZXp3UDRrK3NwWUFJN2drCkViS3AvcDJha0RHT3NXZVREZk1W
            R0hyUnJMMkZQMHBsUG56dkJnMkx0OFEKLS0tIGJlNGFza29DeDV0K21GOWpvNG05
            dWF4SGtiaVVvQk9udERzMkRIU1pKVUUKg1AlN7hwUDW9YMEQuu0P8diJSMLsm0+E
            +4TEa9/AMJJpG3ZRBVzH+4gmGcpWwsYZ7QPDEPgKGbnsFRjeuTgY+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T14:38:53Z"
    mac: ENC[AES256_GCM,data:izTtUe/yJGAleyzwrWitbDFRkV+RkEhLRy2Zu/ubVdhlm3FJ1ZuPQ9Sf71lmX3kTBbL+fFUeYu6g4kmBOoFAmrkBbqk4WoFb4gWZMVwXEtb4XhDt/ZJW8rAwMDPAdjxK4USJKzCHtlRwhNQEkTWxoFIRk0lwe/Uh/O3fZ77tvMc=,iv:+IasflOo7ZM3LvrvofuQ8RaVdrkHmS3Xlk3y1gzEaAg=,tag:YEHEUBZPRtYxSz/XrzFoXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
