kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bookstack-secrets
    namespace: production
stringData:
    DB_HOST: ENC[AES256_GCM,data:Iyw1r6nxm4l57de9,iv:TeNwGen7rOZnV0RfD/gXGvWS8r8fMY0P2arh/6W7k20=,tag:V7dr4R5bldygGRijx2O+hA==,type:str]
    DB_USER: ENC[AES256_GCM,data:7iKlh80=,iv:pfUDmrjjuwQu28OzyNz7agZzyRi8z5SF41/LT+fSjW0=,tag:ArtvVBItsPA9mhLI3v2jKQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:6Rw4W/ALOulG82weI8Q4+uKVXVdhwb/m,iv:EfrGQDAc7SXQBt1CoTmgkK5kL/UoZ67w5mUhx6JUrHA=,tag:PzVDJixBM6m3YIFhLTzoxw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:m5rjM+AQyeTKKeFdGdGW3gU+,iv:EMwnVrh+pl74Kujy6fEvUxDLFJfjOTMqsC39D4r6vb0=,tag:PDDtCA2CnS1KHNGWh14b7Q==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:MlDyOWpLR2pv+Xi98AFed+N/XQN6Hsv8e46sYHo5sFv/tw==,iv:m2OQ53zpyz99SzaGJCG1fbzqnZOjT66672dZJncuuC8=,tag:BsgDGJyknH6bZpUYgPES4A==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:iU7ql1Z/e894WqJiuIvzMhrMO4U=,iv:wwV0YNcUGnxozqErFuMPEiYMp2QG3iggAKi8qGmTHPM=,tag:Yfw9CDqQlEIbiZszWEwb3A==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:fTXITMkEji2fo3s5wSv22Rj2bziobGR6r2v7AjGdeAxYdHs9S0AQ1oUQm0M=,iv:YmbjA32bB45fGOojnnFYKkMfTQF7TBXiHVM9hwTmUHs=,tag:j14ktsXcuMUtWarE1x5iXg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:NfHNmITfb1u2WgEEjApiWn19,iv:ke47yLTgbuSm4jlfY79SgPE3NGKMySdmmY2LrIHh0/w=,tag:ttPifaXGt3wWLompf7VNyQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:14Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHS95ridHsjzbQxFF5SwoC0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvJ9ROQb99EM990ShAgEQgDu2f37JXRGotSLDaOGkmFv9xVG/KdSqVuMaK0ACn//PCYs3IW25zX6FVOg7GNW46ys7B70GHlXrvftobw==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNGE4MER2N2ZjQ3pTVjMr
            dGJQYTJVT0ZKODVGTmlYOXcvSDFTRHJoQ3pVCmVoZ3liamc4L09hUFltTk1NKy83
            cHdBUmNQV1Y5L2QxQjNJNDcwa2lWNGsKLS0tIEZTb3lTUTloRXFFS3p6cld2dTlo
            eHNYU0N2ZU5wbzhjTkVGZFM2djBGdUkKL9LPSSa7AiaYMAhEVKzkW+MqLGtijQEk
            zYhA3fNB78VAJHvnYnMJFAiRVXl1IhiLiTU5IDnou3kjYJXrt9RcZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:16Z"
    mac: ENC[AES256_GCM,data:QQsBAw2q+2t3I4W7hXKj0fXQyue6ZHdXZvhlfomBv44smfXGuPFed0EhYMVZJ96E8pJLF+5R6xIxJHaqctI2u/ERlfFYuvvSL8hdZATKiWkSHkDJ6me6xfE5R1SgxuyiG/RBWTjXFbmi1kv6OWATwA/RwLDNpQdILrloJTfRWSQ=,iv:9qlQanSQQe5hxMv0WvMabhSkuGSWDuf9GdOBOCrJMWw=,tag:Q6wNrjRZb2684C/zdgrpkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
