kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bookstack-secrets
    namespace: production
stringData:
    DB_HOST: ENC[AES256_GCM,data:JRgNVZlTfZVxS/UL,iv:5jFKakUcvQ2LkbaB/ruf7Joa1LxviMxNnwzFIOYqFTI=,tag:KivlX3OUdQ5cWIxrJ8+t3g==,type:str]
    DB_USER: ENC[AES256_GCM,data:LetXQ24=,iv:pndIOE3A2cPVKRctCKUN6ORoIqOWcgTXLkhs+na3W+g=,tag:DXzs5Aqtvs3lT/6X+9HGlQ==,type:str]
    DB_PASS: ENC[AES256_GCM,data:AhC1YkKMAjzcpaSUuOoQJHtHtrx+ckiq,iv:a+nJJWmbExI0SOxqCaG4jslZChhdWWaFB0ejbKuA++I=,tag:iw2+yk336cmW900WrU9WXQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:F7iQUY8z41q3TZXRu1PH2S3s,iv:pXWrc13EBahjz1CfVZ7LBCMsnhvHsPNAWGoGm+EkA1E=,tag:L8Z/kipka367Ijw2JA8ngw==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:aJ/Meew+mW12Dd/wn5hIy46bH/H6l2Po5xjsnOADCzNEvw==,iv:pmZ6BUQh1VKw/uVkefmnX6t5fzcRxHhj7LsekJcJGTw=,tag:eoB1Bmz0HcMtaNdc4OKqEw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:uRjiOO3urupZaVoHiTLb60esQNs=,iv:/FAK0QsfTFZ5UceGaBUGR+MNPpb/doDXqyqpnmxpi0s=,tag:xcft4R7z9xHScYbh5j5vaQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:KqFo+AZAZKbWYNgiAYFaTI3WF9qMc8u1FrGS80eXwRMJCjVtww6ZCwbCLPo=,iv:46iicleihiFFHIdDWq5773ru6pejZJSyZ4b/yOikUoU=,tag:kqrkfcplBzMal3q0mk1Flg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:2GBYxlgk3zCucbrVco7uSOn6,iv:yYy1KU/jXb3pqnqFrDoC0kQ8PZhnUORZDI2mr7YTuvs=,tag:yvizZEU5tm8h62VjSTG9kA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:36Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGJf1WgaQF4lrfTdjWWiORRAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPOCsyTpHVnDnOtlVAgEQgDvg0KbERnAq2YxSYDXwmkv3fS+GW3BdDmURWYzxkqX5rDF9C9VhKjCE4dQ3ShE8IIW53lsxOxtUoM+nzw==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK1BCN1N2S2hXVHNoblRG
            SzIvQWxhaWlRd3ZycjBYdks4em5wQTh1T1NVClpyWTd0UHZsdi9YemdETDd2Yzlv
            RHpXbCsrMUptRko0S1EzeXRxSHhDcTgKLS0tIDAvd1o0bzE1Y2twWW5BRUZIOFdQ
            NHpCQVZOeGlZZXFKTHdKYnFud0RzWkEKcAKnel0o56k4d+BgcZpYRip47CkgTqDz
            kwy7prGDj58C0TxzCkv8o//evmjeBsm9nfKrUsQxgcFVMRtxN/V2Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:37Z"
    mac: ENC[AES256_GCM,data:P9TjBhTt726FabmhJ3jvOh34IODN56FKYKwefFz/ou7xjGAP7eyzcZfmE0kFlK+huu7K4U/oxDnzkMOrjXvts+lkn0toqPfgkRm6LYY6draHz1y9ephGkrzUv2bzksPlhTYwbgA3+Yze0cZ2gEKtvTzTvtjBg1z/VEPsh2PGjwg=,iv:aYxobIUw3uNUKxzwEHq31DxXdmz4EkcN8jNm1+HbtFY=,tag:MKjgHeiBTFoou0zl6OvH7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
