kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bookstack-secrets
    namespace: production
stringData:
    DB_HOST: ENC[AES256_GCM,data:ARAAbMm0KXECCYpD,iv:LbbLYjH3/0pR0onryUE++tJzQC5OwV2FT43+MiqKafA=,tag:0dkJNhJ2UJzK0N+xYpespg==,type:str]
    DB_USER: ENC[AES256_GCM,data:xtuOfOY=,iv:SPRbWdnEfJMkOZiBRdhHHG3nCTxAIZzuQdV6mZOuyJI=,tag:eqgpaJ1iNMo+7lLFTueWRA==,type:str]
    DB_PASS: ENC[AES256_GCM,data:7HrglQ1bNOK1myYbJXTZQhmJhagd6zq6,iv:O2D1mLb9W58lV/1ANaBXlZ1JQiMYNtvbmuIboL677PM=,tag:dkXHJlHAVXUkD+DDZhHGDg==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:Ec75sCVSnt5PZCsQnSr5FuzM,iv:k7F5kZoMCajj7Mn+8kRxSgQP4rF+SLNPp4XAJ4RmyBQ=,tag:Dozwxg4QRv3JDSoYtWMJMA==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:fkRJFi/YtdlbdyqhOgH2eQaKZE8dFdc5nk4bPIDuHJn0EQ==,iv:Sxbmg4b3339PYbbaFpnJFW0B96/kNaU3LQSbeyzlTOU=,tag:g1cs1aZVxSVlXwJyX5TmUw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:JRHwLNeR0HLtq1tIHU2pH0LhohA=,iv:FxS/M0rlbUkVCjNNZXcje5ehUgfWk6bMcSyg0LVjPXs=,tag:yKO4UI3Teex3hvNMRchH6w==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:u5jW26beFCIj/9xMsLTXz106QJOLHkKLk+bnpgyop47ImJCAsnaJqIKf1DA=,iv:6FzphjwgsH9yP2bZVescv+StWyT8+l5QtAexcnbMh7w=,tag:2ErzxH1G0WA0jbreDY4KNw==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:Oygny+gg4I7y4hFyOLbj/5o2,iv:zR8URdd2qZEfLlVSyWplgSMZGaN5WTeRcVRkYVg8gOQ=,tag:d8pnHU/0TZ1rcNNjuMztmw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:41Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQEVNwJ3sgkPAXPIfrA96GBsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMprLhGVrrUt8YaKp7AgEQgDuL0iOeUGMa4+5H8z2pGRzBaSbS6RWcmNcPJoyOJFS2OafRzgS7jEXIFczNGzasQFCH+1ZSj2qAw0CrDw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSWVOdWIzWHFMeWxFQk1y
            OE1saVBNa21DYkNmaDk4UUYwWG1hUWNkdTNvCjdGdUc3dFdRbXVrcFRyZlVSRG0w
            aHU4RHlrNnJETG5EbGl5RDlqcTVqbEEKLS0tIEJwMjRmNFhSbThrSFFuUnZQR0Rl
            dlRVSnZIL0pOUGp6cExzZk4wam1wRFUKTRVXklRQ7q73Zi3QKJQWEj2/EDE/c4mb
            Ry41Xxr9Q9pJHeq6uIw1QlgatyBrcH+OPaht8I1tDxaWIvvJVkYS/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:42Z"
    mac: ENC[AES256_GCM,data:zFlKK7f9y/J43FIcRuGZ6SZ905XrfdYpcN1/6kgN8KWbw4RmoKSMuAZT8kgQxOM+Ew5nU+Ro2NobdUX7ojrTzA1rMcJBEOzni4QYNNxQFjWqqCfn5CWzUAef3f4hWOOaejyHEK+rL632DXFz8QJkD1db4ySVNzPyEYyc/Ab0elk=,iv:2D1rry93UmVDHqg/LZZGobahQU3MgVCKLh8+DhvUiwM=,tag:6k52pOSQqw1x3SG2XSu8ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
