kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bookstack-secrets
    namespace: production
stringData:
    DB_HOST: ENC[AES256_GCM,data:x6f13v4kqoRz54e7,iv:zQj1UwoaBi6UBnFTZfMMqHUnKK8FqEaPm/n3GMQ5BAA=,tag:0848k96mLuiS9mFxyZ9D7w==,type:str]
    DB_USER: ENC[AES256_GCM,data:mpmOArI=,iv:71sCeH3WQ0yHDIxJg/qdgo8QDgev9XMsWc+l8ViIdpM=,tag:Cfi5hFEcjuzAb8eFYXKLgw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:HKy8Y7+q0+8O84Vtg7sBuzbSLHlWlF2y,iv:4jboq2Hgo1vFoQnF/4/ukaN7kszu3BwdOdoG8Dq6uGM=,tag:QSrdunLYyOe9UZPxZOjYVw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:FdfW4AJSYOZy2j8qWqzY/asr,iv:5BxWes3FXHLyyfr+1ZSdNvCqD9r9u9yBeKy7kfWK+ZI=,tag:Tp3tQkY2tjDH9f4aATQhxg==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:KCFjeLs7jevNOCa5W1ahtBIQrOhOIfPs8tjLrweF0bOwnQ==,iv:9K+2gZeirOIBb+lQHmgT4JkKodWRkwIkfJilKm0/vB8=,tag:0G0SQ9TB52fX5Gw07gHpjg==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:HCvtlf3ABve3bTtVgbY2XAG0hrc=,iv:vg/h5to2i7+qnj/ovgVCu/T0a5xmnm86kVZGt/4MT60=,tag:/kbDXFqC8fDh1APxkTnQAQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:2L4KkeW5ThMJzupEjhIa3yl96eGioplksrq/xv4SSa4oBbJxdGjNMvd2wfs=,iv:yNZUXDCE6A+xTaYeu1J0HLouIEDtFHhBvKQ9SFLlWZ8=,tag:BMw7oSV76Papbb40IAeN+A==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:C1YB8IXCRtZOc1a2bSr/fk+h,iv:cbGEygwcRvOgvD9m9Zm8KPEJUMP52rRRn6p+UZwjnGo=,tag:YERuSP5+ZooNaeTjtzZLlw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:59Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwFqS/h/oD71fGBkXNVHOeiCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMadIwuj3zw6wLfNfAAgEQgDtSUXPP6KGgeHqr4CaIrzyG1/PKrYWYh92RkGTQSvk4ucx0MdDR8E376c/aezKYGbX/ZY7OkfGf6IGF5w==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNUZLei8xeDcxZFdLZHIy
            SzhQSktYd3p3MHoxd1dyMUhVNG9FZDFpYlI4CnU0UW5TajVaOStuT2ZPd29JYVll
            QXQ4RnBJL1NQeU1Sb2ZtdjRDK0ovVlEKLS0tIEpVclRBbnBmcENkYWxqNE4rNVFv
            T3J0TTZMc3A0MUZFeVc1L29XOStuR2cKXplIVTsCRKEAn4ZnJSj69EwDz6TCAVS1
            +CN5qmgR36jIKZ0MgWCcArRfIP9lxBkAzquJxq0H3oHdD6SWyq4UXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:10:02Z"
    mac: ENC[AES256_GCM,data:E2ZfIwLiBNZi9Jg2hGF5d611DEpCVW4MQAYL6M06VeE7gddM2hGf0EwApPQdBzY45IrSw/fB8tc5yp8jrGrZGyG1tm3uXo1r5aEcHFrKcIl6Wj7DaYzFNsN9JVkgi8YCrBGIyEWNeCYdG2eJv0eYDGJlUXndYAc9HQloC0riNPw=,iv:h1PPwjlzVywxjALxB2AjEp+jDK+ux0BPAA5LWITJPkY=,tag:bgiDPwSkL/8cPFpkodNYfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
