---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 8.25.1
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: &port 8091
          websocket:
            enabled: true
            port: 3000
    # serviceMonitor:
    #   main:
    #     enabled: true
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        hosts:
          - host: &host "zwave.tnwks.local"
            paths:
              - path: /
                pathType: Prefix
    securityContext:
      privileged: true
    volumeClaimTemplates:
      - name: config
        mountPath: /usr/src/app/store
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: cephfs
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00  #had to configure this serial port in settings manually via browser
        hostPathType: CharDevice
    nodeSelector:
      kubernetes.io/hostname: "sce-uk8sw03"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
