---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: zwave-js-ui
  app.kubernetes.io/instance: zwave-js-ui
