---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: selfhosted-apps-obsidian-couchdb
  namespace: flux-system
spec:
  path: ./kubernetes/apps/selfhosted/obsidian-couchdb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 3m
