apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JDTnkek=,iv:Ma+CshZvsbAtQHE6x6pNa8qsRzbE6M8OSYnJHzXuLQI=,tag:g277MAFXFIOvHRsg4/DiyA==,type:str]
    password: ENC[AES256_GCM,data:4RMHRXbU6a+9pp6xHh637sKW7+KhZvK0JE9vzqBF5K0iDlLKSkBMofA+GdyB3qm+L2nXzKWokIkephNS,iv:UPmBBqUNgR3zUMTKnSi3okjWYtuaBsWJowvT1h1aHYk=,tag:XVDQbgQ+Qe8LJQFFYLIjyQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-30T15:14:37Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwG6swxKcOZM/seqWgnmZoz8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdG91y2nA2ZL/kO4qAgEQgDtuA7wLx7gfpJlUoZLgMyTtxV1h8i0g7mD2e8x3IkSxqwv1Qlz9NgarQ9Ya8K+rVmTq6NiKU5hgE8HE8A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZUZzVnRXRGgraVcveXJK
            RHBFT2htNjliK29pYm9jaFJzMHlwd3JvY2tZCjZWTzNBOG9sRmlITDJtS20xQTJl
            QWpGK2RNMnVmYWV5RXVWMDFmcWdtVzQKLS0tIFh0RCtWZFJZSGVTSFlYZlJBYkhn
            Y3lOdEJTVWp5S3hSN0xmYlhVTHRlZjQKFXw71UR0RljIVBKDRwpVzcijGkbJ/kwR
            bPxg3K+C6QPKChD3wjfodoVxXM6YxnY88wshfqsF6hdV3/KxZXKJyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T15:14:38Z"
    mac: ENC[AES256_GCM,data:ABYDrrdYKWtSoauPUBTijP3+S77uo5yabFbAtGHErbrQi9zeDfIhNPBHbRD/3jJMjJm9xcRIaOUPCHo0mcPiGPWo1urfGripPEwr7ZhDdp6Drs1t438V1MaobDHDDo6hNnQE6fK1Mhr4k96pRZzjiauQ2a1B0ncSwb3iPdG6G4M=,iv:bpPOAFa/EHeajlJoY9tbWzvKSz57+FX3fCHf34T7HDM=,tag:b9TlyW7S08sobGHMtO5hsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
