apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:H6eP604=,iv:4dAJFFBoNAxBFLtpCazx7xT+ID86wf+oLXVCmVHHYjw=,tag:D5OTjauCFCm2ej+Uq2rgJA==,type:str]
    password: ENC[AES256_GCM,data:GktR3XyX18sgjMmyN9CYc3kebw+WASReEQ5bwY+zEalP74Ve2JTXKdel7ml289j7bxwwPQ/RX64/VRVw,iv:LZ5YXLSTlXUaiDir/Si00Ng0x3ROjCWbgZ1F+Ay7vaM=,tag:qENVI2C1b+6LXfcD2zFUKA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:23Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwFnNa7agnM9EYrVUZuOuZYbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2CIXvvtoldXfpICGAgEQgDvMcL3ULkDSOZNyV9J6Oq/kBbwjhLaWHrzXn5Vs9xi6k23kKVFTOwC8RmoSATV16/rTfA7O+f0EuLmwHw==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMG85K2RQTjdRTjJXV1B0
            U0tBSjFrd1NRYVhNeVVFU1dZRGdPQzNJa0VjCmc4cWw5UjlCcXJidWp5YVNXYlZN
            RW9EZlhnQlJrTVhMeWZZZHlwN2NPVTQKLS0tIEl4ODN4c2ZpeGJiSW9HamRvdmpG
            U2dLc2F0dzhoZDY3b2RPM2F4ZVczT00KJ7hvxHoOWH8MB90YAJ/5ZhlSdrQnbqtJ
            M1rTJABtZhRtdJKDksA+oWWh/T0Gy12XeZ9SI2JX0KjAlk07tFQIkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:25Z"
    mac: ENC[AES256_GCM,data:KU+jILSMuRDz+6cGePeWfgHqHRooJeUAyAM3xdTSX/J3iQ+tSZ+/5+KhFg0kpYBECknKpjjpINjMaT2mgvtAD1BTbpQpnkSPYE3gLSlmSPNp3gI52jKsoZozXekZxz93OR1vEDoLkNoE6oCG+Modyt6op+NfLUf8gzFvOMORcvY=,iv:rudFopvrHyClNKGVpncdObLVrzsp9h8wijt2XWqZ8i8=,tag:AEUPsLHjdkrW4uXx68QvXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
