apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iNbdp5I=,iv:1QS0JjtJtUd+eyJPu48hu2Mahf1P+VCCywK7dnkB3es=,tag:AmwXND8arW19v0gY1SWa7g==,type:str]
    password: ENC[AES256_GCM,data:0nywjYDguP+XutMRlaGnppeLkTMW4dI24Py9niyfHiLh0pm6NgBKon5A52IdqaAX9hTnmPqKluemjJw2,iv:eMD4Etm2k956ej60bDfm0PEhW7Vy8l5GnX+UXb/9coY=,tag:awEdUA0G3SibSmZ8Kjx5fw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:48Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHpzu4hCGZ3Wi/xa5htPS6MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtCrqPAJJL8TtRXEJAgEQgDuGDoBvwj9ROT75gzo9n8KQFkcK7FBj0eGKPYt6HYhjoVPJEZteb7hA8MB67qJ5W8v4l3f9WANyOv/RoA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT2tvaFQvWDBHSHFCNFFI
            UXhwZlV2Um9kYmNDV0psSXhWSUs5aUsxMFRrCnlpNGVGTE42VzJtRWxBMnBhWFpX
            eTZaZCtHbExNd09DY0NGR3BKZ1J6U0UKLS0tIEN6WUhWeFBiN3hac3JZWEJvWGY2
            b0FhWnEvdDIvQUlkcTZDMmV1a2JzUDQKlI+v29qTqi3cPDCuh8pm0fLJFBcDyG0L
            u6+deMaTYtRGET0ysK0etAIweLUHvbqjrxdjwyiFsFZsPcJ9+3MeHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:35:50Z"
    mac: ENC[AES256_GCM,data:E1YEdIy8QAEqIzYw4ZSUoj+kN5vXNHHIiGdwIaLV2sbUwaP9VI8OO5cyBAbUPhOt7dI3WiXxa9VWIGwD5kIG17FF5Ez4AZu9rpYgfplKhB+EqWXSRmJdJ/nHKw2vofG04LcXQgpdXbvkGcaJ5e6PEPTVAJrL+omgsIjocBNP8zg=,iv:wMIGncya0pS53mSrxsitvkRg2m2ZVYroirRKeJ0JAeg=,tag:hS3EjncAaAH+cXXilVYZag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
