apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L8XVCQY=,iv:HdiqUwZ+Yo2WdSBw4RWLzaSFVn06uGqkYJnPtSVhXgI=,tag:lEkapOhHYl74pQ0MUEhKmg==,type:str]
    password: ENC[AES256_GCM,data:9jG240qA76BDwUH82rIZlcKKUKx184RYAcqOk+5ClZQZtCvDzIKK74mkTti8y/eWr3wE8eKPRzwidxAq,iv:B4EnH+Qy8uLlxHLRCgC/VAEztiikxYFMz1ZdMNjJCW4=,tag:fNEL6n4cx7jk2hu3WWsUhg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:10Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGlWi2T/tSiRCoTfyxQbZhBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqwxMHbQiCY1vRG3aAgEQgDu08YOqDNXO7gmzmc2BwVYDrhfbz7LfxhnOZSLtq5ZYs8X0WVU9UKQB7ic0s/kw8+tbLKcKeIp+t9B2Cw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WnhqNVZzZitaTElJdndO
            dVlvcDNVYTAwdldlR2J4dVI4VTNKK21tN1M0CnVja0VyT0lhUVJpS0FPSGphdmF5
            b0k5bFFpYndFVEZseGJma05TV0FwbWcKLS0tIGdrRzh5eHMzMjJBUzJ0dFZxa0U3
            dHM0RHR1eFZ3aUxGekgrRWV2R2NLR0EKzfwUg/j5voE2bq33ZQhzPud839GPHOrB
            6vz7Gtk1fp8yGkL38uVFELtUGu9JzaY3YmYMC5d3G4yIT0U2TiMDVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOWovVHZPQWc5djZhb3hD
            UXJncVdraUl1b3FuTzg2RXkxNEhUcytGTURRCklzekxyWVk2N0ZNZklFU2kxdTll
            S0preEovQkpFZ09uOE5kME5OUkJJdWsKLS0tIEZDZGlYSm5iQVRQOFhlNnZMRVp5
            WGxrbGRkMVZhdlVVTkdGRzJ5U3BjZjgK46+44J1KDs590eq1tiJ5I/RraIMOxqcL
            hgB7fP3y4IZ/i8MBCPc9+h9jAWfE5ykOYqNm8sytgBuHhVRWpVkMHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY0U2cEFIQTM2ZlJpVUhW
            b3FhWHRxSU44K2VDNjVaNmRXNkIveVR0NEZJCkJRNVlqcWd2T1A5cWplakxxZVQ3
            ZVhoQktZYXRwdjQwNys0MlZobnZPUHcKLS0tIE51QjhibnVjRVRoWTNvdWNrby9a
            TEtqTDRGLzhERGdZOUlMTkhNMFNZc0kKDuMbZIkcM6jccdRE7quW12yiFp73AnZK
            uuv6tKXoOpEy7o/sz14Qb9QeVi9TG+OMC+m92w6H7NC/r26vCeknQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:44Z"
    mac: ENC[AES256_GCM,data:H23NVO3z+4Fz2UBaSV3E9OAtMzPRMCSuCsXaDMJSzdsdptoGyVLvrJZuEvBa+d+WZREABe0XE73XWUWFQwhhc8ocNlaST/KgGRoRzLUWOSjAxyL+wITiCFXMBM2NNfzmlASxLHYvtkr5upO/IoFT8JcTBfa4c+rf2qVcWGo7hO4=,iv:WhN+Ct3L9QcCczc+ZU4NxH8UIXcB6e/DTeT5caICV+4=,tag:/darWq3y+9WMHuFOUr3fZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
