apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:EXEWICA=,iv:Ci/Sql7F3LqSqF748/5//B87Ca8Z60QPCBgL6P7nBSo=,tag:N5REsZNG9XxtIt+3JS8RKg==,type:str]
    password: ENC[AES256_GCM,data:0lhg6az4hHkklxg34sDjJKR+Ymu1CLD1HbLNgqTpWel5i7qGgFEUbgNYPpxaSet3aoB8rNcz2nfYUZbz,iv:hKpxsPvIB4GmRDRXMnEHdOrsEPxdd0gErhxoq8dut6Y=,tag:CyXp9sdgHcKM966xatUFNg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:37Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGCJwHRoRnKokjiCdozUMKPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0dcngEiIo28nJBv+AgEQgDuvJjLMKp95cN0gS4FI9I+Alix/z/SpTM6zFxR66cW9BWdj9DpVGlQOtxVV2TozM8IxxiN2TyPBj/NSMw==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRDMxWHJkUDRCSzI2aUZl
            TXRqOC9OZWh4Umo5TGJkU2xCbkYyMndYVWtFCk00TGJQdVlxRnVsN01BQXlBcjRV
            OUpRL3Q4WEtkc2UvNmtSc0REMTE2bTQKLS0tIExkQWhmbWZXZ1NuL1pzbGRZVDBa
            SkkyRE93YWFIbTNLcE9FbjQwL20rNFEKRZkaC1fgmvn4pNSqYj2SWqYKBJ6R9Ty8
            gNzNWLl5aTm/LL0l+ATF2/YzEkYHXP3pBZUtihVQzEX0jyItKgscqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:38Z"
    mac: ENC[AES256_GCM,data:Fv8aVxIKv0mdYvSf6qMrsak13ktrUBR5ZfT4PxP71TcyYobTzxpcc73SWUnvon0F+ZQdXAMy09sWN5VGP/345Osq+0irh5wlKUm1zbm48hUnTO779iNsrZI8e3oaeP6Zum9Zd4FncBaUyxK4HL1ZvEKJwOhcXikrx5ty0lf5j8c=,iv:HPsYiFLErxyV0YYXfjFrJpA0MEpimJlhHOcKZxZMPkk=,tag:19UvuHntMOcLdwBzKxODfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
