apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L8XVCQY=,iv:HdiqUwZ+Yo2WdSBw4RWLzaSFVn06uGqkYJnPtSVhXgI=,tag:lEkapOhHYl74pQ0MUEhKmg==,type:str]
    password: ENC[AES256_GCM,data:9jG240qA76BDwUH82rIZlcKKUKx184RYAcqOk+5ClZQZtCvDzIKK74mkTti8y/eWr3wE8eKPRzwidxAq,iv:B4EnH+Qy8uLlxHLRCgC/VAEztiikxYFMz1ZdMNjJCW4=,tag:fNEL6n4cx7jk2hu3WWsUhg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:40Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHuSo7PBUDtC3O7ENjSa+uAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMw2mpY8S1fRWVh33WAgEQgDv5hc+zDk2lkoYSkgeusnzz5myg0MSeWM8T7gf6x/c6PmPmtuHCL6YUKQqtVA6eHAmD5p9UAWPKC00d+w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc1pFWjlXaWZPbXRTbi85
            WHdHeHF3S3Ivc2pTYkZ0M2p3NmF5eWJZazJJCmMzQWFrbHhxc254UXlyRUVmM09V
            QnNIc0g1NzRKSUkya2d3dG1FM2pVL3MKLS0tIHowUFN1UW9pblVXR3gwTmFJQlUv
            RytyNXFBblpTdHFBQmp1RnBmOU93bVEK4hc7twEv1ChFxFgYXyCenvVV0u3+6HRi
            nNcgdcF9KcdnqPggG7mHy4RonwFM3KrSAYmbB3h+kqqdzPUGDv2gRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZUhUN29aS0ZVc2ZZN2o3
            aEhqRERTK1pnZWRNZGZ5TkhTVnhUS3NNeDA0CnRiY0RXMWFxbG5rcmVodGIwdWhk
            MW1aUDhFUERHdHc1R2F2REdlRmlmOWsKLS0tIEpLV0ppMTNSS281dDdOZm1Cd1Qw
            T0lIWUE4akFIeVpXS1Fkak5oQ2tWZU0Kc0NYVb0RKuT7QaCPUSAtJgBBh1xIUr7P
            0ATmq26m5Bs4pD2THO2d5XoqA6JsLCBy3I4UEjTdzTFE9VN/Vk6KRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:44Z"
    mac: ENC[AES256_GCM,data:H23NVO3z+4Fz2UBaSV3E9OAtMzPRMCSuCsXaDMJSzdsdptoGyVLvrJZuEvBa+d+WZREABe0XE73XWUWFQwhhc8ocNlaST/KgGRoRzLUWOSjAxyL+wITiCFXMBM2NNfzmlASxLHYvtkr5upO/IoFT8JcTBfa4c+rf2qVcWGo7hO4=,iv:WhN+Ct3L9QcCczc+ZU4NxH8UIXcB6e/DTeT5caICV+4=,tag:/darWq3y+9WMHuFOUr3fZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
