apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:OODRMmcXC6l9uWqa/vBJ8wgBIRbjYByer8P7ifE3VGgnv+tzBDkApWbEZm1xXA8pjKfWWoWs3yxNCZRm,iv:dJEH6jw9JLp3RQgzS6rMLBq2x5uL6B+RcFh1a9ctFCY=,tag:id3YWCR1FdK+TZPLowJn6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVGl6SmRvakZ5cHBEcytn
            VzVhSVFQZktIYWRRdjR1QXo4YngxbXZIbUNZClRGb0NaZU1XYnc4WWdoNzNzR0JP
            RVZlaWE5UkZNOEp3MnhTZlQvZi9kNlkKLS0tIFV4MFdwY0dMb2ticHJtZkpiekdQ
            c0krQStKZkUvakVIZ2pDTEVmVk1nNGcKwHwFZMHPx+Gr9kNABWRkN8xqOqWh2IZE
            PF1A7fHRwkkabWdW9i5y721uaRRPTC6QeVGVlB8F2tqlZbEWLvgYeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T22:56:21Z"
    mac: ENC[AES256_GCM,data:YCzt/+JhFtH+j7/XbcaTy7rGfJfcLJFIsRJIft2Y8wwIB3Eja5O3ACCrl2csnRhUmeAP9P32OBJdrMtzHD4GbHj/ERo1XqSSD8sztPScjFPIcQDpPj4qRPT50X+CecjJ2oNH8mC9BvR9GZmEuPWEtfR7RCTZxNlgInwYnQjWDLA=,iv:hiRjZW9o5CRV+/OANn/G1vED7RDd88H7Dna66E1dK1g=,tag:UJdhidrUGzMP6i738+lwbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
