apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L8XVCQY=,iv:HdiqUwZ+Yo2WdSBw4RWLzaSFVn06uGqkYJnPtSVhXgI=,tag:lEkapOhHYl74pQ0MUEhKmg==,type:str]
    password: ENC[AES256_GCM,data:9jG240qA76BDwUH82rIZlcKKUKx184RYAcqOk+5ClZQZtCvDzIKK74mkTti8y/eWr3wE8eKPRzwidxAq,iv:B4EnH+Qy8uLlxHLRCgC/VAEztiikxYFMz1ZdMNjJCW4=,tag:fNEL6n4cx7jk2hu3WWsUhg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:42Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFXaMYRRawHl24hibcx9puiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQML7mlMSUxg/qWiyDSAgEQgDs4qGApk1wgnJ5qbEH02iDSosISwQzo3qkXAAUIiizzG/Zznatv+2AblQrOdkTpek7RffOMiSlCwyFw1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dWozMU82ajZYQ1ZtYU5r
            SFpLd0pQcHFpcmxlZHd6dXhFa0JLMUE0WFV3Ck9nNGkxM2dlRGJtWVVwQSswc1Jr
            KzBoamNFbUkrUjduVHFBeng5U1I1OEkKLS0tIEx5VThldThxQ3dxdFJrb1hsQ2ZS
            Q05mOEZLVFRUaklZbG93QmxyQmVLaFkKEWJQGjpbmtvel//CtL1vkJMzaqQ358jH
            LlgKlUF6vlNby2Ar8DdwwFwrJXQV9LFlaLQRK/huVC2B1CnAFOJTYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:44Z"
    mac: ENC[AES256_GCM,data:H23NVO3z+4Fz2UBaSV3E9OAtMzPRMCSuCsXaDMJSzdsdptoGyVLvrJZuEvBa+d+WZREABe0XE73XWUWFQwhhc8ocNlaST/KgGRoRzLUWOSjAxyL+wITiCFXMBM2NNfzmlASxLHYvtkr5upO/IoFT8JcTBfa4c+rf2qVcWGo7hO4=,iv:WhN+Ct3L9QcCczc+ZU4NxH8UIXcB6e/DTeT5caICV+4=,tag:/darWq3y+9WMHuFOUr3fZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
