apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cephfs
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-9fd50c88-129f-45e5-9368-efd3c729b9fb
