---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-hdd-subvolume
  namespace: production
  labels:
    backup: "false"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "${STORAGE_CLASS_BULK}"
  resources:
    requests:
      storage: "${BULK_PVC_SIZE}"
  volumeMode: Filesystem
