---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: production
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist

    controller:
      type: statefulset
    image:
      repository: jellyfin/jellyfin
      tag: 10.9.3
    env:
      TZ: "America/Los_Angeles"

    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:jellyfin
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx
        tls:
          - hosts:
              - *host

      internal:
        enabled: true
        ingressClassName: "nginx-internal"
        hosts:
          - host: &internalHost "jellyfin.tnwks.local"
            paths:
              - path: /

    resources:
      requests:
        memory: 512m
      limits:
        memory: 6Gi

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [44, 109, 10000]

    persistence:
      config:
        enabled: true
        storageClass: ssd-pool
        accessMode: ReadWriteOnce
        size: 150Gi
        retain: true

      cephfs:
        enabled: true
        existingClaim: cephfs-hdd-subvolume
        mountPath: /cephfs
