---
kasm:
  children:
    # First zone
    # Optionally modify names to reference zone location IE east
    zone1:
      children:
        # The datbase can only be defined once, if initializing a remote database omit this host
        # It will always be named zone1_db_1 if used, regardless of zone name modifications
        zone1_db:
          hosts:
            zone1_db_1:
              ansible_host: 10.10.91.156
        zone1_web:
          hosts:
            zone1_web_1:
              ansible_host: 10.10.91.156
        zone1_agent:
          hosts:
            zone1_agent_1:
              ansible_host: 10.10.91.156
        zone1_guac:
          hosts:
            zone1_guac_1:
              ansible_host: 10.10.91.156
        # Optional Web Proxy server
        #zone1_proxy:
          #hosts:
            #zone1_proxy_1:
              #ansible_host: zone1_proxy_hostname
              #ansible_port: 22
              #ansible_ssh_user: ubuntu
              #ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # Second zone
    # Optionally modify names to reference zone location IE west
    #zone2:
      #children:
        #zone2_web:
          #hosts:
            #zone2_web_1:
              #ansible_host: zone2_web_hostname
              #ansible_port: 22
              #ansible_ssh_user: ubuntu
              #ansible_ssh_private_key_file: ~/.ssh/id_rsa
        #zone2_agent:
          #hosts:
            #zone2_agent_1:
              #ansible_host: zone2_agent_hostname
              #ansible_port: 22
              #ansible_ssh_user: ubuntu
              #ansible_ssh_private_key_file: ~/.ssh/id_rsa
        #zone2_guac:
          #hosts:
            #zone2_guac_1:
              #ansible_host: zone2_guac_hostname
              #ansible_port: 22
              #ansible_ssh_user: ubuntu
              #ansible_ssh_private_key_file: ~/.ssh/id_rsa
        # Optional Web Proxy server
        #zone2_proxy:
          #hosts:
            #zone2_proxy_1:
              #ansible_host: zone2_proxy_hostname
              #ansible_port: 22
              #ansible_ssh_user: ubuntu
              #ansible_ssh_private_key_file: ~/.ssh/id_rsa
