---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unms-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/unms-exporter/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents

