---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unms-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: quay.io/ffddorf/unms-exporter
      tag: sha-4c13c27@sha256:7200af98df05fcea2e85b29c440b24e9da32905665cec192c5f87b1714d37f4e

    env:
      UNMS_EXPORTER_TOKEN:
        valueFrom:
          secretKeyRef:
            name: unms-exporter-secrets
            key: UNMS_EXPORTER_TOKEN

    service:
      main:
        ports:
          http:
            port: 9806

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m
            scrapeTimeout: 5s

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
