apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:UlRNadAy/NX4PU4ffp3L6Ku7qwT4Pc8dL6+PhA==,iv:8sSD7DLBKJMAQnLtIfPTVFNERJBgt/6NOqJ9V4mKKwQ=,tag:Kvhpdjiim4lGJ/q2VEDJhQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:6UViELRkMc4=,iv:G+ZSUyRDp3hP4IQkLGUMS5U4qmL5hZqCJr71o/ZUYeM=,tag:qIf2QpM9XihzjLspXwaHmQ==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:ZYBdWs6/j1fH,iv:17cxNJMMRWw/zBaJh/d/V6wxqECz0f1K2gbjwLzgnNs=,tag:HD+gQDwrTWY+LXAkrGlDLg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MoO8ZUpq6opfROnzOe+cTw==,iv:Fpk0auCFpTfUKUFI8He9mpPE1xzvOkziq/EV0iAwfm0=,tag:nVj2ZH+80o1M4wN210Z7/A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dsa7DtGfRzf1lmlEFLBHeF1D+3sUd/zhZtNlLfQ0XbVu49FF,iv:RRZCLfXJJAZEunRsXWFI+SjuzUEofmyvT8bh87/r7rQ=,tag:fxabTJZUVOX7NqVKBOt8UA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:aIfUugA/,iv:BZNcWtUB+1DeMxeDqDd7a/+wAySUrfcbrAxwHxj/gfM=,tag:L9QoiLtlpfBk3/jc0pVeVQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rVzBbYxiMJWH8B5oNSaqP2QvP+q36riN,iv:HpEnG2NjvnSKfjCuLHmnnhdN5IbU/A0yObD6b5FTDr4=,tag:LgRgEpxWYZP+J45Fd56pqQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:UPCFf+2mx91OGtSw,iv:p3ghKT/RKumdP0nzwpGRiwDVt1paHTqkHIkO7x+VQmM=,tag:2TSU0kCQflIC5RjVrpV2aQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:qwc0NbPG+oaOwit6cRybyqxrClM=,iv:hKy1qjXqETsRy5FNjstrPGRn2ihFNDvcNVabOpMdFjI=,tag:rmNWU25Ps11hP0WHk+ySDA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:85JtyiLRmGAeO03pJAEMSiTRgMYCF9txnUHrlvCMbcnk9cdpXf3nI5sk7EU=,iv:0mDoVk6QRI7zup2SS5vhriV28bMaa71WHE2+PdV9WQM=,tag:K7vb1lmtW/K28jrEcujPTQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:JiB9l+FvwJY4ZrolJLm/Svdh5Q==,iv:O2KLNlxeIZjjWxMAQuFBp4W03amK65ILyb6gGfqs+pY=,tag:mE7OdQOTdB0iyrxl0fToGg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:48Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGrDmnDIR4Msb5wEeWjMauvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrupMUpW5F+26CLhCAgEQgDtwtGTdX97AjX64OdDfWndS0P6y1k+slCVlFif8ffdP1Jsn+L/i4iCB46mOWRwbcQ2NCK1hKP5KyoHqsg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWnVtdzQyQXhJd2pyb0ZG
            ZnFXODUrU1pIcEp0dkFCdTh6RlY5aUh2U0FjCm9rV1ZBT1VkeEdiaDRrMzc5cDZN
            RTNqZGF3Q1Fsd2N6Tk9KZ29nTCtkWmcKLS0tIEZ2VGFFYUJ3UkUvZHdQRWh3RDh4
            R2hvSmNIbUt3UDZaeWZBMlVCQ1d3TEEK4uOaXJVpn0Zi+kya/4XTm9meqltSTX6J
            KflqfxYnDsk5i85/tSd0BsJ4R+0fSi1ZFSXrKGO7PBqDD0kEouMOEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:50Z"
    mac: ENC[AES256_GCM,data:4RKl/5ZJ9YCjrwZRj/pvsRIE5rJ3rPDXT0+lPyo4lqYYcKJ4YT1qer8gw2Zjd2NBKONr/0iXN7gwHswFBa6gj80MDPNPjsqwyu42cNyJzoZyym27rW42wWi+1gq6m4vcJV/6lUWyceqRJwgHeoc/VZ0aO26IzUjXIdYkGv64tJg=,iv:tb7VN6/fbuQ72hHAvkeemtq0zXTQfl3jPIh58UA6TkA=,tag:1Fec752neZvcpbMxcw42Fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
