---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "10.10.120.70"
  METALLB_LB_RANGE: "10.10.120.50-10.10.120.60"
  METALLB_K8S_GATEWAY_ADDR: "10.10.120.50"
  METALLB_INGRESS_ADDR: "10.10.120.51"
