apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0ucIHIfILe8=,iv:LzyngBokett6t6N08A3/ygLbyghePj84c2i0hvmmK9M=,tag:Qz989b0AiMJ0Ku593lBdKQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:weyyQfC3IgDjlkDOhtK3iuU7iI+dB6t7NyHuZw==,iv:w/x5nNMDdDRi8rVLqXcdvYrjM9y+QZ0YM6h1R/V2BwI=,tag:ZeCC/NhBbkBael3vtfHClg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-28T23:51:51Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwE/App9tqL+vf1tXKSe4wBNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMu5HfIRjYgbMd5dFLAgEQgDsGpAH6zSJH9i1pQ1hmbcTk9AbiY49aBvRDa4uxbs1sv3E34QCI35ZDLXBfb4qK7YaRI3yAJ7dsFS1vaQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR3VVeEpseWxjdndqZ3Nh
            TUdVNy84cTE4K0dxWTRDZkN6YUhpZ0xGWHlBCkxyMkF1MnV6K0IzKzdFNjRrekN3
            cmFNaTlaSElLbjVoM2FXT1hEMHlNOFEKLS0tIHN1L3ZzT3RlOGVpZklweHpwdE1G
            Ky9xd3h3RzlIWFdSUUZYNU5LSEpWQzgKWvU5vVqI1yqn7acfN0JlBNdDTF2iWOM8
            kvzTU3Z+EBz1w7vpEO/BZily3WW6Fmy22TRp/u4KZkRIFRRpM+N+MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T23:51:51Z"
    mac: ENC[AES256_GCM,data:gHrcghyHU8dtXImUbCZh9wsPW/Fj2mSOn8cLVsoNd9suXbSkYMTrvuNHA0VmM/6UM4tcD/OK8SrYPuLkqpJtbHIjysfmbVhfgUmD0lqiSVINR9bxqdmJI+eMD5WGxPN+EsXXuBYFpFt5Xuy2tbyruC13lPirPS/3hj2J+6t2Sxo=,iv:fndFFAj7PT01bP4z9FB3Z9ZhaxpkbIxiGykBcCffYWk=,tag:KtLQAUvSsR0KmgOL3dtqog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
