apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:85YUp1xN+o0=,iv:m0rfzvFlcaAPIZG7Lmm0fAuxmfMbK4ct64c1K2RyteE=,tag:GppKmyJMKZ6lOCXrNo6b1Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fLkUk8NweaD7fnFe9727wg==,iv:q49A8HfRfu0TSESLTFlu7UFYmcanwd/WRNk1hhsYS8k=,tag:4Cf1pk+SDcD6vV8flyBo2g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jHQt7FAjb1yOWLQ4eB51XGcAQmuQOa1ALFOJcbgTB/vE8E4J,iv:DjU+eXxWaRY0DQDE9RtadqyOoBdJxmi8Fh64IANyEzE=,tag:WCq05nsmQb8tyT6TDD5OTQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-30T15:14:26Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGF4P4u96j3GpczVvfvfvytAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtWLY/2yJJHO2n1ttAgEQgDs/JR8B5B6eM9wkmcSgJSpjSDW4SBP0oi37n1MInmFFfTuqy/B5L0EpEX3FeTrIYxjXMuYH7qaHtPeUfg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZmN1Z3RQQW5TVVVZUDhq
            c1hUYThiTE1zN0grSThxU0N0RW5MNU1hQURnCjRVcUxxV3k2NFRkQks3Vm0zTjY3
            MzFRUmFWVDkzcm9Ra0k1ZVhzT1ZibkEKLS0tIDZjeVJUS1RialI4UnNqUVdoQ1Vs
            NEM5RHQ0MjRIUHJYWjRzUHU2WnczN0kKZdz06pKfm4Ubb1G+yn+jrnLjRQQIst22
            M/rv25gf32D7YnrtNCGNh8MthKPfVzqiyb/gJpi5vT+HfOYnAIEEeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T15:14:27Z"
    mac: ENC[AES256_GCM,data:0SiRfhxBEJDd+dYMipAQE5Os5PXqBr+7wIodswj/nxzDHc0I4mNBwZCens5/Y5InpFThZI6t8V/tFRqAzz4mp/nV1gpFGLCLe4RlqilaaS5tEqjUmIzufmor5p9zNgJaMoGmYhcfCy1mmfBGv/yMNJppYWEpTb3LugNTnLB42KI=,iv:jSZCuugWwD/2mciXZlbdX5AhpAQCfmwsiRQZI+DFxvY=,tag:Srz9JAiuGExE3wFfAy4mCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
