apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BN6zr1z7Cw4=,iv:WdSWt06nJgxIeYFiy09abQJ9OZQDBwEc4KFp/p8F3ak=,tag:fCfZrP36DELRkoUCYqL1Ag==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:d+tuWblDAqIK,iv:nkjgOao26nt+ORc1x5j03m21KAYs47eYrP9cQGa4sHg=,tag:yEXADmX0O7mBdGDU54gf9Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:hYJAqqrOLGfFOH1WVkGNKQ==,iv:Pek5e1AOz25ByvRx4b0JrGHNiYirgoJ5umoqFL+kPqQ=,tag:HmrTbhrNEva7UdbG3Ts55w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NWzvMiBvfhD/hKRelXbuzh5qRRwiooMGMdOFfqa+RrDv0ZLq,iv:tUByxe8NkHfFnRVO/SbR9eCDkuGZ2inJJjJutUByiFs=,tag:1FwLrBIv1EQJTEe/V0o+zw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:RpeWjjvc,iv:UcWLNm91SR9NmG0lk5vyFwcKcJVW7sAe7SNMdzFf77E=,tag:QKc2L8pMCQ0pfq1y50FTZw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rJAoPxtuuk4cIj2YdL/VNAKSSbyU2Cr5,iv:zdjVQs8itn2yTxgcmweEQlcDVekz4GxRH+vIuNOEkVg=,tag:z7sSZZI5KsJPvz4dYNbLHQ==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:NzuGsYnPwdJNADqQ,iv:UYO6kGsy8xPHH1cl7HkDC7Oq5oiCUShD99wpCF6sgng=,tag:+Tjw6OSfrCKN5EaRJSvXfw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:8MYxklDM//UI6gYTQKDwbwpY9Kk=,iv:AKSUEAsdrdu+5OSeurMRcpuzwlkmJq9Wvnx6CZGsLoI=,tag:vEd8YCHHPpUruMGSs4/0rA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:w0ktC/FME9dn1MMtkaPlbn2V9zSxML0hU7H1ef75DrViNL0440TIZ+2s7Dw=,iv:ZR3rnxcqFLAGC5sXzg6emMWgoD8CNx5rsY7Z3CYjorQ=,tag:M71h5+19rX29pGOeg5kefw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:lF+WTs7tMpnx9CPI4t1YBgA5fQ==,iv:ykBNgZG+cFC8RRUZKTomvD8uI+00VMAtLMF4xOWr6HY=,tag:Z53sWh/g0Fgk9zt4GlVatQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:28Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHI0IAd+pfnUpUg2EdbZ45KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOC13OdwCDmZCuHVJAgEQgDusKUvO43JQ8aD7NBohPKspNN771c2l+fdjyO4HA04vHOfsad9MchPKzpho17qSxwNga7WiI0YGI6nOFg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRzlWMGVlWDgyTzJ1UHd3
            Tmtoek1mbVgrZkJLekpqSmo5VWRFYTlhc0U0ClRQUFhuZEE2dnp6dVp4RXdqdlpJ
            eHlBOEQzU1REN3ZoVVhxdndhMnFnSEEKLS0tIC9DTVU1NmQzWEJVbmFZYS9XTGlx
            NW84LzYrTFBMeS9hYTV0MWNhNTZwVWsKsUJ9djBeb49S1u/Uq5V1KicX3x76WBkH
            4dj3G8DOYQZWaydz8f9e1wWazwKV9ReXqpUyT9ljEktxbR6ASh8Q2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:29Z"
    mac: ENC[AES256_GCM,data:HjifocTs8rpm0HVy7EdDsvKEM89foSMlWHU3c+XBvFbki6yypCOO59aVYlAuvHxG1uy42UgdFlhp3408B0mbzH4gnMDFEdwwrfrLosDTH0qA98iWhb/wpQPUyzZEU9TmLtEn7mdTXyBHCBpWM1+Kv4qaz7KWWobom/b6/Az3zEM=,iv:KpT55u7DLJWL3vhK0wdt0M4HFfoG0FFlwejnaq/QabY=,tag:QJVtaa8FlvBbyXFnz8ODeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
