apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:85YUp1xN+o0=,iv:m0rfzvFlcaAPIZG7Lmm0fAuxmfMbK4ct64c1K2RyteE=,tag:GppKmyJMKZ6lOCXrNo6b1Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fLkUk8NweaD7fnFe9727wg==,iv:q49A8HfRfu0TSESLTFlu7UFYmcanwd/WRNk1hhsYS8k=,tag:4Cf1pk+SDcD6vV8flyBo2g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:jHQt7FAjb1yOWLQ4eB51XGcAQmuQOa1ALFOJcbgTB/vE8E4J,iv:DjU+eXxWaRY0DQDE9RtadqyOoBdJxmi8Fh64IANyEzE=,tag:WCq05nsmQb8tyT6TDD5OTQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6lvCRFdC,iv:GPIwBEpE8L5XfEfRZjLhz1+tCzoxTI5+erQPpL5eVkE=,tag:sEhFscWUJBOvSpt6ZpBe7Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BBd3Af6rBT05OEEiYXRCLA7uAi7osjTS,iv:r79OmNMrc0zLXEvHdRfLEWY/rkxVyYds0gwdHHIhV+0=,tag:QNVX8EMmj4ahO1+YEgu7Tg==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:skYivNwDmmvizXu6,iv:pWKLMMwy7d1TSo1ArtVm/quhyD13ij7Tdw4v52c//y0=,tag:kFqb+JUflhblp5TV2t1GOw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:LBPXIvXq493+JbJPZhGiEMuZNLU=,iv:zbamLU9tEOHJ6ZRZtp81HvDIvoFhLp65c+LajuMssQU=,tag:CzlgJa3CwciAK/1A8PRl2Q==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:XH/wBNNPC/7KF39ZJtRB0pNR4fr/1veEgO0uZw9ByGWTJs85f0zTTqh8SsI=,iv:kLar8IFno081jMkZbNdWIHO7HprXzqsUD9W77hnstyk=,tag:X5gv/HX4DXam8A43o+wbDg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:hzXMBnDic/gMiNRaFKl0gd36tQ==,iv:YmoFt8DEavKDGE932TaCIz/O7hKSzmXwcvbQaBnzBKk=,tag:+k0gK0oTkuHxBo9lyU0EYA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-30T15:14:26Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGF4P4u96j3GpczVvfvfvytAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtWLY/2yJJHO2n1ttAgEQgDs/JR8B5B6eM9wkmcSgJSpjSDW4SBP0oi37n1MInmFFfTuqy/B5L0EpEX3FeTrIYxjXMuYH7qaHtPeUfg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZmN1Z3RQQW5TVVVZUDhq
            c1hUYThiTE1zN0grSThxU0N0RW5MNU1hQURnCjRVcUxxV3k2NFRkQks3Vm0zTjY3
            MzFRUmFWVDkzcm9Ra0k1ZVhzT1ZibkEKLS0tIDZjeVJUS1RialI4UnNqUVdoQ1Vs
            NEM5RHQ0MjRIUHJYWjRzUHU2WnczN0kKZdz06pKfm4Ubb1G+yn+jrnLjRQQIst22
            M/rv25gf32D7YnrtNCGNh8MthKPfVzqiyb/gJpi5vT+HfOYnAIEEeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T18:19:28Z"
    mac: ENC[AES256_GCM,data:t8627ESiNX76ZCRpMZ3llbqqT2KCzqwUKZoU0Bdpkne9YegPf1tUuDrk9RxnqkwrPRujAHy1GmqkFCtUuZpSVEc1lFtYyLEyRv+emfPMWmp9w8ufQDmB7+MJSDcPn5eGxqrP/MRhLWFEenf4fmWxxh1ruuuFXGv72UeKv9ZtWdU=,iv:lIdO+IK4rba6xNenAtYdj66mf+wxtfjOaqLy44CfUxI=,tag:QOYa2SsVg89Komq6r/6G6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
