apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z5/LPchfhHk=,iv:zzA0KI9OcjYLFTfezV7qebcxdZ2u5WjwGXKGU/OhTqE=,tag:LXdUG6qxYY/rYH3P1jYG7w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fAI7wY1g1U7/snIKBEqkgwYyV0RcLtYypfe4+w==,iv:b0ttv2ODudTRK2o7pk7NclGL3qt/JToZve/SWs81tN4=,tag:0OM+hp+CAASaIWH1OV2eYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdy8yYnROTjk3Rmdjak5F
            V3E1blJreG5LaExGcFhLbE9aUTAvMGp6azBNCkhtUnRnV2ViR3lTVHhLS3ljYk40
            ck90WS93N0drZ0VadDh5Y3ZBSCtWaTAKLS0tIEtvWVVHRzcwZWM1UDdTS3lMdHhI
            L1F1WnFmb1pRY3NyM3h2SUZmZk5SZW8KaT3NYHf0jkL7iRblRQt2J+pU1NH0JGXs
            6yWjTyM0htRPHCHepjhTTyiIrdQynBaqqIzjh9FfmjFjVZQkKvpYXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T22:56:18Z"
    mac: ENC[AES256_GCM,data:0loq+isZCGrV9Wr5RXzR5ANEinxEkgrL87sotljzVeOChEVUMLQX7axbywxOx+iUt8mvAPjZqOv8T0Q5ORHnFbL93SPtXoEAqDsAu060hx9GTKZy9zM+SA6y5fhN8mCentlQDD4RdaeJMazeIVFnwqf0Oiwejy6iIWxHxG3idrg=,iv:jZh5TxVXHMzmrq62dLf++w1j6K8EXIM69CbLUFHrWA4=,tag:BHDWtt+X3o/WdrMnDtKS1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
