---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  METALLB_LB_RANGE: "10.10.120.50-10.10.120.60"
  METALLB_K8S_GATEWAY_ADDR: "10.10.120.50"
  METALLB_INGRESS_ADDR: "10.10.120.51"
  KUBE_VIP_ADDR: "10.10.120.70"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
