apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:+L1+AXRce2y4YU8B1XgvT6efkyftNfQtPhpJ1g==,iv:PWXf9x1ubytV1c4tBN+4c+xJLcL5N4ovy29wZCysG2o=,tag:arWZR0wOMXLt2/HQFFXsxA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:RY6B7Cu83qU=,iv:zbIpoqCCpzQrJdzGo58ZbI/MEj0alE8QDhq/c8tHIL4=,tag:3fZmky8wwlctyZ6gFGxDbw==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:ZTGu3R6P0Nb9,iv:b/XKG3K9WAT5TMZFe+IYs+P16lqY9xLxYBd3V2iP9zw=,tag:6iHpLNoue6y/Vk0WzyJc0g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:G+clhbXCJKPCyVeZQ6/FIA==,iv:kXwb0pWSRsrgMBVn3tfD8T/B3xDtwpDQmsKUslfKXJ4=,tag:bwS1MN31sn5Hb57t0jfIJw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IxrrS9t7oFGtUfSM7JzRvwkRQP6/g0J/BMf01OzrKeXQ0k7G,iv:tRhLKu8fjKOG6l3dei57qRq1wowTk9ToWOEh1o26/Bo=,tag:68h3E08/dM7NLzIUf19GIQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:SDVKIMfr,iv:AU2PSvmrQ9ExsSuhLb6BKsm79wLKaVrpXkWquXDf7ls=,tag:KzS70PzerEazMQQi5BeK2Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zVV+FhBF/KAWwiOm39uTRaGsUQQfqg7S,iv:koxzIsM2t0xYmE7oavSeayb+yxz4w6wL2FKUJLwfGGw=,tag:ArwvITdClnM95vT48wxshA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:DNkU0ZolDoRu3VAH,iv:OEOn6pEZiEaDvPCLI4yFm/8oiIux0P84zvufB7YQDDM=,tag:dpu2inoWw5P5g6DHeawXNw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:Tq5yqHL7L39EZ6bNe7xMdMihOV0=,iv:i0JMLO7i+KzRt4GMX7vvmkDyVyY0jFkTTWYs2JRSmE4=,tag:+SEjEZbd48RxQAx4T9SQHQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:a90zQ7tlCrs0ViDZ1Ey4j4QCUxOpFCWiQ8sJqMvY4MGn53mdTgiNKdV65Pc=,iv:opWz3evBJZ3UptdrHWsWs2gEguwrZ1UbURXtP+TXJwA=,tag:qEI+d5nJXxY9Kh3OXwzhIA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:ZoVC7IABFKazdicJrbb672UJ7w==,iv:zr7OUHSbu7c74f2bvjelJnOZdrPOkfHrx1eiAJ//fOI=,tag:fJRQRXYl2P4JAbb1+Is4dg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:10:19Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwHoJGQmuH//2pjaYZCYPosxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMWYkWEKNTn3Ogk6CfAgEQgDsWEK2IBeo7UbRxt7drnmxy7kAU7flfA1hq3LrCCtekG8oQ/CMMtcoUY5My2zdsd1/fN5S8Fa657XkbQQ==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK1ZkZFptbFBNdEl2RkFB
            MkMzU2x3cUhueWtzU004U0ExbC9kNHk2V1I4CnFya283RWFDWFpYc2FMbG8zMFgy
            cDhyMzRNR1p5N2hwMlFRcytoKzIrbE0KLS0tIFhuQXlJNkw3aGRsVlJuc0hhbTI1
            Z2tQeERSOVB5WTl6eVA3MnBvNWhGYTgKJG2u2sg8idebpgnVSRr476+5ERRbQ37e
            VcTGIhvpFuOI47udSg6XayUu5me0uz1w7+LqeERdeOVKiF6G54RsFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:10:21Z"
    mac: ENC[AES256_GCM,data:/BPERFbGBhZ0hx0Ni73zKE8TuKdVVWRiajZdYSOq/H05/xXZb8wdBgcs4vEJtiWLERZ8pEg6GA6fTRcfL7bm8Y9vhFtnm2NxNdwRcXIyR/Uzj8hg8c+U6bId1hwbcVlcUqspCCndOWC71b+xsG1OXxV2Jf5LODEteSrEUq2AIYc=,iv:6FUvAkAnKCJrDC0fGgrZpmZBBO10bz71zRTy2J2DUhk=,tag:i9El/kMvtIuv95AGRQD6Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
