apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    MAUBOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:AMHrwAHGpX2Sgx/HxY9mCoPgF0vZjFDzDGHbLA==,iv:/p9dkU9g9/ZJRisA1BMWIum5UuI2x7hvHKDfNYp+xFI=,tag:oaxKqVzWTtDAR4f9qvg2Mw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:VQ8u/WFRkUg=,iv:8jUF9z4CWzNahjkxFR9/79KmhO8wQi9kENO8aqs7M/E=,tag:auUWEAQQSEoWTWPu/hIb7w==,type:str]
    SECRET_PREFIX: ENC[AES256_GCM,data:sRhKqTPMc3MG,iv:E11oEeKoFs7pO63536LihmSyjirJEn9whMAbanZ0h8s=,tag:YMlIDnxei1rQNZHkuw4sbw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DE4xbq6dQWOKA7cntiAdrw==,iv:xFylFNxEYmUlqu4re0Swv1ieAo/3vsNbOUmiMLa4o6Q=,tag:tBxJTMVp5cpdHuIdcwdhiQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Obbe8W/zpSJXX6mDlythDJDoOYJ5hMNmvM0M98AAIQ+Eq6zk,iv:/dY7pJsh7yXWe+1uJAyLVilYZ2bc5rmh8jnxHehXqk0=,tag:+qMKhdYEWwUm1qKe/WLdpg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:lqcs6fC2,iv:1ErFHKjDoXnsMRydx/M71aZuBHlWfEEudYsmYdXLGAo=,tag:l8nDkKfs0WjIaLlFgQLdyQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KMo6hfgS8RIE7P+teTX8iBPE4JqNPZoY,iv:F9IZV6X9fAV7HNb7z+DLDzWfCf1EM367aPzUnxklUa8=,tag:tIK0ciqhm9G8Q38SUYyV9w==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:S23zerBfgyBFXvWT,iv:EuxOGmWk0cVCR/T3AjISWoHtUeuouYwIW0Wf6/uAfzc=,tag:aJDMOnhLsc03ekYUpGmaDw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:+mqxm5dpuEpKk7YkASz4LKyOKSA=,iv:GjgwqC5sak++Laex1G2h/ZYKHIR0Q+X7KlX55RI3h6Y=,tag:2/v8xPuXeYsMExQia8U1Ww==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ajUdAJaMftBmwualnYdp3lIF7i2X5ZXx20966xEn/EipKs0rIp4mL8NH5eI=,iv:0hryUEFKwhbhwS7xlQ40EsR6SVt/qkJwXO9TzpaVpz4=,tag:DwAtGOLAmER6Phg2/mXdng==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:x3pMzc059NG5/M4mwi3jnyb7GA==,iv:WfvRDZAozyyqAuDAstrP3n2HK9BfTNwFi70vniyYHOA=,tag:zfoE0Np39nEUBhp1uIqJWg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:42Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGAZLfngMAvFc1cwDfKdtwjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6VAt4ywujHWUnZbDAgEQgDt0cZLEQYVPLyTbd3aTiRTgMXe2rrn8BqVkZgEVdnG9PZawnjsS2Zuh4W7wSBh/0lY9Pw8hgr1hQU0k6Q==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcitMSzZGaTVUUzY1b0lJ
            ZlltZWk1N0xuQWE1Z2xJSWQzUXd2dEcvaTBRCm9vaXZxbzJ4cXBJbHBhSmIvb1RM
            cEhVVEZIY2pidlBTbVJiaDBaUmxTbjQKLS0tIDhVUlNwZDU2Y01DZkozQlhzVEtL
            TjN5WkNFeGNtTzBpVzBzTzcrREVKMXcKUAyLhYrrlapD/RgI6QtXm2YgR1MGE/UW
            9hYYVxUJ7xzHLpiUvVfP8AtlR+vvlkT+PYVVZYCRsdVKRqUxDn5UeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:43Z"
    mac: ENC[AES256_GCM,data:fmv5S1dAwAtqYl2U9clHLXdIIemWUprKbU93IXI820uX5Ra9F7Nfm4V/+971FdJGxJtk5Bvpf+P1+y8mo4qk9XkHZQeCiMzeu8XMRGQcPmH7ezfJtGI3FlTT54geLtEwKGQMes5cpPxfMS8nYyz0z91yDZPoYer0NoRId02sdHk=,iv:DXWfUGxbGPl+UHAc4spLhbUc64ntXJGf30fxaR83Zt4=,tag:sX7+h3y2lE6/o7jeLStC3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
