kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:vFT7zqVCgIGy9Xq17Qr+Qlrh59Q=,iv:j4hkpxmYwRV9GEIJFMI7qBWk8WiyxZBHt91ZooYFNtg=,tag:RaE3hENl0YCBPFAq80VnzQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:8yU+f9Pb7I+ESZlDu/BrRgba4ac=,iv:bc/E+STzTSIRN737vc/i2CBR2hhWiX+1pNUFFoloNDM=,tag:4P70YPgx5ZSbIJIDLqFi6Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:oVkqaWKe5NJFbQ4PINcHALiNgXk=,iv:zfeXoOIfQ9PHvvIerXVeuXdqpjbCS0BWK6j0ohGC4I0=,tag:5YAcpZmrHKvILGWwFEKHJg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-12T23:29:44Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwFYn05fVXwOWm/yk2F0BfTFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkO8tSds2hpDcQb6YAgEQgDu4cQYVakB4cRUVsa0X6vCRRwIBUzQ3ttybkU2qJo1e8ny/xxGZ6PfjTSxDvTD4WneHNWRaMUoJgaUAPw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdFBENDhVRisrcnhYTnk1
            WmdDTUNaY0k2UUpDdUR0SEtNRWFEbnVlaGpJClA3OC9Wd2lxanZ1a3RvbzlNSWxi
            M0hZS05Nd2x3VW1YellUOVlFZmhJSTAKLS0tIHBMSVhobTRORmJWVzYxS1crRWFw
            Q1RRejFtQi94aVhlaCtkelE0bHFUQlEK8ynLn3baYVs8fD/Q0tgu4oDuCkiet4eO
            ry1X05YKCf9m61QplLbhoPuY4scFNQCwBesQWkeLTOzsYe5yCoMRnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-13T04:02:28Z"
    mac: ENC[AES256_GCM,data:3S09VSHG+ISh3piMDVGwSmL5Ro47fCIgtT/iEnN+T4A2qatZUSb5P9coU+4Ru0mNqaN459yGpwgJtFfxzExN9sAWmHAnsoXYdsdNap0Hl/PCcT3IV5IGKhKQY6elwaTsA8V0okdY6obTF7qN/4LvqifB+7BkZLkUNJtSWvOegXg=,iv:Kb4tGsd3cZdsbALORe3FNFjhxlBEBWc3hSOn9U0YGf8=,tag:yRwj59tx8dtTZLdjsauCQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
