kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:ASRVQDyWzl1Fb4g6uFEhclc/NIk=,iv:MxApedWFGz43DqLl8t+LydFmrN0e8Iczgdk1T+Z+n5s=,tag:epqbuLYICiuXsU4W+0+F5Q==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:9So/UY+FyO/Af9deH07HHFEIK1g=,iv:qEMgnWodl/cUMrm+2rJaiEXpQcYb9IzJG72fMBjb9bs=,tag:0FHzccH4S50Ce7OUo9RQvA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:PGesngABktHTEVsGIp1GNPXB1lo=,iv:ggYjyTbWTCCUAcV0Dq2bqTDTEGk2hK742dI2fmG5m3g=,tag:IvxCHfOxbLcug2sscFPtmg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:29Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQF3bL7e54uFLwC5R9FNd2yyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPlDzRa20BKCQN/qBAgEQgDsjDfeRvwx0WkR3q8MvS4HVwbvaDCNHn3rrljPDNyTQQ0ymnUdTsLc20OS9dsc6t8iMjC8G3Hb5S2y/qw==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQzEwb09zcXMrakFZOFh2
            MVc4U1RnSklHMmlxQ1FBVVQ3dEc2MFZ1SjFZCnJTWC9nRzh1a0RuTlBjbUJoaEdN
            R0l4clRMUFZOQU9kYzlqbnBoN2FRR00KLS0tIEYwUHJMN2YrNGpCS2hkZDBzUk1D
            dTBQUTZFdmNUNmJ1d3R5R3lKRDh2WlkKTdsa8GDdafLvDHS0izihuVzGWNzx5QHi
            mlzjsw9SBUOIAHYMAJRNgpyysPPGNK97OfLrk5mf/VohB2n69aG1jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:30Z"
    mac: ENC[AES256_GCM,data:+kvrpweodqRKHIWQ7qhERd/IHFKXjayd1Q40ujZO6VhLoPs/RSJU7f0cMwrPVUTMoX0YrALNgcAzmbzIBr2fadpTzrOYh9JXsnola1gtdjPHnoxs07LCBmV1zOvndWR4elPASnlIpq1v1hJ4LZrGk64jOmlVV8JQfqlKEWhNB8c=,iv:68syno6QE2lwisuc5Gzs7zEITHbjnLu5QHWptV27drk=,tag:+8EskgGJGv50YMENlv/a5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
