kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:bi1FxmP3pwOEBcFRV3QVYUIfvQY=,iv:0t8SHoUT1zfchOkbFh8B024Bx7EZD+5jmhw0Os53JGo=,tag:cMbZc/Kac+6JmYaafqxh1A==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:wtMZCjlkMUHtrPnwDnv6Ma+kDxA=,iv:G+VGx6Xhxw7w/AGGGKsCmeBObEfx523CipH9qptCP+s=,tag:cv1ymTk9EsB4UpLjMCjThA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:y+TRl1mgXoJHei6I0WhByUdZKBQ=,iv:YGxARSgktqDyNvR1zL3QX0mISuXSYUdX3AQzQ+z5rfo=,tag:5jqYLRWnPdO7x0QDEXMdaQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:44Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgFm4noEBDarCnpv02LGKMrzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlXnLjZtU/j3XWPRJAgEQgDumHw+FH4oQ4NpWsDK+RUlg2NF9yIVpLnKUYWuTWVCL0D0VgU+ThxULvb9HXPIEYFzb2uFVUyjw8lCdHA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeUF1NEJZV3dXSHAxUy83
            aGRITzZwYmdHNjRiNHc5NnFoczFjb0w3anhBClMxak5KNDVtRVFIeWVteXBtSlpJ
            S0l0VXNlU3FmQjl0M0FJbHpKSlp3cWMKLS0tIEFwMG5XYXI3QjI5c21iUlo5SjBS
            N1NuOU5VUGw5RDJqeTExS25TTGVodTQK9vAazbYJmIYOplZtsQP2YLe/G6NEX7rO
            d9iJLpbPNSDi9/6rhvoqhOOElwhylybvJsFr+90a20N724DJFeop3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:35:46Z"
    mac: ENC[AES256_GCM,data:c6oZTDolTKvVmnPyg0BwZgkweCMBKh6E4COgrIVxUFRKe5ml+uW54FB6TsYfiHg9R8X/pOZsj5tV0uBk/AWdJZdukS4tEgUVUzUtEZ92IHsJ9lG6TcHHpFXyQLj4EgVae5mCWkNIwYCfV6D4Abex5qSfOcd4xcvCdjun5agcj6k=,iv:XGnuMy+WbWmA7AB0Og24c3xDDJQCQuDHK/AfCL9dfQ0=,tag:h2P0Le2xmlNvqNV3eHxbFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
