kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:sYSj7qMcXPsWSUciSS3UxhDT1eg=,iv:/G2U9Bu6JoeaTvjbOPnvGEdZlpwiYeEpcaNywR928lI=,tag:kiUY8qEaJTNh9TPUxbilzg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:wSf7VrIxP8lYNUImSPQ5vh2QvPQ=,iv:8LaKBiIihVXguIvOxkZx/yRhoHtad9YrICReS/qyT/4=,tag:hd2vM3Otf2qJub2Bxb+SDA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:p0WaH5GzTOnxu/j4mYF5UqSDeUg=,iv:ZM8DABqh6r6CMjaFCIBcGzccVPNtzpNKXNOJYXiykGM=,tag:JBN419+C3Jtqr/tUgJ+mwA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:19Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGm2H5hIxcRIxCug7wsJ0t3AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1x2rxzlfflOpEspgAgEQgDuoqMNA8QUvcgdEfDum9k2zujY43tF+CSUrBpe5bL+epm9lylwnqOGXSnn3p4i4yp+5FgNZatuBIZoFnA==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eFBOSXFZNk43cXVqcHp1
            NnE3cnVEQVFxYTMyYWIxVWN0YVNPWGNReEQwCjB6MlovdHg1YlprMzEybXV5NjQz
            UVVhWU54NnlUYTN6blJwMWNia09uU1kKLS0tIHRZUlhPQ25yOEhBZUtUZ0x3Mlp2
            OGJOT2t0a3NncHFJOWxJMkF2T1FtOHMKZ90fD4QTTH98zA6JRP5GcquWENfGHla/
            xkN16H0kInFReRXK+idNluwOb3rJgTTqiIFcwZ21xXPrkZYw4eeDww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:21Z"
    mac: ENC[AES256_GCM,data:XNsSyBCKdeJrSwcl2VQ8/2h0c0UUscT2xftsARFkSv5RafGAuNDKWtTJ4fGxTabfl27j7xpN/ar1gWQeY+4Ulfplnz3l/hKfysy7Vv3t7LLQN5yQ4N7zddsPdLd9zSH+FZN3ZIkekSLabaJDoZq6ScYbru64NEdHOKDpBazZ+yM=,iv:XghYFPZ3VXQ3U3jQrJA0e+qmShDkn3pIgHiUwOF3tvI=,tag:oFbHduBI2suki3o1PdP3mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
