kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:nEJD5e2CjsDxFTdaMGspbDpVq5E=,iv:8M5rkIV3uStUvWRtwOt4W6Di222gBmmXmChMmVXbuT8=,tag:DR80ItChfbfZIw8LxtbDyg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:EMzqjSny3KgDkSG48Cj64A1TjqQ=,iv:aC0U6S4++QwE2HHKk3EN+qKud8AWg308Wk6ULW7rWrQ=,tag:jQu6K+h3PfDmBaksbO9onA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:5/v+ZqV+IJ0w2NX8v7uZmFXmdmA=,iv:YiwENQPkDrPBOerH2iHOUbo8e5wYzjxuhA9Xuv5H4UY=,tag:nplqLZdhQAKIi4DtrACJ2w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:44Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHJpvVwP5/DQOckznf7TYPJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqvs9orR1RTKmPMDlAgEQgDsERQQlMrHH3aqqeUZFpObUrdToL+0cyry/gA59/gC0/uxjRVWKQqZOrwUCee6wMitDOrFehJibt1vjsQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSHZ2aFNZVnRwYmpYUzlR
            WWtKVE0vK2NFMWswNUUycmF2eFpMZlJaMms4ClIrZ2N6WjkvZGMxZ1U2dFVaa2FM
            Mmt1bHFZaGI4Y3M4Vis3ckFSWnBHMm8KLS0tIGd3TmhpMnA4L3RlZEtMOTF2elk5
            K21xTy9QSml4WS9Rb0lVeTBFT1ExancKJZoFF9QWYs8vl/REH/NTpxhlZTUS33R2
            Ggu4Yt/f7VUEWYea2FmMntG4GhQLRk+nLH6KiKpZwpF2S2+qWySu0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEthRVgxbUorQkpjMXJq
            cDRKbEE4WlFPd0JVenFET0hvVlgyQy9RSUd3Clh6UE5GbzJjb3BBdExmcDY1Mzdu
            cFA0ZlI3d0NPL0RlTnBHYUcwWDhRTGsKLS0tIE16NDhPbGdmci9KOG1Qa2pHUGh2
            eGVscGdqOExZc2I0RTM3OUdIdGlkaVUKZMTF0pm5Z2URAGeLBtTf+ZvRVu1rZuOM
            knprKMdr2SP6j14EwtV67Oc1QOiq7jlcA8j13iUhNQGe64LZiI559A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:36Z"
    mac: ENC[AES256_GCM,data:CYNMsDau18+R7sKf5Nqlf6SHDHVJMTG7Wh2jrKVVL8JppmM0WwBCiJA8WKfXxxor+diSR+rT/xBQiyE/EdMWYufH0nvDBgaWsyqw/L2qRkK2RT54KY3rGj6HofNz1sczZvVNk679Jx+St250yl9t+AiZLdc/0bwbvuqrt/Mn+Cg=,iv:UvYHtRRKjdffEB5mNMyGfIiPHA3YdjDdaVEV1v+ZOPw=,tag:tOE0kbhs2s4bSPi1MuoFTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
