kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: databases
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:nEJD5e2CjsDxFTdaMGspbDpVq5E=,iv:8M5rkIV3uStUvWRtwOt4W6Di222gBmmXmChMmVXbuT8=,tag:DR80ItChfbfZIw8LxtbDyg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:EMzqjSny3KgDkSG48Cj64A1TjqQ=,iv:aC0U6S4++QwE2HHKk3EN+qKud8AWg308Wk6ULW7rWrQ=,tag:jQu6K+h3PfDmBaksbO9onA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:5/v+ZqV+IJ0w2NX8v7uZmFXmdmA=,iv:YiwENQPkDrPBOerH2iHOUbo8e5wYzjxuhA9Xuv5H4UY=,tag:nplqLZdhQAKIi4DtrACJ2w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:35Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGFRhtXolVosI1Ixj+lFlyZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1DcD4ZWTRc2YItWeAgEQgDsZ+tO0FrsU4Uf9SDT2HCd40qZk3nuidlPG77FUbKTWxZS0VYKXk2hYiPzEOynJwLA3hSreu9m3rJlxTA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb0IrTVBIYmRCZUpEVkw0
            WTB5c3RaUUlnUFpobHlCQkV2SXZFdjBEdkd3CmMyRlJienVKWTBvNUNzaVphZSsx
            ZS90UWdFUHJ4ZG9JcEpha2hRZ2JheXMKLS0tIHB6NGw4NlpSSUtRMlFlRWlqeTdJ
            elhGRkF5UkphZXdMamd6SUlZVzRWcFUKt0GnmEApD4rnkKbU0Xzkyd40/cg2zJNq
            0npjdK38G0hz2DcIldTOq//+txz7y7NgKIJq5TOGQP8SfQvHL0vfCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:36Z"
    mac: ENC[AES256_GCM,data:CYNMsDau18+R7sKf5Nqlf6SHDHVJMTG7Wh2jrKVVL8JppmM0WwBCiJA8WKfXxxor+diSR+rT/xBQiyE/EdMWYufH0nvDBgaWsyqw/L2qRkK2RT54KY3rGj6HofNz1sczZvVNk679Jx+St250yl9t+AiZLdc/0bwbvuqrt/Mn+Cg=,iv:UvYHtRRKjdffEB5mNMyGfIiPHA3YdjDdaVEV1v+ZOPw=,tag:tOE0kbhs2s4bSPi1MuoFTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
