kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mariadb-secrets
    namespace: production
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:vFT7zqVCgIGy9Xq17Qr+Qlrh59Q=,iv:j4hkpxmYwRV9GEIJFMI7qBWk8WiyxZBHt91ZooYFNtg=,tag:RaE3hENl0YCBPFAq80VnzQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:8yU+f9Pb7I+ESZlDu/BrRgba4ac=,iv:bc/E+STzTSIRN737vc/i2CBR2hhWiX+1pNUFFoloNDM=,tag:4P70YPgx5ZSbIJIDLqFi6Q==,type:str]
    mariadb-password: ENC[AES256_GCM,data:oVkqaWKe5NJFbQ4PINcHALiNgXk=,iv:zfeXoOIfQ9PHvvIerXVeuXdqpjbCS0BWK6j0ohGC4I0=,tag:5YAcpZmrHKvILGWwFEKHJg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-12T23:29:44Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwFYn05fVXwOWm/yk2F0BfTFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkO8tSds2hpDcQb6YAgEQgDu4cQYVakB4cRUVsa0X6vCRRwIBUzQ3ttybkU2qJo1e8ny/xxGZ6PfjTSxDvTD4WneHNWRaMUoJgaUAPw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdFBENDhVRisrcnhYTnk1
            WmdDTUNaY0k2UUpDdUR0SEtNRWFEbnVlaGpJClA3OC9Wd2lxanZ1a3RvbzlNSWxi
            M0hZS05Nd2x3VW1YellUOVlFZmhJSTAKLS0tIHBMSVhobTRORmJWVzYxS1crRWFw
            Q1RRejFtQi94aVhlaCtkelE0bHFUQlEK8ynLn3baYVs8fD/Q0tgu4oDuCkiet4eO
            ry1X05YKCf9m61QplLbhoPuY4scFNQCwBesQWkeLTOzsYe5yCoMRnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T23:31:01Z"
    mac: ENC[AES256_GCM,data:vRzfw7GnoIsSXwQHbXVNPXGG8B2FeR/vw+YQ/bjI1XYRJ91XXxwPDuk7Lvk6Ka/13O3u3z88UI5k/Y2ijJaMYIzY3U5/oWyx+6N2eKW1K7aRQLnZ6SJ5y3ZsMZT7u/wLE5+pZ0Df6Xwj6q0ukcVQgptdRCET2/DSfBiDs06eAUk=,iv:VX00mXlLV+vGs+88bGkqHN1F/ZWyJROF2o7MR61P/AM=,tag:BuklI9nvNWoKlOgA+RnhLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
