---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
  namespace: databases
  annotations:
    coredns.io/hostname: mariadb.tnwks.local
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    mariadb: mariadb

