---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
  - ./prometheus-rule.yaml
  - ./s3-loki-bucket.yaml
