kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:VSlfsPpZIWs2wfbiZBYUxg==,iv:DsSnm5Itf4Z7JA1IR1JiG7za776Q0tCBCpp+AisNZgQ=,tag:wwEEj2QsdM1ShcrzNV0byg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:52Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQE4a6ec8LeG9sTQ6AaxZ1BRAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAmhbWAWl3k60QKeZAgEQgDsNJJsnnF+otOnLir1OX4YmqauR8x0MNaxwPWq9pADTmDOhzJme6J+9xfNkKOr3AteAHLa2fp/dRb7fxg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN2RnZU5GekpORnc0bE5M
            ejd4MktUYmRqV0FsZU9FK29OMXFsQVo2ZUFNCjd2Y25XWkoyNlJSNlJQREliZzNs
            bExiNDBhd2dyMHZlRnIrQWh2WE1aSjAKLS0tIDNvSHE5NkhhWUh3RXF4cHY4T29R
            cFcrNGphaDRIMW5ITGVZZVNZa1d2TWsKcQYleFBFLkpHaXJ3OvdJZGjKuaxKx5TE
            oq37dSbhVh21+RvjnS4Il8sGd8Ap9+1jqQG9Wf/MRWBAIDCLE4ci/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RzR2Y0RaQjdSazUvTjVz
            MmtXUlJoc2VxdVVwMjVpVkR3UTBacEVCdVJjCnBBMGtBN0JjQXVBRkpFRk9VU2hS
            NThiWTZVMVNrVVJ5N2VyeExibTkybU0KLS0tIHY1Qmp1OEdXMGw2REdTcHhBS2ZO
            a3NzVnB4MjF4ZXFZZ1FyRVFsa2tPWXcKcEBMWc2ih/2rOxvKUh5ZD9DngFYg6t7V
            BdBeFWDdZhLjo6bKndgAC03IvxP8sKQxl2JD/h5PrqczTn7ICED/ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:25Z"
    mac: ENC[AES256_GCM,data:E4gQXhle0XHaqhQlRnfdl+8M4ouQz5jqZRWOv4nHxycr9j2/RNeWIX0QIg6Ksx4hUTEaAdeZlWFBUrdLwHBP4Ky8J4jT0VPrsBCaXUU6v3koXhhl4nVj+S5htOIldrY3wkDQlLQP1LFJjkJ0ipL5hHA2RuZa7oNM++8r7nz6qzQ=,iv:3SQv1VzsrMl9x8CmzSdzB/l+GWAIAtKpWEyt/iU58TI=,tag:MsMRIVCjUIOnVnfOUohyyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
