kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:V2nTTyHdlEfRWKww8j102Q==,iv:eF2QzgfyaZjHpYOFZIMUib2cU7vQaAjmJbv+r0Nb+ac=,tag:KBLm0PFxg3u6ETkN+nXKWQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:06Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgE354i7gwhw+OrvM8obt+GjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaD2q9eeBDmayXvC0AgEQgDtjRYuHmHpR9lcUyuCvpuCNaPAUdCMva/8PI7R8sW8FJogI7PsIDkm1F28HjVtpISikmg0qhcBO/r1b2g==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRWVJMS9uK200OStKV2I2
            TG9SOHhKcUtjYVJiVENFZXVaNnI1cVJDOGtBClN4S04vMjkwRERHVUMwVDlaZTJm
            Q0VBanpxS29OcEtIam1XNVg1YXBsVUUKLS0tIHZSdzNMY2k1WFo4eFpNVmNCOTNj
            M2pvRlhhN2VOUWttdkExTG93dURtU0kKvVuqaIXFdm3CtE9zBqSAeHAHMtuZ0+Q4
            aZVS2OAe3JJ++HGRP467dalvAEse7OZUmEXvkm/faY2/vPIRZTGWpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:07Z"
    mac: ENC[AES256_GCM,data:m+ACCaOH1O7jPiMnXOANBZNwWvdIXMsj0/bj4z8/+KBtbYVeMnPjxLpClQOez0B6JklqFIeeGw2RNNwse3kIOB4V97LcD8YUxmiPvvY5srh2nFbocXtYdWa0mp8cjtGocFKGPJEpfY7FoGUEKSztPOpINO7JamMP7u98ol1U++s=,iv:3QOl6I+sjg7VVo5p+lh6tR5f1tICoUfHDMsqaSlQiEI=,tag:szYGb+YDSx3S/dGajia7Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
