kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:VSlfsPpZIWs2wfbiZBYUxg==,iv:DsSnm5Itf4Z7JA1IR1JiG7za776Q0tCBCpp+AisNZgQ=,tag:wwEEj2QsdM1ShcrzNV0byg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:21Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGT3E+Z5Srjh9bMEv4tci7EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/0RQuMY7D9h+i/zpAgEQgDsW2Y6R31ZBmonSFX0BJwPx29BDGFo1KEK7sUt3QC7e/p4r5FfSzjHn7e94B8W4XtzeE/YHwS0gSejqzw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmttazNtWE0rR0hxb2tN
            S281L2J4KzdpWVhhZUtJR1h1U0VjMkVCaUF3CnNRNUFYZXB1S2dBN20ya2JtN04v
            Qm9tYTZtdlUzUENRSkVzZ1lnSE1CeU0KLS0tIElrc3ZRQitvSkF1eE9SR0lBcW10
            eHNKOTRubUxXcVpzMGhabGZCZkxVNGsK2micyJNboif7gUfnRgKP8tZH1294wg1U
            XxS7FvYhX4dy1ZyGfQsvpo0XWDvnwQPKJTAMpJoIp6QgFZtiiWm4zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyckVqTlE1QVFpczZWUnpx
            MXVJTWIzZ0VZOWxCcmw5eFR0RkxCY25OZGo0Cklack1PUjdOK0tVbndDTTNTaEtH
            UnFwRDFQdUd0aGtjSHk3SHNXZFNWaVUKLS0tIDg1dktqYWhYbnVBNjQrcFNYZDhF
            WTh1cUJhRFJSbFk5TjNSQWpJZXlTbUUKiArVhN5/B5nPc4Pm8bb8sfr1dR4ZGGy5
            jQ55zLs9sBzDIPUciCJaNI01zrBQdgCbGMTTZjqZrgN46vs5EpF8qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia0tPWWhMTFNHVVRjNnpS
            bVVITFJXOWpEbmRka2dqVUE1L0xVNUdvdkY0CkxBMVpyTXpJS251Q1hubXEvN3R0
            ckk4V0JFMjNPTStDU1FlYnhMYVhRbGcKLS0tIGxxa2hmaVdieUYxbklubTVsZzZO
            T1NRbWpreXdtSlFHSklvcTZkdXdPRE0KJuuinyZb47Ql0O5fZd/SkJUx51ZyksuO
            nYdfchnVVWhKAB4V0Gp4LLbO/6E7kQR5akFFkSXkwUU35ZMXnu2JXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:25Z"
    mac: ENC[AES256_GCM,data:E4gQXhle0XHaqhQlRnfdl+8M4ouQz5jqZRWOv4nHxycr9j2/RNeWIX0QIg6Ksx4hUTEaAdeZlWFBUrdLwHBP4Ky8J4jT0VPrsBCaXUU6v3koXhhl4nVj+S5htOIldrY3wkDQlLQP1LFJjkJ0ipL5hHA2RuZa7oNM++8r7nz6qzQ=,iv:3SQv1VzsrMl9x8CmzSdzB/l+GWAIAtKpWEyt/iU58TI=,tag:MsMRIVCjUIOnVnfOUohyyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
