kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:nJFkji307jezVUXkidSkbw==,iv:znnOTA5MYosvrN2yG/hgwCE4Ce519P9tyc3Xe5jfnV8=,tag:IBGUy8AH60BUvjOZAv8jqA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:17Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQH639/PduRSXcVuU7AuBjsIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFMsMUfAJEvcVUEVxAgEQgDuWRoCMzM4iP4ym7ugnaieKsbdRBanNqjfulIak3BDmRSCxmXonPHGCtH9b0ePOic14H6v1a1oElI4FDg==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMGM5VmY5SGFQd1E0emhL
            N3dXeC9lbUpWM0RBc29PanZUWEg4bFdrOWlVCnZTS2pXekExd0pqRGhYNlZpZnBj
            b3Q3R3RSL3RBeFpBOWZRYjdMZkc3c2sKLS0tIEtlY3h0SHpCNlRFQ2JTNHA3Rm51
            TXBVOW5uMVMrWkJBZUZGZ0JJNzNqWUUKP1almE0iJ1iAJkpnxO3e46+xtTc+jScg
            6UnVID+6aGojlCDUPsiQ81BsCwmib0Z5zD7WA4OVMYwujSOttSESEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:18Z"
    mac: ENC[AES256_GCM,data:bWm2UFi6kJK3vYrs6+fKdlzlEEMqogzmyoh3yPMRL+lR++FcNna+I5NL6QvGtn6JR+QPlCO3d8vu7IH7fGGaWgd1gKI84AQEeOEYTxAu3k4H97+o9Yve/b+VVn+7XCVEK414MfBoJhAjUj4GQ/I7R7OJTrrbdgA7Gntc8FBi5As=,iv:SlxhLv7z3HzQripT00zoJGdzAHolxOH0CZE0wdRTh7Y=,tag:w26NwidLckd47zSJyWgsYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
