---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudflared
      namespace: networking
  values:
    controller:
      replicaCount: 2
      extraEnvs:
        - name: TZ
          value: "${TIMEZONE}"
      service:
        annotations:
        loadBalancerIP: "10.10.120.52"
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        name: "nginx-internal"
        default: false
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: "100M"
        ssl-protocols: "TLSv1.3 TLSv1.2"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: networking
          namespaceSelector:
            any: true
      resources:
        requests:
          cpu: 20m
          memory: 500Mi
        limits:
          memory: 1000Mi
    defaultBackend:
      enabled: false
