---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
