---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 12.8.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  values:
    objstoreConfig:
      type: s3
      config:
        insecure: true

    query:
      enabled: true
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      replicaLabels:
        - "__replica__" # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.replicaExternalLabelName`
      resources:
        requests:
          cpu: 15m
          memory: 64M
        # limits:
        #   memory: 99M

    queryFrontend:
      enabled: true
      ingress:
        enabled: true
        hostname: "thanos.tnwks.local"
        ingressClassName: "nginx-internal"
        tls: true

    bucketweb:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 64M
        # limits:
        #   memory: 64M

    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency"
        - "4"
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      resources:
        requests:
          cpu: 15m
          memory: 204M
        # limits:
        #   memory: 270M
      persistence:
        enabled: true
        storageClass: "cephfs"
        size: 15Gi

    storegateway:
      enabled: true
      resources:
        requests:
          cpu: 23m
          memory: 204M
        # limits:
        #   memory: 226M
      persistence:
        enabled: true
        storageClass: "cephfs"
        size: 1Gi

    ruler:
      enabled: true
      alertmanagers:
        - http://alertmanager.monitoring.svc.cluster.local:9093
      clusterName: kubernetes # must match with kube-prometheus-stack value `.prometheus.prometheusSpec.externalLabels.cluster`
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      dnsDiscovery:
        enabled: true
      persistence:
        enabled: true
        storageClass: "cephfs"
        size: 512Mi
      resources:
        requests:
          cpu: 23m
          memory: 94M
        limits:
          memory: 113M

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  valuesFrom:
    - kind: ConfigMap
      name: s3-thanos-bucket
      valuesKey: BUCKET_NAME
      targetPath: objstoreConfig.config.bucket
    - kind: Secret
      name: thanos-secrets
      valuesKey: BUCKET_HOST
      targetPath: objstoreConfig.config.endpoint
    # - kind: ConfigMap
    #   name: s3-thanos-bucket
    #   valuesKey: BUCKET_REGION
    #   targetPath: objstoreConfig.config.region
    - kind: Secret
      name: s3-thanos-bucket
      valuesKey: AWS_ACCESS_KEY_ID
      targetPath: objstoreConfig.config.access_key
    - kind: Secret
      name: s3-thanos-bucket
      valuesKey: AWS_SECRET_ACCESS_KEY
      targetPath: objstoreConfig.config.secret_key
