kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: thanos-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:2FA/hqjB6Gh/ord+FfzlMg==,iv:mvY+c2lhc9ukW+zsYFoW0C9+Ijplhgn0aTHsUln15P0=,tag:VRcAhog4fFEf5wWTwhk5LA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:23Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQGcaswH6zYVOZi+rLZpbrhJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjQOyPxJix3zBAyqEAgEQgDvuKryvijfKaJMpCm+GQ7qbloI9+pu8awVqGhOaMdWfImByGcufgKFHNmWQ8GmXNN3jtf0bDPO+C7W8oQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybmpkemg5eFFreU8rWHdQ
            WE0wcFBXb1h5S2xMOXJJRDVVdWhuZzJGVFFBCjdvRXJnZnlXcFRpSzhkQ2VtWGZ0
            RkpvaUtuMk1yN3QxWk5xUElWcTdMVWsKLS0tIHNRMTB4U1BvdWh5cHAxazBoRE5Y
            UGxsdVNtK2pXMlRZdEZPNVhRSnY2Z3cKWj221ZJnt+LVhuEqeIWwMAhAiuMr9g8K
            buzkD0oN/5yYisLBIzq0Ib8fUN68wx0jdtDoo9uSiEU0rCyM4a6KZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:24Z"
    mac: ENC[AES256_GCM,data:f/+uVSn2EtfX+wLoGCjsEvFQGhWMbv0HBrtprGyCV+JnwToWLid1R8K2Ky8pMJMaQrb4t4QmZT5QN+Bx+ddf6kczONWEpBqyqCnIvZpyAwJhzMsdijVf9j27b74SM0lmykT3X07R3TNutBmky31sazBz6xiqVuqwOmiJf0+wLxw=,iv:0WwWP0OF6MfqHJwoFJre0cZqcoxrYlOMSvluDVlGVew=,tag:pLUSzNtBtf2uaiCbgsH0CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
