kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: thanos-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:QBQovhKDs0j3H1H4saItPg==,iv:mwZ55eZtMDfgbMTc6fCisaePT1WGeQpv8zImjauU+68=,tag:vaQ/Fnh7pCaAG6V+vwiDvg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-25T04:57:58Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGmt/u9WvC0eW4j1MjrlOWbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmUjdwfFYKTosblZbAgEQgDsCYK8gvmOfWjfltdfRBRca/YB99NZ5iRZ97lT6y8Gsg82EWjYt07GhCGrCGrPu5yU9F5AV84uGQXYh1A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bE0rbmhCNjBYR3huVjJ0
            bG1YN2JoVEMycHAyQ3ZnYWtjUmptZ1lOWVdNCjErL2ZOMDhQejBmT0hYM0JJZmZt
            MlZXZ2JrY0VLYjdFM01pVUtOWkVSdTAKLS0tIHhySVJGYi9KS2RGUDFZYjNUWkVS
            SjJVUnVBOW5qSU1vTVE3aUJ5c1FudkkK3/zGkoJxuXnIYn6SvV6UemQQ6/E/8/OE
            d9zqnk70Oyx/iMzZBUj6/orfWRJ9MW0fw6vZvSDBFLyxQBjV1WZmFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T04:57:59Z"
    mac: ENC[AES256_GCM,data:4FZaU4UWuGU2CKun396VBVcLNwLWlZBYE/CWyYRUehBhGiC0BokwfT7Zx5fZBHBaigHUKA7zNXyucFr/3s3ntKXBLwx6Gc4Kcd13tcu1ZqiOVc5pXAcQuc/kvlHslHflOuh7XHoyOfbpmDAMV+9B/hImWNwvM/QlMQ6sDc13i+c=,iv:CMsU9svAqpX/XJ1tSDBBxs/obb3RBrBMgNRSCq2iacE=,tag:tZ05nZVKTAtUJ6cTnMM2aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
