kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: thanos-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:6/GCsT16iuIgJLoDZUd+Ng==,iv:xHKDbWKha0EHKhM4Xyj/eem4wAyF1CjbJDt736QViPQ=,tag:Jq1Rjma2hXbCPhSXdPwdjg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:36:08Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgHFjNyIgUV/2RXJxSvtui5MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3YCeIci1gMV43GJxAgEQgDt8Pt0M7EgnL0o6KP0n6y/Jx2c6nt/vnWfzu0hKUp3FcS7TJXcq+QqJGNFphyuwycs5PfOUxrr9AiiV6Q==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlUyM3B2aFpKOW1VeFhT
            NnUxbk5zK2JIbG1NZmlEdVVkaXhuaUQ4SVI4Ckp2OEowSERPSUZ6U01XdjVnV3p5
            WWsvK2hkaGF4RXRab0RKbG41NW44NDAKLS0tIE02Smp4L1RQMmxhRTlwUDVzWmRD
            eUpIbTNydUNjSnh0QjEvQkx3Mmlqa1kKZhnlg+BvD4uCnL4ktSGkAAvnBIofnTFx
            MT+wp1x02UdYHbCH/wtTcNu7iVr3YdCPNSE+DgfLtlMgn7NI6puRiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:36:09Z"
    mac: ENC[AES256_GCM,data:1mVxwdGvUkgt6nXl10oNgtIRGM7b9HCs1ezf6kSpyTRkGh1D2FCcBObt5KnI9s+enh36FsPTMSRc8hxCMPqkuwsnLMf405i2kO9sTR7slysEebS1H8A/FnkZGUJh0EREghdnmoIuHXWpcDVQIpRvEOD3mBYHqch51nz8CVxoLDc=,iv:po9xu0Z94wy5NvkUnzz0a8+TSQp7SrhVkvCbDF4tp3I=,tag:OHK7sXg03ca55l2YFRqHZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
