kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: thanos-secrets
    namespace: monitoring
stringData:
    BUCKET_HOST: ENC[AES256_GCM,data:JOG1BOUJSJlCxs6486dx9Q==,iv:5hk2q/LcrTAMOzw0qJCk2ffnk+b/EMENdAdWRY6jUT4=,tag:pehzJlaH4ttCxM1tRxoCHQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:16Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQED3sph2M1UN2RXI3CLenodAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQaWmTEmSPsaSPoohAgEQgDsKsKMcENJ7HivBRjpYnODYSFkK2BoKCrAK01/K/I+hbuybhawCdoouqDUXjdJ1/ho/KtzbKQ9ZgyWfug==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNjFGOUpuN2JZSzNJYUJI
            c1N6ckxFRXl1N29NZ2lickpPZkdZWjB0dlJZCnZuZ2Nmb09GMHZFUHFEK2xXc2tT
            K2RSUUM3SXlYTWNyWFlvOEhhb081YkkKLS0tIDNzYkpSNTZIT2UxWUtMQzdCL2RO
            eGl0NmJrSVpZWFZ6ZVVqaWF2QldkMWMKzqvYClJnjYCNfv0Bd++2k3GO/zJvb71Q
            1/BR4GS2HmnDrOEjK0meW9ZWLjSSqQT1NDg86mYkK0d6hb/q0uYkMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:17Z"
    mac: ENC[AES256_GCM,data:6q5v+G1sE3eX1aFQe2EGoRIR1NhJEfcLh1Pnmn7MHMY0igygVJBxBhEFqgK+9tw+JDzUe07/xoL+Gs8YG/+qcZG833IBMzwQLEsvu5SA5pw0io2chGXnnDXxCoJCA0HZZCgVcX7zgMcqXPkXAnSIlOsOHBCf3Dgu5964Q6xri1s=,iv:ss/Mt6x/Aq1EGHEFnXtPY4Za4+ZRKBfTaGzqNIMcqvY=,tag:sdjcscvp6MOcb47CTvtBvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
