---
collections:
  - name: community.general
    version: 6.6.2
  - name: community.sops
    version: 1.6.1
  - name: ansible.posix
    version: 1.5.2
  - name: ansible.utils
    version: 2.9.0
  - name: kubernetes.core
    version: 2.4.0
  - name: ansible.netcommon
    version: 5.1.1
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1
  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox.git
    version: v1.7.1
  - name: geerlingguy.ntp
    src: https://github.com/geerlingguy/ansible-role-ntp.git
    version: 2.3.1
