apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ph7p9gDhQ1vz66lWMjisHTxYOaFF0MhGsTmXd1k7XuqRoNVo,iv:lfEgwHMS3w3ocXt2X8NUxiZdUfqTFFunHHbFg5pAXpU=,tag:RXM5VqPJKvVjAbmnNtdwWw==,type:str]
    credentials.json: ENC[AES256_GCM,data:2A/BWQzA0MES8vWKSfV3YZaUrCecxK62tv4F8TA3as0wroJ6decw6NsvpQZvqfg1kRYMXMQM0D0Zjzl6vsKRJz04NDyQgDDnG8aFHKk/DQ0hCgzqUzFtb1BYp1Tq2hY8Ei8OqNJPFVTQ/0+eehRdPe+M+/Oyib5UEJMYWWn5E3B51b/y40OcKsUI63rakUpfzghkf4qKG3t3Il7oUL2Fs0iICtlk9udgoH92KnYVHg==,iv:rLqC0vdwOUV03dtvUnmzgx7pweqn4/uXHaFep8dpTYU=,tag:GxFE5GXx+zJ3PX498xGIVg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-06-30T15:14:28Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwH8KC+6KWL3paCfO1ei6eEXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0jVg7A0G6EEVvKm2AgEQgDs+9xgHcB3zKxs1LrBE5vlbyZG2JVbR7ZHi0SbczTNy1NZr3CJdiCW1dobZ5wPXPag4waFWN7S6MMZocQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFA0VDcxN0FYbXY5bDRX
            SUR4cHpheUphb29MK0o0dlhTdWtxbWdxd1R3CmYwU2hhSzMyT0FmaG5HNDZYNFRa
            ZkFGNHpnWnYzQTVmOUk5eGVLYUUzSUUKLS0tIHNNMW4rMEVacnJjZ3k3T3B6bHJh
            QXZkM25HQjFlY3ZQblU4OCtkeWdtZjQKdTuEp16SBC804PIVtFkS8OJwRDhQ00V6
            USH7IXKhKA1D6gLxwe576TpsojUOcc8HegKGEfbe23UjFqJkp/Yf0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T15:14:28Z"
    mac: ENC[AES256_GCM,data:m5o86ukzW6xnN8MmkEu1+C6vP0UH714nOLnw01WGQ7P+X3gLrA7SdtfcrsNUNy0EVRtNVDepJMtpkukbY3LSJDeOCpwA0LXEXZMcSDJ0v31Zjs8UMzRjhV4JSKpwB9t3CrzDs+D8A0tCuqAHySgEi6P151yuzjNse3X8gT/cgb0=,iv:ytDabl0B/mVzXVuqC+QESO0wacUUNyZS6x9oi29S5ts=,tag:kcJVsq8r2YslRk2Eoy1flA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
