apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:tzIfsubhuTMRFRnpb/AGB5HrNl6pgbkrjPzSqN1F0OHrjO8e,iv:QphnMIYCBHvdNQasWC/T4bAY2j5iGUl+looa1NldRRw=,tag:We9j+iVADG3zbDaPTjwjeA==,type:str]
    credentials.json: ENC[AES256_GCM,data:/5PWbLNLScYkWdHKwPhnATQ62rHmt56a5ezsq0m5O1WehSciOKc02THqypiDFDt3bAYhKSG60VGDeOgZ6T+NB8psSzcI7yVcb8vbA6BLOjR0+TFqOGZu6UWaLqCxMMCeD8rgHarmE9tvMucPxv4W16BsU89eaf2LrwkAWoYfXS6JtJwkc5BxmGftV0XHCMe9/Zx7iUqjNumbVWbMMW7yVGrvUwi2Mpf/d+wmHEDeuQ==,iv:ZfSXA7UG9FxWHu3R2wG0wpOEkzHtCofNfdWis1sW9Sk=,tag:0acsWTr5IjvAzS6/U1TZxw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T02:56:41Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQG35f7Zc4p/nrRK8LC+MTILAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZla8VY1MZHP1U302AgEQgDsASGhCcY7DLsCpsxjzgZyNqwoHjx7JR0Xr6+ytKT5JWcTidLtTEfVAe5xiydUbD02Xq3OH9n5vu4y0dA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUnZNa0xEaW5mbFIwN3FR
            YUFHenA0MFhNK3dhWXJ4SG5rNTh4bFFmUzJvCmN5ZFdScmE2NzFHd1QxUThWMEhw
            bEJPVy9aM1NvTXp6NGVWQndVUDg3ZlUKLS0tIFdPQnZQZXp3UjJuZ1Q1UzAxZ0xH
            eEwybm83NFQvRy81aXl5dmlQaDZuMVkKrSpBGAdmSK6ObsvNyVv0GAAtz0YKgxE3
            rrIKhuEkQ4Q1+Pu+RAR0spIJMNyictajbmamc8tmirwu38Q7y/4d5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cThQQ3pwajhHcktWVk5t
            bU9nT0YzcktVeGpwdVg5bzZ3bGFZaWNsSmtNCnBucHNaU2x2NjV5WitCdUp5dTIx
            bmYzWFFaeXdkRGZmeno2U1RFNTZYMVUKLS0tIE0xOGh3MStoZ0p3Z3ZWaHorRC82
            TWJkbFRUempOZXh5SE5VOG5Xa0ticmcK/EsCAAStRS+wXJnR+hOs91q794fdwtu5
            laoQsQLh1ljRGsUe5MlWt3qi2SjXvTcdQmKauYQROO8rBOFIxpZy2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:46Z"
    mac: ENC[AES256_GCM,data:E61UZ5vt+64K7kLCDy4tRuHI4tTdZgp4OQEegpqmMlTEUB0F9a9VfOP2Qk9uYh8SZzzcl4TfBQ7Pat+wGDYxiDj7bTRMdkOAj5/96cfErTPMJbZ0uQt8KHUOtGXy2fW40Eg4h9yFCJHlbewyWMw4DZZlVpuMXintwoSyjCNohac=,iv:RiuNVv5liPLSqSnNEDA9/XUO51hiJMdEoL812oQ3/OU=,tag:lbj5cLbxwbWPLDCEtZOkGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
