apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CtXoKo8GxoPdqC6uxnhnUmM1w175uiQYkyZ3hsm80FacTicQ,iv:nXlMs6TajeJ4ALu8M/ziP68ohi8pWkpJgvjRaOKyuoQ=,tag:VpCv4g5AFrPbvY8AGeHeVA==,type:str]
    credentials.json: ENC[AES256_GCM,data:QP7fGzd2ry52C8kj91Rp1Up44ciIGQXMIg7T4u5sNlioe8Fak24JYAdmCFz/IpyVaBEtOCQ4jcjoL+BS3JbVlQOHmcUXPOELS9dZz1iTbkxcL0Yp1e9pmxC2eO8QdrVzx6YS7MDay9t2VYMFNVRZRKALrXCFQ/lDstprVzIfXTJ6NFkK5BLB/X7an7EzGuiUHnaaKgz55Omj3B/Bp6AACgb+rK5Rl8dVf+evtP+VHIEVw50y4saKtLEWRwAWlcIYJw==,iv:gOCMNyJvluPQBr2cbBCicakcpVadSqnqE7Q4pG5p4E4=,tag:KeT6bz0BbddzVSoBtiAG+g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T19:52:15Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFXZhVSrJ1Zu6PI4ieP19JfAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBcB/sOtKJFRYmtYfAgEQgDvrDPttZZvqe7i91ohvM5mN7tTTTyScMZE+d5TDa74nU/XenN6tvbjBwwuHxy7rbg1pfqJ+Q72ag3ZMvQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRmNYUzhCYlNwK2RGYzBF
            dnFXRzJvaHo5OU5VVkdJS090bFl5Tk5OaEg0CmVoZGdzSjJtaE9hQ0pIcG9uWGdW
            UzdkUEN2aFNyRkxiejE4akc4dlZHM1UKLS0tIEU3SDlzTVJIR0RHOFY5Vmdmekll
            aDNmQkFMeXFTN0RwazdMTkJkZzYyMFEKgIflepAx4PR1m9g5gmuaV68gNU4Zr5hk
            xz5mJZCOW6DEtUuvNT6sOkSwP8lmm1jEaziUn5CmfMRPh5jdDSMndQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU3crUGo5Qzh4NnpjTU1E
            YUVMQ3Q4bkh4MXFIYmNCV1QwL1dxcDAyVGxZCnluaE5rQzFPRUY3YlVhRFJmcml5
            cHZIM3p6UFJBUWQ3WmpXSk9QUG1VMmMKLS0tIFRwa0E2Z09rRmVDUkQvRUdVWmdw
            NE4vYzFLYWxXZC9Vc3dXR0VTU0VUSEUKL0hhSFDvUWmK8oc55LWiiBRQyX34E20u
            yZ7nsEZN6yO740NLXzKluMPIpl9tlIxiJLH+Uph4KcrW7sxyvouK2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOER5cll2MTFZWEtiRjU4
            VExuWXc1b1pnYWFsN2hsVGJVU3R2b2d2Z1ZrCnc4dFE2V1RNd1pTaHdJdThtTDky
            YkJxQlNONkZEd1hyclBDUXdZMjFCU2MKLS0tIE50cWRJNzVTMVVsUEdTS1BpYzJV
            S25jNUtxV1JOUklmdXEwdlBDS1NNQmcKCHYgtzgYKEJcQF8TT5vAd76t+VsWfw5b
            wRKy0XC+fO2PNmwwu3Bu007x4FrVR6qhqOBDZFecJnnXm9rITCmnRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T17:22:35Z"
    mac: ENC[AES256_GCM,data:8XXvyhHBQ8c34Tf/K5LLYhfgGctFN+Q496Uik721s3P2ORpp5Bg360tNTSDxMmYURSfPLQ4qV+MuYmxVXnLKlgeJvHdhu1KLdQsNlNgeJZrDn3Hc7QgokokllI5sBejVqQRerjMQTyT0fLCG9r/jcYHvZInsDtG5hlmfUcNXJyA=,iv:vPyDP9lZ3JZHpT0MeAF6l5Twp1tshZd35hPczYaHL1Q=,tag:cSZDFxw3jVAn9PdBxv23Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
