apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CtXoKo8GxoPdqC6uxnhnUmM1w175uiQYkyZ3hsm80FacTicQ,iv:nXlMs6TajeJ4ALu8M/ziP68ohi8pWkpJgvjRaOKyuoQ=,tag:VpCv4g5AFrPbvY8AGeHeVA==,type:str]
    credentials.json: ENC[AES256_GCM,data:QP7fGzd2ry52C8kj91Rp1Up44ciIGQXMIg7T4u5sNlioe8Fak24JYAdmCFz/IpyVaBEtOCQ4jcjoL+BS3JbVlQOHmcUXPOELS9dZz1iTbkxcL0Yp1e9pmxC2eO8QdrVzx6YS7MDay9t2VYMFNVRZRKALrXCFQ/lDstprVzIfXTJ6NFkK5BLB/X7an7EzGuiUHnaaKgz55Omj3B/Bp6AACgb+rK5Rl8dVf+evtP+VHIEVw50y4saKtLEWRwAWlcIYJw==,iv:gOCMNyJvluPQBr2cbBCicakcpVadSqnqE7Q4pG5p4E4=,tag:KeT6bz0BbddzVSoBtiAG+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMnVpazE4TWYySXZJVStB
            aStwbWl6YlQ2SC9heGJUZDVic1pmakxnaVQwCjkwS1FpQ3VPeCtQcmxldFNNcHJF
            azNoUUpRWGhGVllEUVdxbEFTYVhWdlEKLS0tIGhubHY2TzVzTStCVGREU3ljTS9T
            T2toT0IvN1ZETkpCRVRmNStRaDliaGcKPFdtC55vUyIMSjxxe6WSxNFZdukDtpPk
            Pi3Y9u6kefZCXHbK0kyVmc8fO1mrzWVRb6Sq8ut4DJ8dzvCGDAtJog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TG53MlQ5OFFSclFPbWRS
            a2ZQOG5SVVdOQWZ4TXFEa0cvSzIwUGVSYm53CmhRREExY3djWW12MzlPSFhTUmNQ
            M0VjY1FYemRIc0t4TS9kQloranl1SjgKLS0tIHM0UGNJWkdxb1dLeFVXd3ZqQU1X
            SElucFNGdHJOZVZhaUx0eno2aG5qTjAKCkR/4aiR4indRGeZlBiikH+mW6kXIakB
            uLcpxeAn+7Snlu2nJLNh8Sr3as5p3rAtceb5GOfhO58r4708FapB6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTEl5ZXE5QTFVTStUQWsy
            aDFRNGRKNE82MWNQKzEzUnMvcFVIMEhEMkJZCkxBdlFuYmZPKzRoQ3Y2TUIwckFU
            TUcyYnVBYjIzdEFWWll0TmFDRlNFWXcKLS0tIEZRVGtGUkZXRjBsY2lIRTVvRjZM
            K1VFeHNwb3B5dm91K3RaaGZtQkp6cEUKY2Zrg5iMX2G97mz2zrU3/gx0bDXMH5WU
            JCV+Nv9ISBnniGgFpHHHdncbKRJ7Fvzg8Opw+9uu12upxKDG2GSzXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T17:22:35Z"
    mac: ENC[AES256_GCM,data:8XXvyhHBQ8c34Tf/K5LLYhfgGctFN+Q496Uik721s3P2ORpp5Bg360tNTSDxMmYURSfPLQ4qV+MuYmxVXnLKlgeJvHdhu1KLdQsNlNgeJZrDn3Hc7QgokokllI5sBejVqQRerjMQTyT0fLCG9r/jcYHvZInsDtG5hlmfUcNXJyA=,iv:vPyDP9lZ3JZHpT0MeAF6l5Twp1tshZd35hPczYaHL1Q=,tag:cSZDFxw3jVAn9PdBxv23Gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
