{
 "title": "UNMS Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UNMS Device Interface Traffic, Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "unms_interface_tx_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UNMS Device Interface Traffic, Rx",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "unms_interface_rx_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UNMS Device Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 19 },
   "targets": [
    { "expr": "unms_device_ram", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UNMS Device CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 19 },
   "targets": [
    { "expr": "unms_device_cpu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UNMS Devices",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unms_device_enabled{deviceName=\"airCube-ISP\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unms_device_enabled{deviceName=\"LiteAP GPS\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unms_device_enabled{deviceName=\"LiteBeam 5AC Gen2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unms_device_enabled{deviceName=\"EdgePoint R6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UNMS Interface Drops",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unms_interface_dropped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UNMS Device Interface Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unms_interface_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}