pve_acls:
    - path: ENC[AES256_GCM,data:zg==,iv:qArg+8MURJPm2UAcmIqEtpdqtSlkP2i5HyFhFpIbZC4=,tag:6GLYcwRoO0BJIR/m/eqGHQ==,type:str]
      roles:
        - ENC[AES256_GCM,data:YGLxKo6dwJ3h9S1jxw==,iv:krahmWDSUjFr/dShkzKmChzdfcnSXZinWUR/9ID6lhY=,tag:oJfpUY0H+wtzAIW7eAU6dA==,type:str]
      groups:
        - ENC[AES256_GCM,data:3Q1K,iv:/atYp5kcK287wy425u3ECZb62hdY2+xjlGllG8Qb+Ao=,tag:+xlC7zVljw6N4Wq7IJ9aVQ==,type:str]
      users:
        - ENC[AES256_GCM,data:vNH+dvjiWUu6iNq6Iw==,iv:V7dLCppw/+JCWN5eSUvGKncv/ANDun3tz69PLnfHO1g=,tag:7m4hYqsf3rXVRajKrh06NA==,type:str]
    - path: ENC[AES256_GCM,data:zg==,iv:qArg+8MURJPm2UAcmIqEtpdqtSlkP2i5HyFhFpIbZC4=,tag:6GLYcwRoO0BJIR/m/eqGHQ==,type:str]
      roles:
        - ENC[AES256_GCM,data:Y5ZQIOggq2w=,iv:vEL+3308xBuAZxpVtdq3X2HjcRAj30U78JoA5sb7ieY=,tag:L/6TCtAFL/4ceIUZ1q4HAQ==,type:str]
      users:
        - ENC[AES256_GCM,data:FKI5vLKQakshUg==,iv:Gr6Aq1neySZiZmzJW6uB5BORgAtP2M0H+5UoBzkMaEo=,tag:wcw+yr7dPJf5O9FFmQMDqA==,type:str]
    - path: ENC[AES256_GCM,data:zg==,iv:qArg+8MURJPm2UAcmIqEtpdqtSlkP2i5HyFhFpIbZC4=,tag:6GLYcwRoO0BJIR/m/eqGHQ==,type:str]
      roles:
        - ENC[AES256_GCM,data:nZdW2sIIAOo/ZQ==,iv:H7/mQYW1RqM8qHL3ms7OINkASigfeGhlr2dOigob94g=,tag:ngkVnschDGo6K0DPhK6AbQ==,type:str]
      users:
        - ENC[AES256_GCM,data:XhbO09/i3SqnEe2skQFPag==,iv:OFypSRQR4eDZ3PYr/psQhH0JMqsnENSqKsymuWXE980=,tag:blEgF/DNfJR86gjHAUyyFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3RHcGxuYWdGRzlyRmgr
            anFWTjkrWGJreWhhVk5TL0NiejRTMXIxU0RzCjZzS0xSOHI4cXZrYVM4MkpqM1VL
            cGt5blh2cVdVQkt4OStQMXF4L25kQ3cKLS0tIGNzYnVRN1c4MTBTMjBsVmNwUVph
            WDFGTkgybFVjTkZoQnI3eGJlUFhUSHMKnPOdg67oG033/BRYDuar9CTImdYGKidl
            aS1oGQo58TtXJsCK6U0+sWNaA6oFZCowmCj9yICWB2QLL9SNfGH8aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T20:01:15Z"
    mac: ENC[AES256_GCM,data:UfGs8cVts3bpeEjEVxh8Sn7Yt4BqIAl8oJIevjs6HIjzPtR68CfD+PV8ahwg9tx10CEjiaEPa93brdgcHLnUTXDrUY7r8/ekfB1br6kMPM9Mo0HGoXNcp9rpfmjb+gvERaGd/vANeixYMXmGYJi3kcBqf4nrmIEhhpC3N8DQg44=,iv:SldO/d8CgdT9E83ojx5W7jg93NJGy8a5gkhTKf3j0sA=,tag:XXCwOZZL0inlg/rtPzcyYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
