kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:0JQNSP2YehV6Brxa+SBB2jUn1N7i3sxlZRTA/g==,iv:iKAp3UZAYWzPFFaziGMTlBbha5e1iFFOk89yYxMjkKM=,tag:FUOGFVZ5BQWSdxvreqDRkQ==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:mAm37Z/T63s0s5of3Cn+pKX0moCrcdKMRY+ZnQ==,iv:IjxEmut5p0z4WDPSD5y2JeJQzWjdFy1Ip6PnaZF5Qx0=,tag:cL75rmBd4PmxcUofKx1qYQ==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:enKma5zGuP5qYwIdoHOsrksR5Z4vqAX/2TUNvw==,iv:sQsL/gHouNf0Yhzf5U0YqP5jEmbQUytun/XqVnuUfyg=,tag:Hi5f6hB+xsR6F/CUmLLG5Q==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:iMMcytv9rWmwMJfFe5P1xzwU/jZPL5zlPM2W0Q==,iv:LKDinP6EDQnUNff6IIomQe36jcKSY9hu1y+82AmysXA=,tag:tp2frHvFqeRe4uKuhxQEpA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/mrk-4e456e11170a4342a518df4017e3cb0c
          role: arn:aws:iam::323952031338:role/iam-role-sops
          created_at: "2023-11-05T21:09:29Z"
          enc: AQICAHjuzQTaLq/1y+NX1JFH1WzFqwgR9wTszOhmkTc2w4mmPwGnw8o4WFEylnPAU1PVPTWvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuosgI0g6F2QpnzRpAgEQgDv6xYJEgTHYLf9dc2Jrp9oQpLeYL8hkjB6h3hg21JEso23v/IBB6WDeWYJupfFAA3W6Z4ttFzGXKfsolw==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcEo3NlA0Z0hQTnFxRy9y
            eUpEZi96cld5a002Tk1lK1FmT3FOb0VzVDNjCmpTeE5raDd6MEp5MmVOSWNNd25T
            QnhQWUl1RHV5Y21HdWY2TGdDTlI0V1EKLS0tIE5qbGhpVE0yTVRRZW0zTFlXdVVm
            ZkxYZndoaitCSXBTRlNTRGd5dHRlVzgKkZt6gs/FeAE2QF9Jtox/PgdVfQtvjndY
            YBce1GUWhPJCTtTVO+lh+8pbodLcj4vjQxD4vX9HHuMAdXtO2Mxwaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T21:09:32Z"
    mac: ENC[AES256_GCM,data:4AqUHk33+ZwZMAliPrLvzBuvga+9suUmCo4xYxKfqrnRrq+mTdBtAW1Ti3wcpN2FvciFSDJ2TQDk4v6mSihphLFJ/thTKZva/TDA2XKDYD0vyB6rkby3b+6W0Djh5iyRooLhsKZsq1FxoP9DIwPWip/Moo5KFgUNukDxtaLGug8=,iv:T4hOd2Y9xDOH2R+tN4qYuWtgv41gZ6FbXWmWy3yMei0=,tag:lKh3yAmRuni2zs1gN4ETjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
