kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:ZfykiAsexnNkMQvtrK4PBCQvYsRoKPqdLcROBw==,iv:xO95y9mYcAFWoBxvmkQcoWDSPiyVdG8WVTNa5yaVzYs=,tag:eLlWFoEuREIAIVYrIFtOSQ==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:kGOfAii6fG8kwOFEXnvwm+eatQco0GAiTxfJXw==,iv:uAXkN2fmO7OYTpwBCg+GeCNBVL8nSf/U60LtOlWSPZA=,tag:QiYgU4iqxEy76b/4X9sXxA==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:XzQmlulIuAxq0HzNN3Ttn7OePCrhvD5pyiGC6Q==,iv:TsR3B24Van7GOlW3g+yATSQEH5Vdwc3pIwE8Y7kiab0=,tag:f/yuAVA3xMvx5kRazMjMjA==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:PcM3AeePPl9o3MH8mcoQyzu2ye1zi0Yg7Vo9Xg==,iv:H84Vmh/yrQM8b5EFCzGM6idowySVhSaUk4ca7pr4bPM=,tag:G9hPquRQOS/Tl9cv4hg5bg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-18T18:41:34Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGc0/Oz+k1CqEwQxx3XbsrJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf/afdMvAN4NW0A0cAgEQgDuDD3vyGy68ZTxovML3U/9nIct3Cn4U3ZaJJlASiSExvtTjs7oySC0+xxsJPrRu2s9b3GYUo81DcEza7A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRnJ6c1ZQbWxwYXNGNGxY
            Y1c5cEZuNjBiYUhlZURmYWZBT2MySCtOaGlVCm1BeGEySWY1R2tDUjI0eVJ2a1hL
            OXFSOFZzTWp0NU45ZSs1V0VpR0tDemMKLS0tIDJjVXBIUUlOQlhpYVlwd1RMcUI4
            ODNiWUV3SzRrZkxWcW5HVjUwSWo1aEUKoFsy37GEokX6ERiZ7ImHQUYpz8PGfXfp
            QBpsDlWkt3aC+lu76eh7sSN3fDsVRX5187XzeuvCvtSV7MHL417LgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:45:08Z"
    mac: ENC[AES256_GCM,data:xALPLni8W8mw4oak20z3j/8DIkNnS5V+k4av4qH+z3cnKyglBQmrCbdjK2/H2uVU3zKJhjD59UMOKOflhC2VuyUxRXyP2tnEihk8U3XXb7y8k/UolrVa0zgLb50nHwVmb7EgUJUHwv1lnby/H6NECNC+bVbWn5nvcWkDw1EdTEE=,iv:I4WKyihVGGDb38/qSBw709xQNmRXrcRKzf+QGqZnuXw=,tag:TUbImYiTsfZOeHngs+XMGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
