kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:CiCpv2+p2eq3GqqH8u8anEPTSR09vK2Wt5OC9Q==,iv:NuERNJ53DI7/h67ubS5NroMYuO0EaH6R3Pw/fakOn0k=,tag:Vk2uNq1HvS00/A4YkXK8MQ==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:nXEnlYd9Tdcd6my0yuliiXztzZSGEEuS6KH5BA==,iv:lG/i43DdruyxhdXQ+ggaVhYqPaVxpYpi/HIT+jFMi2s=,tag:bLG1JaVgxNAeU5trLpqKMg==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:X7kU1LqlAT8IjjVoZSUUMXWe9NxZWP6PolCTxw==,iv:P9JvAo+l6IrnIkziEhOR+KBA4jZd12TEesG1GMHst0U=,tag:K4jWXdFHt194iTRcGR5ZRw==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:BvZfzDH/ENZK54g+fUGZBQcqNIl/6M0Ml9PKqw==,iv:AGvGVcoS1GQ4mk03AMI29M0EDkX4QnpEHDy8Mo7ibrE=,tag:BPtOziF8eaON9jP5yXEqGw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-16T02:01:20Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQFoNK2A37xbq0dOJDW9ZkPvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHjIGh9DxJdAGO8edAgEQgDta9LwStMongfkB16amTbija1Wa+UTsne5C1gLjS7RSA2sQa+QqXpZOduSEiCU6mNvzvt9F2zbQH23UKw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdE5jZjR1blJJMUU1eGth
            ZDJSQTgzR21zeEpHTTlSSGUvNDdxbkF5Y1RnCmFPZVZtQkJrUzdmRHduRGtMS212
            aUVhaGRoUzhHK2FlZU9zRU9EQ2xVR1EKLS0tIENMbEdVbFZQQkw5NW9aSEk3QzlZ
            dGdzcG94OU15aTQ0dlRXbTkrbkg3VUkKCEHO6OUd//h6cDLboKFmdG4WWp8A0MOv
            9Y5rxeVG+YkORqj6B0O23ILCm46Ipr0p/veQenDKskXI+41OOR1RnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:21Z"
    mac: ENC[AES256_GCM,data:x0fAJJmgoLxmIWsgo82pQG6Jmcp4FG9Hw37CPniydo8ShsS9ry+papZOVg0/+9rNMbK28+Kwk9G3GyRFZZLvHiBcckUTdytDYupNxDMiqUKgM0GyRiFqLqRDQ4u3IdiQ3A3X5zaWfZJDxG0Rxu+NOD0W+BqrYbZ0MT8ADhGYWWs=,iv:bvxSoupkT98soCFFxWge+S0DSvjNtBn2VjUyDpLlNlk=,tag:ey8R+H1vFKfeU003fsQqDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
