kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:CiCpv2+p2eq3GqqH8u8anEPTSR09vK2Wt5OC9Q==,iv:NuERNJ53DI7/h67ubS5NroMYuO0EaH6R3Pw/fakOn0k=,tag:Vk2uNq1HvS00/A4YkXK8MQ==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:nXEnlYd9Tdcd6my0yuliiXztzZSGEEuS6KH5BA==,iv:lG/i43DdruyxhdXQ+ggaVhYqPaVxpYpi/HIT+jFMi2s=,tag:bLG1JaVgxNAeU5trLpqKMg==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:X7kU1LqlAT8IjjVoZSUUMXWe9NxZWP6PolCTxw==,iv:P9JvAo+l6IrnIkziEhOR+KBA4jZd12TEesG1GMHst0U=,tag:K4jWXdFHt194iTRcGR5ZRw==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:BvZfzDH/ENZK54g+fUGZBQcqNIl/6M0Ml9PKqw==,iv:AGvGVcoS1GQ4mk03AMI29M0EDkX4QnpEHDy8Mo7ibrE=,tag:BPtOziF8eaON9jP5yXEqGw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2026-05-24T15:56:12Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQH+ji9Dw3yYxiSjjZ4QgJFAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5u69sjeKyDS4Kbt/AgEQgDvt/ZsBhRwI8iX3CprIbFlf7AX9T9CA3Y0u4vGanhnOcvIPLHYSG/VCtNao6i7R70dh0x8Th/SdMuofTg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdGI5eXVPc2czN21qbDI4
            Z0JnY0V6RFBpbGlxZmNFdVRUTXg3SW9JNnc4ClBTV1dOVE9kV2JGSVpSazhwUUc2
            eXBSajBYblhIc3VXV2krbm50SGFzQWcKLS0tIHhSbVptVTFhZWVlajYxZ1l2MFVS
            SzlXaC8rWlU2MjBFbzVRK0JhNnNSUzAKbyXryn/NZSo/aAueRNXBmfJczC9LpBiM
            yw8HtYkanaQA/sOgue+bO8JgyEytGPZbpv+3Nt1L8v/3bAjJTbSQUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySEpSUVRiRThPRklhM0p2
            SVA4aFAxSVdwYlVmb3NYMXhlaFo5VnBHTXlzCk9PUUdrcjltbHZUK0pGL3AxYmFX
            ZERyNWEzMjA3MWVaRHdHN01qZ1ZuUXMKLS0tIDR0Z1dhdlIxc1NVVFMrZjVJYW5x
            RFRVeHBuRHJRNWZNbU15Q3VuVTF5bEEKEZwffkrIiUX7w8gA1ZfyN8TvMSSLrE/D
            1x5HDHi+3e+oc74knf/We6mLJVTGiH113OLT89uPEB3HZopSvh3OVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQWVDZldWcFI4dmFMV0VT
            ajdZREpaRC9EY3FReUNwZmtnUXlHUGJVN0NzCmlRR08zRzRZaWgzd2pud3RpQzJy
            T05seERqeU5TS2VXa0dVL1ZKYm5VMDAKLS0tIFpnbXpLeUhYNVZKZTNPVUdNYXcw
            RmROTlhnN1RKUE9yMXo4RFRvL2wvUUEK2L+W49p3ap8aoQvPg9aGh3TRpmud5DNX
            Bu/bSIfScYy3y5JSUQAoiySlTlB40f77Kdv+KjuzaJkPt5Fpok7FzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T02:01:21Z"
    mac: ENC[AES256_GCM,data:x0fAJJmgoLxmIWsgo82pQG6Jmcp4FG9Hw37CPniydo8ShsS9ry+papZOVg0/+9rNMbK28+Kwk9G3GyRFZZLvHiBcckUTdytDYupNxDMiqUKgM0GyRiFqLqRDQ4u3IdiQ3A3X5zaWfZJDxG0Rxu+NOD0W+BqrYbZ0MT8ADhGYWWs=,iv:bvxSoupkT98soCFFxWge+S0DSvjNtBn2VjUyDpLlNlk=,tag:ey8R+H1vFKfeU003fsQqDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
