kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:YwiCopbsZGR7Qfg/zpYbUf3M6Bw7GVS03iS60Q==,iv:oUgobL7zj4tXP8Qci8EXKLxtNbNL6/cubN97c8/6M1U=,tag:i89v+JwKyKUlaW5SQCB5uw==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:yFQmVADzgtglxcPDWfvRXtBTxsLpRJ9LesZABg==,iv:8r7wdOFhZmQUzAw0G6Gu+xd6tVoTdrikUmPRb8J/NGc=,tag:hj3s5sMiC2wv8oVziEBGeQ==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:PrJvLO4M8740D9lCQ3vYA/ey00LqZZQwa26/Lw==,iv:+ZMwtt+fr3L1crVfhDyljV5zzd4RlVxd4gNP73vNMA4=,tag:P0X5k10My8EBfLrn8s1tlg==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:mfTrsey2EMG97D4eO+MTosmMO30ecS2zcii2ag==,iv:G2+DaBt/HKW4yj+jj0bBh1YwfO2bVC8txbjLHU3K74s=,tag:84bMNxvwY/2CXJrhrEXkDA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:323952031338:key/56902c4b-1aa5-4679-b6cb-dec2db7a1c90
          role: arn:aws:iam::323952031338:role/sops_role
          created_at: "2023-09-03T22:35:53Z"
          enc: AQICAHhbTusm/IiWd6UmPr8RCfcjUPlYn+bGnRY4lqjZVC5CQgGD+hq9+o+VK701nkd+PsqVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkUFMGC8PTdmz80EIAgEQgDue0fOt/TJSE70h5WqvVlM2dfUFfH7378LOReTCC/fOTr1vZ+iZE45RpeKKu481bCnukZ8hPD1MfBbwLg==
          aws_profile: sso-legacy
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y2ZzUmVyazRxRDM1VFI2
            Qm1mcHA3RGNROVlHWVM4RmN2b1JaRUFld2drCk1VOHVreGZMWDczWGFFMjFIMlM3
            QmVuY1FuUUx2WkhqN0VFZ2FCc1U3WU0KLS0tIGRnWGxpRVVYREtWbll1VEVTbGxR
            UkdOaHV3ak4vZmZVYU5QWGJmbC9EU1kKdywprFChTmXoO5w7ICbWxlNvNfHxcppt
            MtuqCNd8q9sdMBYx8lttP4D4t5JcTjKCwmCDVtnS8/iyxRBW4MDaWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T22:35:55Z"
    mac: ENC[AES256_GCM,data:nr1hvT1Sf0YpJYc8dy2ErJ1hk+YML5sryzjeyvRRizaBKNA2AJ+jWg/3mwqmDGzazBj1QT4mdW1WHhEuf98juURfn2oTGV45OwEouQb7LChpvKmusQO2jKTSpipRQzlFikKa+wGc5gcG3RDWhNvRLOmcM9NRcpyLue0/hjnxzMY=,iv:h8lFgoyWutDwIQhMwBy1tVwm8HrHE+0FaMF2sGRKLGE=,tag:Bm1MUORDCUR8aLeltyNtFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
