kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON__EMAIL: ENC[AES256_GCM,data:rZEUAMqqP2GoCEK2Udlk1AtLJEz5fu04z53t0g==,iv:fMSvAeYJvWIt/aH0eQyPXh9zFhdzIvlGCFDCwBIE6Xg=,tag:7sGRsJdD4XsNd8I1bqbfsg==,type:str]
    P2G_PELOTON__PASSWORD: ENC[AES256_GCM,data:6LqS4Xm7/fqSK91U7AzYC8qILZohPcnK1wKaFQ==,iv:XGapjXKU2FQVOGOZgsz8sLLMTw759vL1yZcebA/K3/4=,tag:NFk1m0qv7+7wrD6HIXiR9A==,type:str]
    P2G_GARMIN__EMAIL: ENC[AES256_GCM,data:ErO8R4teKVD34oSuzCEz+8rtVZcWn4I5u/Ek7g==,iv:QBT0S+Qr5MKj/BXFaqfFTgYhVoS1RB2Vmx3IZAA4ess=,tag:ulfgYSBTL09wLmL7SxuzfA==,type:str]
    P2G_GARMIN__PASSWORD: ENC[AES256_GCM,data:nK24iM8W9cHPBY9J5Mar5g9YQZLUJzUzK/I3CA==,iv:2a03QqXi1RL8/P3rusGQa0d3gSb2wdeh0bjmEXACnhQ=,tag:hgetGVoV2j3swqj/aN/bZg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:654654220436:key/mrk-74c4597ebffd41d38a852228e13d76cc
          role: arn:aws:iam::654654220436:role/iam-role-sops
          created_at: "2024-01-15T18:32:13Z"
          enc: AQICAHhNDAK0Is+rGNAlNYnav2FEvs37O7WQwrCmqkcTMDWNIQHWxvnENke/zhBmoDS5c++2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+I82nrL66J+pDKrlAgEQgDsciXU+grQa5Zuwrb+Ii3N6ROn77YV2+YVukl8jClwIIf/bkeQUMJ9L4Lzy+ox8slJVEyrrSR1DIXQ2EQ==
          aws_profile: sso-legacy-new
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBM1ZzVVR1c0hqZldQdVl2
            VWE1U1pkUmN4YTdoaENBa2g1dm4xaGJoVmdnCllocUVoOGFBY0lEYkxGczJYd0h1
            ZjJlYmhDQVRJeHF5TUxuRXVRVG9XWlkKLS0tIHlGNlorRnlKL0Izb2xjSm4wakpO
            eTROcjNkdTZTVWNWRW5DMEdubmJWZDgKqHgt8PpQ8zLxPN9WcgWvowwjkA7Tr7wH
            B0rOTjdGU7JpS2lO1egp/QuPPJ+ETz4huKtsAPwdg4g+wET21WenjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T18:32:14Z"
    mac: ENC[AES256_GCM,data:ZgI7q458A5MiuR84Xu8f4RfRuuuJu3QSwOcC8jVd7lgkPYOMRVo84+lcTfMYQSUljIqL2QhiSHZMd3tQtauwNKZ7o9C0gIw6+25WjqczAmRSuKVTz2ZG84jJOBmQZ9BNCeNCjruZRmaW5WFvvPTPAYdyj6OZXH+7dkSNUgWZpPo=,iv:JpvV0g6tU0LLwrnRar261h82kW9OcTi0A8xsU/k9BCE=,tag:SD+FPp65NoYLinJqrs2DFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
