kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: peloton-to-garmin-it-secrets
    namespace: home-automation
stringData:
    P2G_PELOTON_EMAIL: ENC[AES256_GCM,data:IT1Z4LQ2gAbGx9JgRZpD2GqkWsAYGUWtMntgNQ==,iv:v+nuO9Ffc77NVmfcUtZjpvGbkQdO3xDWKEmWnHau4gU=,tag:+gllae4Lprwhk7g3gURSvw==,type:str]
    P2G_PELOTON_PASSWORD: ENC[AES256_GCM,data:KSeNYyBWWFb2puLRHTVp9gApDkzXEgFFOTM5ew==,iv:hXUy5UlxOpclXSsVYvaSzrOphOUHxdX5+oNIh2aj2rM=,tag:pJVWUpm7zBSjddsDlkv5Fw==,type:str]
    P2G_GARMIN_EMAIL: ENC[AES256_GCM,data:iQkc5XijB0xh4jIYooW6jDTTR0YXzoKl6dV7qw==,iv:GME5qplucfbJjq24S+/gBeMjladEy5z0zBhyybKl9OI=,tag:6TP4zazOVYADsIynnwhtEA==,type:str]
    P2G_GARMIN_PASSWORD: ENC[AES256_GCM,data:Y2BiF9zd6Oq11YDPCxmhaa5KcNXMtenmpg1n5Q==,iv:Cp1tL5i+b9NBBIJ+nragCjiIUBb6tWyG+w1YuX5LvF4=,tag:v+Pn7ira1APCyvi3nD1OSA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-18T18:41:34Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwGc0/Oz+k1CqEwQxx3XbsrJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf/afdMvAN4NW0A0cAgEQgDuDD3vyGy68ZTxovML3U/9nIct3Cn4U3ZaJJlASiSExvtTjs7oySC0+xxsJPrRu2s9b3GYUo81DcEza7A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRnJ6c1ZQbWxwYXNGNGxY
            Y1c5cEZuNjBiYUhlZURmYWZBT2MySCtOaGlVCm1BeGEySWY1R2tDUjI0eVJ2a1hL
            OXFSOFZzTWp0NU45ZSs1V0VpR0tDemMKLS0tIDJjVXBIUUlOQlhpYVlwd1RMcUI4
            ODNiWUV3SzRrZkxWcW5HVjUwSWo1aEUKoFsy37GEokX6ERiZ7ImHQUYpz8PGfXfp
            QBpsDlWkt3aC+lu76eh7sSN3fDsVRX5187XzeuvCvtSV7MHL417LgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-29T00:25:16Z"
    mac: ENC[AES256_GCM,data:7tD0loy28oBfM60Li9zoIbUuvjnmhXSc5PDJ5o+twMd2Yw0VN5TGZuX+OIJGZEHJbP1jUG4/weLlbNXZN+1OXiZtaOZXD4WKM+wGT4Ta+MGBfcCVPp8vHZsv6XzJLiQxSdYSTX3X4LrR/1GIdVIdhSz85ZW78W/ugr3boi5vOEc=,iv:cnLbQFepEL8Pv95yUy36toK/z9SOJTl/cdhjz1lL1mc=,tag:6DyTCMZ0zAQ2waqf4t7Dow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
