apiVersion: v1
kind: Secret
metadata:
    name: controller-manager
    namespace: tools
type: Opaque
stringData:
    #ENC[AES256_GCM,data:DGkd4+ZARDyq/ITJ8hU2f5s6H7VQ6wgPMdxxcl+MvWIw9+wZ3H8mle7bZ+POlj2vNWFGBxTub4ww8WWKRtM+EeKa3EutRCg2TXXe8Q==,iv:y+LshPHJgPCC/dp/WoZ7T0ekrTdIcescjpuuGgiA0OE=,tag:7Yc/SgUArY6hioa3AN/gIQ==,type:comment]
    #ENC[AES256_GCM,data:CpeLbcRtCDdAoyf9ef+o0/4aG9L+dzvg5oNvXIT8oUOVgrMTUVVXwWSkawGy13zaDAKUfLHNiNG0l9iEsv2hOGrIguVKt8TtsIY=,iv:klOSdPhaStvRAwYcFOyups+bTZxvGjVShHnpPOfnxr8=,tag:1YtUB9gRKaCaSdTn9eyT5w==,type:comment]
    #ENC[AES256_GCM,data:InMj//jTnU7OHuMcRRFZTnTPEWYPGTGWCfTRUltNKwRL+ApDOALp0C+49C0P1KWwFeEMPbB22ycTXw==,iv:eoSalC8otGPC7TrnOQ4CWJOYnmxL8NrvFcfa5cOHe1Y=,tag:nsEyCMV6d5D4+OpRKp/TXA==,type:comment]
    github_token: ENC[AES256_GCM,data:5CRpJcjgsMrb32CHy98yCAVUCXb4,iv:2OjoYSldyIhT5LnRlDmcA1KXASq8Dz/kwJov9vHF43M=,tag:1ed5je0p0bc8LOYmlFUPgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOC82WWNPeG16bnBHZlNk
            R1N5UXhFVUk0amMxWXNBVjR0RkhZbnErY200CmxqNVZlRW1Zem40dmtiN3ZlbW9t
            cFRlU1o3bXR2UlpKZ21tY1RsMWJvZW8KLS0tIDlsQnd4cHVaUHhqRlJPZW5RdkZr
            Wmhjc3E4eUdiRkRjdHFXMFZWOEFQaDQKRYfygRDfCftlRuLSkCn9plxv3WabUlBb
            TbHVsJhTLEb7VT43Notnc9srHw9pyewdFdWh1EiWwZJjTDoMJ6dhKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12uckcdwv9p2s75ae3h20wgn70taatdzzl44n9x6vr8h9qurzkaqqkhphz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcDk3eEpCMEpEeVQ1NlU3
            eFVoSEhsS1VpOGJPMjhGNTJ0V2dzankrS3dFCmdiZ3N3SWVYTkVqVExKSnBXNXdS
            dTBCbnBrZFBpZURtOGJzMXdvK01Eb0EKLS0tIHhqckQySG5CWGFFY05sa0NqVnkr
            T3UzdFRwVlpEc1MxU2w0TzNzTjlsajAKeH3R0rGUUQoO8c63zzkR+vsPV2HvpPGN
            TnLE5g4oeNWOvinG3BqD6PPHgLJP/Q2cAraI0Yh4fXoyCi5UCEsp/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hmmuna95ktwl9sf9j56wjjukyf22ukdyjd8c47nlf5fjgyeyk5rsmhtyjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbnlRUW1iS1d2V29pb0hT
            b3FBREpiNDd1c0xEWkRTRXd4U01SNnppV0RRCjZLWXZRTWt1T1g0T3E0RE9IbytB
            MlJFajZUNG9kdUJrYjlhcFFlNitOQ2sKLS0tIFlOZ245d2ZVV1dabGFWczVBMGZp
            UDRSbW5tR2dDYWJYODM5am5HRXFTa3MKoDifSCTRGyM40UJMEOSj9QMBicJ+b1hL
            CDEbMIHnPB37mNrvULLGQ5juaD2mnuxRyQxU1Be14G3FXX87XwfTZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T04:00:00Z"
    mac: ENC[AES256_GCM,data:Z//db4ybgCWtHfhnZVfftQ4ashahdTGTLDanw+TluMgy8Un9LoMFDwRzpz53X7cTky28bP3RQJFY1FAUnrdVMoy7cgJ62DtUL6bzyiadIE4+Yx9J3KMx2uSwxMRkRnztVHPu5flHqkn7uI6xRqAlzUHjGXcs2ML1G5vQwotSkME=,iv:2DHG+pX4NRxcdBUPPQ48LMmfoerBRTCdS8vwQvmkucE=,tag:GsUeTkoBraR1OhbyVXMbMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
