---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: maubot
  namespace: production
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: dock.mau.dev/maubot/maubot
      tag: v0.4.2

    service:
      main:
        ports:
          http:
            port: 29316

    podAnnotations:
      secret.reloader.stakater.com/reload: maubot-config

    probes:
      liveness:
        enabled: false
        custom: true
        spec:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: 3000
      readiness:
        enabled: false
        custom: true
        spec:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 5
          httpGet:
            path: /api/v1/health
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hosts:
          - host: &host "maubot.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        storageClass: cephfs
        size: 5Gi
        accessMode: ReadWriteOnce
      config:
        enabled: true
        name: maubot-config
        type: configMap
        readOnly: true
        mountPath: /data/config.yaml
        subPath: config.yaml
