name: "Terraform Plan"

on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "tnwks-ops"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  set-workspace:
    runs-on: ubuntu-latest
    outputs:
      tf_workspace: ${{ steps.set-env.outputs.tf_workspace }}
      config_directory: ${{ steps.set-env.outputs.config_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine workspace from changed directory
        id: set-env
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Files changed: $FILES_CHANGED"
          if [[ "$FILES_CHANGED" == *"infrastructure/terraform/aws/init/"* ]]; then
            echo "tf_workspace=tnwks-ops-aws-init" >> "$GITHUB_OUTPUT"
            echo "config_directory=infrastructure/terraform/aws/init/" >> "$GITHUB_OUTPUT"
          elif [[ "$FILES_CHANGED" == *"infrastructure/terraform/aws/accounts/identity/"* ]]; then
            echo "tf_workspace=tnwks-ops-aws-identity" >> "$GITHUB_OUTPUT"
            echo "config_directory=infrastructure/terraform/aws/accounts/identity/" >> "$GITHUB_OUTPUT"
          elif [[ "$FILES_CHANGED" == *"infrastructure/terraform/aws/accounts/prod/"* ]]; then
            echo "tf_workspace=tnwks-ops-aws-prod" >> "$GITHUB_OUTPUT"
            echo "config_directory=infrastructure/terraform/aws/accounts/prod/" >> "$GITHUB_OUTPUT"
          else
            echo "No Terraform files changed in the watched directories."
            exit 78 # This exit code could be used to neutral exit indicating "nothing to do".
          fi



  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: [set-workspace]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: List variables as test
        id: test-vars
        run: |
          echo "${{ needs.set-workspace.outputs.tf_workspace }}"
          echo "${{ needs.set-workspace.outputs.config_directory }}"

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ needs.set-workspace.outputs.tf_workspace }}
          directory: ${{ needs.set-workspace.outputs.config_directory }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: ${{ needs.set-workspace.outputs.tf_workspace }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Update PR
        uses: actions/github-script@v6
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
            });
            const output = `#### Terraform Cloud Plan Output
               \`\`\`
               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
               \`\`\`
               [Terraform Cloud Plan](${{ steps.plan-run.outputs.run_link }})
               `;
            // 3. Delete previous comment so PR timeline makes sense
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
