apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser-testrestore
    namespace: databases-testrestore
stringData:
    username: ENC[AES256_GCM,data:/37GTe0d5Jc=,iv:uPZvGIqs6XJ5BKlRpT5Fd0tK7ZC5yxs4NrbqvX1YlgE=,tag:KVU8mtXPBagPdL2PIYeBqg==,type:str]
    password: ENC[AES256_GCM,data:H9Kfdlr3PKIX0OzDcXjnv9FdGws=,iv:vvpJZNFZ/9Sm1BCzMgfmrTeW5MOk09nU3YsERLkE7HA=,tag:37mnkkuxY8vLko0HBtsVoQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:919859941427:key/9f302670-24c3-44fc-a25c-f8b685429309
          role: arn:aws:iam::919859941427:role/sops_role
          created_at: "2023-07-02T00:56:31Z"
          enc: AQICAHhFgizsJYqi2jDNanNwkwmQ12zIOj0p33qjZ/GcXWoeRwFMkc845Y1v0Fmyvz1SLUZ9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMiqpT4g4yQoCxKCw+AgEQgDtzXh3XFUWWvbIxMbJZPLX7JgtcnHROKhIQvGFdShVEOpzYTVYWJe5BZ8A6BAUEdmTIalAL60uwy/CYAQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S0pES0hlQ2dNbWUrbU85
            MmdyRWpYRWYvYXRtcEdnTThxQXBRSlZwdEhBCitqVWphZUFFTFRiWllUN09nQit0
            Tm5DbTlWeStSam03QXQ0QXJHc3FXRFEKLS0tIHdUSmJ6bi9GYmRLQWVGd2NXSEZQ
            NmZOcFhHVjc0ME1YUU1GQS94bU9vVVEKPjtDfMZigpFFl9YdqW0dT9vpshqU8/q7
            D6O5uA8VM0N/dDgGZSiznlPJVgp+xG1H6FKiUfnO6vbXOitoUf38Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T03:36:49Z"
    mac: ENC[AES256_GCM,data:pOL5H/ewMq0ID7G4/hcWtefUc2B4WPJJROIET02jN7XM/qJ6o9HVF57n306fGcKhUR8F+78yf9RrN8JpZZnmx1yrBpcyZXvn2vFU+NsUn9msS7xFaPOnwktQthbHQ/ckizr3rixLwaO1e+p7i/XJel0UsCLQaErKdhwiFjuyoes=,iv:sQ8d7FTWcSttE3VWxh9+lPa9EmNLvOeaTPYnQsZtCro=,tag:yEz6sx2UbYCuVX+ffs1tbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
